In [4]:
import pandas as pd
import numpy as np

In [30]:
# 휠라
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_master_260420.csv", encoding='utf-8')
df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv", encoding='utf-8')
df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv", encoding='utf-8')

---
# 휠라 네이버스토어 리뷰 데이터

## 1. 전처리

In [39]:
# 데이터 불러오기
df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv", encoding='utf-8')
display(df_review_fila_naverstore.head())

,Unnamed: 0,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,reviewer_id,review_content_class,extra_id,extra_reviewContentClassType,extra_reviewScore,extra_reviewContent,extra_createDate,extra_writerId,extra_productName,extra_productOptionContent,extra_reviewTopics
0,3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,mini******,PHOTO,4.669237e+09,PHOTO,5.0,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,2025-02-24 13:14:50.302000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
1,4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,mini******,PHOTO,4.652212e+09,PHOTO,5.0,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,2025-01-31 13:07:37.398000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
2,5,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,ex****,PHOTO,4.652239e+09,PHOTO,5.0,넘 귀야워요 만족ㅎㅎ,2025-01-31 14:23:34.326000+00:00,ex****,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
3,6,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,youn*******,PHOTO,4.634973e+09,PHOTO,5.0,깜찍합니다.이뿌구요^^,2025-01-03 23:36:57.419000+00:00,youn*******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
4,7,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,yoon*******,PHOTO,4.944300e+09,PHOTO,4.0,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,2026-04-02 04:45:38.825000+00:00,yoon*******,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,"[{""topicCode"": ""size"", ""topicCodeName"": ""사이즈"",..."

In [40]:
# 필요한 컬럼 선택

df_review_fila_naverstore = df_review_fila_naverstore[[
    'product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'review_content_class', 'extra_productName', 'extra_productOptionContent'
]] # 10개

display(df_review_fila_naverstore.head())
display(df_review_fila_naverstore.info())

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,PHOTO,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   str
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 444.0 KB

None

In [41]:
# review_content_class 변환
df_review_fila_naverstore['review_content_class'].value_counts() # PHOTO, TEXT, VIDEO

# PHOTO, VIDEO = 1
# TEXT = 0
df_review_fila_naverstore['review_content_class'] = df_review_fila_naverstore['review_content_class'].map({
    'PHOTO' : 1,
    'TEXT' : 0,
    'VIDEO' : 1
})

print(df_review_fila_naverstore['review_content_class'].value_counts())
print(df_review_fila_naverstore.info())

review_content_class
1    887
0    390
Name: count, dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 438.2 KB
None

In [42]:
# 데이터 타입 변환
# rating, helpful_count, review_date
df_review_fila_naverstore['rating'] = df_review_fila_naverstore['rating'].astype(int)
df_review_fila_naverstore['helpful_count'] = df_review_fila_naverstore['helpful_count'].astype(int)
df_review_fila_naverstore['review_date'] = pd.to_datetime(df_review_fila_naverstore['review_date']).dt.normalize().dt.tz_localize(None)

print(df_review_fila_naverstore.info())

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: datetime64[us](1), float64(1), int64(4), str(4)
memory usage: 398.3 KB
None

In [43]:
# 파생컬럼 생성 -> year, month
df_review_fila_naverstore['year'] = df_review_fila_naverstore['review_date'].dt.year
df_review_fila_naverstore['month'] = df_review_fila_naverstore['review_date'].dt.month

df_review_fila_naverstore.head(3)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1

In [44]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
 10  year                        1277 non-null   int32
 11  month                       1277 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), str(4)
memory usage: 408.3 KB

In [45]:
# 컬럼명 정리
df_review_fila_naverstore = df_review_fila_naverstore.rename(columns={
    'review_content_class' : 'has_image',
    'extra_productName' : 'product_name',
    'extra_productOptionContent' : 'purchase_option'
})

df_review_fila_naverstore.head(1)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2

In [46]:
# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'review_body', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_naverstore.columns:
        df_review_fila_naverstore[col] = None

df_review_fila_naverstore.head()

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month,collect_date,platform,user_height,user_weight,user_height_group,user_weight_group
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2,None,None,None,None,None,None
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5,0,2025-01-03,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,0,2026-04-02,1,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,2026,4,None,None,None,None,None,None

In [47]:
# 컬럼 순서 정리
df_review_fila_naverstore = df_review_fila_naverstore[required_columns]
df_review_fila_naverstore.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,review_body,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,None,None,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,None,None,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,None,None,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
3,None,None,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다.이뿌구요^^,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
4,None,None,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,0,1,색상: Beige / 사이즈: 220,None,None,None,None,https://brand.naver.com/fila/products/11293482675

In [155]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       0 non-null      object
 1   platform           0 non-null      object
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   review_body        1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        1277 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), object(6), str(4)
memory usage: 468.1+ KB

In [48]:
# 이상치 확인
df_review_fila_naverstore['platform'].value_counts(dropna=False)

platform
None    1277
Name: count, dtype: int64

In [172]:
# review_id 중복 확인
df_review_fila_naverstore['review_id'].duplicated().sum()

np.int64(0)

In [49]:
# 'platform' 데이터 '네이버스토어'로 넣기
df_review_fila_naverstore['platform'] = '네이버스토어'
df_review_fila_naverstore['platform'].value_counts()

platform
네이버스토어    1277
Name: count, dtype: int64

In [50]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       0 non-null      object
 1   platform           1277 non-null   str
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   review_body        1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        1277 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), object(5), str(5)
memory usage: 490.7+ KB

---
# 휠라 자사몰 리뷰 데이터

## 1. 전처리

In [38]:
import pandas as pd

In [39]:
df_product_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/products/fila_snapshot_master_260422.csv", encoding='utf-8')
df_product_fila_D2C.head(1)

,category1,category2,category3,collect_date,brand,product_id,product_name,product_type,category,gender,original_price,discount_price,color_count,raw_colors,review_count,launch_year,launch_season
0,상의,긴팔티셔츠,일반,2026-04-20,FILA,1100fs261rl01x001001,베이직 긴팔 티셔츠,의류,긴팔,공용,49900,49900,3,블랙,1,2026,SPRING

In [40]:
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_master_260423.csv", encoding='utf-8')
print(df_review_fila_D2C.info())
display(df_review_fila_D2C.head())

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_id         48244 non-null  int64
 1   collect_date      48244 non-null  str
 2   post_date         48244 non-null  str
 3   platform          48244 non-null  str
 4   brand             48244 non-null  str
 5   search_keyword    48244 non-null  str
 6   reviewer_id       48244 non-null  str
 7   content           48244 non-null  str
 8   source_url        48244 non-null  str
 9   rating            48244 non-null  int64
 10  helpful_count     48244 non-null  int64
 11  purchased_option  7036 non-null   str
 12  has_image         48244 non-null  int64
dtypes: int64(4), str(9)
memory usage: 19.3 MB
None

,review_id,collect_date,post_date,platform,brand,search_keyword,reviewer_id,content,source_url,rating,helpful_count,purchased_option,has_image
0,123617,2026-04-23,2025-07-07,자사몰리뷰,휠라,1170fi4ith2659flsa,khk****,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
1,142021,2026-04-23,2026-04-03,자사몰리뷰,휠라,1170fi4ith2659flsa,meg****,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
2,142012,2026-04-23,2026-04-03,자사몰리뷰,휠라,1170fi4ith2659flsa,meg****,색상이 파스텔톤으로 예쁩니다. 감촉이 부드럽고 시원한 느낌입니다. 세일기간에 구입하...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
3,124095,2026-04-23,2025-07-22,자사몰리뷰,휠라,1170fi4ith2659flsa,lil****,아주 얇고 좋아요 어제 너무 더웠는데 이 브라입고 답답하지 않고 시원하고 넘 좋았...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
4,129745,2026-04-23,2025-10-27,자사몰리뷰,휠라,1170fi4ith2659flsa,jhy****,"정말 가볍고 얇고 편합니다 여러 브라 사입었는데, 요 제품 라인이 제일인 것 같습니...",https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,0

In [41]:
# 필요한 컬럼 선택

df_review_fila_D2C = df_review_fila_D2C[[
    'review_id', 'collect_date', 'post_date', 'platform', 'search_keyword', 'content', 'source_url', 'rating', 'helpful_count', 'purchased_option', 'has_image'
]] # 11개

display(df_review_fila_D2C.head())
display(df_review_fila_D2C.info())

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image
0,123617,2026-04-23,2025-07-07,자사몰리뷰,1170fi4ith2659flsa,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
1,142021,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
2,142012,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 파스텔톤으로 예쁩니다. 감촉이 부드럽고 시원한 느낌입니다. 세일기간에 구입하...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
3,124095,2026-04-23,2025-07-22,자사몰리뷰,1170fi4ith2659flsa,아주 얇고 좋아요 어제 너무 더웠는데 이 브라입고 답답하지 않고 시원하고 넘 좋았...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
4,129745,2026-04-23,2025-10-27,자사몰리뷰,1170fi4ith2659flsa,"정말 가볍고 얇고 편합니다 여러 브라 사입었는데, 요 제품 라인이 제일인 것 같습니...",https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,0

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_id         48244 non-null  int64
 1   collect_date      48244 non-null  str
 2   post_date         48244 non-null  str
 3   platform          48244 non-null  str
 4   search_keyword    48244 non-null  str
 5   content           48244 non-null  str
 6   source_url        48244 non-null  str
 7   rating            48244 non-null  int64
 8   helpful_count     48244 non-null  int64
 9   purchased_option  7036 non-null   str
 10  has_image         48244 non-null  int64
dtypes: int64(4), str(7)
memory usage: 17.6 MB

None

In [42]:
# merge 전 product_id 매칭 확인하기
# 제품 리스트의 product_id
product_ids = set(df_product_fila_D2C['product_id'])

# 리뷰 데이터의 search_keyword
search_keywords = set(df_review_fila_D2C['search_keyword'])

# 매칭 확인
matched = product_ids & search_keywords
unmatched = search_keywords - product_ids

print(f"매칭되는 값: {len(matched)}개")
print(f"매칭 안 되는 search_keyword: {len(unmatched)}개")
print(unmatched)

매칭되는 값: 1001개
매칭 안 되는 search_keyword: 0개
set()

In [43]:
# 제품 데이터에서 product_name, raw_colors 추가
df_review_fila_D2C = df_review_fila_D2C.merge(
    df_product_fila_D2C[['product_id', 'product_name', 'raw_colors']],  # 필요한 컬럼만 선택
    left_on='search_keyword',
    right_on='product_id',
    how='left'  # 리뷰 데이터 기준으로 merge
)

df_review_fila_D2C.head(2)

# merge 확인
# df_review_fila_D2C['product_id'].isna().sum() =>>>>>> product_id => null 없음
# df_review_fila_D2C[df_review_fila_D2C['search_keyword'] != df_review_fila_D2C['product_id']] =>>>>>> 'search_keyword'와 'product_id'가 잘 매칭 됐는지 확인 완료!
# df_product_fila_D2C['raw_colors'].isna().sum() =>>>>>>>>>> raw_colors 원래 null 값 있었는지 확인 완료!

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,product_id,product_name,raw_colors
0,123617,2026-04-23,2025-07-07,자사몰리뷰,1170fi4ith2659flsa,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN
1,142021,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN

In [44]:
# raw_colors + purchased_option
import numpy as np

df_review_fila_D2C['purchase_option_combined'] = np.where(
    df_review_fila_D2C['purchased_option'].isna(),
    
    # 1) purchased_option이 NaN이면 → raw_colors 그대로
    df_review_fila_D2C['raw_colors'],
    
    # 2) purchased_option이 있으면
    np.where(
        df_review_fila_D2C['raw_colors'].isna(),
        
        # raw_colors도 NaN이면 → purchased_option만
        df_review_fila_D2C['purchased_option'],
        
        # 둘 다 있으면 → 합치기
        df_review_fila_D2C['purchased_option'] + ' / 컬러:' + df_review_fila_D2C['raw_colors']
    )
)

pd.set_option('display.max_rows', None)
df_review_fila_D2C['purchase_option_combined'].value_counts(dropna=False)

purchase_option_combined
블랙                                   8340
브라운                                  5475
그레이                                  3646
화이트                                  2600
베이지                                  2550
크림                                   2250
핑크                                   2084
그린                                   1986
라이트멜란지                               1725
NaN                                  1714
블루                                   1411
퍼플                                   1117
페일블루                                  837
더스티그린                                 724
드라이로즈                                 645
레드                                    535
오트밀                                   436
우드                                    366
민트                                    339
라이트베이지                                335
라이트브라운                                297
다크레드                                  284
옐로우                                   272
인디안핑크                                 223
내추럴베이지                                156
다크베이지                                 148
퍼플리시블루                                122
더스트그린                                 122
오렌지                                   101
민트, 블루                                 73
페일핑크                                   72
다크그린                                   70
사이즈:95(M) / 컬러:블랙                      57
페일베이지                                  52
사이즈:095                                49
플럼                                     48
사이즈:95(M) / 컬러:핑크                      42
사이즈:240 / 컬러:화이트                       42
사이즈:240 / 컬러:그레이                       41
사이즈:240 / 컬러:핑크                        41
사이즈:270 / 컬러:화이트                       38
사이즈:240 / 컬러:219 / 컬러:브라운              38
사이즈:240 / 컬러:브라운                       37
사이즈:90(S) / 컬러:블랙                      36
사이즈:240 / 컬러:블랙                        36
사이즈:100(L) / 컬러:블랙                     33
사이즈:100(L) / 컬러:핑크                     32
사이즈:090                                31
사이즈:095 / 컬러:블랙                        31
컬러:001 / 사이즈:000(Free) / 컬러:블랙         31
사이즈:240 / 컬러:베이지                       31
컬러:001 / 사이즈:000(Free) / 컬러:화이트        31
사이즈:105                                30
사이즈:090 / 컬러:블랙                        29
사이즈:90(S) / 컬러:핑크                      29
사이즈:95(M) / 컬러:베이지                     29
사이즈:235 / 컬러:핑크                        29
사이즈:095 / 컬러:라이트멜란지                    28
사이즈:090 / 컬러:라이트멜란지                    28
사이즈:090 / 컬러:화이트                       27
사이즈:235 / 컬러:그레이                       27
사이즈:95(M) / 컬러:그린                      27
사이즈:105(XL) / 컬러:블랙                    26
사이즈:235 / 컬러:219 / 컬러:브라운              26
사이즈:265 / 컬러:화이트                       25
사이즈:250 / 컬러:그레이                       24
사이즈:090 / 컬러:레드                        23
사이즈:250 / 컬러:핑크                        23
사이즈:245 / 컬러:그레이                       22
사이즈:280 / 컬러:화이트                       22
사이즈:090 / 컬러:다크그린                      22
size:95(M) / 컬러:블랙                     22
사이즈:090 / 컬러:오렌지                       22
사이즈:100(L) / 컬러:화이트                    22
사이즈:245 / 컬러:핑크                        22
사이즈:250 / 컬러:화이트                       21
사이즈:235 / 컬러:베이지                       21
사이즈:245 / 컬러:219 / 컬러:브라운              21
사이즈:000(Free) / 컬러:블랙                  20
사이즈:100(L) / 컬러:그린                     20
사이즈:100(L) / 컬러:베이지                    20
사이즈:95(M) / 컬러:그레이                     19
사이즈:105(XL) / 컬러:그린                    19
사이즈:90(S) / 컬러:그린                      19
사이즈:235 / 컬러:브라운                       19
사이즈:100 / 컬러:블랙                        18
사이즈:L(100) / 컬러:블루                     18
사이즈:250 / 컬러:베이지                       18
사이즈:240 / 컬러:001 / 컬러:블랙               18
사이즈:250 / 컬러:블랙                        18
사이즈:245 / 컬러:베이지                       18
오프화이트                                  18
사이즈:105(XL) / 컬러:핑크                    18
사이즈:090 / 컬러:BLK / 컬러:라이트멜란지           18
사이즈:90(S) / 컬러:베이지                     18
사이즈:105(XL) / 컬러:베이지                   18
사이즈:250 / 컬러:219 / 컬러:브라운              18
사이즈:235 / 컬러:화이트                       17
사이즈:230 / 컬러:브라운                       17
사이즈:WM(W90) / 컬러:화이트                   17
사이즈:95(M) / 컬러:화이트                     17
사이즈:230 / 컬러:베이지                       17
사이즈:270 / 컬러:핑크                        17
사이즈:230 / 컬러:핑크                        17
사이즈:275 / 컬러:화이트                       16
사이즈:260 / 컬러:화이트                       16
사이즈:000(Free) / 컬러:화이트                 16
사이즈:235 / 컬러:블랙                        16
사이즈:WM(W90) / 컬러:블루                    16
사이즈:230 / 컬러:블랙                        16
사이즈:095 / 컬러:BLK / 컬러:블랙               15
사이즈:230 / 컬러:화이트                       15
사이즈:L(100) / 컬러:블랙                     15
사이즈:235 / 컬러:370 / 컬러:브라운              15
사이즈:250 / 컬러:브라운                       15
사이즈:245 / 컬러:브라운                       15
사이즈:230 / 컬러:그레이                       14
사이즈:090 / 컬러:BLK / 컬러:블랙               14
사이즈:XL(105) / 컬러:블랙                    14
사이즈:245 / 컬러:블랙                        14
사이즈:095 / 컬러:BLK / 컬러:라이트멜란지           14
사이즈:100 / 컬러:라이트멜란지                    14
사이즈:100(L) / 컬러:그레이                    13
사이즈:L(100) / 컬러:화이트                    13
size:95(M)                             13
사이즈:270 / 컬러:블랙                        13
사이즈:240 / 컬러:219 / 컬러:베이지              13
사이즈:100(L) / 컬러:블루                     13
사이즈:090 / 컬러:LML / 컬러:라이트멜란지           13
사이즈:265 / 컬러:핑크                        13
사이즈:240 / 컬러:219 / 컬러:그린               13
사이즈:95(M) / 컬러:블루                      12
사이즈:240 / 컬러:219 / 컬러:블루               12
사이즈:240 / 컬러:블루                        12
사이즈:095 / 컬러:LML / 컬러:블랙               12
사이즈:090 / 컬러:LML / 컬러:블랙               12
컬러:001 / 사이즈:100(L) / 컬러:블랙            12
사이즈:95(M)                              12
사이즈:240 / 컬러:001 / 컬러:브라운              12
사이즈:90(S) / 컬러:화이트                     12
사이즈:000(Free) / 컬러:블루                  12
사이즈:WM(W90) / 컬러:브라운                   12
스카이블루                                  12
사이즈:095 / 컬러:LML / 컬러:라이트멜란지           12
사이즈:240 / 컬러:그린                        12
사이즈:240 / 컬러:219 / 컬러:핑크               12
사이즈:255 / 컬러:219 / 컬러:브라운              12
사이즈:225 / 컬러:219 / 컬러:브라운              12
사이즈:245 / 컬러:370 / 컬러:브라운              12
사이즈:245 / 컬러:217 / 컬러:브라운              12
사이즈:WM(W90) / 컬러:레드                    12
사이즈:240 / 컬러:219 / 컬러:화이트              12
사이즈:240 / 컬러:219 / 컬러:블랙               12
사이즈:L(90) / 컬러:블랙                      11
size:95(M) / 컬러:크림                     11
사이즈:90(S) / 컬러:그레이                     11
사이즈:270 / 컬러:001 / 컬러:브라운              11
사이즈:WM(W90) / 컬러:블랙                    11
size:100(L) / 컬러:블랙                    11
size:240 / 컬러:브라운                      11
사이즈:255 / 컬러:그레이                       11
size:235 / 컬러:브라운                      11
사이즈:095 / 컬러:화이트                       11
컬러:001 / 사이즈:90(S) / 컬러:블랙             10
사이즈:XL(105) / 컬러:화이트                   10
사이즈:095 / 컬러:라이트베이지                    10
사이즈:WM(W80) / 컬러:블랙                    10
사이즈:245 / 컬러:화이트                       10
컬러:032 / 사이즈:90(S) / 컬러:블랙             10
사이즈:235 / 컬러:001 / 컬러:블랙               10
사이즈:240 / 컬러:001 / 컬러:그린               10
사이즈:095 / 컬러:다크레드                      10
사이즈:240 / 컬러:옐로우                       10
사이즈:000 / 컬러:BLK / 컬러:블랙               10
사이즈:240 / 컬러:370 / 컬러:브라운              10
사이즈:230 / 컬러:217 / 컬러:브라운              10
사이즈:90(S) / 컬러:블루                       9
사이즈:95(M) / 컬러:크림                       9
size:90(S) / 컬러:블랙                      9
사이즈:270 / 컬러:001 / 컬러:블랙                9
사이즈:235 / 컬러:219 / 컬러:베이지               9
사이즈:090 / 컬러:BLK / 컬러:화이트               9
사이즈:265 / 컬러:브라운                        9
size:105(XL) / 컬러:블랙                    9
사이즈:230 / 컬러:그린                         9
사이즈:240 / 컬러:001 / 컬러:옐로우               9
사이즈:230 / 컬러:219 / 컬러:브라운               9
사이즈:250 / 컬러:370 / 컬러:브라운               9
사이즈:235 / 컬러:217 / 컬러:브라운               9
사이즈:235 / 컬러:219 / 컬러:그린                9
사이즈:235 / 컬러:219 / 컬러:블루                8
size:105(XL) / 컬러:크림                    8
컬러:032 / 사이즈:90(S) / 컬러:크림              8
사이즈:95(M) / 컬러:레드                       8
사이즈:095 / 컬러:레드                         8
size:105(XL)                            8
사이즈:240 / 컬러:217 / 컬러:브라운               8
size:000(Free) / 컬러:블랙                  8
사이즈:WS(W85) / 컬러:화이트                    8
사이즈:095 / 컬러:다크그린                       8
사이즈:090 / 컬러:BLK / 컬러:퍼플                8
사이즈:245 / 컬러:001 / 컬러:블랙                8
사이즈:260 / 컬러:블랙                         8
size:240 / 컬러:블랙                        8
사이즈:265 / 컬러:블랙                         8
사이즈:100 / 컬러:WHI                        8
사이즈:240 / 컬러:370 / 컬러:블랙                8
사이즈:WL(W95) / 컬러:화이트                    8
사이즈:275 / 컬러:핑크                         8
사이즈:280 / 컬러:핑크                         8
사이즈:260 / 컬러:핑크                         8
사이즈:240 / 컬러:370 / 컬러:그린                8
사이즈:235 / 컬러:그린                         8
사이즈:235 / 컬러:219 / 컬러:핑크                8
사이즈:260 / 컬러:100 / 컬러:화이트               8
사이즈:100 / 컬러:다크레드                       8
사이즈:090 / 컬러:LML / 컬러:화이트               8
사이즈:250 / 컬러:101 / 컬러:화이트               8
size:250 / 컬러:브라운                       8
size:000(Free) / 컬러:화이트                 8
사이즈:000(Free) / 컬러:217 / 컬러:화이트         8
사이즈:095 / 컬러:오렌지                        8
사이즈:235 / 컬러:219 / 컬러:화이트               8
사이즈:250 / 컬러:217 / 컬러:브라운               8
차콜그레이                                   8
사이즈:000(Free) / 컬러:217 / 컬러:블랙          8
핫핑크                                     8
사이즈:235 / 컬러:219 / 컬러:블랙                8
컬러:001 / 사이즈:100(L) / 컬러:핑크             7
size:95(M) / 컬러:핑크                      7
사이즈:245 / 컬러:219 / 컬러:블루                7
컬러:001 / 사이즈:100(L) / 컬러:그레이            7
size:90(S) / 컬러:크림                      7
사이즈:255 / 컬러:화이트                        7
사이즈:090 / 컬러:LML / 컬러:레드                7
사이즈:090 / 컬러:BLK / 컬러:레드                7
사이즈:100 / 컬러:라이트베이지                     7
컬러:032 / 사이즈:90(S)                      7
size:95(M) / 컬러:화이트                     7
size:95(M) / 컬러:그레이                     7
컬러:150 / 사이즈:000(Free) / 컬러:블랙          7
컬러:001 / 사이즈:100(L) / 컬러:화이트            7
사이즈:260 / 컬러:001 / 컬러:블랙                7
사이즈:250 / 컬러:001 / 컬러:블랙                7
사이즈:245 / 컬러:219 / 컬러:베이지               7
사이즈:L(90) / 컬러:블루                       7
사이즈:240 / 컬러:101 / 컬러:화이트               7
size:95(M) / 컬러:브라운                     7
사이즈:100 / 컬러:BLK / 컬러:블랙                7
사이즈:255 / 컬러:핑크                         7
사이즈:245 / 컬러:그린                         7
사이즈:000(Free) / 컬러:브라운                  7
사이즈:095 / 컬러:페일블루                       7
사이즈:245 / 컬러:219 / 컬러:핑크                7
컬러:150 / 사이즈:000(Free) / 컬러:화이트         7
사이즈:255 / 컬러:001 / 컬러:브라운               7
size:230 / 컬러:브라운                       7
사이즈:095 / 컬러:드라이로즈                      7
사이즈:245 / 컬러:219 / 컬러:그린                7
사이즈:245 / 컬러:219 / 컬러:화이트               7
사이즈:095 / 컬러:크림                         7
사이즈:000 / 컬러:BLK / 컬러:오프화이트             7
사이즈:245 / 컬러:219 / 컬러:블랙                7
사이즈:250 / 컬러:219 / 컬러:블루                6
사이즈:230 / 컬러:블루                         6
사이즈:90(S) / 컬러:크림                       6
사이즈:240 / 컬러:100 / 컬러:화이트               6
컬러:001 / 사이즈:M(085) / 컬러:블랙             6
사이즈:100(L) / 컬러:레드                      6
size:100(L)                             6
size:90(S)                              6
size:245 / 컬러:화이트                       6
사이즈:090 / 컬러:LML / 컬러:다크그린              6
사이즈:000(Free) / 컬러:베이지                  6
사이즈:90(S)                               6
컬러:001 / 사이즈:M(085) / 컬러:블루             6
사이즈:250 / 컬러:219 / 컬러:베이지               6
size:240 / 컬러:베이지                       6
사이즈:090 / 컬러:BLK / 컬러:페일블루              6
사이즈:090 / 컬러:BLK / 컬러:크림                6
사이즈:095 / 컬러:BLK / 컬러:화이트               6
사이즈:M(095) / 컬러:블루                      6
사이즈:000(Free) / 컬러:그레이                  6
사이즈:100 / 컬러:화이트                        6
사이즈:100 / 컬러:레드                         6
size:240 / 컬러:그레이                       6
사이즈:100 / 컬러:MIT / 컬러:민트                6
사이즈:235 / 컬러:001 / 컬러:그린                6
사이즈:245 / 컬러:001 / 컬러:그린                6
사이즈:250 / 컬러:그린                         6
컬러:001 / 사이즈:000(Free) / 컬러:브라운         6
사이즈:WL(W95) / 컬러:블랙                     6
사이즈:250 / 컬러:219 / 컬러:핑크                6
사이즈:L(100) / 컬러:핑크                      6
사이즈:260 / 컬러:브라운                        6
사이즈:XL(105) / 컬러:블루                     6
사이즈:WS(W75) / 컬러:블랙                     6
사이즈:235 / 컬러:옐로우                        6
사이즈:XL(95) / 컬러:블랙                      6
사이즈:240 / 컬러:102 / 컬러:화이트               6
사이즈:225 / 컬러:그레이                        6
컬러:422 / 사이즈:95(M) / 컬러:블루              6
size:95(M) / 컬러:베이지                     6
사이즈:90(S) / 컬러:레드                       6
사이즈:240 / 컬러:001 / 컬러:화이트               6
사이즈:245 / 컬러:001 / 컬러:브라운               6
사이즈:220 / 컬러:브라운                        6
사이즈:275 / 컬러:브라운                        6
사이즈:220 / 컬러:219 / 컬러:브라운               6
사이즈:270 / 컬러:219 / 컬러:브라운               6
사이즈:250 / 컬러:001 / 컬러:브라운               6
사이즈:90(S) / 컬러:민트, 블루                   6
사이즈:090 / 컬러:BLK / 컬러:드라이로즈             6
사이즈:M(095) / 컬러:블랙                      6
사이즈:090 / 컬러:LML / 컬러:오렌지               6
사이즈:250 / 컬러:219 / 컬러:그린                6
사이즈:WL(W95) / 컬러:블루                     6
사이즈:250 / 컬러:219 / 컬러:화이트               6
컬러:001 / 사이즈:WM(W90) / 컬러:블랙            6
사이즈:270 / 컬러:브라운                        6
사이즈:265 / 컬러:217 / 컬러:브라운               6
사이즈:255 / 컬러:베이지                        6
사이즈:250 / 컬러:219 / 컬러:블랙                6
컬러:001 / 사이즈:90(S) / 컬러:블루              5
컬러:001 / 사이즈:100(L) / 컬러:블루             5
사이즈:235 / 컬러:370 / 컬러:블루                5
사이즈:250 / 컬러:블루                         5
사이즈:235 / 컬러:블루                         5
사이즈:95(M) / 컬러:내추럴베이지                   5
컬러:031 / 사이즈:90(S) / 컬러:크림              5
사이즈:105(XL) / 컬러:크림                     5
size:100(L) / 컬러:크림                     5
사이즈:100 / 컬러:다크그린                       5
사이즈:105(XL) / 컬러:452 / 컬러:레드            5
컬러:001 / 사이즈:95(M) / 컬러:블랙              5
사이즈:095 / 컬러:더스티그린                      5
컬러:001 / 사이즈:90(S) / 컬러:그레이             5
컬러:001 / 사이즈:105(XL) / 컬러:블랙            5
사이즈:M(095) / 컬러:화이트                     5
사이즈:95(M) / 컬러:412 / 컬러:핑크              5
사이즈:100 / 컬러:오렌지                        5
사이즈:95(M) / 컬러:다크베이지                    5
사이즈:270 / 컬러:그레이                        5
사이즈:290 / 컬러:화이트                        5
size:250 / 컬러:화이트                       5
사이즈:235 / 컬러:001 / 컬러:브라운               5
사이즈:105(XL) / 컬러:452 / 컬러:블루            5
사이즈:260 / 컬러:그레이                        5
사이즈:105(XL) / 컬러:452 / 컬러:그린            5
사이즈:000(Free) / 컬러:핑크                   5
사이즈:105 / 컬러:BLK / 컬러:블랙                5
사이즈:110 / 컬러:BLK / 컬러:블랙                5
사이즈:WM(W80) / 컬러:브라운                    5
사이즈:085 / 컬러:블랙                         5
사이즈:95(M) / 컬러:412 / 컬러:블랙              5
사이즈:090 / 컬러:BLK / 컬러:다크그린              5
컬러:001 / 사이즈:90(S) / 컬러:화이트             5
사이즈:95(M) / 컬러:412 / 컬러:화이트             5
사이즈:255 / 컬러:블랙                         5
사이즈:280 / 컬러:블랙                         5
사이즈:090 / 컬러:BLK / 컬러:더스티그린             5
사이즈:235 / 컬러:370 / 컬러:베이지               5
사이즈:240 / 컬러:001 / 컬러:베이지               5
size:250 / 컬러:베이지                       5
사이즈:095 / 컬러:LML / 컬러:페일블루              5
사이즈:090 / 컬러:LML / 컬러:페일블루              5
사이즈:105(XL) / 컬러:452 / 컬러:블랙            5
size:260 / 컬러:블랙                        5
size:230 / 컬러:블랙                        5
컬러:031 / 사이즈:90(S) / 컬러:블랙              5
사이즈:255 / 컬러:001 / 컬러:블랙                5
사이즈:245 / 컬러:370 / 컬러:블랙                5
사이즈:280 / 컬러:001 / 컬러:블랙                5
사이즈:105(XL) / 컬러:452 / 컬러:크림            5
사이즈:WS(W85) / 컬러:블루                     5
사이즈:XL(105) / 컬러:브라운                    5
사이즈:250 / 컬러:001 / 컬러:그린                5
사이즈:245 / 컬러:370 / 컬러:그린                5
사이즈:265 / 컬러:001 / 컬러:블랙                5
사이즈:235 / 컬러:370 / 컬러:핑크                5
사이즈:105(XL) / 컬러:452 / 컬러:브라운           5
사이즈:235 / 컬러:001 / 컬러:옐로우               5
사이즈:245 / 컬러:옐로우                        5
사이즈:L(100) / 컬러:레드                      5
사이즈:95(M) / 컬러:브라운                      5
사이즈:230 / 컬러:217 / 컬러:핑크                5
size:090 / 컬러:라이트멜란지                    5
사이즈:95(M) / 컬러:412 / 컬러:그레이             5
사이즈:240 / 컬러:218 / 컬러:브라운               5
사이즈:245 / 컬러:100 / 컬러:브라운               5
사이즈:230 / 컬러:218 / 컬러:브라운               5
사이즈:000(Free) / 컬러:370 / 컬러:그린          5
size:000(Free) / 컬러:그린                  5
사이즈:95(M) / 컬러:민트, 블루                   5
컬러:001 / 사이즈:90(S) / 컬러:민트, 블루          5
컬러:001 / 사이즈:90(S) / 컬러:핑크              5
사이즈:095 / 컬러:LML / 컬러:드라이로즈             5
사이즈:090 / 컬러:LML / 컬러:드라이로즈             5
사이즈:230 / 컬러:217 / 컬러:옐로우               5
컬러:001 / 사이즈:L(100) / 컬러:블랙             5
사이즈:090 / 컬러:BLK / 컬러:오렌지               5
사이즈:235 / 컬러:370 / 컬러:그린                5
사이즈:235 / 컬러:370 / 컬러:화이트               5
사이즈:95(M) / 컬러:라이트브라운                   5
사이즈:230 / 컬러:217 / 컬러:화이트               5
사이즈:235 / 컬러:370 / 컬러:블랙                5
사이즈:95(M) / 컬러:412 / 컬러:블루              4
사이즈:255 / 컬러:219 / 컬러:블루                4
사이즈:225 / 컬러:219 / 컬러:블루                4
사이즈:245 / 컬러:370 / 컬러:블루                4
사이즈:245 / 컬러:블루                         4
사이즈:260 / 컬러:블루                         4
size:090 / 컬러:블랙                        4
사이즈:095 / 컬러:퍼플리시블루                     4
컬러:001 / 사이즈:90(S) / 컬러:크림              4
사이즈:235 / 컬러:001 / 컬러:화이트               4
사이즈:090 / 컬러:RED / 컬러:다크그린              4
컬러:001 / 사이즈:XL(95) / 컬러:블랙             4
사이즈:090 / 컬러:RED / 컬러:블랙                4
사이즈:80A / 컬러:블랙                         4
사이즈:95(M) / 컬러:066 / 컬러:블랙              4
컬러:650 / 사이즈:95(M) / 컬러:블랙              4
size:090 / 컬러:레드                        4
사이즈:95(M) / 컬러:066 / 컬러:그레이             4
컬러:650 / 사이즈:95(M) / 컬러:그레이             4
사이즈:270 / 컬러:그린                         4
사이즈:105(XL)                             4
컬러:031 / 사이즈:90(S)                      4
사이즈:260 / 컬러:베이지                        4
컬러:650 / 사이즈:95(M) / 컬러:핑크              4
사이즈:95(M) / 컬러:066 / 컬러:핑크              4
사이즈:090 / 컬러:RED / 컬러:오렌지               4
사이즈:090 / 컬러:RED / 컬러:화이트               4
사이즈:265 / 컬러:그레이                        4
컬러:001 / 사이즈:100(L)                     4
사이즈:105 / 컬러:블랙                         4
사이즈:090 / 컬러:우드                         4
사이즈:090 / 컬러:LML / 컬러:더스티그린             4
사이즈:095 / 컬러:LML / 컬러:더스티그린             4
사이즈:275 / 컬러:블랙                         4
size:95(M) / 컬러:레드                      4
사이즈:WM(W80) / 컬러:블루                     4
사이즈:240 / 컬러:031 / 컬러:그레이               4
사이즈:95(M) / 컬러:민트                       4
사이즈:255 / 컬러:219 / 컬러:베이지               4
사이즈:225 / 컬러:219 / 컬러:베이지               4
사이즈:245 / 컬러:370 / 컬러:베이지               4
사이즈:225 / 컬러:베이지                        4
사이즈:270 / 컬러:001 / 컬러:베이지               4
사이즈:220 / 컬러:베이지                        4
사이즈:230 / 컬러:260 / 컬러:베이지               4
사이즈:090 / 컬러:CRM / 컬러:페일블루              4
사이즈:090 / 컬러:DRO / 컬러:페일블루              4
사이즈:090 / 컬러:DRO / 컬러:블랙                4
사이즈:090 / 컬러:CRM / 컬러:블랙                4
사이즈:090 / 컬러:CRM / 컬러:크림                4
사이즈:095 / 컬러:LML / 컬러:크림                4
사이즈:090 / 컬러:LML / 컬러:크림                4
사이즈:090 / 컬러:DRO / 컬러:크림                4
size:090 / 컬러:화이트                       4
사이즈:095 / 컬러:LML / 컬러:화이트               4
size:100(L) / 컬러:핑크                     4
size:250 / 컬러:블랙                        4
사이즈:WS(W85) / 컬러:브라운                    4
사이즈:WL(W95) / 컬러:브라운                    4
사이즈:290 / 컬러:블랙                         4
사이즈:100                                 4
사이즈:090 / 컬러:RED / 컬러:레드                4
size:230 / 컬러:그레이                       4
size:100(L) / 컬러:그린                     4
사이즈:XL(105) / 컬러:레드                     4
사이즈:000 / 컬러:BLK / 컬러:스카이블루             4
사이즈:090 / 컬러:DRO / 컬러:라이트멜란지            4
사이즈:090 / 컬러:DTG / 컬러:라이트멜란지            4
사이즈:090 / 컬러:CRM / 컬러:라이트멜란지            4

In [45]:
# 데이터 타입 정리
display(df_review_fila_D2C.info())
display(df_review_fila_D2C.head(2))

# collect_date, post_date
df_review_fila_D2C['collect_date'] = pd.to_datetime(df_review_fila_D2C['collect_date']).dt.normalize().dt.tz_localize(None)
df_review_fila_D2C['post_date'] = pd.to_datetime(df_review_fila_D2C['post_date']).dt.normalize().dt.tz_localize(None)

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 48244 non-null  int64
 1   collect_date              48244 non-null  str
 2   post_date                 48244 non-null  str
 3   platform                  48244 non-null  str
 4   search_keyword            48244 non-null  str
 5   content                   48244 non-null  str
 6   source_url                48244 non-null  str
 7   rating                    48244 non-null  int64
 8   helpful_count             48244 non-null  int64
 9   purchased_option          7036 non-null   str
 10  has_image                 48244 non-null  int64
 11  product_id                48244 non-null  str
 12  product_name              48244 non-null  str
 13  raw_colors                46300 non-null  str
 14  purchase_option_combined  46530 non-null  str
dtypes: int64(4), str(11)
memory usage: 22.4 MB

None

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,product_id,product_name,raw_colors,purchase_option_combined
0,123617,2026-04-23,2025-07-07,자사몰리뷰,1170fi4ith2659flsa,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,NaN
1,142021,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,사이즈:105

In [46]:
# platform 데이터 변경 (다른 데이터도 변경했는지 확인해보기)
df_review_fila_D2C['platform'].value_counts()

df_review_fila_D2C['platform'] = df_review_fila_D2C['platform'].map({
    '자사몰리뷰' : '자사몰',
    '무신사리뷰' : '무신사',
    '네이버리뷰' : '네이버스토어',
    '인스타그램' : '인스타그램'
})

# <기존 데이터>
# platform
# 자사몰리뷰    23130
# 무신사리뷰    14663
# 네이버리뷰     8317
# 인스타그램     2134

# <변경 후 데이터>
# 자사몰       23130
# 무신사       14663
# 네이버스토어     8317
# 인스타그램      2134

In [47]:
# purchase_option_combined만 남기고 raw_colors, purchased_option는 지우기
df_review_fila_D2C = df_review_fila_D2C.drop(['raw_colors', 'purchased_option'], axis=1)

df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 48244 non-null  int64
 1   collect_date              48244 non-null  datetime64[us]
 2   post_date                 48244 non-null  datetime64[us]
 3   platform                  48244 non-null  str
 4   search_keyword            48244 non-null  str
 5   content                   48244 non-null  str
 6   source_url                48244 non-null  str
 7   rating                    48244 non-null  int64
 8   helpful_count             48244 non-null  int64
 9   has_image                 48244 non-null  int64
 10  product_id                48244 non-null  str
 11  product_name              48244 non-null  str
 12  purchase_option_combined  46530 non-null  str
dtypes: datetime64[us](2), int64(4), str(7)
memory usage: 20.0 MB

In [48]:
# post_date 파생컬럼 만들기 year, month
df_review_fila_D2C['year'] = df_review_fila_D2C['post_date'].dt.year
df_review_fila_D2C['month'] = df_review_fila_D2C['post_date'].dt.month

In [49]:
df_review_fila_D2C = df_review_fila_D2C.drop(['search_keyword'], axis=1)

In [15]:
df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 48244 non-null  int64
 1   collect_date              48244 non-null  datetime64[us]
 2   post_date                 48244 non-null  datetime64[us]
 3   platform                  48244 non-null  str
 4   content                   48244 non-null  str
 5   source_url                48244 non-null  str
 6   rating                    48244 non-null  int64
 7   helpful_count             48244 non-null  int64
 8   has_image                 48244 non-null  int64
 9   product_id                48244 non-null  str
 10  product_name              48244 non-null  str
 11  purchase_option_combined  46530 non-null  str
 12  year                      48244 non-null  int32
 13  month                     48244 non-null  int32
dtypes: datetime64[us](2), int32(2), int64(4), str(6)
memory usage: 19.1 MB

In [50]:
# 컬럼명 수정
df_review_fila_D2C = df_review_fila_D2C.rename(columns={
    'post_date' : 'review_date',
    'content' : 'review_body',
    'source_url' : 'product_url',
    'purchase_option_combined' : 'purchase_option',
})

df_review_fila_D2C.head(2)

,review_id,collect_date,review_date,platform,review_body,product_url,rating,helpful_count,has_image,product_id,product_name,purchase_option,year,month
0,123617,2026-04-23,2025-07-07,자사몰,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,2025,7
1,142021,2026-04-23,2026-04-03,자사몰,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,사이즈:105,2026,4

In [51]:
# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'review_body', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_D2C.columns:
        df_review_fila_D2C[col] = None

# 컬럼 순서 정리
df_review_fila_D2C = df_review_fila_D2C[required_columns]

In [52]:
# 확인
df_review_fila_D2C.info()
df_review_fila_D2C.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       48244 non-null  datetime64[us]
 1   platform           48244 non-null  str
 2   review_id          48244 non-null  int64
 3   product_id         48244 non-null  str
 4   product_name       48244 non-null  str
 5   review_date        48244 non-null  datetime64[us]
 6   year               48244 non-null  int32
 7   month              48244 non-null  int32
 8   review_body        48244 non-null  str
 9   rating             48244 non-null  int64
 10  helpful_count      48244 non-null  int64
 11  has_image          48244 non-null  int64
 12  purchase_option    46530 non-null  str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        48244 non-null  str
dtypes: datetime64[us](2), int32(2), int64(4), object(4), str(6)
memory usage: 20.6+ MB

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,review_body,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-23,자사몰,123617,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,2025-07-07,2025,7,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,5,0,1,NaN,None,None,None,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
1,2026-04-23,자사몰,142021,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,2026-04-03,2026,4,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,5,0,1,사이즈:105,None,None,None,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
2,2026-04-23,자사몰,142012,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,2026-04-03,2026,4,색상이 파스텔톤으로 예쁩니다. 감촉이 부드럽고 시원한 느낌입니다. 세일기간에 구입하...,5,0,1,사이즈:105,None,None,None,None,https://www.fila.co.kr/product/1170fi4ith2659flsa

In [53]:
# 'purchase_option' NaN -> None으로 처리
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].astype(object)
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].fillna(None)

df_review_fila_D2C['purchase_option'].value_counts(dropna=False)

purchase_option
블랙                                   8340
브라운                                  5475
그레이                                  3646
화이트                                  2600
베이지                                  2550
크림                                   2250
핑크                                   2084
그린                                   1986
라이트멜란지                               1725
None                                 1714
블루                                   1411
퍼플                                   1117
페일블루                                  837
더스티그린                                 724
드라이로즈                                 645
레드                                    535
오트밀                                   436
우드                                    366
민트                                    339
라이트베이지                                335
라이트브라운                                297
다크레드                                  284
옐로우                                   272
인디안핑크                                 223
내추럴베이지                                156
다크베이지                                 148
퍼플리시블루                                122
더스트그린                                 122
오렌지                                   101
민트, 블루                                 73
페일핑크                                   72
다크그린                                   70
사이즈:95(M) / 컬러:블랙                      57
페일베이지                                  52
사이즈:095                                49
플럼                                     48
사이즈:95(M) / 컬러:핑크                      42
사이즈:240 / 컬러:화이트                       42
사이즈:240 / 컬러:그레이                       41
사이즈:240 / 컬러:핑크                        41
사이즈:270 / 컬러:화이트                       38
사이즈:240 / 컬러:219 / 컬러:브라운              38
사이즈:240 / 컬러:브라운                       37
사이즈:90(S) / 컬러:블랙                      36
사이즈:240 / 컬러:블랙                        36
사이즈:100(L) / 컬러:블랙                     33
사이즈:100(L) / 컬러:핑크                     32
사이즈:090                                31
사이즈:095 / 컬러:블랙                        31
컬러:001 / 사이즈:000(Free) / 컬러:블랙         31
사이즈:240 / 컬러:베이지                       31
컬러:001 / 사이즈:000(Free) / 컬러:화이트        31
사이즈:105                                30
사이즈:090 / 컬러:블랙                        29
사이즈:90(S) / 컬러:핑크                      29
사이즈:95(M) / 컬러:베이지                     29
사이즈:235 / 컬러:핑크                        29
사이즈:095 / 컬러:라이트멜란지                    28
사이즈:090 / 컬러:라이트멜란지                    28
사이즈:090 / 컬러:화이트                       27
사이즈:235 / 컬러:그레이                       27
사이즈:95(M) / 컬러:그린                      27
사이즈:105(XL) / 컬러:블랙                    26
사이즈:235 / 컬러:219 / 컬러:브라운              26
사이즈:265 / 컬러:화이트                       25
사이즈:250 / 컬러:그레이                       24
사이즈:090 / 컬러:레드                        23
사이즈:250 / 컬러:핑크                        23
사이즈:245 / 컬러:그레이                       22
사이즈:280 / 컬러:화이트                       22
사이즈:090 / 컬러:다크그린                      22
size:95(M) / 컬러:블랙                     22
사이즈:090 / 컬러:오렌지                       22
사이즈:100(L) / 컬러:화이트                    22
사이즈:245 / 컬러:핑크                        22
사이즈:250 / 컬러:화이트                       21
사이즈:235 / 컬러:베이지                       21
사이즈:245 / 컬러:219 / 컬러:브라운              21
사이즈:000(Free) / 컬러:블랙                  20
사이즈:100(L) / 컬러:그린                     20
사이즈:100(L) / 컬러:베이지                    20
사이즈:95(M) / 컬러:그레이                     19
사이즈:105(XL) / 컬러:그린                    19
사이즈:90(S) / 컬러:그린                      19
사이즈:235 / 컬러:브라운                       19
사이즈:100 / 컬러:블랙                        18
사이즈:L(100) / 컬러:블루                     18
사이즈:250 / 컬러:베이지                       18
사이즈:240 / 컬러:001 / 컬러:블랙               18
사이즈:250 / 컬러:블랙                        18
사이즈:245 / 컬러:베이지                       18
오프화이트                                  18
사이즈:105(XL) / 컬러:핑크                    18
사이즈:090 / 컬러:BLK / 컬러:라이트멜란지           18
사이즈:90(S) / 컬러:베이지                     18
사이즈:105(XL) / 컬러:베이지                   18
사이즈:250 / 컬러:219 / 컬러:브라운              18
사이즈:235 / 컬러:화이트                       17
사이즈:230 / 컬러:브라운                       17
사이즈:WM(W90) / 컬러:화이트                   17
사이즈:95(M) / 컬러:화이트                     17
사이즈:230 / 컬러:베이지                       17
사이즈:270 / 컬러:핑크                        17
사이즈:230 / 컬러:핑크                        17
사이즈:275 / 컬러:화이트                       16
사이즈:260 / 컬러:화이트                       16
사이즈:000(Free) / 컬러:화이트                 16
사이즈:235 / 컬러:블랙                        16
사이즈:WM(W90) / 컬러:블루                    16
사이즈:230 / 컬러:블랙                        16
사이즈:095 / 컬러:BLK / 컬러:블랙               15
사이즈:230 / 컬러:화이트                       15
사이즈:L(100) / 컬러:블랙                     15
사이즈:235 / 컬러:370 / 컬러:브라운              15
사이즈:250 / 컬러:브라운                       15
사이즈:245 / 컬러:브라운                       15
사이즈:230 / 컬러:그레이                       14
사이즈:090 / 컬러:BLK / 컬러:블랙               14
사이즈:XL(105) / 컬러:블랙                    14
사이즈:245 / 컬러:블랙                        14
사이즈:095 / 컬러:BLK / 컬러:라이트멜란지           14
사이즈:100 / 컬러:라이트멜란지                    14
사이즈:100(L) / 컬러:그레이                    13
사이즈:L(100) / 컬러:화이트                    13
size:95(M)                             13
사이즈:270 / 컬러:블랙                        13
사이즈:240 / 컬러:219 / 컬러:베이지              13
사이즈:100(L) / 컬러:블루                     13
사이즈:090 / 컬러:LML / 컬러:라이트멜란지           13
사이즈:265 / 컬러:핑크                        13
사이즈:240 / 컬러:219 / 컬러:그린               13
사이즈:95(M) / 컬러:블루                      12
사이즈:240 / 컬러:219 / 컬러:블루               12
사이즈:240 / 컬러:블루                        12
사이즈:095 / 컬러:LML / 컬러:블랙               12
사이즈:090 / 컬러:LML / 컬러:블랙               12
컬러:001 / 사이즈:100(L) / 컬러:블랙            12
사이즈:95(M)                              12
사이즈:240 / 컬러:001 / 컬러:브라운              12
사이즈:90(S) / 컬러:화이트                     12
사이즈:000(Free) / 컬러:블루                  12
사이즈:WM(W90) / 컬러:브라운                   12
스카이블루                                  12
사이즈:095 / 컬러:LML / 컬러:라이트멜란지           12
사이즈:240 / 컬러:그린                        12
사이즈:240 / 컬러:219 / 컬러:핑크               12
사이즈:255 / 컬러:219 / 컬러:브라운              12
사이즈:225 / 컬러:219 / 컬러:브라운              12
사이즈:245 / 컬러:370 / 컬러:브라운              12
사이즈:245 / 컬러:217 / 컬러:브라운              12
사이즈:WM(W90) / 컬러:레드                    12
사이즈:240 / 컬러:219 / 컬러:화이트              12
사이즈:240 / 컬러:219 / 컬러:블랙               12
사이즈:L(90) / 컬러:블랙                      11
size:95(M) / 컬러:크림                     11
사이즈:90(S) / 컬러:그레이                     11
사이즈:270 / 컬러:001 / 컬러:브라운              11
사이즈:WM(W90) / 컬러:블랙                    11
size:100(L) / 컬러:블랙                    11
size:240 / 컬러:브라운                      11
사이즈:255 / 컬러:그레이                       11
size:235 / 컬러:브라운                      11
사이즈:095 / 컬러:화이트                       11
컬러:001 / 사이즈:90(S) / 컬러:블랙             10
사이즈:XL(105) / 컬러:화이트                   10
사이즈:095 / 컬러:라이트베이지                    10
사이즈:WM(W80) / 컬러:블랙                    10
사이즈:245 / 컬러:화이트                       10
컬러:032 / 사이즈:90(S) / 컬러:블랙             10
사이즈:235 / 컬러:001 / 컬러:블랙               10
사이즈:240 / 컬러:001 / 컬러:그린               10
사이즈:095 / 컬러:다크레드                      10
사이즈:240 / 컬러:옐로우                       10
사이즈:000 / 컬러:BLK / 컬러:블랙               10
사이즈:240 / 컬러:370 / 컬러:브라운              10
사이즈:230 / 컬러:217 / 컬러:브라운              10
사이즈:90(S) / 컬러:블루                       9
사이즈:95(M) / 컬러:크림                       9
size:90(S) / 컬러:블랙                      9
사이즈:270 / 컬러:001 / 컬러:블랙                9
사이즈:235 / 컬러:219 / 컬러:베이지               9
사이즈:090 / 컬러:BLK / 컬러:화이트               9
사이즈:265 / 컬러:브라운                        9
size:105(XL) / 컬러:블랙                    9
사이즈:230 / 컬러:그린                         9
사이즈:240 / 컬러:001 / 컬러:옐로우               9
사이즈:230 / 컬러:219 / 컬러:브라운               9
사이즈:250 / 컬러:370 / 컬러:브라운               9
사이즈:235 / 컬러:217 / 컬러:브라운               9
사이즈:235 / 컬러:219 / 컬러:그린                9
사이즈:235 / 컬러:219 / 컬러:블루                8
size:105(XL) / 컬러:크림                    8
컬러:032 / 사이즈:90(S) / 컬러:크림              8
사이즈:95(M) / 컬러:레드                       8
사이즈:095 / 컬러:레드                         8
size:105(XL)                            8
사이즈:240 / 컬러:217 / 컬러:브라운               8
size:000(Free) / 컬러:블랙                  8
사이즈:WS(W85) / 컬러:화이트                    8
사이즈:095 / 컬러:다크그린                       8
사이즈:090 / 컬러:BLK / 컬러:퍼플                8
사이즈:245 / 컬러:001 / 컬러:블랙                8
사이즈:260 / 컬러:블랙                         8
size:240 / 컬러:블랙                        8
사이즈:265 / 컬러:블랙                         8
사이즈:100 / 컬러:WHI                        8
사이즈:240 / 컬러:370 / 컬러:블랙                8
사이즈:WL(W95) / 컬러:화이트                    8
사이즈:275 / 컬러:핑크                         8
사이즈:280 / 컬러:핑크                         8
사이즈:260 / 컬러:핑크                         8
사이즈:240 / 컬러:370 / 컬러:그린                8
사이즈:235 / 컬러:그린                         8
사이즈:235 / 컬러:219 / 컬러:핑크                8
사이즈:260 / 컬러:100 / 컬러:화이트               8
사이즈:100 / 컬러:다크레드                       8
사이즈:090 / 컬러:LML / 컬러:화이트               8
사이즈:250 / 컬러:101 / 컬러:화이트               8
size:250 / 컬러:브라운                       8
size:000(Free) / 컬러:화이트                 8
사이즈:000(Free) / 컬러:217 / 컬러:화이트         8
사이즈:095 / 컬러:오렌지                        8
사이즈:235 / 컬러:219 / 컬러:화이트               8
사이즈:250 / 컬러:217 / 컬러:브라운               8
차콜그레이                                   8
사이즈:000(Free) / 컬러:217 / 컬러:블랙          8
핫핑크                                     8
사이즈:235 / 컬러:219 / 컬러:블랙                8
컬러:001 / 사이즈:100(L) / 컬러:핑크             7
size:95(M) / 컬러:핑크                      7
사이즈:245 / 컬러:219 / 컬러:블루                7
컬러:001 / 사이즈:100(L) / 컬러:그레이            7
size:90(S) / 컬러:크림                      7
사이즈:255 / 컬러:화이트                        7
사이즈:090 / 컬러:LML / 컬러:레드                7
사이즈:090 / 컬러:BLK / 컬러:레드                7
사이즈:100 / 컬러:라이트베이지                     7
컬러:032 / 사이즈:90(S)                      7
size:95(M) / 컬러:화이트                     7
size:95(M) / 컬러:그레이                     7
컬러:150 / 사이즈:000(Free) / 컬러:블랙          7
컬러:001 / 사이즈:100(L) / 컬러:화이트            7
사이즈:260 / 컬러:001 / 컬러:블랙                7
사이즈:250 / 컬러:001 / 컬러:블랙                7
사이즈:245 / 컬러:219 / 컬러:베이지               7
사이즈:L(90) / 컬러:블루                       7
사이즈:240 / 컬러:101 / 컬러:화이트               7
size:95(M) / 컬러:브라운                     7
사이즈:100 / 컬러:BLK / 컬러:블랙                7
사이즈:255 / 컬러:핑크                         7
사이즈:245 / 컬러:그린                         7
사이즈:000(Free) / 컬러:브라운                  7
사이즈:095 / 컬러:페일블루                       7
사이즈:245 / 컬러:219 / 컬러:핑크                7
컬러:150 / 사이즈:000(Free) / 컬러:화이트         7
사이즈:255 / 컬러:001 / 컬러:브라운               7
size:230 / 컬러:브라운                       7
사이즈:095 / 컬러:드라이로즈                      7
사이즈:245 / 컬러:219 / 컬러:그린                7
사이즈:245 / 컬러:219 / 컬러:화이트               7
사이즈:095 / 컬러:크림                         7
사이즈:000 / 컬러:BLK / 컬러:오프화이트             7
사이즈:245 / 컬러:219 / 컬러:블랙                7
사이즈:250 / 컬러:219 / 컬러:블루                6
사이즈:230 / 컬러:블루                         6
사이즈:90(S) / 컬러:크림                       6
사이즈:240 / 컬러:100 / 컬러:화이트               6
컬러:001 / 사이즈:M(085) / 컬러:블랙             6
사이즈:100(L) / 컬러:레드                      6
size:100(L)                             6
size:90(S)                              6
size:245 / 컬러:화이트                       6
사이즈:090 / 컬러:LML / 컬러:다크그린              6
사이즈:000(Free) / 컬러:베이지                  6
사이즈:90(S)                               6
컬러:001 / 사이즈:M(085) / 컬러:블루             6
사이즈:250 / 컬러:219 / 컬러:베이지               6
size:240 / 컬러:베이지                       6
사이즈:090 / 컬러:BLK / 컬러:페일블루              6
사이즈:090 / 컬러:BLK / 컬러:크림                6
사이즈:095 / 컬러:BLK / 컬러:화이트               6
사이즈:M(095) / 컬러:블루                      6
사이즈:000(Free) / 컬러:그레이                  6
사이즈:100 / 컬러:화이트                        6
사이즈:100 / 컬러:레드                         6
size:240 / 컬러:그레이                       6
사이즈:100 / 컬러:MIT / 컬러:민트                6
사이즈:235 / 컬러:001 / 컬러:그린                6
사이즈:245 / 컬러:001 / 컬러:그린                6
사이즈:250 / 컬러:그린                         6
컬러:001 / 사이즈:000(Free) / 컬러:브라운         6
사이즈:WL(W95) / 컬러:블랙                     6
사이즈:250 / 컬러:219 / 컬러:핑크                6
사이즈:L(100) / 컬러:핑크                      6
사이즈:260 / 컬러:브라운                        6
사이즈:XL(105) / 컬러:블루                     6
사이즈:WS(W75) / 컬러:블랙                     6
사이즈:235 / 컬러:옐로우                        6
사이즈:XL(95) / 컬러:블랙                      6
사이즈:240 / 컬러:102 / 컬러:화이트               6
사이즈:225 / 컬러:그레이                        6
컬러:422 / 사이즈:95(M) / 컬러:블루              6
size:95(M) / 컬러:베이지                     6
사이즈:90(S) / 컬러:레드                       6
사이즈:240 / 컬러:001 / 컬러:화이트               6
사이즈:245 / 컬러:001 / 컬러:브라운               6
사이즈:220 / 컬러:브라운                        6
사이즈:275 / 컬러:브라운                        6
사이즈:220 / 컬러:219 / 컬러:브라운               6
사이즈:270 / 컬러:219 / 컬러:브라운               6
사이즈:250 / 컬러:001 / 컬러:브라운               6
사이즈:90(S) / 컬러:민트, 블루                   6
사이즈:090 / 컬러:BLK / 컬러:드라이로즈             6
사이즈:M(095) / 컬러:블랙                      6
사이즈:090 / 컬러:LML / 컬러:오렌지               6
사이즈:250 / 컬러:219 / 컬러:그린                6
사이즈:WL(W95) / 컬러:블루                     6
사이즈:250 / 컬러:219 / 컬러:화이트               6
컬러:001 / 사이즈:WM(W90) / 컬러:블랙            6
사이즈:270 / 컬러:브라운                        6
사이즈:265 / 컬러:217 / 컬러:브라운               6
사이즈:255 / 컬러:베이지                        6
사이즈:250 / 컬러:219 / 컬러:블랙                6
컬러:001 / 사이즈:90(S) / 컬러:블루              5
컬러:001 / 사이즈:100(L) / 컬러:블루             5
사이즈:235 / 컬러:370 / 컬러:블루                5
사이즈:250 / 컬러:블루                         5
사이즈:235 / 컬러:블루                         5
사이즈:95(M) / 컬러:내추럴베이지                   5
컬러:031 / 사이즈:90(S) / 컬러:크림              5
사이즈:105(XL) / 컬러:크림                     5
size:100(L) / 컬러:크림                     5
사이즈:100 / 컬러:다크그린                       5
사이즈:105(XL) / 컬러:452 / 컬러:레드            5
컬러:001 / 사이즈:95(M) / 컬러:블랙              5
사이즈:095 / 컬러:더스티그린                      5
컬러:001 / 사이즈:90(S) / 컬러:그레이             5
컬러:001 / 사이즈:105(XL) / 컬러:블랙            5
사이즈:M(095) / 컬러:화이트                     5
사이즈:95(M) / 컬러:412 / 컬러:핑크              5
사이즈:100 / 컬러:오렌지                        5
사이즈:95(M) / 컬러:다크베이지                    5
사이즈:270 / 컬러:그레이                        5
사이즈:290 / 컬러:화이트                        5
size:250 / 컬러:화이트                       5
사이즈:235 / 컬러:001 / 컬러:브라운               5
사이즈:105(XL) / 컬러:452 / 컬러:블루            5
사이즈:260 / 컬러:그레이                        5
사이즈:105(XL) / 컬러:452 / 컬러:그린            5
사이즈:000(Free) / 컬러:핑크                   5
사이즈:105 / 컬러:BLK / 컬러:블랙                5
사이즈:110 / 컬러:BLK / 컬러:블랙                5
사이즈:WM(W80) / 컬러:브라운                    5
사이즈:085 / 컬러:블랙                         5
사이즈:95(M) / 컬러:412 / 컬러:블랙              5
사이즈:090 / 컬러:BLK / 컬러:다크그린              5
컬러:001 / 사이즈:90(S) / 컬러:화이트             5
사이즈:95(M) / 컬러:412 / 컬러:화이트             5
사이즈:255 / 컬러:블랙                         5
사이즈:280 / 컬러:블랙                         5
사이즈:090 / 컬러:BLK / 컬러:더스티그린             5
사이즈:235 / 컬러:370 / 컬러:베이지               5
사이즈:240 / 컬러:001 / 컬러:베이지               5
size:250 / 컬러:베이지                       5
사이즈:095 / 컬러:LML / 컬러:페일블루              5
사이즈:090 / 컬러:LML / 컬러:페일블루              5
사이즈:105(XL) / 컬러:452 / 컬러:블랙            5
size:260 / 컬러:블랙                        5
size:230 / 컬러:블랙                        5
컬러:031 / 사이즈:90(S) / 컬러:블랙              5
사이즈:255 / 컬러:001 / 컬러:블랙                5
사이즈:245 / 컬러:370 / 컬러:블랙                5
사이즈:280 / 컬러:001 / 컬러:블랙                5
사이즈:105(XL) / 컬러:452 / 컬러:크림            5
사이즈:WS(W85) / 컬러:블루                     5
사이즈:XL(105) / 컬러:브라운                    5
사이즈:250 / 컬러:001 / 컬러:그린                5
사이즈:245 / 컬러:370 / 컬러:그린                5
사이즈:265 / 컬러:001 / 컬러:블랙                5
사이즈:235 / 컬러:370 / 컬러:핑크                5
사이즈:105(XL) / 컬러:452 / 컬러:브라운           5
사이즈:235 / 컬러:001 / 컬러:옐로우               5
사이즈:245 / 컬러:옐로우                        5
사이즈:L(100) / 컬러:레드                      5
사이즈:95(M) / 컬러:브라운                      5
사이즈:230 / 컬러:217 / 컬러:핑크                5
size:090 / 컬러:라이트멜란지                    5
사이즈:95(M) / 컬러:412 / 컬러:그레이             5
사이즈:240 / 컬러:218 / 컬러:브라운               5
사이즈:245 / 컬러:100 / 컬러:브라운               5
사이즈:230 / 컬러:218 / 컬러:브라운               5
사이즈:000(Free) / 컬러:370 / 컬러:그린          5
size:000(Free) / 컬러:그린                  5
사이즈:95(M) / 컬러:민트, 블루                   5
컬러:001 / 사이즈:90(S) / 컬러:민트, 블루          5
컬러:001 / 사이즈:90(S) / 컬러:핑크              5
사이즈:095 / 컬러:LML / 컬러:드라이로즈             5
사이즈:090 / 컬러:LML / 컬러:드라이로즈             5
사이즈:230 / 컬러:217 / 컬러:옐로우               5
컬러:001 / 사이즈:L(100) / 컬러:블랙             5
사이즈:090 / 컬러:BLK / 컬러:오렌지               5
사이즈:235 / 컬러:370 / 컬러:그린                5
사이즈:235 / 컬러:370 / 컬러:화이트               5
사이즈:95(M) / 컬러:라이트브라운                   5
사이즈:230 / 컬러:217 / 컬러:화이트               5
사이즈:235 / 컬러:370 / 컬러:블랙                5
사이즈:95(M) / 컬러:412 / 컬러:블루              4
사이즈:255 / 컬러:219 / 컬러:블루                4
사이즈:225 / 컬러:219 / 컬러:블루                4
사이즈:245 / 컬러:370 / 컬러:블루                4
사이즈:245 / 컬러:블루                         4
사이즈:260 / 컬러:블루                         4
size:090 / 컬러:블랙                        4
사이즈:095 / 컬러:퍼플리시블루                     4
컬러:001 / 사이즈:90(S) / 컬러:크림              4
사이즈:235 / 컬러:001 / 컬러:화이트               4
사이즈:090 / 컬러:RED / 컬러:다크그린              4
컬러:001 / 사이즈:XL(95) / 컬러:블랙             4
사이즈:090 / 컬러:RED / 컬러:블랙                4
사이즈:80A / 컬러:블랙                         4
사이즈:95(M) / 컬러:066 / 컬러:블랙              4
컬러:650 / 사이즈:95(M) / 컬러:블랙              4
size:090 / 컬러:레드                        4
사이즈:95(M) / 컬러:066 / 컬러:그레이             4
컬러:650 / 사이즈:95(M) / 컬러:그레이             4
사이즈:270 / 컬러:그린                         4
사이즈:105(XL)                             4
컬러:031 / 사이즈:90(S)                      4
사이즈:260 / 컬러:베이지                        4
컬러:650 / 사이즈:95(M) / 컬러:핑크              4
사이즈:95(M) / 컬러:066 / 컬러:핑크              4
사이즈:090 / 컬러:RED / 컬러:오렌지               4
사이즈:090 / 컬러:RED / 컬러:화이트               4
사이즈:265 / 컬러:그레이                        4
컬러:001 / 사이즈:100(L)                     4
사이즈:105 / 컬러:블랙                         4
사이즈:090 / 컬러:우드                         4
사이즈:090 / 컬러:LML / 컬러:더스티그린             4
사이즈:095 / 컬러:LML / 컬러:더스티그린             4
사이즈:275 / 컬러:블랙                         4
size:95(M) / 컬러:레드                      4
사이즈:WM(W80) / 컬러:블루                     4
사이즈:240 / 컬러:031 / 컬러:그레이               4
사이즈:95(M) / 컬러:민트                       4
사이즈:255 / 컬러:219 / 컬러:베이지               4
사이즈:225 / 컬러:219 / 컬러:베이지               4
사이즈:245 / 컬러:370 / 컬러:베이지               4
사이즈:225 / 컬러:베이지                        4
사이즈:270 / 컬러:001 / 컬러:베이지               4
사이즈:220 / 컬러:베이지                        4
사이즈:230 / 컬러:260 / 컬러:베이지               4
사이즈:090 / 컬러:CRM / 컬러:페일블루              4
사이즈:090 / 컬러:DRO / 컬러:페일블루              4
사이즈:090 / 컬러:DRO / 컬러:블랙                4
사이즈:090 / 컬러:CRM / 컬러:블랙                4
사이즈:090 / 컬러:CRM / 컬러:크림                4
사이즈:095 / 컬러:LML / 컬러:크림                4
사이즈:090 / 컬러:LML / 컬러:크림                4
사이즈:090 / 컬러:DRO / 컬러:크림                4
size:090 / 컬러:화이트                       4
사이즈:095 / 컬러:LML / 컬러:화이트               4
size:100(L) / 컬러:핑크                     4
size:250 / 컬러:블랙                        4
사이즈:WS(W85) / 컬러:브라운                    4
사이즈:WL(W95) / 컬러:브라운                    4
사이즈:290 / 컬러:블랙                         4
사이즈:100                                 4
사이즈:090 / 컬러:RED / 컬러:레드                4
size:230 / 컬러:그레이                       4
size:100(L) / 컬러:그린                     4
사이즈:XL(105) / 컬러:레드                     4
사이즈:000 / 컬러:BLK / 컬러:스카이블루             4
사이즈:090 / 컬러:DRO / 컬러:라이트멜란지            4
사이즈:090 / 컬러:DTG / 컬러:라이트멜란지            4
사이즈:090 / 컬러:CRM / 컬러:라이트멜란지            4

In [54]:
df_review_fila_D2C['purchase_option'].info() # 46530 + 1714 = 48244 >>>>>> None이 NaN으로 처리되고 있는 거 확인 완료

<class 'pandas.Series'>
RangeIndex: 48244 entries, 0 to 48243
Series name: purchase_option
Non-Null Count  Dtype
--------------  -----
46530 non-null  object
dtypes: object(1)
memory usage: 377.0+ KB

In [55]:
# 'purchase_option' == None

# 1) 데이터 확인
df_review_fila_D2C[df_review_fila_D2C['purchase_option'].isna()][['product_id', 'product_name', 'purchase_option', 'product_url']].head(10)

,product_id,product_name,purchase_option,product_url
0,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
3,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
4,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
6,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
7,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
8,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,None,https://www.fila.co.kr/product/1170fi4ith2659flsa
170,1170fi4pjh2609mblk,링클 체크 남성 파자마 세트,None,https://www.fila.co.kr/product/1170fi4pjh2609mblk
1440,1170fi253br01f008031,에센셜 클래식 노와이어 브라,None,https://www.fila.co.kr/product/1170fi253br01f0...
1441,1170fi253br01f008031,에센셜 클래식 노와이어 브라,None,https://www.fila.co.kr/product/1170fi253br01f0...
1443,1170fi253br01f008031,에센셜 클래식 노와이어 브라,None,https://www.fila.co.kr/product/1170fi253br01f0...

In [35]:
display(df_review_fila_D2C[df_review_fila_D2C['purchase_option'].isna()]['product_id'].value_counts())

product_id
1170fi253sk13f001031    268
1170fi253mp13f003032    240
1170fi253fz13f003031    238
1170fi253mp13f005031    238
1170fi253fz13f004031    237
1170fi253dr01f008031     78
1170fi4bah2450fwhi       52
1170fi4bah2450flle       52
1170fi4bah2450fblk       52
1170fi4bah2450fmab       52
1170fi253br01f008031     31
1170fi4rsh1145mdid       19
1170fi253dr01f007031     17
1170fi4poh1146mdid        9
1170fi4drh2657fsad        8
1170fi4drh2657fblk        8
1170fi253br01f011031      7
1170fi4ith2659flsa        6
1170fi4ith2659fdid        6
1170fi253br01f010031      6
1170fi253br01f001031      6
1170fi4drh2450fwhi        5
1170fi4drh2450flle        5
1170fi4drh2656fsad        5
1170fi4drh2656flvy        5
1170fi4drh2450fmab        5
1170fi4drh2656fblk        5
1170fi4tkh1143mdid        5
1170fi4drh2450fblk        5
1170fi4cah1148mdid        5
1170fi4ith2656flvy        4
1170fi4ith2656fblk        4
1170fi4ith2656fsad        4
1170fi253bf01f003031      3
1170fi4pjh2645flde        2
1170fi4drh2658flsa        2
1170fi4pjh2612mdpt        2
1170fi4drh2658fdid        2
1170fi261mt13f002031      2
1170fi4pjh2609mblk        1
1170fi4pjh2650fnay        1
1170fi4pjh2651frop        1
1170fi4oph2649frop        1
1170fi4pjh2641ftgr        1
1170fi4drh1142mdid        1
1170fi4pjh2608midb        1
1170fi4pjh2642ftgr        1
1170fi4pjh2643ftgr        1
1170fi4pjh2648fidb        1
1170fi4bah2657fblk        1
1170fi4pjh2609mdst        1
1170fi4bah2657fsad        1
1170fi261mp13f004031      1
Name: count, dtype: int64

In [ ]:
# 'purchase_option' == None
# 2) 검색해서 값 매칭
mapping = {
    '1170fi253sk13f001031' : '컬러:MOCHA',
    '1170fi253mp13f003032' : '컬러:MOCHA',
    '1170fi253fz13f003031' : '컬러:MOCHA',
    '1170fi253mp13f005031' : '컬러:MOCHA',
    '1170fi253fz13f004031' : '컬러:MOCHA',
    '1170fi253dr01f008031' : '컬러:LIGHT SAND', # 에센셜 클래식 사각 드로즈
    '1170fi4bah2450fwhi' : '컬러:화이트',
    '1170fi4bah2450flle' : '컬러:라이트레몬',
    '1170fi4bah2450fblk' : '컬러:블랙',
    '1170fi4bah2450fmab' : '컬러:마린블루',
    '1170fi253br01f008031' : '컬러:LIGHT SAND', # 에센셜 클래식 노와이어 브라
    '1170fi4rsh1145mdid' : '컬러:다크인디고',
    '1170fi253dr01f007031' : '컬러:LIGHT SAND', # 에센셜 클래식 햄 팬티
    '1170fi4poh1146mdid' : '컬러:다크인디고',
    '1170fi4drh2657fsad' : '컬러:샌드',
    '1170fi4drh2657fblk' : '컬러:블랙',
    '1170fi253br01f011031' : '컬러:LIGHT SAND', # 에센셜 클래식 베이직 브라
    '1170fi4ith2659flsa' : '컬러:라이트샌드', # 에어플러스 라이트 스트랩 브라탑
    '1170fi4ith2659fdid' : '컬러:다크인디고',
    '1170fi253br01f010031' : '컬러:LIGHT SAND', # 에센셜 클래식 하프컵 브라
    '1170fi253br01f001031' : '컬러:LIGHT SAND', # 에센셜 클래식 오프숄더 브라
    '1170fi4drh2450fwhi' : '컬러:화이트',
    '1170fi4drh2450flle' : '컬러:라이트레몬',
    '1170fi4drh2656fsad' : '컬러:샌드',
    '1170fi4drh2656flvy' : '컬러:라벤더그레이',
    '1170fi4drh2450fmab' : '컬러:마린블루',
    '1170fi4drh2656fblk' : '컬러:블랙',
    '1170fi4tkh1143mdid' : '컬러:다크인디고',
    '1170fi4drh2450fblk' : '컬러:블랙',
    '1170fi4cah1148mdid' : '컬러:다크인디고',
    '1170fi4ith2656flvy' : '컬러:라벤더그레이',
    '1170fi4ith2656fblk' : '컬러:블랙',
    '1170fi4ith2656fsad' : '컬러:샌드',
    '1170fi253bf01f003031' : '컬러:LIGHT SAND',
    '1170fi4pjh2645flde' : '컬러:라이트데님',
    '1170fi4drh2658flsa' : '컬러:라이트샌드', # 에어플러스 라이트 팬티
    '1170fi4pjh2612mdpt' : '컬러:딥틸',
    '1170fi4drh2658fdid' : '컬러:다크인디고',
    '1170fi261mt13f002031' : '컬러:MOCHA',
    '1170fi4pjh2609mblk' : '컬러:블랙',
    '1170fi4pjh2650fnay' : '컬러:네이비',
    '1170fi4pjh2651frop' : '컬러:로즈핑크',
    '1170fi4oph2649frop' : '컬러:로즈핑크',
    '1170fi4pjh2641ftgr' : '컬러:틸그린',
    '1170fi4drh1142mdid' : '컬러:다크인디고',
    '1170fi4pjh2608midb' : '컬러:인디고블루',
    '1170fi4pjh2642ftgr' : '컬러:틸그린',
    '1170fi4pjh2643ftgr' : '컬러:틸그린',
    '1170fi4pjh2648fidb' : '컬러:인디고블루',
    '1170fi4bah2657fblk' : '컬러:블랙',
    '1170fi4pjh2609mdst' : '컬러:다크스틸',
    '1170fi4bah2657fsad' : '컬러:샌드',
    '1170fi261mp13f004031' : '컬러:GRAY'
}

mask = df_review_fila_D2C['purchase_option'].isna()

df_review_fila_D2C.loc[mask, 'purchase_option'] = (
    df_review_fila_D2C.loc[mask, 'product_id'].map(mapping)
)

# df_review_fila_D2C['purchase_option'].isna().sum() >>>>>>>>>>> 결측치 사라진 것 확인 완료

In [63]:
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].astype(str)

In [64]:
df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       48244 non-null  datetime64[us]
 1   platform           48244 non-null  str
 2   review_id          48244 non-null  int64
 3   product_id         48244 non-null  str
 4   product_name       48244 non-null  str
 5   review_date        48244 non-null  datetime64[us]
 6   year               48244 non-null  int32
 7   month              48244 non-null  int32
 8   review_body        48244 non-null  str
 9   rating             48244 non-null  int64
 10  helpful_count      48244 non-null  int64
 11  has_image          48244 non-null  int64
 12  purchase_option    48244 non-null  str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        48244 non-null  str
dtypes: datetime64[us](2), int32(2), int64(4), object(4), str(6)
memory usage: 20.6+ MB

In [ ]:
df_review_fila_D2C_2024 = df_review_fila_D2C[df_review_fila_D2C['year'] >= 2024]

In [ ]:
df_review_fila_D2C.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final.csv", encoding='utf-8-sig', index=False)
df_review_fila_D2C_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final_s2024.csv", encoding='utf-8-sig', index=False)

---
# 휠라 무신사 리뷰 데이터

## 1. 전처리

In [90]:
df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv", encoding='utf-8')
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,...,option,helpful,comment_count,has_image,image_urls,survey_size,survey_width,survey_comfort,survey_instep,url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,스타일,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,기발한스웨덴웨지,NaN,...,Grey/White/White · 270,1,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,보통,아주 편안,https://www.musinsa.com/products/3892794#revie...
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,스타일,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,아트텍,NaN,...,Grey/White/White · 260,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,적당,https://www.musinsa.com/products/3892794#revie...
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,스타일,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,신중한하얀단화,NaN,...,Grey/White/White · 255,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,편안,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   collect_date    14100 non-null  str
 1   review_date     14100 non-null  str
 2   product_id      14100 non-null  int64
 3   product_name    14100 non-null  str
 4   review_no       14100 non-null  int64
 5   review_type     14100 non-null  str
 6   rating          14100 non-null  int64
 7   review_text     14090 non-null  str
 8   author          14100 non-null  str
 9   user_height     0 non-null      float64
 10  user_weight     0 non-null      float64
 11  option          14086 non-null  str
 12  helpful         14100 non-null  int64
 13  comment_count   14100 non-null  int64
 14  has_image       14100 non-null  bool
 15  image_urls      8621 non-null   str
 16  survey_size     4227 non-null   str
 17  survey_width    4227 non-null   str
 18  survey_comfort  4227 non-null   str
 19  survey_instep   4227 non-null   str
 20  url             14100 non-null  str
dtypes: bool(1), float64(2), int64(5), str(13)
memory usage: 7.6 MB

None

In [92]:
# 사용 컬럼 선정
df_review_fila_mss = df_review_fila_mss[['review_date', 'product_id', 'product_name', 'review_no', 'rating', 'review_text', 'url']]
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,review_date,product_id,product_name,review_no,rating,review_text,url
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_date   14100 non-null  str
 1   product_id    14100 non-null  int64
 2   product_name  14100 non-null  str
 3   review_no     14100 non-null  int64
 4   rating        14100 non-null  int64
 5   review_text   14090 non-null  str
 6   url           14100 non-null  str
dtypes: int64(3), str(4)
memory usage: 4.3 MB

None

In [94]:
# 결측치 처리
# 리뷰 분석이 중요하기 때문에 review_text가 null인 컬럼은 제거
df_review_fila_mss = df_review_fila_mss.dropna(subset=['review_text'], axis=0)
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_date   14090 non-null  str
 1   product_id    14090 non-null  int64
 2   product_name  14090 non-null  str
 3   review_no     14090 non-null  int64
 4   rating        14090 non-null  int64
 5   review_text   14090 non-null  str
 6   url           14090 non-null  str
dtypes: int64(3), str(4)
memory usage: 4.4 MB

In [98]:
# review_date 파생컬럼
df_review_fila_mss['review_date'] = pd.to_datetime(df_review_fila_mss['review_date'])

df_review_fila_mss['year'] = df_review_fila_mss['review_date'].dt.year
df_review_fila_mss['month'] = df_review_fila_mss['review_date'].dt.month

display(df_review_fila_mss.head())
display(df_review_fila_mss[['review_date', 'year', 'month']].info())

,review_date,product_id,product_name,review_no,rating,review_text,url,year,month
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...,2025,11
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...,2025,11
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...,2025,10
3,2025-10-13,3892794,에샤페 실버문(1XM02348H063),78679747,5,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,https://www.musinsa.com/products/3892794#revie...,2025,10
4,2025-10-12,3892794,에샤페 실버문(1XM02348H063),78939688,5,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,https://www.musinsa.com/products/3892794#revie...,2025,10

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_date  14090 non-null  datetime64[us]
 1   year         14090 non-null  int32
 2   month        14090 non-null  int32
dtypes: datetime64[us](1), int32(2)
memory usage: 330.2 KB

None

In [108]:
# 컬럼명 변경
df_review_fila_mss = df_review_fila_mss.rename(columns={
    'review_no' : 'review_id',
    'review_text' : 'review_body',
    'url' : 'product_url'
})

df_review_fila_mss.head()

,review_date,product_id,product_name,review_id,rating,review_body,product_url,year,month
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...,2025,11
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...,2025,11
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...,2025,10
3,2025-10-13,3892794,에샤페 실버문(1XM02348H063),78679747,5,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,https://www.musinsa.com/products/3892794#revie...,2025,10
4,2025-10-12,3892794,에샤페 실버문(1XM02348H063),78939688,5,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,https://www.musinsa.com/products/3892794#revie...,2025,10

In [109]:
# 컬럼순서 변경
df_review_fila_mss = df_review_fila_mss[['review_id', 'product_id', 'product_name', 'review_date', 'year', 'month', 'review_body', 'rating', 'product_url']]
df_review_fila_mss.head()

,review_id,product_id,product_name,review_date,year,month,review_body,rating,product_url
0,79849708,3892794,에샤페 실버문(1XM02348H063),2025-11-16,2025,11,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,5,https://www.musinsa.com/products/3892794#revie...
1,79753882,3892794,에샤페 실버문(1XM02348H063),2025-11-11,2025,11,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,5,https://www.musinsa.com/products/3892794#revie...
2,79033605,3892794,에샤페 실버문(1XM02348H063),2025-10-15,2025,10,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,5,https://www.musinsa.com/products/3892794#revie...
3,78679747,3892794,에샤페 실버문(1XM02348H063),2025-10-13,2025,10,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,5,https://www.musinsa.com/products/3892794#revie...
4,78939688,3892794,에샤페 실버문(1XM02348H063),2025-10-12,2025,10,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,5,https://www.musinsa.com/products/3892794#revie...

In [110]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_id     14090 non-null  int64
 1   product_id    14090 non-null  int64
 2   product_name  14090 non-null  str
 3   review_date   14090 non-null  datetime64[us]
 4   year          14090 non-null  int32
 5   month         14090 non-null  int32
 6   review_body   14090 non-null  str
 7   rating        14090 non-null  int64
 8   product_url   14090 non-null  str
dtypes: datetime64[us](1), int32(2), int64(3), str(3)
memory usage: 4.4 MB

In [120]:
# 이상치 확인
df_review_fila_mss['product_url'].value_counts()

product_url
https://www.musinsa.com/products/5311939#review_81270327    5
https://www.musinsa.com/products/5312026#review_81244311    5
https://www.musinsa.com/products/5312026#review_81248800    5
https://www.musinsa.com/products/5311939#review_81244528    5
https://www.musinsa.com/products/5312098#review_81069728    5
                                                           ..
https://www.musinsa.com/products/5311984#review_79605475    1
https://www.musinsa.com/products/5311984#review_79258458    1
https://www.musinsa.com/products/5311984#review_79198367    1
https://www.musinsa.com/products/5311984#review_78888434    1
https://www.musinsa.com/products/5311984#review_78378268    1
Name: count, Length: 8575, dtype: int64