In [2]:
import pandas as pd
import numpy as np

---
# 안다르 자사몰 리뷰 데이터

## 1. 전처리

In [17]:
# 안다르
df_review_andar_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/andar_reviews_final_new.csv")
display(df_review_andar_D2C.head(3))
display(df_review_andar_D2C.info())

,review_id,product_id,post_date,post_time,platform,brand,search_keyword,content,source_url,rating,...,media_count,main_content_type,upload_from,labels,topics,키,몸무게,평소사이즈,사이즈_평가,사이즈_한줄평
0,48724074,5147,2026-04-14,03:48:43,자사몰리뷰,안다르,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕",https://andar.co.kr/product/detail.html?product_no=5147,5,...,2,image,vreview-board,[],"['functionality', 'activity', 'color']",155~159cm,45~49kg,S,잘 맞아요,마사지하기 딱 좋은 사이즈!
1,48590531,5147,2026-04-07,17:50:41,네이버페이,안다르,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등록된 네이버 페이 구매평),https://andar.co.kr/product/detail.html?product_no=5147,3,...,0,text,api-ingest,[],['material'],NaN,NaN,NaN,NaN,NaN
2,48535840,5147,2026-04-05,10:10:20,자사몰리뷰,안다르,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워요 핑크조아~,https://andar.co.kr/product/detail.html?product_no=5147,5,...,1,image,vreview-board,['재구매'],"['activity', 'color']",165~169cm,55~59kg,M,잘 맞아요,좋아요

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   review_id          925663 non-null  int64
 1   product_id         925663 non-null  int64
 2   post_date          925663 non-null  str
 3   post_time          925663 non-null  str
 4   platform           925663 non-null  str
 5   brand              925663 non-null  str
 6   search_keyword     925663 non-null  str
 7   content            918763 non-null  str
 8   source_url         925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  purchased_option   750889 non-null  str
 12  has_image          925663 non-null  int64
 13  collect_date       925663 non-null  str
 14  title              676233 non-null  str
 15  user_nickname      925663 non-null  str
 16  media_count        925663 non-null  int64
 17  main_content_type  925663 non-null  str
 18  upload_from        925663 non-null  str
 19  labels             925663 non-null  str
 20  topics             925663 non-null  str
 21  키                  633734 non-null  str
 22  몸무게                624861 non-null  str
 23  평소사이즈              620967 non-null  str
 24  사이즈_평가             677892 non-null  str
 25  사이즈_한줄평            654363 non-null  str
dtypes: int64(6), str(20)
memory usage: 630.4 MB

None

In [18]:
# =======================================
# 사용할 컬럼만 선택
# =======================================
df_review_andar_D2C = df_review_andar_D2C.drop(['post_time', 'brand', 'user_nickname', 'media_count', 'main_content_type', 'upload_from', 'labels', 'topics', '평소사이즈', '사이즈_평가'], axis=1)
df_review_andar_D2C.head(3)

,review_id,product_id,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,collect_date,title,키,몸무게,사이즈_한줄평
0,48724074,5147,2026-04-14,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕",https://andar.co.kr/product/detail.html?product_no=5147,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,릴렉스 마사지 듀얼볼 Ⅱ 후기,155~159cm,45~49kg,마사지하기 딱 좋은 사이즈!
1,48590531,5147,2026-04-07,네이버페이,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등록된 네이버 페이 구매평),https://andar.co.kr/product/detail.html?product_no=5147,3,0,NaN,0,2026-04-21,보통,NaN,NaN,NaN
2,48535840,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워요 핑크조아~,https://andar.co.kr/product/detail.html?product_no=5147,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,릴렉스 마사지 듀얼볼 Ⅱ 후기,165~169cm,55~59kg,좋아요

In [19]:
# =======================================
# 리뷰 본문 합치기 => content + title, 사이즈_한줄평
# =======================================
# 합치기
df_review_andar_D2C['content'] = df_review_andar_D2C[['content', 'title', '사이즈_한줄평']].fillna('').agg(' '.join, axis=1).str.strip()

# 합친 컬럼 삭제하기
df_review_andar_D2C = df_review_andar_D2C.drop(['title', '사이즈_한줄평'], axis=1)

display(df_review_andar_D2C.head())

,review_id,product_id,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,collect_date,키,몸무게
0,48724074,5147,2026-04-14,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕 릴렉스 마사지 듀얼볼 Ⅱ 후기 마사지하기 딱 좋은 사이즈!",https://andar.co.kr/product/detail.html?product_no=5147,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,155~159cm,45~49kg
1,48590531,5147,2026-04-07,네이버페이,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등록된 네이버 페이 구매평) 보통,https://andar.co.kr/product/detail.html?product_no=5147,3,0,NaN,0,2026-04-21,NaN,NaN
2,48535840,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워요 핑크조아~ 릴렉스 마사지 듀얼볼 Ⅱ 후기 좋아요,https://andar.co.kr/product/detail.html?product_no=5147,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,165~169cm,55~59kg
3,48535469,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈,https://andar.co.kr/product/detail.html?product_no=5147,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",0,2026-04-21,160~164cm,50~54kg
4,48521693,5147,2026-04-03,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 사이즈 딱 좋아요,https://andar.co.kr/product/detail.html?product_no=5147,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,160~164cm,55~59kg

In [21]:
# =======================================
# review_id 중복 확인
# =======================================
df_review_andar_D2C['review_id'].duplicated().sum()

np.int64(0)

In [8]:
# =======================================
# 결측치 처리
# =======================================
# purchased_option => 18.8%
# 키 => 31.5%
# 몸무게 => 32.4%

In [22]:
# purchased_option => 18.8%
pd.set_option('display.max_colwidth', None) # 컬럼 안 텍스트 잘림 제거
df_review_andar_D2C[['search_keyword', 'source_url', 'purchased_option']].drop_duplicates().head(20)
# ‘product_id’와 제품 옵션이 1:1로 매칭되지 않음. 결측치 그대로 유지

,search_keyword,source_url,purchased_option
0,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02DPK] 샤이 핑크, F (Free)"
1,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,NaN
6,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02NAV] 마린 네이비, F (Free)"
28,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02PNK] 블라썸핑크, F (Free)"
58,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02MNT] 파스텔민트, F (Free)"
75,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLU] 마일드 블루, F (Free)"
313,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLK] 블랙, F (Free)"
314,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02GRN] 포레스트 그린, F (Free)"
976,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02GRY] 올리브그레이, F (Free)"
1429,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07CRM] 치즈크림, F (Free)"
1462,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07GRY] 올리브그레이, F (Free)"
1564,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07PNK] 블라썸핑크, F (Free)"
1766,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02LVD] 페털 라일락, F (Free)"
1964,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07MNT] 파스텔민트, F (Free)"
2355,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLK] 시크 블랙, F (Free)"
2506,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EKRMB-02LVD] 페털 라일락, F (Free)"
4115,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01GRN] 아카시아그린, F (Free)"
4117,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,NaN
4121,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01DGY] 프로스트그레이, F (Free)"
4123,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01BLK] 블랙, F (Free)"

In [23]:
# 키 => 31.5%
df_review_andar_D2C['키'] = df_review_andar_D2C['키'].astype(object)
df_review_andar_D2C['키'] = df_review_andar_D2C['키'].fillna(None) # None으로 잘 대체 됨.

# 몸무게 => 32.4%
df_review_andar_D2C['몸무게'] = df_review_andar_D2C['몸무게'].astype(object)
df_review_andar_D2C['몸무게'] = df_review_andar_D2C['몸무게'].fillna(None) # None으로 잘 대체 됨.

# display(df_review_andar_D2C['키'].value_counts(dropna=False))
# display(df_review_andar_D2C['몸무게'].value_counts(dropna=False))

In [24]:
# =======================================
# 파생컬럼 생성 (year, month)
# =======================================
df_review_andar_D2C['post_date'] = pd.to_datetime(df_review_andar_D2C['post_date'])

df_review_andar_D2C['year'] = df_review_andar_D2C['post_date'].dt.year
df_review_andar_D2C['month'] = df_review_andar_D2C['post_date'].dt.month

In [26]:
# =======================================
# 컬럼 이름 통일
# =======================================

df_review_andar_D2C = df_review_andar_D2C.rename(columns={
    'post_date' : 'review_date', 
    'search_keyword' : 'product_name',
    'source_url' : 'product_url',
    'purchased_option' : 'purchase_option',
    '키' : 'user_height_group',
    '몸무게' : 'user_weight_group'
})

In [28]:
# =======================================
# 없는 컬럼 추가
# =======================================

required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_andar_D2C.columns:
        df_review_andar_D2C[col] = None

# =======================================
# 컬럼 순서 정리
# =======================================
df_review_andar_D2C = df_review_andar_D2C[required_columns]

In [29]:
df_review_andar_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   collect_date       925663 non-null  str
 1   platform           925663 non-null  str
 2   review_id          925663 non-null  int64
 3   product_id         925663 non-null  int64
 4   product_name       925663 non-null  str
 5   review_date        925663 non-null  datetime64[us]
 6   year               925663 non-null  int32
 7   month              925663 non-null  int32
 8   content            925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  has_image          925663 non-null  int64
 12  purchase_option    750889 non-null  str
 13  user_size          0 non-null       object
 14  user_height        0 non-null       object
 15  user_weight        0 non-null       object
 16  user_height_group  633734 non-null  object
 17  user_weight_group  624861 non-null  object
 18  product_url        925663 non-null  str
dtypes: datetime64[us](1), int32(2), int64(5), object(5), str(6)
memory usage: 486.8+ MB

In [30]:
# =======================================
# 데이터 타입 통일
# =======================================
df_review_andar_D2C['collect_date'] = pd.to_datetime(df_review_andar_D2C['collect_date'])
df_review_andar_D2C['platform'] = df_review_andar_D2C['collect_date'].astype('category')
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype('category')
df_review_andar_D2C['user_height_group'] = df_review_andar_D2C['user_height_group'].astype('category')
df_review_andar_D2C['user_weight_group'] = df_review_andar_D2C['user_weight_group'].astype('category')

In [31]:
# =======================================
# 데이터 값 정리
# =======================================

# platform 데이터 => 자사몰
df_review_andar_D2C['platform'] = '자사몰'

# purchase_option => None
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype(object)
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].fillna(None)

In [33]:
df_review_andar_D2C.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,자사몰,48724074,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-14,2026,4,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕 릴렉스 마사지 듀얼볼 Ⅱ 후기 마사지하기 딱 좋은 사이즈!",5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,None,155~159cm,45~49kg,https://andar.co.kr/product/detail.html?product_no=5147
1,2026-04-21,자사몰,48590531,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-07,2026,4,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등록된 네이버 페이 구매평) 보통,3,0,0,None,None,None,None,NaN,NaN,https://andar.co.kr/product/detail.html?product_no=5147
2,2026-04-21,자사몰,48535840,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-05,2026,4,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워요 핑크조아~ 릴렉스 마사지 듀얼볼 Ⅱ 후기 좋아요,5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,None,165~169cm,55~59kg,https://andar.co.kr/product/detail.html?product_no=5147
3,2026-04-21,자사몰,48535469,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-05,2026,4,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈,5,0,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,None,160~164cm,50~54kg,https://andar.co.kr/product/detail.html?product_no=5147
4,2026-04-21,자사몰,48521693,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-03,2026,4,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 사이즈 딱 좋아요,5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,None,160~164cm,55~59kg,https://andar.co.kr/product/detail.html?product_no=5147

In [ ]:
# =======================================
# user_height_group, user_weight_group => 데이터 확인
# =======================================
display(df_review_andar_D2C['user_height_group'].value_counts())
display(df_review_andar_D2C['user_weight_group'].value_counts())

user_height_group
160~164cm    196826
155~159cm    132055
165~169cm    118817
170~174cm     78276
175~179cm     43072
150~154cm     36726
180~184cm     18156
185~189cm      3426
145~149cm      2941
139cm 이하       2036
140~144cm       949
190cm 이상        454
Name: count, dtype: int64

user_weight_group
50~54kg    147281
55~59kg    123792
60~64kg     90099
45~49kg     71134
65~69kg     50532
70~74kg     45790
75~79kg     30015
80~84kg     26262
44kg 이하     15892
90kg 이상     12570
85~89kg     11494
Name: count, dtype: int64

In [35]:
# =======================================
# dtype
# =======================================

df_review_andar_D2C['platform'] = df_review_andar_D2C['platform'].astype('category')
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype('category')
df_review_andar_D2C['user_height_group'] = df_review_andar_D2C['user_height_group'].astype('category')
df_review_andar_D2C['user_weight_group'] = df_review_andar_D2C['user_weight_group'].astype('category')

In [37]:
# =======================================
# 최종확인
# =======================================
display(df_review_andar_D2C.head(1))
print(df_review_andar_D2C.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,자사몰,48724074,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-14,2026,4,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕 릴렉스 마사지 듀얼볼 Ⅱ 후기 마사지하기 딱 좋은 사이즈!",5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,None,155~159cm,45~49kg,https://andar.co.kr/product/detail.html?product_no=5147

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   collect_date       925663 non-null  datetime64[us]
 1   platform           925663 non-null  category
 2   review_id          925663 non-null  int64
 3   product_id         925663 non-null  int64
 4   product_name       925663 non-null  str
 5   review_date        925663 non-null  datetime64[us]
 6   year               925663 non-null  int32
 7   month              925663 non-null  int32
 8   content            925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  has_image          925663 non-null  int64
 12  purchase_option    750889 non-null  category
 13  user_size          0 non-null       object
 14  user_height        0 non-null       object
 15  user_weight        0 non-null       object
 16  user_height_group  633734 non-null  category
 17  user_weight_group  624861 non-null  category
 18  product_url        925663 non-null  str
dtypes: category(4), datetime64[us](2), int32(2), int64(5), object(3), str(3)
memory usage: 405.1+ MB
None

## 2. 중복제거

In [61]:
# ===============================
# 제품명 매칭 확인
# ===============================
multi_name = df_review_andar_D2C.groupby('product_id')['product_name'].nunique()
multi_url = df_review_andar_D2C.groupby('product_id')['product_url'].nunique()

# product_name 매핑 확인
print(multi_name.gt(1).sum(), "개의 product_id가 여러 product_name에 매핑됨")
display(
    df_review_andar_D2C[df_review_andar_D2C['product_id'].isin(multi_name[multi_name > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

# product_url 매핑 확인
print(multi_url.gt(1).sum(), "개의 product_id가 여러 product_url에 매핑됨")
display(
    df_review_andar_D2C[df_review_andar_D2C['product_id'].isin(multi_url[multi_url > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

6 개의 product_id가 여러 product_name에 매핑됨

,product_id,product_name,product_url
347824,7259,[아울렛] 에어리핏 오버핏 롱슬리브,https://andar.co.kr/product/detail.html?product_no=7259
909794,7259,에어리핏 오버핏 롱슬리브,https://andar.co.kr/product/detail.html?product_no=7259
67512,7297,[아울렛] 에어터치 페이스 숏슬리브 크롭티,https://andar.co.kr/product/detail.html?product_no=7297
925545,7297,에어터치 페이스 숏슬리브 크롭티,https://andar.co.kr/product/detail.html?product_no=7297
144647,8576,[아울렛] 에어리핏 맨즈 폴로 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8576
921273,8576,에어리핏 맨즈 폴로 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8576
412018,8732,[아울렛] 에어로코튼 슬림핏 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8732
917833,8732,에어로코튼 슬림핏 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8732
333333,10768,[아울렛] [워셔블] 니트 플러스 맨즈 숏슬리브,https://andar.co.kr/product/detail.html?product_no=10768
917747,10768,[워셔블] 니트 플러스 맨즈 숏슬리브,https://andar.co.kr/product/detail.html?product_no=10768
363924,10951,[아울렛] 안다르 맨즈 심리스 드로즈,https://andar.co.kr/product/detail.html?product_no=10951
923303,10951,안다르 맨즈 심리스 드로즈,https://andar.co.kr/product/detail.html?product_no=10951

0 개의 product_id가 여러 product_url에 매핑됨

Empty DataFrame
Columns: [product_id, product_name, product_url]
Index: []

In [67]:
# ===============================
# 리뷰 내용 중복 확인
# ===============================
# 2-1. product_id 같고 content 중복인 데이터 확인
dup_mask = df_review_andar_D2C.duplicated(subset=['product_id', 'content'], keep=False)
print("product_id는 같고 content가 중복 개수: ", dup_mask.sum())
display(df_review_andar_D2C[dup_mask][['product_id', 'product_name', 'review_date', 'content']].sort_values(['product_id', 'content']).head(20))

# 2-2. 위 경우 중 review_date까지 완전히 동일한 경우 개수
print(
    "review_date까지 완전히 동일한 경우 개수: "
    , df_review_andar_D2C[dup_mask].duplicated(subset=['product_id', 'content', 'review_date'], keep=False).sum()
)

# 2-3. product_id, content, review_date, purchase_option 까지 모두 중복인 경우
dup_mask_full = df_review_andar_D2C.duplicated(
    subset=['product_id', 'content', 'review_date', 'purchase_option'],
    keep=False
)
print("purchase_option까지 완전히 동일한 경우 개수: ", dup_mask_full.sum())
display(
    df_review_andar_D2C[dup_mask_full][['product_id', 'product_name', 'review_date', 'purchase_option', 'content']]
    .sort_values(['product_id', 'review_date'])
    .head(20)
)

product_id는 같고 content가 중복 개수:  16420

,product_id,product_name,review_date,content
565548,5144,릴렉스 마사지 스틱 Ⅱ,2021-05-27,가격대비 정말 견고하고 마감도 깔끔하네요 대근육 근막 마사지에 정말 활용도가 높아요 이쁜 색감은 덤이구요🥰 감사합니다
565551,5144,릴렉스 마사지 스틱 Ⅱ,2021-05-27,가격대비 정말 견고하고 마감도 깔끔하네요 대근육 근막 마사지에 정말 활용도가 높아요 이쁜 색감은 덤이구요🥰 감사합니다
558455,5144,릴렉스 마사지 스틱 Ⅱ,2025-11-27,딱좋아요 요기조기 불편한곳에 사용중입니다!! 릴렉스 마사지 스틱 Ⅱ 후기 딱
558456,5144,릴렉스 마사지 스틱 Ⅱ,2025-11-27,딱좋아요 요기조기 불편한곳에 사용중입니다!! 릴렉스 마사지 스틱 Ⅱ 후기 딱
560511,5144,릴렉스 마사지 스틱 Ⅱ,2024-07-04,리뷰가 많아서 한 번 구매해봤어요 \n어머!! 너무 시원해서 집에도 하나 놓고\n사무실에서도 꾸준히 하러고 하나 더 샀어요\n주변에도 선물로 주려고 추가 구매했답니다 \n너무 시원하고 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 너무 시원해요👍
560512,5144,릴렉스 마사지 스틱 Ⅱ,2024-07-04,리뷰가 많아서 한 번 구매해봤어요 \n어머!! 너무 시원해서 집에도 하나 놓고\n사무실에서도 꾸준히 하러고 하나 더 샀어요\n주변에도 선물로 주려고 추가 구매했답니다 \n너무 시원하고 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 너무 시원해요👍
560513,5144,릴렉스 마사지 스틱 Ⅱ,2024-07-04,리뷰가 많아서 한 번 구매해봤어요 \n어머!! 너무 시원해서 집에도 하나 놓고\n사무실에서도 꾸준히 하러고 하나 더 샀어요\n주변에도 선물로 주려고 추가 구매했답니다 \n너무 시원하고 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 너무 시원해요👍
559386,5144,릴렉스 마사지 스틱 Ⅱ,2024-12-11,릴렉스 마사지 스틱 Ⅱ 후기
559754,5144,릴렉스 마사지 스틱 Ⅱ,2024-11-17,릴렉스 마사지 스틱 Ⅱ 후기
560034,5144,릴렉스 마사지 스틱 Ⅱ,2024-10-31,릴렉스 마사지 스틱 Ⅱ 후기
560489,5144,릴렉스 마사지 스틱 Ⅱ,2024-07-09,릴렉스 마사지 스틱 Ⅱ 후기
561266,5144,릴렉스 마사지 스틱 Ⅱ,2023-10-18,릴렉스 마사지 스틱 Ⅱ 후기
561334,5144,릴렉스 마사지 스틱 Ⅱ,2023-09-20,릴렉스 마사지 스틱 Ⅱ 후기
561472,5144,릴렉스 마사지 스틱 Ⅱ,2023-08-08,릴렉스 마사지 스틱 Ⅱ 후기
561782,5144,릴렉스 마사지 스틱 Ⅱ,2023-05-26,릴렉스 마사지 스틱 Ⅱ 후기
561806,5144,릴렉스 마사지 스틱 Ⅱ,2023-05-22,릴렉스 마사지 스틱 Ⅱ 후기
561850,5144,릴렉스 마사지 스틱 Ⅱ,2023-05-15,릴렉스 마사지 스틱 Ⅱ 후기
561872,5144,릴렉스 마사지 스틱 Ⅱ,2023-05-10,릴렉스 마사지 스틱 Ⅱ 후기
565738,5144,릴렉스 마사지 스틱 Ⅱ,2021-04-26,"마사지,근육풀어주는데 넘 좋아요 색깔고 핑쿠핑쿠 넘예뻐요 (2021-04-24 19:56:25 에 등록된 네이버 페이 구매평)"
565739,5144,릴렉스 마사지 스틱 Ⅱ,2021-04-26,"마사지,근육풀어주는데 넘 좋아요 색깔고 핑쿠핑쿠 넘예뻐요 (2021-04-24 19:56:25 에 등록된 네이버 페이 구매평)"

review_date까지 완전히 동일한 경우 개수:  12459
purchase_option까지 완전히 동일한 경우 개수:  3160

,product_id,product_name,review_date,purchase_option,content
565738,5144,릴렉스 마사지 스틱 Ⅱ,2021-04-26,NaN,"마사지,근육풀어주는데 넘 좋아요 색깔고 핑쿠핑쿠 넘예뻐요 (2021-04-24 19:56:25 에 등록된 네이버 페이 구매평)"
565739,5144,릴렉스 마사지 스틱 Ⅱ,2021-04-26,NaN,"마사지,근육풀어주는데 넘 좋아요 색깔고 핑쿠핑쿠 넘예뻐요 (2021-04-24 19:56:25 에 등록된 네이버 페이 구매평)"
565548,5144,릴렉스 마사지 스틱 Ⅱ,2021-05-27,"[EJFMS-01BLU] 에메랄드 블루, F (Free)",가격대비 정말 견고하고 마감도 깔끔하네요 대근육 근막 마사지에 정말 활용도가 높아요 이쁜 색감은 덤이구요🥰 감사합니다
565551,5144,릴렉스 마사지 스틱 Ⅱ,2021-05-27,"[EJFMS-01BLU] 에메랄드 블루, F (Free)",가격대비 정말 견고하고 마감도 깔끔하네요 대근육 근막 마사지에 정말 활용도가 높아요 이쁜 색감은 덤이구요🥰 감사합니다
561606,5144,릴렉스 마사지 스틱 Ⅱ,2023-07-06,NaN,여러개 사서 선물했어요 좋아요 :) 여러개 사서 선물했어요 좋아요 :)
561607,5144,릴렉스 마사지 스틱 Ⅱ,2023-07-06,NaN,여러개 사서 선물했어요 좋아요 :) 여러개 사서 선물했어요 좋아요 :)
561608,5144,릴렉스 마사지 스틱 Ⅱ,2023-07-06,NaN,여러개 사서 선물했어요 좋아요 :) 여러개 사서 선물했어요 좋아요 :)
561031,5144,릴렉스 마사지 스틱 Ⅱ,2024-02-03,"[EJPMS-05BLU] 에메랄드 블루, F (Free)",추천\n\n좋아요\n아주 좋아요 좋라요
561033,5144,릴렉스 마사지 스틱 Ⅱ,2024-02-03,"[EJPMS-05BLU] 에메랄드 블루, F (Free)",추천\n\n좋아요\n아주 좋아요 좋라요
560263,5144,릴렉스 마사지 스틱 Ⅱ,2024-08-22,"[EJPMS-05MNT] 파스텔민트, F (Free)","좋은 가격에 훌륭한 품질! 디자인, 색감도 너무 좋습니다~! 운동하는 데 큰 도움이 됩니다. 추천해요~ 릴렉스 마사지 스틱 Ⅱ 후기 좋아요"
560265,5144,릴렉스 마사지 스틱 Ⅱ,2024-08-22,"[EJPMS-05MNT] 파스텔민트, F (Free)","좋은 가격에 훌륭한 품질! 디자인, 색감도 너무 좋습니다~! 운동하는 데 큰 도움이 됩니다. 추천해요~ 릴렉스 마사지 스틱 Ⅱ 후기 좋아요"
559209,5144,릴렉스 마사지 스틱 Ⅱ,2025-02-12,"[EJPMS-05LVD] 페털 라일락, F (Free)",좋아요 좋아요 좋아요 좋아요 좋아요 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 좋아요 좋아요 좋아요 좋아요 좋아요 좋아요
559210,5144,릴렉스 마사지 스틱 Ⅱ,2025-02-12,"[EJPMS-05LVD] 페털 라일락, F (Free)",좋아요 좋아요 좋아요 좋아요 좋아요 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 좋아요 좋아요 좋아요 좋아요 좋아요 좋아요
559211,5144,릴렉스 마사지 스틱 Ⅱ,2025-02-12,"[EJPMS-05LVD] 페털 라일락, F (Free)",좋아요 좋아요 좋아요 좋아요 좋아요 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 좋아요 좋아요 좋아요 좋아요 좋아요 좋아요
558902,5144,릴렉스 마사지 스틱 Ⅱ,2025-07-18,"[EJPMS-05LVD] 페털 라일락, F (Free)",조아요조아요조아요조아요조아요 릴렉스 마사지 스틱 Ⅱ 후기 조아요조아요조아요조아요조아요
558904,5144,릴렉스 마사지 스틱 Ⅱ,2025-07-18,"[EJPMS-05LVD] 페털 라일락, F (Free)",조아요조아요조아요조아요조아요 릴렉스 마사지 스틱 Ⅱ 후기 조아요조아요조아요조아요조아요
558724,5144,릴렉스 마사지 스틱 Ⅱ,2025-08-21,"[EJPMS-05MNT] 파스텔민트, F (Free)",배송 빠르고 좋아요 \n색도 너무 예쁘고 마사지 잘되요\n보라색이 제일 예쁘네요 \n가족들 주려고 5개 주문했는데 좋아하실듯요 릴렉스 마사지 스틱 Ⅱ 후기 배송 빠르고 좋아요 색도 너무 예쁘고 마사지 잘되요
558726,5144,릴렉스 마사지 스틱 Ⅱ,2025-08-21,"[EJPMS-05MNT] 파스텔민트, F (Free)",배송 빠르고 좋아요 \n색도 너무 예쁘고 마사지 잘되요\n보라색이 제일 예쁘네요 \n가족들 주려고 5개 주문했는데 좋아하실듯요 릴렉스 마사지 스틱 Ⅱ 후기 배송 빠르고 좋아요 색도 너무 예쁘고 마사지 잘되요
558727,5144,릴렉스 마사지 스틱 Ⅱ,2025-08-21,"[EJPMS-05MNT] 파스텔민트, F (Free)",배송 빠르고 좋아요 \n색도 너무 예쁘고 마사지 잘되요\n보라색이 제일 예쁘네요 \n가족들 주려고 5개 주문했는데 좋아하실듯요 릴렉스 마사지 스틱 Ⅱ 후기 배송 빠르고 좋아요 색도 너무 예쁘고 마사지 잘되요
558455,5144,릴렉스 마사지 스틱 Ⅱ,2025-11-27,"[EJPMS-05PNK] 블라썸핑크, F (Free)",딱좋아요 요기조기 불편한곳에 사용중입니다!! 릴렉스 마사지 스틱 Ⅱ 후기 딱

In [68]:
# ===============================
# 중복리뷰 제거
# ===============================
before = len(df_review_andar_D2C)

df_review_andar_D2C = (
    df_review_andar_D2C
    .sort_values(
        by=['helpful_count', 'has_image', 'user_size', 'user_height', 'user_weight', 'user_height_group', 'user_weight_group'],
        ascending=[False, False, False, False, False, False, False],
        na_position='last'
    )
    .drop_duplicates(
        subset=['product_id', 'content', 'review_date', 'purchase_option'],
        keep='first'
    )
    .sort_index()
)

after = len(df_review_andar_D2C)

print(f"제거 전: {before}개")
print(f"제거된 데이터: {before - after}개")
print(f"남은 데이터: {after}개")

제거 전: 925663개
제거된 데이터: 1787개
남은 데이터: 923876개

## 3. 저장

In [75]:
df_review_andar_D2C.shape

(923876, 19)

In [76]:
# =======================================
# 저장
# =======================================

df_review_andar_D2C_2024 = df_review_andar_D2C[df_review_andar_D2C['year'] >= 2024]

df_review_andar_D2C.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_homepage_review_final.csv", encoding='utf-8-sig', index=False)
df_review_andar_D2C_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_homepage_review_final_s2024.csv", encoding='utf-8-sig', index=False)

---
# 안다르 무신사 리뷰 데이터

## 1. 전처리

In [39]:
import pandas as pd
import numpy as np

df_review_andar_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_andar_reviews.csv", encoding='utf-8')
display(df_review_andar_mss.head())
display(df_review_andar_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,user_weight,option,helpful,comment_count,has_image,image_urls,survey_json,url
0,2026-04-21 23:09:37,2024-07-09,3297519,릴렉스 에어소프트 요가매트 (8mm),62257472,스타일,5,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,Whg_,0,0,F · 포그 그레이[EJFMT-01LGY],0,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_668cfde61e980.jpg,NaN,https://www.musinsa.com/products/3297519#review_62257472
1,2026-04-21 23:09:37,2024-06-25,3297519,릴렉스 에어소프트 요가매트 (8mm),61262848,스타일,5,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느낌에 손톱자국 잘남아요,엔나짱,0,0,F · 포그 그레이[EJFMT-01LGY],0,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_667abd78371f4.jpg,NaN,https://www.musinsa.com/products/3297519#review_61262848
2,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59417236,스타일,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,183_80,0,0,F · 포레스트 그린[EJFMT-01GRN],0,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_664446e8c0984.jpg,NaN,https://www.musinsa.com/products/3297519#review_59417236
3,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59408897,스타일,5,"아침에 스트레칭 하거나 아이가 닌텐도 링핏 할때도 사용하는데 완전 좋아요,,,",애너벨리33,0,0,F · 포그 그레이[EJFMT-01LGY],1,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_664413a54ba16.jpg,NaN,https://www.musinsa.com/products/3297519#review_59408897
4,2026-04-21 23:09:37,2024-04-19,3297519,릴렉스 에어소프트 요가매트 (8mm),58192969,스타일,5,아기가 따라 운동 하고 폭싱 폭싱 하니까 점프 점프 하고 놀아요 ㅎㅎ,Bajga,0,0,F · 파스텔 민트[EJFMT-01MNT],22,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_66222386b7e46.jpg,NaN,https://www.musinsa.com/products/3297519#review_58192969

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   collect_date   7552 non-null   str
 1   review_date    7552 non-null   str
 2   product_id     7552 non-null   int64
 3   product_name   7552 non-null   str
 4   review_no      7552 non-null   int64
 5   review_type    7552 non-null   str
 6   rating         7552 non-null   int64
 7   review_text    7552 non-null   str
 8   author         7552 non-null   str
 9   user_height    7552 non-null   int64
 10  user_weight    7552 non-null   int64
 11  option         7546 non-null   str
 12  helpful        7552 non-null   int64
 13  comment_count  7552 non-null   int64
 14  has_image      7552 non-null   bool
 15  image_urls     3007 non-null   str
 16  survey_json    1 non-null      str
 17  url            7552 non-null   str
dtypes: bool(1), int64(7), str(10)
memory usage: 3.5 MB

None

In [40]:
# ======================
# 사용할 컬럼만 남기기
# ======================
df_review_andar_mss = df_review_andar_mss.drop(['review_type', 'author', 'comment_count', 'image_urls', 'survey_json'], axis=1, errors='ignore')
df_review_andar_mss.head(3) # (7552, 13)

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
0,2026-04-21 23:09:37,2024-07-09,3297519,릴렉스 에어소프트 요가매트 (8mm),62257472,5,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,0,0,F · 포그 그레이[EJFMT-01LGY],0,True,https://www.musinsa.com/products/3297519#review_62257472
1,2026-04-21 23:09:37,2024-06-25,3297519,릴렉스 에어소프트 요가매트 (8mm),61262848,5,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느낌에 손톱자국 잘남아요,0,0,F · 포그 그레이[EJFMT-01LGY],0,True,https://www.musinsa.com/products/3297519#review_61262848
2,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59417236,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,0,0,F · 포레스트 그린[EJFMT-01GRN],0,True,https://www.musinsa.com/products/3297519#review_59417236

In [41]:
display(df_review_andar_mss.head(1))
display(df_review_andar_mss.info())

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
0,2026-04-21 23:09:37,2024-07-09,3297519,릴렉스 에어소프트 요가매트 (8mm),62257472,5,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,0,0,F · 포그 그레이[EJFMT-01LGY],0,True,https://www.musinsa.com/products/3297519#review_62257472

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  7552 non-null   str
 1   review_date   7552 non-null   str
 2   product_id    7552 non-null   int64
 3   product_name  7552 non-null   str
 4   review_no     7552 non-null   int64
 5   rating        7552 non-null   int64
 6   review_text   7552 non-null   str
 7   user_height   7552 non-null   int64
 8   user_weight   7552 non-null   int64
 9   option        7546 non-null   str
 10  helpful       7552 non-null   int64
 11  has_image     7552 non-null   bool
 12  url           7552 non-null   str
dtypes: bool(1), int64(6), str(6)
memory usage: 2.8 MB

None

In [42]:
# ======================
# 데이터 타입 통일
# ======================
df_review_andar_mss['collect_date'] = pd.to_datetime(df_review_andar_mss['collect_date'])
df_review_andar_mss['review_date'] = pd.to_datetime(df_review_andar_mss['review_date'])
df_review_andar_mss['product_id'] = df_review_andar_mss['product_id'].astype(int)
df_review_andar_mss['has_image'] = df_review_andar_mss['has_image'].astype(int)
df_review_andar_mss['option'] = df_review_andar_mss['option'].astype('category')

In [43]:
# ===========================
# 파생 컬럼 생성 (year, month)
# ===========================
df_review_andar_mss['year'] = df_review_andar_mss['review_date'].dt.year
df_review_andar_mss['month'] = df_review_andar_mss['review_date'].dt.month

In [44]:
# ===========================
# option 결측치 처리 (0.079%)
# ===========================

# option 컬럼의 결측치 비율 확인
df_review_andar_mss['option'].isna().mean()*100

# 실제 option 컬럼의 값 확인 (6개 행)
pd.set_option('display.max_rows', None) # 행 보이기
df_review_andar_mss[df_review_andar_mss['option'].isna()] #.value_counts(dropna=False)

# >>>>> 제품 아이디 & 옵션 1:1 매칭이 아니라 대체값 없이 결측 유지 <<<<<

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url,year,month
1681,2026-04-21 23:10:53,2024-07-07,3414542,[2 PACK] 에어쿨링 지니 시그니처 레깅스 (9부),62129779,5,쫀쫀하고 사이즈도 딱 맞고 운동할때 너무 좋은거 같아요,159,54,NaN,0,0,https://www.musinsa.com/products/3414542#review_62129779,2024,7
2170,2026-04-21 23:11:24,2024-07-11,3351097,[2 PACK] 비 프리 올데이 크롭탑,62114238,5,이게 가장 입고 벗기 편하고 여러번 세탁해도 큰변형없이 오래입을 수 있어서 재구매합니다!,176,70,NaN,0,1,https://www.musinsa.com/products/3351097#review_62114238,2024,7
2174,2026-04-21 23:11:24,2024-07-06,3351097,[2 PACK] 비 프리 올데이 크롭탑,62114264,5,이게 가장 입고 벗기 편하고 여러번 세탁해도 큰변형없이 오래입을 수 있어서 재구매합니다!,0,0,NaN,0,0,https://www.musinsa.com/products/3351097#review_62114264,2024,7
2588,2026-04-21 23:11:51,2024-07-07,2722562,릴렉스 폼롤러 II (L),62130071,5,잘 받았습니다. 저렴하게 잘 구입하였습니다. 디자인도 마음에 들고 좋아요,0,0,NaN,0,0,https://www.musinsa.com/products/2722562#review_62130071,2024,7
3810,2026-04-21 23:13:32,2024-07-07,4225369,에어스트 밴딩 3.5부 쇼츠,62121303,5,"색감도 진하고, 마감처리도 어디하나 문제가 없네요! 특히 재질이 너무 부드럽고 쫀쫀해서 좋은거 같아여!",161,48,NaN,1,1,https://www.musinsa.com/products/4225369#review_62121303,2024,7
3811,2026-04-21 23:13:32,2024-07-07,4225369,에어스트 밴딩 3.5부 쇼츠,62121261,5,"여름맞이 숏한 팬츠중에 안다르 제품 추찬받아서 구매해봤는데, 너무 이쁘네요.",161,48,NaN,0,0,https://www.musinsa.com/products/4225369#review_62121261,2024,7

In [45]:
# ===========================
# 컬럼 이름 변환
# ===========================
df_review_andar_mss = df_review_andar_mss.rename(columns={
    'review_no': 'review_id',
    'review_text' : 'content',
    'option' : 'purchase_option',
    'helpful' : 'helpful_count',
    'url' : 'product_url'
})

# 컬럼명 잘 변환된 거 확인 완료!
# Index(['collect_date', 'review_date', 'product_id', 'product_name',
#        'review_id', 'rating', 'review_body', 'user_height', 'user_weight',
#        'purchase_option', 'helpful_count', 'has_image', 'product_url', 'year',
#        'month'],
#       dtype='str')

In [46]:
# ===========================
# 컬럼 추가
# ===========================
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_andar_mss.columns:
        df_review_andar_mss[col] = None

# ===========================
# 컬럼 순서 정리
# ===========================
df_review_andar_mss = df_review_andar_mss[required_columns]

In [47]:
# ===========================
# 데이터 값 확인
# ===========================
df_review_andar_mss['collect_date'].value_counts(dropna=False)
df_review_andar_mss['platform'].value_counts(dropna=False)
df_review_andar_mss['user_height_group'].value_counts(dropna=False)
df_review_andar_mss['user_weight_group'].value_counts(dropna=False)
df_review_andar_mss['product_url'].value_counts(dropna=False).sort_values(ascending=False).head(10)

# collect_date 시간 제거해야 함
# platform 데이터 => 무신사 
# user_height_group => 세그먼트 해야 함
# user_weight_group => 세그먼트 해야 함

product_url
https://www.musinsa.com/products/3297519#review_62257472    1
https://www.musinsa.com/products/4505859#review_76474830    1
https://www.musinsa.com/products/4505859#review_72903531    1
https://www.musinsa.com/products/4505859#review_73883466    1
https://www.musinsa.com/products/4505859#review_74114809    1
https://www.musinsa.com/products/4505859#review_74258060    1
https://www.musinsa.com/products/4505859#review_74323158    1
https://www.musinsa.com/products/4505859#review_74828388    1
https://www.musinsa.com/products/4505859#review_74828416    1
https://www.musinsa.com/products/4505859#review_74829308    1
Name: count, dtype: int64

In [48]:
display(df_review_andar_mss.head(1))
display(df_review_andar_mss.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21 23:09:37,None,62257472,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-07-09,2024,7,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,5,0,1,F · 포그 그레이[EJFMT-01LGY],None,0,0,None,None,https://www.musinsa.com/products/3297519#review_62257472

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       7552 non-null   datetime64[us]
 1   platform           0 non-null      object
 2   review_id          7552 non-null   int64
 3   product_id         7552 non-null   int64
 4   product_name       7552 non-null   str
 5   review_date        7552 non-null   datetime64[us]
 6   year               7552 non-null   int32
 7   month              7552 non-null   int32
 8   content            7552 non-null   str
 9   rating             7552 non-null   int64
 10  helpful_count      7552 non-null   int64
 11  has_image          7552 non-null   int64
 12  purchase_option    7546 non-null   category
 13  user_size          0 non-null      object
 14  user_height        7552 non-null   int64
 15  user_weight        7552 non-null   int64
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        7552 non-null   str
dtypes: category(1), datetime64[us](2), int32(2), int64(7), object(4), str(3)
memory usage: 2.7+ MB

None

In [49]:
# 1) collect_date 시간 제거
df_review_andar_mss['collect_date'] = pd.to_datetime(df_review_andar_mss['collect_date']) # dtype('<M8[us]')
df_review_andar_mss['collect_date'] = df_review_andar_mss['collect_date'].dt.normalize() # 시간 제거

In [50]:
# 2) platform 데이터 => 무신사
df_review_andar_mss['platform'] = '무신사' # 확인 완료

In [51]:
# 3-1) user_height, user_weight == 0 => NaN으로 변경
df_review_andar_mss['user_height'] = df_review_andar_mss['user_height'].replace(0, np.nan)
df_review_andar_mss['user_weight'] = df_review_andar_mss['user_weight'].replace(0, np.nan)

In [52]:
# 3) user_height_group 세그먼트
# 왼 미포함, 오른 포함
height_bins = [0, 139, 144, 149, 154, 159, 164, 169, 174, 179, 184, 189, 999]
height_labels = [
    '139cm 이하',
    '140~144cm',
    '145~149cm',
    '150~154cm',
    '155~159cm',
    '160~164cm',
    '165~169cm',
    '170~174cm',
    '175~179cm',
    '180~184cm',
    '185~189cm',
    '190cm 이상'
]
df_review_andar_mss['user_height_group'] = pd.cut(df_review_andar_mss['user_height'], bins=height_bins, labels=height_labels, right=True)

# 데이터 확인 완료

In [53]:
# user_height_group => NaN 데이터 생긴 이유 확인
a = df_review_andar_mss[df_review_andar_mss['user_height_group'].isna()][['user_height', 'user_height_group']]
a.value_counts(dropna=False)

# >>>>> 'user_height', 'user_weight' 데이터가 없어서 NaN이 생김 = 정상 <<<<<

user_height  user_height_group
NaN          nan                  2091
             139cm 이하                0
             140~144cm               0
             145~149cm               0
             150~154cm               0
             155~159cm               0
             160~164cm               0
             165~169cm               0
             170~174cm               0
             175~179cm               0
             180~184cm               0
             185~189cm               0
             190cm 이상                0
Name: count, dtype: int64

In [54]:
# 4) user_weight_group 세그먼트
weight_bins = [0, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 999]
weight_labels = [
    '44kg 이하',
    '45~49kg',
    '50~54kg',
    '55~59kg',
    '60~64kg',
    '65~69kg',
    '70~74kg',
    '75~79kg',
    '80~84kg',
    '85~89kg',
    '90kg 이상'
]
df_review_andar_mss['user_weight_group'] = pd.cut(df_review_andar_mss['user_weight'], bins=weight_bins, labels=weight_labels, right=True)

# 데이터 확인 완료

In [55]:
# user_weight_group => NaN 데이터 생긴 이유 확인
b = df_review_andar_mss[df_review_andar_mss['user_weight_group'].isna()][['user_weight', 'user_weight_group']]
b.value_counts(dropna=False)

# >>>>> 'user_height', 'user_weight' 데이터가 없어서 NaN이 생김 = 정상 <<<<<

user_weight  user_weight_group
NaN          nan                  2101
             44kg 이하                 0
             45~49kg                 0
             50~54kg                 0
             55~59kg                 0
             60~64kg                 0
             65~69kg                 0
             70~74kg                 0
             75~79kg                 0
             80~84kg                 0
             85~89kg                 0
             90kg 이상                 0
Name: count, dtype: int64

In [56]:
display(df_review_andar_mss.head(1))
display(df_review_andar_mss.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,무신사,62257472,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-07-09,2024,7,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,5,0,1,F · 포그 그레이[EJFMT-01LGY],None,NaN,NaN,NaN,NaN,https://www.musinsa.com/products/3297519#review_62257472

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       7552 non-null   datetime64[us]
 1   platform           7552 non-null   str
 2   review_id          7552 non-null   int64
 3   product_id         7552 non-null   int64
 4   product_name       7552 non-null   str
 5   review_date        7552 non-null   datetime64[us]
 6   year               7552 non-null   int32
 7   month              7552 non-null   int32
 8   content            7552 non-null   str
 9   rating             7552 non-null   int64
 10  helpful_count      7552 non-null   int64
 11  has_image          7552 non-null   int64
 12  purchase_option    7546 non-null   category
 13  user_size          0 non-null      object
 14  user_height        5461 non-null   float64
 15  user_weight        5451 non-null   float64
 16  user_height_group  5461 non-null   category
 17  user_weight_group  5451 non-null   category
 18  product_url        7552 non-null   str
dtypes: category(3), datetime64[us](2), float64(2), int32(2), int64(5), object(1), str(4)
memory usage: 2.6+ MB

None

In [57]:
# ======================
# 데이터 타입 통일
# ======================
df_review_andar_mss['platform'] = df_review_andar_mss['platform'].astype('category')

df_review_andar_mss['user_weight'] = pd.to_numeric(df_review_andar_mss['user_weight'], errors='coerce').astype('Int64')
df_review_andar_mss['user_height'] = pd.to_numeric(df_review_andar_mss['user_height'], errors='coerce').astype('Int64')

In [59]:
# ===========================
# 실시간 데이터 확인
# ===========================
df_review_andar_mss.info()
df_review_andar_mss.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       7552 non-null   datetime64[us]
 1   platform           7552 non-null   category
 2   review_id          7552 non-null   int64
 3   product_id         7552 non-null   int64
 4   product_name       7552 non-null   str
 5   review_date        7552 non-null   datetime64[us]
 6   year               7552 non-null   int32
 7   month              7552 non-null   int32
 8   content            7552 non-null   str
 9   rating             7552 non-null   int64
 10  helpful_count      7552 non-null   int64
 11  has_image          7552 non-null   int64
 12  purchase_option    7546 non-null   category
 13  user_size          0 non-null      object
 14  user_height        5461 non-null   Int64
 15  user_weight        5451 non-null   Int64
 16  user_height_group  5461 non-null   category
 17  user_weight_group  5451 non-null   category
 18  product_url        7552 non-null   str
dtypes: Int64(2), category(4), datetime64[us](2), int32(2), int64(5), object(1), str(3)
memory usage: 2.5+ MB

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,무신사,62257472,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-07-09,2024,7,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,5,0,1,F · 포그 그레이[EJFMT-01LGY],None,<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_62257472
1,2026-04-21,무신사,61262848,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-06-25,2024,6,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느낌에 손톱자국 잘남아요,5,0,1,F · 포그 그레이[EJFMT-01LGY],None,<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_61262848
2,2026-04-21,무신사,59417236,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-05-15,2024,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,5,0,1,F · 포레스트 그린[EJFMT-01GRN],None,<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_59417236
3,2026-04-21,무신사,59408897,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-05-15,2024,5,"아침에 스트레칭 하거나 아이가 닌텐도 링핏 할때도 사용하는데 완전 좋아요,,,",5,1,1,F · 포그 그레이[EJFMT-01LGY],None,<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_59408897
4,2026-04-21,무신사,58192969,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-04-19,2024,4,아기가 따라 운동 하고 폭싱 폭싱 하니까 점프 점프 하고 놀아요 ㅎㅎ,5,22,1,F · 파스텔 민트[EJFMT-01MNT],None,<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_58192969

## 2. 중복제거

In [70]:
# ===============================
# 제품명 매칭 확인
# ===============================
multi_name = df_review_andar_mss.groupby('product_id')['product_name'].nunique()
multi_url = df_review_andar_mss.groupby('product_id')['product_url'].nunique()

# product_name 매핑 확인
print(multi_name.gt(1).sum(), "개의 product_id가 여러 product_name에 매핑됨")
display(
    df_review_andar_mss[df_review_andar_mss['product_id'].isin(multi_name[multi_name > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
    .head(20)
)

# product_url 매핑 확인
print(multi_url.gt(1).sum(), "개의 product_id가 여러 product_url에 매핑됨")
display(
    df_review_andar_mss[df_review_andar_mss['product_id'].isin(multi_url[multi_url > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
    .head(20)
)

1 개의 product_id가 여러 product_name에 매핑됨

,product_id,product_name,product_url
6130,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_55021296
6152,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_73534979
6151,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_74306087
6150,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_74307611
6149,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_74830335
6148,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_51989554
6147,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_53494672
6146,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_53894234
6145,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_54768932
6144,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_55076982
6143,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_55373996
6153,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_71464361
6142,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_57559731
6140,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_67034868
6139,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_68801818
6138,3727805,NEW 에어무스 기모 조거핏 레깅스,https://www.musinsa.com/products/3727805#review_69225301
6137,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_69730808
6136,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_72107687
6135,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_72478128
6134,3727805,에어무스 기모 조거핏 레깅스 / AMFJT-16,https://www.musinsa.com/products/3727805#review_72775904

180 개의 product_id가 여러 product_url에 매핑됨

,product_id,product_name,product_url
2587,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_62249329
2667,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_34975236
2666,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_35136316
2665,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_36477440
2664,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_36937689
2663,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_37085685
2662,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_37085705
2661,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_38049782
2660,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_38114978
2668,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_34860950
2659,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_38251201
2657,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_38810138
2656,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_39022775
2655,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_39022788
2654,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_39144683
2653,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_39335074
2652,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_40993408
2651,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_40993509
2650,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_41134666
2658,2722562,릴렉스 폼롤러 II (L),https://www.musinsa.com/products/2722562#review_38747951

In [71]:
# ===============================
# 리뷰 내용 중복 확인
# ===============================
# 2-1. product_id 같고 content 중복인 데이터 확인
dup_mask = df_review_andar_mss.duplicated(subset=['product_id', 'content'], keep=False)
print("product_id는 같고 content가 중복 개수: ", dup_mask.sum())
display(df_review_andar_mss[dup_mask][['product_id', 'product_name', 'review_date', 'content']].sort_values(['product_id', 'content']).head(20))

# 2-2. 위 경우 중 review_date까지 완전히 동일한 경우 개수
print(
    "review_date까지 완전히 동일한 경우 개수: "
    , df_review_andar_mss[dup_mask].duplicated(subset=['product_id', 'content', 'review_date'], keep=False).sum()
)

# 2-3. product_id, content, review_date, purchase_option 까지 모두 중복인 경우
dup_mask_full = df_review_andar_mss.duplicated(
    subset=['product_id', 'content', 'review_date', 'purchase_option'],
    keep=False
)
print("purchase_option까지 완전히 동일한 경우 개수: ", dup_mask_full.sum())
display(
    df_review_andar_mss[dup_mask_full][['product_id', 'product_name', 'review_date', 'purchase_option', 'content']]
    .sort_values(['product_id', 'review_date'])
    .head(20)
)

product_id는 같고 content가 중복 개수:  1166

,product_id,product_name,review_date,content
2651,2722562,릴렉스 폼롤러 II (L),2023-03-26,냄새도 않나고 크기도 적당하고 마감도 잘되서 좋아요
2652,2722562,릴렉스 폼롤러 II (L),2023-03-26,냄새도 않나고 크기도 적당하고 마감도 잘되서 좋아요
2577,2722562,릴렉스 폼롤러 II (L),2024-10-25,너무 만족하며 잘 사용하고 있습니다 감사합니다
2578,2722562,릴렉스 폼롤러 II (L),2024-10-25,너무 만족하며 잘 사용하고 있습니다 감사합니다
2625,2722562,릴렉스 폼롤러 II (L),2023-08-08,단단함 정도도 적당하고 크기도 너무 크지않아서 유용하게 사용하고 있습니다!
2626,2722562,릴렉스 폼롤러 II (L),2023-08-08,단단함 정도도 적당하고 크기도 너무 크지않아서 유용하게 사용하고 있습니다!
2525,2722562,릴렉스 폼롤러 II (L),2024-04-26,배송도 빠르고 품질도 너무 만족스러워요. 다른 곳에서 산거는 너무 이상한 냄새가 나서 못쓰겠는데 안다르 폼롤러는 냄새도 없고 색상도 아주 예쁘네요.
2594,2722562,릴렉스 폼롤러 II (L),2024-04-26,배송도 빠르고 품질도 너무 만족스러워요. 다른 곳에서 산거는 너무 이상한 냄새가 나서 못쓰겠는데 안다르 폼롤러는 냄새도 없고 색상도 아주 예쁘네요.
2595,2722562,릴렉스 폼롤러 II (L),2024-04-26,배송도 빠르고 품질도 너무 만족스러워요. 다른 곳에서 산거는 너무 이상한 냄새가 나서 못쓰겠는데 안다르 폼롤러는 냄새도 없고 색상도 아주 예쁘네요.
2631,2722562,릴렉스 폼롤러 II (L),2023-07-19,사이즈도 딱 제가 생각하던크기였고 색감도 너무 쨍한 컬러가 아니라서 마음에 들어요
2634,2722562,릴렉스 폼롤러 II (L),2023-06-30,사이즈도 딱 제가 생각하던크기였고 색감도 너무 쨍한 컬러가 아니라서 마음에 들어요
2697,2722562,릴렉스 폼롤러 II (L),2024-12-01,상품 너무 만족하며 잘 사용중입니다 굿굿 감사합니다
2698,2722562,릴렉스 폼롤러 II (L),2024-12-01,상품 너무 만족하며 잘 사용중입니다 굿굿 감사합니다
2629,2722562,릴렉스 폼롤러 II (L),2023-07-21,색상 너무 예뻐요 사이즈 가늠이 잘 안가서 후기 사진 보고 골랐는데 딱 원하는 크기 고른 것 같아요 가벼운데 탄탄해서 스트레칭할때 유용하게 쓰고 있어요
2630,2722562,릴렉스 폼롤러 II (L),2023-07-21,색상 너무 예뻐요 사이즈 가늠이 잘 안가서 후기 사진 보고 골랐는데 딱 원하는 크기 고른 것 같아요 가벼운데 탄탄해서 스트레칭할때 유용하게 쓰고 있어요
2627,2722562,릴렉스 폼롤러 II (L),2023-07-27,생각보다 약간 말랑거지만 스트레칭할 때 요긴하게 쓰고 있습니다. 한쪽으로 쏠려서 쓰다보니 한 쪽 부분만 약간 꺼지긴 했어요ㅎ
2628,2722562,릴렉스 폼롤러 II (L),2023-07-27,생각보다 약간 말랑거지만 스트레칭할 때 요긴하게 쓰고 있습니다. 한쪽으로 쏠려서 쓰다보니 한 쪽 부분만 약간 꺼지긴 했어요ㅎ
2583,2722562,릴렉스 폼롤러 II (L),2024-08-10,싼가격에 세일하길래 바로삿어요!!! 배송도 빠르고 좋아욜 종아리 스트레칭할때 쓸려고 구매했슴니당^^
2584,2722562,릴렉스 폼롤러 II (L),2024-08-10,싼가격에 세일하길래 바로삿어요!!! 배송도 빠르고 좋아욜 종아리 스트레칭할때 쓸려고 구매했슴니당^^
2592,2722562,릴렉스 폼롤러 II (L),2024-04-26,작고 가벼워서 침대위에 두고 누워서도 편하게 굴릴수 있어서 좋네용

review_date까지 완전히 동일한 경우 개수:  1038
purchase_option까지 완전히 동일한 경우 개수:  565

,product_id,product_name,review_date,purchase_option,content
2651,2722562,릴렉스 폼롤러 II (L),2023-03-26,L · 치즈 크림[EJPFR-04CRM],냄새도 않나고 크기도 적당하고 마감도 잘되서 좋아요
2652,2722562,릴렉스 폼롤러 II (L),2023-03-26,L · 치즈 크림[EJPFR-04CRM],냄새도 않나고 크기도 적당하고 마감도 잘되서 좋아요
2639,2722562,릴렉스 폼롤러 II (L),2023-05-22,L · 파스텔 민트[EJPFR-04MNT],폼롤러 처음 사봐서 사이즈 고민 많이 했는데 여기저기 마사지 하기에 좋은 사이즈인 것 같아요. 색상도 예쁘고 재질도 적당히 단단해서 좋아요~
2640,2722562,릴렉스 폼롤러 II (L),2023-05-22,L · 파스텔 민트[EJPFR-04MNT],폼롤러 처음 사봐서 사이즈 고민 많이 했는데 여기저기 마사지 하기에 좋은 사이즈인 것 같아요. 색상도 예쁘고 재질도 적당히 단단해서 좋아요~
2629,2722562,릴렉스 폼롤러 II (L),2023-07-21,L · 파스텔 민트[EJPFR-04MNT],색상 너무 예뻐요 사이즈 가늠이 잘 안가서 후기 사진 보고 골랐는데 딱 원하는 크기 고른 것 같아요 가벼운데 탄탄해서 스트레칭할때 유용하게 쓰고 있어요
2630,2722562,릴렉스 폼롤러 II (L),2023-07-21,L · 파스텔 민트[EJPFR-04MNT],색상 너무 예뻐요 사이즈 가늠이 잘 안가서 후기 사진 보고 골랐는데 딱 원하는 크기 고른 것 같아요 가벼운데 탄탄해서 스트레칭할때 유용하게 쓰고 있어요
2627,2722562,릴렉스 폼롤러 II (L),2023-07-27,L · 파스텔 민트[EJPFR-04MNT],생각보다 약간 말랑거지만 스트레칭할 때 요긴하게 쓰고 있습니다. 한쪽으로 쏠려서 쓰다보니 한 쪽 부분만 약간 꺼지긴 했어요ㅎ
2628,2722562,릴렉스 폼롤러 II (L),2023-07-27,L · 파스텔 민트[EJPFR-04MNT],생각보다 약간 말랑거지만 스트레칭할 때 요긴하게 쓰고 있습니다. 한쪽으로 쏠려서 쓰다보니 한 쪽 부분만 약간 꺼지긴 했어요ㅎ
2625,2722562,릴렉스 폼롤러 II (L),2023-08-08,L · 치즈 크림[EJPFR-04CRM],단단함 정도도 적당하고 크기도 너무 크지않아서 유용하게 사용하고 있습니다!
2626,2722562,릴렉스 폼롤러 II (L),2023-08-08,L · 치즈 크림[EJPFR-04CRM],단단함 정도도 적당하고 크기도 너무 크지않아서 유용하게 사용하고 있습니다!
2620,2722562,릴렉스 폼롤러 II (L),2023-09-25,L · 파스텔 민트[EJPFR-04MNT],폼롤러는 처음 사보는데 적당히 딱딱하고 길이도 전신운동하기에 무리없는 길이 입니다 :) 많이 파세효
2621,2722562,릴렉스 폼롤러 II (L),2023-09-25,L · 파스텔 민트[EJPFR-04MNT],폼롤러는 처음 사보는데 적당히 딱딱하고 길이도 전신운동하기에 무리없는 길이 입니다 :) 많이 파세효
2616,2722562,릴렉스 폼롤러 II (L),2023-12-13,L · 파스텔 민트[EJPFR-04MNT],행사때 상품으로 쓰려고 주문했어요. 쓰신분들이 좋다 하더라구요. 배송 빨라요
2617,2722562,릴렉스 폼롤러 II (L),2023-12-13,L · 파스텔 민트[EJPFR-04MNT],행사때 상품으로 쓰려고 주문했어요. 쓰신분들이 좋다 하더라구요. 배송 빨라요
2601,2722562,릴렉스 폼롤러 II (L),2024-03-19,L · 블라썸 핑크[EJPFR-04PNK],크기도 딱 좋고 단단함도 적당해서 전신 스트레칭하는데 좋아서 본가에도 두려고 하나 더 사요 색상도 예뻐요
2602,2722562,릴렉스 폼롤러 II (L),2024-03-19,L · 블라썸 핑크[EJPFR-04PNK],크기도 딱 좋고 단단함도 적당해서 전신 스트레칭하는데 좋아서 본가에도 두려고 하나 더 사요 색상도 예뻐요
2526,2722562,릴렉스 폼롤러 II (L),2024-03-30,L · 파스텔 민트[EJPFR-04MNT],좀 물렁해서 전신하기에 좋아요 딱딱한거 필요하신분은 ㄴㄴ
2599,2722562,릴렉스 폼롤러 II (L),2024-03-30,L · 파스텔 민트[EJPFR-04MNT],좀 물렁해서 전신하기에 좋아요 딱딱한거 필요하신분은 ㄴㄴ
2600,2722562,릴렉스 폼롤러 II (L),2024-03-30,L · 파스텔 민트[EJPFR-04MNT],좀 물렁해서 전신하기에 좋아요 딱딱한거 필요하신분은 ㄴㄴ
2525,2722562,릴렉스 폼롤러 II (L),2024-04-26,L · 파스텔 민트[EJPFR-04MNT],배송도 빠르고 품질도 너무 만족스러워요. 다른 곳에서 산거는 너무 이상한 냄새가 나서 못쓰겠는데 안다르 폼롤러는 냄새도 없고 색상도 아주 예쁘네요.

In [72]:
# ===============================
# 중복리뷰 제거
# ===============================
before = len(df_review_andar_mss)

df_review_andar_mss = (
    df_review_andar_mss
    .sort_values(
        by=['helpful_count', 'has_image', 'user_size', 'user_height', 'user_weight', 'user_height_group', 'user_weight_group'],
        ascending=[False, False, False, False, False, False, False],
        na_position='last'
    )
    .drop_duplicates(
        subset=['product_id', 'content', 'review_date', 'purchase_option'],
        keep='first'
    )
    .sort_index()
)

after = len(df_review_andar_mss)

print(f"제거 전: {before}개")
print(f"제거된 데이터: {before - after}개")
print(f"남은 데이터: {after}개")

제거 전: 7552개
제거된 데이터: 301개
남은 데이터: 7251개

## 3. 저장

In [73]:
df_review_andar_mss.shape

(7251, 19)

In [74]:
df_review_andar_mss_2024 = df_review_andar_mss[df_review_andar_mss['year'] >= 2024]

df_review_andar_mss.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_musinsa_review_final.csv", encoding='utf-8-sig', index=False)
df_review_andar_mss_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_musinsa_review_final_s2024.csv", encoding='utf-8-sig', index=False)