In [29]:
import pandas as pd
import numpy as np

In [30]:
# 휠라
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_master_260420.csv", encoding='utf-8')
df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv", encoding='utf-8')
df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv", encoding='utf-8')

---
# 휠라 네이버스토어 리뷰 데이터

## 1. 전처리

In [141]:
# 데이터 불러오기
df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv", encoding='utf-8')
display(df_review_fila_naverstore.head())

,Unnamed: 0,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,reviewer_id,review_content_class,extra_id,extra_reviewContentClassType,extra_reviewScore,extra_reviewContent,extra_createDate,extra_writerId,extra_productName,extra_productOptionContent,extra_reviewTopics
0,3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,mini******,PHOTO,4.669237e+09,PHOTO,5.0,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,2025-02-24 13:14:50.302000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
1,4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,mini******,PHOTO,4.652212e+09,PHOTO,5.0,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,2025-01-31 13:07:37.398000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
2,5,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,ex****,PHOTO,4.652239e+09,PHOTO,5.0,넘 귀야워요 만족ㅎㅎ,2025-01-31 14:23:34.326000+00:00,ex****,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
3,6,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,youn*******,PHOTO,4.634973e+09,PHOTO,5.0,깜찍합니다.이뿌구요^^,2025-01-03 23:36:57.419000+00:00,youn*******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
4,7,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,yoon*******,PHOTO,4.944300e+09,PHOTO,4.0,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,2026-04-02 04:45:38.825000+00:00,yoon*******,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,"[{""topicCode"": ""size"", ""topicCodeName"": ""사이즈"",..."

In [142]:
# 필요한 컬럼 선택

df_review_fila_naverstore = df_review_fila_naverstore[[
    'product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'review_content_class', 'extra_productName', 'extra_productOptionContent'
]] # 10개

display(df_review_fila_naverstore.head())
display(df_review_fila_naverstore.info())

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,PHOTO,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   str
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 444.0 KB

None

In [143]:
# review_content_class 변환
df_review_fila_naverstore['review_content_class'].value_counts() # PHOTO, TEXT, VIDEO

# PHOTO, VIDEO = 1
# TEXT = 0
df_review_fila_naverstore['review_content_class'] = df_review_fila_naverstore['review_content_class'].map({
    'PHOTO' : 1,
    'TEXT' : 0,
    'VIDEO' : 1
})

print(df_review_fila_naverstore['review_content_class'].value_counts())
print(df_review_fila_naverstore.info())

review_content_class
1    887
0    390
Name: count, dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 438.2 KB
None

In [147]:
# 데이터 타입 변환
# rating, helpful_count, review_date
df_review_fila_naverstore['rating'] = df_review_fila_naverstore['rating'].astype(int)
df_review_fila_naverstore['helpful_count'] = df_review_fila_naverstore['helpful_count'].astype(int)
df_review_fila_naverstore['review_date'] = pd.to_datetime(df_review_fila_naverstore['review_date']).dt.normalize().dt.tz_localize(None)

print(df_review_fila_naverstore.info())

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
 10  year                        1277 non-null   int32
 11  month                       1277 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), str(4)
memory usage: 408.3 KB
None

In [148]:
# 파생컬럼 생성 -> year, month
df_review_fila_naverstore['year'] = df_review_fila_naverstore['review_date'].dt.year
df_review_fila_naverstore['month'] = df_review_fila_naverstore['review_date'].dt.month

df_review_fila_naverstore.head(3)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1

In [149]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
 10  year                        1277 non-null   int32
 11  month                       1277 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), str(4)
memory usage: 408.3 KB

In [150]:
# 컬럼명 정리
df_review_fila_naverstore = df_review_fila_naverstore.rename(columns={
    'review_content_class' : 'has_image',
    'extra_productName' : 'product_name',
    'extra_productOptionContent' : 'purchase_option'
})

df_review_fila_naverstore.head(1)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2

In [152]:
# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'review_body', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_naverstore.columns:
        df_review_fila_naverstore[col] = None

df_review_fila_naverstore.head()

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month,collect_date,platform,user_height,user_weight,user_height_group,user_weight_group
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2,None,None,None,None,None,None
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5,0,2025-01-03,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,0,2026-04-02,1,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,2026,4,None,None,None,None,None,None

In [154]:
# 컬럼 순서 정리
df_review_fila_naverstore = df_review_fila_naverstore[required_columns]
df_review_fila_naverstore.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,review_body,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,None,None,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,None,None,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,None,None,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
3,None,None,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다.이뿌구요^^,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
4,None,None,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,0,1,색상: Beige / 사이즈: 220,None,None,None,None,https://brand.naver.com/fila/products/11293482675

In [155]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       0 non-null      object
 1   platform           0 non-null      object
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   review_body        1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        1277 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), object(6), str(4)
memory usage: 468.1+ KB

In [178]:
# 이상치 확인
df_review_fila_naverstore['review_date'].value_counts(dropna=False)

review_date
2026-03-10    19
2026-03-26    16
2026-03-30    15
2025-11-11    15
2026-04-04    14
              ..
2025-10-16     1
2025-10-19     1
2025-10-24     1
2025-10-09     1
2026-01-24     1
Name: count, Length: 313, dtype: int64

In [172]:
# review_id 중복 확인
df_review_fila_naverstore['review_id'].duplicated().sum()

np.int64(0)

---
# 휠라 자사몰 리뷰 데이터

## 1. 전처리

In [200]:
df_product_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/products/fila_snapshot_master_260422.csv", encoding='utf-8')
df_product_fila_D2C.head(1)

,category1,category2,category3,collect_date,brand,product_id,product_name,product_type,category,gender,original_price,discount_price,color_count,raw_colors,review_count,launch_year,launch_season
0,상의,긴팔티셔츠,일반,2026-04-20,FILA,1100fs261rl01x001001,베이직 긴팔 티셔츠,의류,긴팔,공용,49900,49900,3,블랙,1,2026,SPRING

In [174]:
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_master_260423.csv", encoding='utf-8')
print(df_review_fila_D2C.info())
display(df_review_fila_D2C.head())

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_id         48244 non-null  int64
 1   collect_date      48244 non-null  str
 2   post_date         48244 non-null  str
 3   platform          48244 non-null  str
 4   brand             48244 non-null  str
 5   search_keyword    48244 non-null  str
 6   reviewer_id       48244 non-null  str
 7   content           48244 non-null  str
 8   source_url        48244 non-null  str
 9   rating            48244 non-null  int64
 10  helpful_count     48244 non-null  int64
 11  purchased_option  7036 non-null   str
 12  has_image         48244 non-null  int64
dtypes: int64(4), str(9)
memory usage: 19.3 MB
None

,review_id,collect_date,post_date,platform,brand,search_keyword,reviewer_id,content,source_url,rating,helpful_count,purchased_option,has_image
0,123617,2026-04-23,2025-07-07,자사몰리뷰,휠라,1170fi4ith2659flsa,khk****,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
1,142021,2026-04-23,2026-04-03,자사몰리뷰,휠라,1170fi4ith2659flsa,meg****,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
2,142012,2026-04-23,2026-04-03,자사몰리뷰,휠라,1170fi4ith2659flsa,meg****,색상이 파스텔톤으로 예쁩니다. 감촉이 부드럽고 시원한 느낌입니다. 세일기간에 구입하...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
3,124095,2026-04-23,2025-07-22,자사몰리뷰,휠라,1170fi4ith2659flsa,lil****,아주 얇고 좋아요 어제 너무 더웠는데 이 브라입고 답답하지 않고 시원하고 넘 좋았...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
4,129745,2026-04-23,2025-10-27,자사몰리뷰,휠라,1170fi4ith2659flsa,jhy****,"정말 가볍고 얇고 편합니다 여러 브라 사입었는데, 요 제품 라인이 제일인 것 같습니...",https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,0

In [179]:
# 필요한 컬럼 선택

df_review_fila_D2C = df_review_fila_D2C[[
    'review_id', 'collect_date', 'post_date', 'platform', 'search_keyword', 'content', 'source_url', 'rating', 'helpful_count', 'purchased_option', 'has_image'
]] # 11개

display(df_review_fila_D2C.head())
display(df_review_fila_D2C.info())

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image
0,123617,2026-04-23,2025-07-07,자사몰리뷰,1170fi4ith2659flsa,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
1,142021,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
2,142012,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 파스텔톤으로 예쁩니다. 감촉이 부드럽고 시원한 느낌입니다. 세일기간에 구입하...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1
3,124095,2026-04-23,2025-07-22,자사몰리뷰,1170fi4ith2659flsa,아주 얇고 좋아요 어제 너무 더웠는데 이 브라입고 답답하지 않고 시원하고 넘 좋았...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1
4,129745,2026-04-23,2025-10-27,자사몰리뷰,1170fi4ith2659flsa,"정말 가볍고 얇고 편합니다 여러 브라 사입었는데, 요 제품 라인이 제일인 것 같습니...",https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,0

<class 'pandas.DataFrame'>
RangeIndex: 48244 entries, 0 to 48243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_id         48244 non-null  int64
 1   collect_date      48244 non-null  str
 2   post_date         48244 non-null  str
 3   platform          48244 non-null  str
 4   search_keyword    48244 non-null  str
 5   content           48244 non-null  str
 6   source_url        48244 non-null  str
 7   rating            48244 non-null  int64
 8   helpful_count     48244 non-null  int64
 9   purchased_option  7036 non-null   str
 10  has_image         48244 non-null  int64
dtypes: int64(4), str(7)
memory usage: 17.6 MB

None

In [ ]:
df_product_fila_D2C['raw_colors'].value_counts()

In [202]:
# merge 전 product_id 매칭 확인하기
# 제품 리스트의 product_id
product_ids = set(df_product_fila_D2C['product_id'])

# 리뷰 데이터의 search_keyword
search_keywords = set(df_review_fila_D2C['search_keyword'])

# 매칭 확인
matched = product_ids & search_keywords
unmatched = search_keywords - product_ids

print(f"매칭되는 값: {len(matched)}개")
print(f"매칭 안 되는 search_keyword: {len(unmatched)}개")
print(unmatched)

매칭되는 값: 1001개
매칭 안 되는 search_keyword: 0개
set()

In [ ]:
# 제품 데이터에서 product_name, raw_colors 추가
df_review_fila_D2C = df_review_fila_D2C.merge(
    df_product_fila_D2C[['product_id', 'product_name', 'raw_colors']],  # 필요한 컬럼만 선택
    left_on='search_keyword',
    right_on='product_id',
    how='left'  # 리뷰 데이터 기준으로 merge
)

df_review_fila_D2C.head(2)

# merge 확인
# df_review_fila_D2C['product_id'].isna().sum() =>>>>>> product_id => null 없음
# df_review_fila_D2C[df_review_fila_D2C['search_keyword'] != df_review_fila_D2C['product_id']] =>>>>>> 'search_keyword'와 'product_id'가 잘 매칭 됐는지 확인!

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,product_id_x,product_name_x,raw_colors_x,product_id_y,product_name_y,raw_colors_y,product_id,product_name,raw_colors
0,123617,2026-04-23,2025-07-07,자사몰리뷰,1170fi4ith2659flsa,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,NaN,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN
1,142021,2026-04-23,2026-04-03,자사몰리뷰,1170fi4ith2659flsa,색상이 짙은 바다색상으로 세트 구입했습니다. 마음에 쏙 듭니다. 감촉이 부드럽고 시...,https://www.fila.co.kr/product/1170fi4ith2659flsa,5,0,사이즈:105,1,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN,1170fi4ith2659flsa,에어플러스 라이트 스트랩 브라탑,NaN

In [ ]:
df_review_fila_D2C[df_review_fila_D2C['search_keyword'] != df_review_fila_D2C['product_id']]

Empty DataFrame
Columns: [review_id, collect_date, post_date, platform, search_keyword, content, source_url, rating, helpful_count, purchased_option, has_image, product_id_x, product_name_x, raw_colors_x, product_id_y, product_name_y, raw_colors_y, product_id, product_name, raw_colors]
Index: []

In [ ]:
# product_name => search_keyword와 매칭해서 데이터 넣기
df_review_fila_D2C['product_name'] = df_review_fila_D2C['search_keyword'].map({
    '1170fi4ith2659flsa' : "에어플러스 라이트 스트랩 브라탑(라이트샌드)",
    "1170fi4ith2659fdid" : "에어플러스 라이트 스트랩 브라탑(다크인디고)",
    '11001xm02348h063' : '<우즈 착용> 휠라 에샤페 실버문',
    '1100fs261od03x087219' : '<한소희 착용> 휠라 에샤페 LX 초코',
    '1100fs261od03x087370' : '<차정원 착용> 휠라 에샤페 LX 말차',
    '1100fs253od03x012260' : '휠라 에샤페 LX 모카',
    '1100fs253od03x012217' : '<차정원 착용> 휠라 에샤페 LX 브릭',
    '11001xm02348h010' : '휠라 에샤페 MS',
    '1100fs261od03x087456' : '<김나영 착용> 휠라 에샤페 LX 블루',
    '1100fs261od03x087661' : '휠라 에샤페 LX',
    '1100fs261od03x087100' : '<한소희 착용> 휠라 에샤페 LX 크림',
    '1100fs261od03x087218' : '휠라 에샤페 LX 카멜',
    '1100fs261od03x087001' : '휠라 에샤페 LX 블랙',
    '1170fi4bag3171fdtg' : '멜로우 노와이어 브라(더스티그린)',
    '1170fi4bag3171fpbe' : '멜로우 노와이어 브라(페일블루)',
    '1170fi4bag3171fpbl' : '멜로우 노와이어 브라(퍼플리시블루)',
    '1100fs261od03x045217' : '에샤페 벨크로 메리제인 초코', # BROWN
    '11001xm02369h050' : '에샤페 벨크로 메리제인', # Grey
    '11001xm02369h001' : '에샤페 벨크로 메리제인', # Black
    '1100fs262sd03x004013' : ''
})

In [191]:
# purchased_option 결측치 처리

# 데이터 확인
df_review_fila_D2C[(df_review_fila_D2C['purchased_option'].isna()) & (df_review_fila_D2C['search_keyword'] == '1170fi4ith2659fdid')]

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image
1856,123617,2026-04-23,2025-07-07,자사몰리뷰,1170fi4ith2659fdid,우와 진짜 입어본 중에 최고로 시원하고 편해요 !!! 혹시 몰라서 사이즈 넉넉하게 ...,https://www.fila.co.kr/product/1170fi4ith2659fdid,5,0,NaN,1
1859,124095,2026-04-23,2025-07-22,자사몰리뷰,1170fi4ith2659fdid,아주 얇고 좋아요 어제 너무 더웠는데 이 브라입고 답답하지 않고 시원하고 넘 좋았...,https://www.fila.co.kr/product/1170fi4ith2659fdid,5,0,NaN,1
1860,129745,2026-04-23,2025-10-27,자사몰리뷰,1170fi4ith2659fdid,"정말 가볍고 얇고 편합니다 여러 브라 사입었는데, 요 제품 라인이 제일인 것 같습니...",https://www.fila.co.kr/product/1170fi4ith2659fdid,5,0,NaN,0
1862,129746,2026-04-23,2025-10-27,자사몰리뷰,1170fi4ith2659fdid,정말 가볍고 얇고 편합니다. 다크인디고 색상이 가장 무난하게 입기 좋은 색이잖아요 ...,https://www.fila.co.kr/product/1170fi4ith2659fdid,5,0,NaN,0
1863,129603,2026-04-23,2025-10-24,자사몰리뷰,1170fi4ith2659fdid,편한 착용감 너무 좋아요 딸이 참 좋아해서 기분이 더 좋네요 오늘두 좋은 하루되세요...,https://www.fila.co.kr/product/1170fi4ith2659fdid,5,0,NaN,0
1864,125173,2026-04-23,2025-07-25,자사몰리뷰,1170fi4ith2659fdid,일단 가볍고 여름인데도 덥지않고 시원합니다 무엇보다 안답답해서 좋아요,https://www.fila.co.kr/product/1170fi4ith2659fdid,5,0,NaN,0

In [190]:
pd.set_option('display.max_rows', None)
df_review_fila_D2C[df_review_fila_D2C['purchased_option'].isna()]['search_keyword'].value_counts()

search_keyword
11001xm02348h063           1746
1100fs261od03x087219       1551
1100fs261od03x087370       1551
1100fs253od03x012260       1545
1100fs253od03x012217       1545
11001xm02348h010           1300
1100fs261od03x087456        835
1100fs261od03x087661        835
1100fs261od03x087100        835
1100fs261od03x087218        835
1100fs261od03x087001        835
1170fi4bag3171fdtg          459
1170fi4bag3171fpbe          459
1170fi4bag3171fpbl          459
1100fs261od03x045217        447
11001xm02369h050            447
11001xm02369h001            447
1100fs262sd03x004013        388
1100fs262sd03x004660        388
1100fs262sd03x004031        388
1100fs262sd03x004260        388
1170fi4bfg3171fpbl          368
1170fi4bfg3171flml          368
1170fi4bfg3171fotl          368
1170fi253sk13f001032        268
1170fi253sk13f001001        268
1170fi253sk13f001031        268
1170fi4bah1104fblk          267
1170fi4bah1104fdro          267
1170fi4bah1104flml          267
1170fi4bah1104fcrm          267
1170fi253mp13f003001        240
1170fi253mp13f003032        240
1170fi253mp13f003034        240
1170fi253fz13f003031        238
1170fi253mp13f005032        238
1170fi253mp13f005001        238
1170fi253mp13f005031        238
1170fi253fz13f003032        238
1170fi253fz13f003001        238
1170fi253fz13f004001        237
1170fi253mp13f004032        237
1170fi253mp13f004001        237
1170fi253fz13f004031        237
1170fi253fz13f004032        237
11001xm02367h102            234
11001rm02946h050            204
11001rm02946h010            204
1100fs261ft01f005234        197
1100fs261ft01f005001        197
1100fs261od03x032260        182
1100fs261od03x032660        182
1100fs261od03x032031        182
1100fs253od03x014660        181
1100fs261od03x095734        181
1100fs253od03x014218        181
1100fs261od03x095100        181
1100fs261od03x095217        181
1170fi4bah1102fpbe          177
1170fi4bah1102fcrm          177
1170fi4bah1102fblk          177
1170fi4bah1102fpbl          177
1170fi4bah1102fdtg          177
1170fi4bah1102flml          177
1170fi4bah1102fdro          177
1100fs261ru03x076217        156
1100fs253ru03x014001        156
1100fs253ru03x014031        156
1170fi261dr01m024001        133
1170fi4bfh1102fpbl          122
1170fi4bfh1102flml          122
1170fi4bfh1102fpbe          122
1170fi4bfh1102fdro          122
1170fi4bfh1102fblk          122
1170fi261dr01m023001        122
1170fi4bfh1102fcrm          122
1170fi4bfh1102fdtg          122
11001xm02347h920            121
1170fi261br01f010650        103
1170fi4drg1106mblk          102
1170fi261br01f010067         96
1170fi4bah1450flbe           95
1170fi4bah1450fblk           95
1170fi4bah1450flml           95
1170fi4bah1450fdrd           95
1170fi261br01f010066         93
1170fi261br01f010412         91
1170fi4drh1450fdrd           91
1170fi4drh1450flml           91
1170fi4drh1450flbe           91
1170fi4drh1450fblk           91
1170fi261br01f033661         90
1100fs261od03x008001         86
1100fs261od03x008370         86
1100fs261od03x008734         86
1170fi4bah1105fblk           86
1170fi261br01f010100         86
1170fi4bah1105fwod           86
1170fi4bah1105flml           86
1170fi261dr01f024001         80
1170fi4drg3173mblk           79
1170fi261br01f033660         79
1170fi261br01f033100         79
1170fi261br01f033217         79
1170fi253jt13u002370         79
1170fi261br01f033250         79
1170fi253dr01f008820         78
1170fi253dr01f008031         78
1100fs254rb01f002150         78
1170fi253dr01f008001         78
1170fi253dr01f008260         78
1100fs254rb01f002001         78
1170fi253dr01f008217         78
1170fi4drh1102fipk           74
1170fi4drh1102fwod           74
1170fi4drh1102flml           74
1170fi4drh1101fdrd           74
1170fi4drh1102fblk           74
1170fi4drh1103flbr           73
1170fi4drh1103fwhi           73
1170fi4drh1103fwod           73
1170fi4drh1103fipk           73
1170fi4drg3177fwod           73
1170fi4drh1103flbe           73
1170fi4drh1103flml           73
1170fi4tkg3171fdtg           68
1170fi4tkg3171fotl           68
1170fi4tkg3171fblk           68
1170fi4tkg3171fpbl           68
1170fi4tkg3171flml           68
1170fi4tkg3171fdro           68
1170fi4tkg3171fpbe           68
1170fi261dr01m022001         66
1170fi261br01f009001         60
1100fs261ft01f005626         60
1100fs261ft01f005175         60
1100fs261ft01f005496         60
1170fi253dr01m011001         56
11001tm01987g475             56
1170fi261br01f009452         55
1170fi261dr01f025001         54
1170fi4drh1120mblk           54
1170fi4bah2450fwhi           52
1170fi4bah2450flle           52
1170fi261br01f009066         52
1170fi4bah2450fblk           52
1170fi4bah2450fmab           52
1170fi261br01f009412         52
1170fi261br01f009100         51
1170fi261br01f009652         51
1170fi253pj13u001370         49
1170fi4bah1123fwhi           49
1170fi261br01f009613         49
1170fi4bah1123fmit           49
1170fi4bah1123fblk           49
11001jm02786h924             48
1170fi253jt13u001613         46
1170fi253jt13u001452         46
1170fi253jt13u001371         46
1170fi253jt13u001260         46
1170fi253jt13u001001         46
1170fi253jt13u001217         46
1170fi253jb13u002613         43
1170fi4tkh1101fblk           43
1170fi253jb13u002001         43
1170fi253jb13u002452         43
1170fi253jb13u002371         43
1170fi253jb13u002217         43
1170fi253jb13u002260         43
1170fi4tkh1101fcrm           43
11001jm02786h067             43
1170fi4tkh1101flml           43
11001tm01987h125             43
1170fi4bfh1123fred           42
1170fi4bfh1123fmit           42
1170fi4drg3178fwhi           40
1170fi4drg3178flml           40
1170fi4drg3178flbr           40
1170fi4drg3178flbe           40
1170fi4drg3178fipk           40
1100fs261ft01x001001         39
1100fs261ft01x001234         39
1100fs261bp01x001001         38
1100fs261bp01x001234         38
1100fs261bp01x001150         38
1170fi253jb13u001371         36
1170fi253jb13u001260         36
1170fi253jb13u001001         36
1170fi253jb13u001217         36
1170fi253jb13u001613         36
1170fi253jb13u001452         36
1170fi253jb13f001371         35
1170fi4bah1122fmit           35
1170fi4bah1122fepk           35
1170fi4bah1122fblk           35
1170fi253jb13f001452         35
1170fi253jb13f001001         35
1170fi253jb13f001260         35
1170fi4bah1122fwhi           35
1170fi253jb13f001613         35
1170fi253jb13f001217         35
1170fi4bah1122flml           35
11001xm02854h100             34
11001xm02854h400             34
11001xm02854h040             34
11001xm02854h001             34
1170fi4bfh1121fmit           33
1170fi4bfh1121fwhi           33
11001jm02787h925             32
1170fi253br01f008031         31
1170fi4bah1103fblk           31
1170fi253br01f008820         31
1170fi4bah1103flbe           31
1170fi4bah1103fwod           31
1170fi4bah1103flbr           31
1170fi253br01f008260         31
1170fi4bah1103fipk           31
1170fi4bah1103fwhi           31
1170fi253br01f008217         31
1170fi4bah1103flml           31
1170fi253br01f008001         31
1170fi4drh1122mblk           30
1170fi4drg1448fpbg           29
1170fi261br01f008067         28
1170fi4bah1121fmit           27
11001tm01987h822             27
1170fi4bah1121fepk           27
1170fi4bah1121flml           27
1170fi4bah1121fblk           27
1170fi4bah1121fwhi           27
11001jm02787h001             25
1170fi261bf01f007066         24
1170fi4bfg3177fwhi           24
1170fi4bfg3177fwod           24
1170fi4bag1448fpbg           23
1170fi4bfh1122fblk           22
1170fi4drg3172mblk           22
1170fi4bfh1122fmit           22
1170fi4bfh1122fwhi           22
1170fi4bfh1122flml           22
1170fi4drh1103mdrd           21
11001rm02844g100             21
11001rm02844g102             21
1170fi261bf01f005001         21
11001rm02844g001             21
1170fi261bf01f006066         20
11001tm01987h117             19
1170fi4rsh1145mdid           19
1170fi4rsh1145mwhi           19
1100fs262jk01u003234         18
1170fi261bf01f007001         18
1100fs262jk01u003175         18
1170fi261bf01f006650         18
1100fs262jk01u003442         18
1100fs262jk01u003626         18
11001jm02787h050             18
1170fi253dr01f007260         17
1170fi253dr01f007820         17
1170fi261br01f023661         17
1170fi261br01f023100         17
1170fi4drh1141mblk           17
1170fi253dr01f007031         17
1170fi253dr01f007001         17
1170fi261br01f023660         17
1170fi261br01f023175         17
1170fi253dr01f007217         17
1170fi261br01f023101         17
1170fi4bfh1113fblk           16
1170fi261bf01f016001         16
1170fi4bfh1113fwhi           16
1170fi261bf01f012151         16
1170fi261br01f025541         16
1170fi261br01f025660         16
1170fi4bfh1113fore           16
1170fi261br01f025370         16
1170fi261br01f025150         16
1170fi261bf01f012541         16
1170fi261bf01f012660         16
1170fi4bfh1113fred           16
1170fi261bf01f012370         16
1170fi4bfh1113flml           16
1170fi261br01f025001         16
1170fi4bfh1113fdgr           16
1170fi261br01f025071         16
1170fi261br01f025442         16
1170fi261bf01f012150         16
1170fi261bf01f012071         16
1170fi261bf01f012371         16
1170fi261bf01f005412         15
1170fi253lg12f002001         15
1100fs253ru02x002002         15
1170fi253lg12f002032         15
1170fi253lg12f002031         15
1170fi261bf01f005066         15
1170fi253lg12f002650         15
1170fi253lg12f002260         15
1170fi261bf01f007452         14
1170fi261bf01f006412         14
1170fi261bf01f007650         14
11001rm02942h112             13
1260fv254br17f001660         13
1170fi261bf01f006100         13
11001rm02942h002             13
1170fi261bf01f005100         13
11001rm02942h071             13
1170fi261br01f008650         13
1170fi261bf01f005650         13
1260fv254br17f001370         13
1260fv254br17f002001         13
1260fv254br17f002260         13
1170fi253br12f003650         12
1170fi253br12f003001         12
1170fi261dr01f025661         12
1260fv254dr17f001660         12
1170fi253br12f003260         12
1260fv254dr17f001370         12
1170fi253br12f003031         12
1170fi261bf01f007412         12
1260fv254dr17f001260         12
1170fi261bf01f007101         12
1260fv254dr17f001261         12
1170fi253br12f003032         12
1170fi261bf01f006001         11
1170fi4rnh1101fdtg           11
1170fi4bah1111fred           11
1170fi261br01f022101         11
1170fi261br07f006100         11
1170fi261bf01f010031         11
1170fi261br07f006071         11
1170fi261bf01f010175         11
1170fi4rnh1101fpbl           11
1170fi261br01f022660         11
1170fi261br07f006217         11
1170fi261br01f022031         11
1170fi4rnh1101flml           11
1170fi4rnh1101fpbe           11
1100fs253ru02x001001         11
1170fi261bf01f007100         11
1170fi253lg12m002031         11
1100fs253ru02x001217         11
1170fi4bah1111fdgr           11
1170fi253lg12m002001         11
1170fi4bah1111fblk           11
1170fi261br07f006660         11
1170fi261bf01f010101         11
1170fi261bf01f010100         11
1170fi253lg12m002100         11
1100fs253ru02x001031         11
1170fi4rnh1101fblk           11
1100fs261od03x009452         11
1170fi4bah1111fore           11
1170fi261br07f006001         11
1170fi4rnh1101fdro           11
1170fi4rnh1101fcrm           11
1100fs261od03x009613         11
1170fi4bah1111fwhi           11
1170fi4bah1111flml           11
1170fi261br07f006250         11
1170fi261bf01f006456         11
1170fi261bf01f010660         11
1170fi261br01f022100         11
1170fi261br01f022661         11
1170fi4bah1112fblk           10
1170fi253lg12m001001         10
1170fi4cmh1124fmit           10
1170fi261bf01f013176         10
1170fi4bah1112fdgr           10
1170fi4bah1112fwhi           10
1170fi253lg12m001100         10
1100fs261od03x040032         10
1170fi261bf01f013175         10
1170fi4bah1112flml           10
1170fi4cmh1124flml           10
1170fi4cmh1124fblk           10
1170fi261bf01f013660         10
1170fi4cmh1124fwhi           10
1170fi4bah1112fore           10
1170fi4cmh1124fidb           10
1170fi261bf01f013100         10
1170fi253lg12m001031         10
1170fi261bf01f013101         10
1170fi4cmh1124fepk           10
1170fi4bah1112fred           10
1170fi261bf07f001071          9
1170fi4ith1116fdgr            9
1170fi4ith1116fore            9
1170fi261dr01m012452          9
1100fs261tn02x001103          9
1170fi4ith1116fred            9
1100fs3bph1003xsbu            9
1100fs261tn02x001660          9
1170fi261bf07f001001          9
1170fi261bf07f001002          9
1100fs261tn02x001106          9
1100fs3bph1003xblk            9
1170fi261br01f008066          9
1170fi261bf07f001217          9
1170fi261bf07f001660          9
1170fi261bf07f001250          9
1170fi4ith1116flml            9
1170fi4bah1115fwhi            9
1170fi4bah1115flml            9
1170fi4poh1146mdid            9
1170fi261dr01m015001          9
1170fi4ith1116fwhi            9
1100fs3bph1003xowh            9
1170fi4ith1116fblk            9
1100fs253ru03x004260          8
1170fi4drh2657fsad            8
1170fi4bfh1112fdgr            8
1170fi4bfh1112fwhi            8
1170fi261br01f008100          8
1100fs261bp01x011450          8
1170fi4bfh1112flml            8
1100fs253ru03x004001          8
1170fi4bfh1112fore            8
1170fi4bfh1112fblk            8
1100fs3bph1004xblk            8
1170fi4bfh1112fred            8
1170fi4hph1005mdtg            8
1100fs253ru03x004100          8
1170fi4drh2657fblk            8
1170fi261cm01f001067          8
1100fs3bph1004xowh            8
1170fi4hph1005mcgy            8
1170fi4hph1005mhpk            8
1170fi4drh1111fblk            7
1100fs261bs01f001150          7
1170fi4drh1111fdgr            7
11001xm02852h050              7
1170fi253br12f002001          7
1170fi253br12f002650          7
11001xm02852h600              7
1170fi261br01f008412          7
11001xm02852h001              7
1170fi253br01f011001          7
1100fs261bs01f001670          7
1170fi253br12f002032          7
1170fi253br01f011260          7
1100fs261bs01f001260          7
1170fi253br01f011031          7
1170fi4drh1111fred            7
1100fs261bs01f001001          7
1170fi4drh1111fwhi            7
1170fi253br01f011217          7
1170fi4drh1111fore            7
1170fi253br12f002031          7
1170fi253br01f011820          7
1170fi4drh1111flml            7
1170fi253br12f002260          7
1100fs261bs01f001442          7
1170fi4ith2659flsa            6
1170fi4ith2659fdid            6
1170fi253br01f010031          6
1170fi253br01f010001          6
1170fi261br01f028456          6
11001xm02853h920              6
1170fi261br01f008456          6
1170fi253br01f010217          6
1170fi261bf01f014100          6
1170fi4drh1151mnbg            6
1170fi4bfh1123mblk            6
1170fi253br01f001820          6
1170fi261bf01f014101          6
1170fi261br01f028001          6
1170fi253br01f001260          6
1170fi261br01f028100          6
1170fi261cm01f001100          6
1170fi253br01f001001          6
11001xm02853h200              6
1170fi253br01f010260          6
1170fi253br01f010820          6
1170fi261dr01f025071          6
1170fi261dr01m013001          6
1170fi253br01f001031          6
1170fi261bf01f014001          6
1170fi253br01f001217          6
1170fi261br01f028260          6
1170fi253br12f001032          5
1170fi4bfh1103fwod            5
1170fi253lg12f003001          5
1170fi4bfh1103fwhi            5
1170fi4bah1113fwhi            5
1170fi4bfh1103fipk            5
1170fi253br12f001650          5
1170fi4drh2450fwhi            5
1170fi4acg0001xwhi            5
1170fi253br12f001031          5
1170fi4bah1113fore            5
1170fi4drh2450flle            5
1170fi4bah1113fblk            5
1170fi4bah1113flml            5
1170fi4drh2656fsad            5
1170fi4bfh1103flbe            5
1170fi253lg12f003032          5
1170fi4drh2656flvy            5
1170fi4drh2450fmab            5
1170fi253br12f001260          5
1100fs3bph1002xblk            5
1170fi4drh2656fblk            5
1170fi253lg12f003260          5
1170fi4bah1113fred            5
1170fi253br12f001001          5
1100fs3bph1002xcrm            5
1170fi253lg12f003031          5
1170fi4bah1113fdgr            5
1170fi4bfh1103flml            5
1170fi4tkh1143mdid            5
1170fi4bfh1103fblk            5
1170fi4drh2450fblk            5
1170fi4acg0002xwhi            5
1170fi4cah1148mdid            5
1170fi4bfh1103flbr            5
1170fi253lg12f003650          5
1170fi253dr01m010001          4
1170fi261br01f029260          4
1170fi4bah1114fdgr            4
11001jm02570h001              4
1170fi261cm01f001650          4
1170fi253lg12f001001          4
1170fi261br01f029100          4
1170fi261br01f029456          4
1170fi253jo13f002260          4
11001rm02723h050              4
1170fi253jo13f002376          4
1170fi261br01f024031          4
1170fi253lg12f001031          4
1170fi253jo13f002613          4
1170fi4ith2656flvy            4
1170fi253jo13f002217          4
1170fi4bah1114flml            4
1170fi4drg3410mblk            4
1100fs253od03x033001          4
1100fs261od03x005101          4
1170fi261br01f024452          4
1170fi4bah1114fwhi            4
1170fi261br01f024660          4
1170fi261cm01f001066          4
1170fi261br01f024150          4
1170fi261dr01f025250          4
1170fi261br01f024100          4
1100fs261ft01x001496          4
1170fi4bah1114fblk            4
1170fi253jo13f002001          4
1100fs261od03x005100          4
1170fi4bah1114fore            4
1170fi253jo13f002452          4
1170fi253lg12f001650          4
1170fi4ith2656fblk            4
11001rm02723h001              4
1170fi253lg12f001032          4
1100fs261od03x005102          4
1170fi4ith2656fsad            4
1100fs253od03x033100          4
1170fi253lg12f001260          4
1170fi4bah1114fred            4
1100fs253od03x033101          4
1170fi261br01f029001          4
1170fi4drh1410mdrd            3
1170fi253bf01f003001          3
1170fi253bf01f003031          3
1170fi253bf01f003260          3
1170fi4tkh1124mblk            3
1100fs261od03x100031          3
1100fs261ru03x052001          3
1100fs261ru03x052031          3
1170fi261br01f032250          3
1170fi261cm01f001452          3
1170fi261cm01f001412          3
1100fs261od03x100100          3
1170fi253bf01f003820          3
1170fi253bf01f003217          3
1100fs261ru03x052734          3
1170fi253br01f009001          2
1170fi261dr01f021001          2
1170fi261dr01f021456          2
1100fs261fp01u001234          2
1170fi4drh1042fblk            2
1170fi4tkh1627mfna            2
1100fs261tn03x006260          2
1100fs261cp01x002660          2
1100fs261ru04x003100          2
1170fi261mt13f002032          2
1100fs261tn03x001001          2
1170fi4poh1147mblk            2
1100fs261ru04x006452          2
1170fi253br01f009031          2
1170fi261mt13f002001          2
1170fi4tkh1638mnbe            2
1100fs262rs02x004191          2
1100fs261tn03x001260          2
1100fs261cp01x002001          2
1100fs261tn03x002001          2
1170fi253br01f009260          2
1170fi253br01f009820          2
1100fs261ru04x003031          2
1170fi4pjh2645flde            2
1170fi253dr01m009260          2
1170fi261bf01f016071          2
1170fi261dr01f025217          2
1100fs261ru04x003101          2
1170fi261dr01f025660          2
1170fi261dr01f021101          2
1170fi4drh1042fsbu            2
1170fi261dr01f021100          2
1100fs253od03x017001          2
1100fs262rs02x004007          2
1100fs261fp01u001001          2
1170fi4drh2658flsa            2
1100fs261tn03x001100          2
1100fs253od03x017260          2
1100fs261tn03x006820          2
1100fs261tn03x002101          2
1170fi4pjh2612mdpt            2
1170fi253br01f009217          2
1170fi4drh2658fdid            2
1170fi261dr01f025100          2
1100fs261tn03x002100          2
1170fi261mt13f002031          2
1170fi4pjh2609mblk            1
1100fs261od03x006031          1
1170fi261dr07f004-32072       1
1100fs261ru02x022100          1
1170fi261mp13f004032          1

In [197]:
df_review_fila_D2C[df_review_fila_D2C['search_keyword']=='1100fs261rl01x001001'] # ['purchased_option']

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image
27997,138292,2026-04-23,2026-03-02,자사몰리뷰,1100fs261rl01x001001,기본 베이직한 티셔츠 입기 편해요 휠라 신발이 저에게는 잘 맞아요 매일 종류별 계...,https://www.fila.co.kr/product/1100fs261rl01x0...,5,0,컬러:175 / 사이즈:S(090),0

---
# 휠라 무신사 리뷰 데이터

## 1. 전처리

In [90]:
df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv", encoding='utf-8')
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,...,option,helpful,comment_count,has_image,image_urls,survey_size,survey_width,survey_comfort,survey_instep,url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,스타일,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,기발한스웨덴웨지,NaN,...,Grey/White/White · 270,1,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,보통,아주 편안,https://www.musinsa.com/products/3892794#revie...
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,스타일,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,아트텍,NaN,...,Grey/White/White · 260,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,적당,https://www.musinsa.com/products/3892794#revie...
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,스타일,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,신중한하얀단화,NaN,...,Grey/White/White · 255,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,편안,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   collect_date    14100 non-null  str
 1   review_date     14100 non-null  str
 2   product_id      14100 non-null  int64
 3   product_name    14100 non-null  str
 4   review_no       14100 non-null  int64
 5   review_type     14100 non-null  str
 6   rating          14100 non-null  int64
 7   review_text     14090 non-null  str
 8   author          14100 non-null  str
 9   user_height     0 non-null      float64
 10  user_weight     0 non-null      float64
 11  option          14086 non-null  str
 12  helpful         14100 non-null  int64
 13  comment_count   14100 non-null  int64
 14  has_image       14100 non-null  bool
 15  image_urls      8621 non-null   str
 16  survey_size     4227 non-null   str
 17  survey_width    4227 non-null   str
 18  survey_comfort  4227 non-null   str
 19  survey_instep   4227 non-null   str
 20  url             14100 non-null  str
dtypes: bool(1), float64(2), int64(5), str(13)
memory usage: 7.6 MB

None

In [92]:
# 사용 컬럼 선정
df_review_fila_mss = df_review_fila_mss[['review_date', 'product_id', 'product_name', 'review_no', 'rating', 'review_text', 'url']]
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,review_date,product_id,product_name,review_no,rating,review_text,url
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_date   14100 non-null  str
 1   product_id    14100 non-null  int64
 2   product_name  14100 non-null  str
 3   review_no     14100 non-null  int64
 4   rating        14100 non-null  int64
 5   review_text   14090 non-null  str
 6   url           14100 non-null  str
dtypes: int64(3), str(4)
memory usage: 4.3 MB

None

In [94]:
# 결측치 처리
# 리뷰 분석이 중요하기 때문에 review_text가 null인 컬럼은 제거
df_review_fila_mss = df_review_fila_mss.dropna(subset=['review_text'], axis=0)
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_date   14090 non-null  str
 1   product_id    14090 non-null  int64
 2   product_name  14090 non-null  str
 3   review_no     14090 non-null  int64
 4   rating        14090 non-null  int64
 5   review_text   14090 non-null  str
 6   url           14090 non-null  str
dtypes: int64(3), str(4)
memory usage: 4.4 MB

In [98]:
# review_date 파생컬럼
df_review_fila_mss['review_date'] = pd.to_datetime(df_review_fila_mss['review_date'])

df_review_fila_mss['year'] = df_review_fila_mss['review_date'].dt.year
df_review_fila_mss['month'] = df_review_fila_mss['review_date'].dt.month

display(df_review_fila_mss.head())
display(df_review_fila_mss[['review_date', 'year', 'month']].info())

,review_date,product_id,product_name,review_no,rating,review_text,url,year,month
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...,2025,11
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...,2025,11
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...,2025,10
3,2025-10-13,3892794,에샤페 실버문(1XM02348H063),78679747,5,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,https://www.musinsa.com/products/3892794#revie...,2025,10
4,2025-10-12,3892794,에샤페 실버문(1XM02348H063),78939688,5,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,https://www.musinsa.com/products/3892794#revie...,2025,10

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_date  14090 non-null  datetime64[us]
 1   year         14090 non-null  int32
 2   month        14090 non-null  int32
dtypes: datetime64[us](1), int32(2)
memory usage: 330.2 KB

None

In [108]:
# 컬럼명 변경
df_review_fila_mss = df_review_fila_mss.rename(columns={
    'review_no' : 'review_id',
    'review_text' : 'review_body',
    'url' : 'product_url'
})

df_review_fila_mss.head()

,review_date,product_id,product_name,review_id,rating,review_body,product_url,year,month
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...,2025,11
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...,2025,11
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...,2025,10
3,2025-10-13,3892794,에샤페 실버문(1XM02348H063),78679747,5,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,https://www.musinsa.com/products/3892794#revie...,2025,10
4,2025-10-12,3892794,에샤페 실버문(1XM02348H063),78939688,5,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,https://www.musinsa.com/products/3892794#revie...,2025,10

In [109]:
# 컬럼순서 변경
df_review_fila_mss = df_review_fila_mss[['review_id', 'product_id', 'product_name', 'review_date', 'year', 'month', 'review_body', 'rating', 'product_url']]
df_review_fila_mss.head()

,review_id,product_id,product_name,review_date,year,month,review_body,rating,product_url
0,79849708,3892794,에샤페 실버문(1XM02348H063),2025-11-16,2025,11,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,5,https://www.musinsa.com/products/3892794#revie...
1,79753882,3892794,에샤페 실버문(1XM02348H063),2025-11-11,2025,11,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,5,https://www.musinsa.com/products/3892794#revie...
2,79033605,3892794,에샤페 실버문(1XM02348H063),2025-10-15,2025,10,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,5,https://www.musinsa.com/products/3892794#revie...
3,78679747,3892794,에샤페 실버문(1XM02348H063),2025-10-13,2025,10,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,5,https://www.musinsa.com/products/3892794#revie...
4,78939688,3892794,에샤페 실버문(1XM02348H063),2025-10-12,2025,10,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,5,https://www.musinsa.com/products/3892794#revie...

In [110]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_id     14090 non-null  int64
 1   product_id    14090 non-null  int64
 2   product_name  14090 non-null  str
 3   review_date   14090 non-null  datetime64[us]
 4   year          14090 non-null  int32
 5   month         14090 non-null  int32
 6   review_body   14090 non-null  str
 7   rating        14090 non-null  int64
 8   product_url   14090 non-null  str
dtypes: datetime64[us](1), int32(2), int64(3), str(3)
memory usage: 4.4 MB

In [120]:
# 이상치 확인
df_review_fila_mss['product_url'].value_counts()

product_url
https://www.musinsa.com/products/5311939#review_81270327    5
https://www.musinsa.com/products/5312026#review_81244311    5
https://www.musinsa.com/products/5312026#review_81248800    5
https://www.musinsa.com/products/5311939#review_81244528    5
https://www.musinsa.com/products/5312098#review_81069728    5
                                                           ..
https://www.musinsa.com/products/5311984#review_79605475    1
https://www.musinsa.com/products/5311984#review_79258458    1
https://www.musinsa.com/products/5311984#review_79198367    1
https://www.musinsa.com/products/5311984#review_78888434    1
https://www.musinsa.com/products/5311984#review_78378268    1
Name: count, Length: 8575, dtype: int64