In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/fila_naver_store_reviews/reviews_since_2020.csv")
df.head()

,product_url,product_id,review_id,review_title,review_body,rating,helpful_count,review_date,reviewer_id,reviewer_nickname,...,extra_repThumbnailTagNameDescription.attachSize,extra_repThumbnailTagNameDescription.attachDescription,extra_repThumbnailTagNameDescription.sortOrder,extra_repThumbnailTagNameDescription.attachName,extra_repThumbnailTagNameDescription.attachDirectoryName,extra_repThumbnailAttach.reviewTagId,extra_repThumbnailAttach.reviewTagName,extra_repThumbnailTagNameDescription.reviewTagId,extra_repThumbnailTagNameDescription.reviewTagName,extra_reviewInspectionPolicyReason
0,https://brand.naver.com/fila/products/10739081170,10739081170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://brand.naver.com/fila/products/10739087534,10739087534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://brand.naver.com/fila/products/10768506789,10768506789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,NaN,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24T13:14:50.302000+00:00,mini******,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,NaN,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31T13:07:37.398000+00:00,mini******,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2267 entries, 0 to 2266
Data columns (total 98 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   product_url                                                2267 non-null   str
 1   product_id                                                 2267 non-null   int64
 2   review_id                                                  1277 non-null   float64
 3   review_title                                               0 non-null      float64
 4   review_body                                                1277 non-null   str
 5   rating                                                     1277 non-null   float64
 6   helpful_count                                              1277 non-null   float64
 7   review_date                                                1277 non-null   str
 8   reviewer_id                                                1277 non-null   str
 9   reviewer_nickname                                          0 non-null      float64
 10  reviewer_grade                                             0 non-null      float64
 11  review_type                                                1277 non-null   str
 12  review_service_type                                        1277 non-null   str
 13  review_content_class                                       1277 non-null   str
 14  product_option                                             0 non-null      float64
 15  size_info                                                  0 non-null      float64
 16  keywords                                                   0 non-null      float64
 17  attach_count                                               1277 non-null   float64
 18  is_modified                                                1277 non-null   object
 19  modified_date                                              0 non-null      float64
 20  is_experience                                              1277 non-null   object
 21  is_purchase_confirmed                                      1277 non-null   object
 22  reply_count                                                1277 non-null   float64
 23  raw_json                                                   1277 non-null   str
 24  collect_status                                             2267 non-null   str
 25  extra_id                                                   1277 non-null   float64
 26  extra_reviewType                                           1277 non-null   str
 27  extra_reviewServiceType                                    1277 non-null   str
 28  extra_reviewContentClassType                               1277 non-null   str
 29  extra_reviewScore                                          1277 non-null   float64
 30  extra_reviewContent                                        1277 non-null   str
 31  extra_contentsStatusType                                   1277 non-null   str
 32  extra_createDate                                           1277 non-null   str
 33  extra_freeTrial                                            1277 non-null   object
 34  extra_repurchase                                           1277 non-null   object
 35  extra_parentReviewId                                       45 non-null     float64
 36  extra_writerId                                             1277 non-null   str
 37  extra_maskedWriterId                                       1277 non-null   str
 38  extra_writerIdNo                                           0 non-null      float64
 39  extra_writerMemberNo                                       1277 non-null   float64
 40  extra_writerProfileImageUrl                                1277 non-null   str
 41  extra_storeType                                            1277 non-null   str
 42  extra_storeNo                                              1277 non-null   float64
 43  extra_checkoutMerchantId                                   0 non-null      float64
 44  extra_checkoutMerchantNo                                   1277 non-null   float64
 45  extra_orderNo                                              0 non-null      float64
 46  extra_productOrderNo                                       1277 non-null   float64
 47  extra_productNo                                            1277 non-null   float64
 48  extra_productName                                          1277 non-null   str
 49  extra_productUrl                                           1277 non-null   str
 50  extra_largeCategorizeCategoryId                            1277 non-null   float64
 51  extra_middleCategorizeCategoryId                           1277 non-null   float64
 52  extra_smallCategorizeCategoryId                            1277 non-null   float64
 53  extra_productOptionContent                                 1277 non-null   str
 54  extra_knowledgeShoppingMallProductId                       1277 non-null   float64
 55  extra_originProductNo                                      1277 non-null   float64
 56  extra_reviewAttaches                                       1277 non-null   str
 57  extra_reviewEvaluationValueIds                             1277 non-null   str
 58  extra_subReviewEvaluationValueIds                          1277 non-null   str
 59  extra_reviewTopics                                         1031 non-null   str
 60  extra_eventTitle                                           0 non-null      float64
 61  extra_profileImageSourceType                               1277 non-null   str
 62  extra_repThumbnailAttach.id                                887 non-null    float64
 63  extra_repThumbnailAttach.reviewAttachmentType              887 non-null    str
 64  extra_repThumbnailAttach.attachUrl                         887 non-null    str
 65  extra_repThumbnailAttach.attachWidth                       887 non-null    float64
 66  extra_repThumbnailAttach.attachHeight                      887 non-null    float64
 67  extra_repThumbnailAttach.attachPath                        887 non-null    str
 68  extra_repThumbnailAttach.attachSize                        887 non-null    float64
 69  extra_repThumbnailAttach.attachDescription                 6 non-null      str
 70  extra_repThumbnailAttach.sortOrder                         887 non-null    float64
 71  extra_repThumbnailAttach.attachName                        887 non-null    str
 72  extra_repThumbnailAttach.attachDirectoryName               887 non-null    str
 73  extra_isMyReview                                           1277 non-null   object
 74  extra_detailCategorizeCategoryId                           731 non-null    float64
 75  extra_reviewUserInfoValues                                 595 non-null    str
 76  extra_reviewContentAnalysisSummaryTags                     976 non-null    str
 77  extra_helpCount                                            71 non-null     float64
 78  extra_modifyDate                                           9 non-null      str
 79  extra_repThumbnailAttach.attachServiceId                   2 non-null      float64
 80  extra_repThumbnailAttach.attachVid                         2 non-null      str
 81  extra_repThumbnailAttach.mimeTypeName                      2 non-null      str
 82  extra_repThumbnailTagNameDescription.id                    7 non-null      float64
 83  extra_repThumbnailTagNameDescription.reviewAttachmentType  7 non-null      str
 84  extra_repThumbnailTagNameDescription.attachUrl             7 non-null      str
 85  extra_repThumbnailTagNameDescription.attachWidth           7 non-null      float64
 86  extra_repThumbnailTagNameDescription.attachHeight          7 non-null      float64
 87  extra_repThumbnailTagNameDescription.attachPath            7 non-null      str
 88  extra_repThumbnailTagNameDescription.attachSize            7 non-null      float64
 89  extra_repThumbnailTagNameDescription.attachDescription     6 non-null      str
 90  extra_repThumbnailTagNameDescription.sortOrder             7 non-null      float64
 91  extra_repThumbnailTagNameDescription.attachName            7 non-null      str
 92  extra_repThumbnailTagNameDescription.attachDirectoryName   7 non-null      str
 93  extra_repThumbnailAttach.reviewTagId                       3 non-null      float64
 94  extra_repThumbnailAttach.reviewTagName                     3 non-null      str
 95  extra_repThumbnailTagNameDescription.reviewTagId           3 non-null      float64
 96  extra_repThumbnailTagNameDescription.reviewTagName         3 non-null      str
 97  extra_reviewInspectionPolicyReason                         2 non-null      str
dtypes: float64(44), int64(1), object(6), str(47)
memory usage: 6.7+ MB

In [ ]:
# ================================================================================================================
# 사용할 컬럼 선정
# 'product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'reviewer_id', 'review_content_class'
# 'extra_id', 'extra_reviewContentClassType', 'extra_reviewScore', 'extra_reviewContent', 'extra_createDate', 'extra_writerId', 'extra_productNo', 'extra_productName', 'extra_productOptionContent', 'extra_reviewTopics', 
#   ㄴ리뷰ID
# ================================================================================================================

df2 = df[['product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'reviewer_id', 'review_content_class',
        'extra_id', 'extra_reviewContentClassType', 'extra_reviewScore', 'extra_reviewContent', 'extra_createDate', 'extra_writerId', 'extra_productNo',
        'extra_productName', 'extra_productOptionContent', 'extra_reviewTopics']
]

display(df2.head())
print(df2.info())

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,reviewer_id,review_content_class,extra_id,extra_reviewContentClassType,extra_reviewScore,extra_reviewContent,extra_createDate,extra_writerId,extra_productNo,extra_productName,extra_productOptionContent,extra_reviewTopics
0,https://brand.naver.com/fila/products/10739081170,10739081170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://brand.naver.com/fila/products/10739087534,10739087534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://brand.naver.com/fila/products/10768506789,10768506789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24T13:14:50.302000+00:00,mini******,PHOTO,4.669237e+09,PHOTO,5.0,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,2025-02-24T13:14:50.302+00:00,mini******,1.129209e+10,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31T13:07:37.398000+00:00,mini******,PHOTO,4.652212e+09,PHOTO,5.0,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,2025-01-31T13:07:37.398+00:00,mini******,1.129209e+10,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."

<class 'pandas.DataFrame'>
RangeIndex: 2267 entries, 0 to 2266
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product_url                   2267 non-null   str
 1   product_id                    2267 non-null   int64
 2   review_id                     1277 non-null   float64
 3   review_body                   1277 non-null   str
 4   rating                        1277 non-null   float64
 5   helpful_count                 1277 non-null   float64
 6   review_date                   1277 non-null   str
 7   reviewer_id                   1277 non-null   str
 8   review_content_class          1277 non-null   str
 9   extra_id                      1277 non-null   float64
 10  extra_reviewContentClassType  1277 non-null   str
 11  extra_reviewScore             1277 non-null   float64
 12  extra_reviewContent           1277 non-null   str
 13  extra_createDate              1277 non-null   str
 14  extra_writerId                1277 non-null   str
 15  extra_productNo               1277 non-null   float64
 16  extra_productName             1277 non-null   str
 17  extra_productOptionContent    1277 non-null   str
 18  extra_reviewTopics            1031 non-null   str
dtypes: float64(6), int64(1), str(12)
memory usage: 1.1 MB
None

In [ ]:
# ================================================================================================================
# dtype 정리
# ================================================================================================================

df2['review_date'] = pd.to_datetime(df2['review_date'])
df2['extra_createDate'] = pd.to_datetime(df2['extra_createDate'])

df2[['review_date', 'extra_createDate']].info()

<class 'pandas.DataFrame'>
RangeIndex: 2267 entries, 0 to 2266
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_date       1277 non-null   datetime64[us, UTC]
 1   extra_createDate  1277 non-null   datetime64[us, UTC]
dtypes: datetime64[us, UTC](2)
memory usage: 35.6 KB

In [ ]:
# ================================================================================================================
# review_body 있는 것들만 남기기
# ================================================================================================================

df_body = df2.dropna(subset=['review_body'], axis=0)
df_body.info()

<class 'pandas.DataFrame'>
Index: 1277 entries, 3 to 2203
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product_url                   1277 non-null   str
 1   product_id                    1277 non-null   int64
 2   review_id                     1277 non-null   float64
 3   review_body                   1277 non-null   str
 4   rating                        1277 non-null   float64
 5   helpful_count                 1277 non-null   float64
 6   review_date                   1277 non-null   datetime64[us, UTC]
 7   reviewer_id                   1277 non-null   str
 8   review_content_class          1277 non-null   str
 9   extra_id                      1277 non-null   float64
 10  extra_reviewContentClassType  1277 non-null   str
 11  extra_reviewScore             1277 non-null   float64
 12  extra_reviewContent           1277 non-null   str
 13  extra_createDate              1277 non-null   datetime64[us, UTC]
 14  extra_writerId                1277 non-null   str
 15  extra_productNo               1277 non-null   float64
 16  extra_productName             1277 non-null   str
 17  extra_productOptionContent    1277 non-null   str
 18  extra_reviewTopics            1031 non-null   str
dtypes: datetime64[us, UTC](2), float64(6), int64(1), str(10)
memory usage: 830.9 KB

In [ ]:
# ================================================================================================================
# 컬럼 매칭 확인
# ================================================================================================================

# 1. product_id = extra_productNo
print("product_id != extra_productNo 개수: ", (df_body['product_id'] != df_body['extra_productNo']).sum(), "개")
# 1277개 : 전체 데이터가 매칭되지 않음. -> url에 표시되는 건 'product_id'이 맞음 -> 이걸로 결정

# 2. review_id = extra_id
print("review_id != extra_id 개수: ", (df_body['review_id'] != df_body['extra_id']).sum(), "개")

# 3. review_body = extra_reviewContent
print("review_body != extra_reviewContent 개수: ", (df_body['review_body'] != df_body['extra_reviewContent']).sum(), "개")

# 4. review_date = extra_createDate
print("review_date != extra_createDate 개수: ", (df_body['review_date'] != df_body['extra_createDate']).sum(), "개")

# 5. reviewer_id = extra_writerId
print("reviewer_id != extra_writerId 개수: ", (df_body['reviewer_id'] != df_body['extra_writerId']).sum(), "개")

# 6. review_content_class = extra_reviewContentClassType
print("review_content_class != extra_reviewContentClassType 개수: ", (df_body['review_content_class'] != df_body['extra_reviewContentClassType']).sum(), "개")

product_id != extra_productNo 개수:  1277 개
review_id != extra_id 개수:  0 개
review_body != extra_reviewContent 개수:  0 개
review_date != extra_createDate 개수:  0 개
reviewer_id != extra_writerId 개수:  0 개
review_content_class != extra_reviewContentClassType 개수:  0 개

In [ ]:
# ================================================================================================================
# product_id -> extra_productNo 제거
# ================================================================================================================
# df_body = df_body.drop(columns=['extra_productNo'])
print("===== 'extra_productNo' 제거 후 컬럼 확인 =====")
print(df_body.columns.to_list()) # 잘 됨.

===== 'extra_productNo' 제거 후 컬럼 확인 =====
['product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'reviewer_id', 'review_content_class', 'extra_id', 'extra_reviewContentClassType', 'extra_reviewScore', 'extra_reviewContent', 'extra_createDate', 'extra_writerId', 'extra_productName', 'extra_productOptionContent', 'extra_reviewTopics']

In [24]:
df_body.head(5)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,reviewer_id,review_content_class,extra_id,extra_reviewContentClassType,extra_reviewScore,extra_reviewContent,extra_createDate,extra_writerId,extra_productNo,extra_productName,extra_productOptionContent,extra_reviewTopics
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,mini******,PHOTO,4.669237e+09,PHOTO,5.0,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,2025-02-24 13:14:50.302000+00:00,mini******,1.129209e+10,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,mini******,PHOTO,4.652212e+09,PHOTO,5.0,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,2025-01-31 13:07:37.398000+00:00,mini******,1.129209e+10,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
5,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,ex****,PHOTO,4.652239e+09,PHOTO,5.0,넘 귀야워요 만족ㅎㅎ,2025-01-31 14:23:34.326000+00:00,ex****,1.076972e+10,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
6,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,youn*******,PHOTO,4.634973e+09,PHOTO,5.0,깜찍합니다.이뿌구요^^,2025-01-03 23:36:57.419000+00:00,youn*******,1.076972e+10,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
7,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,yoon*******,PHOTO,4.944300e+09,PHOTO,4.0,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,2026-04-02 04:45:38.825000+00:00,yoon*******,1.129348e+10,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,"[{""topicCode"": ""size"", ""topicCodeName"": ""사이즈"",..."

In [30]:
df_body.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/fila_naver_store_reviews/FILA_NaverStore_Review_since2020.csv", encoding='utf-8')