In [4]:
import pandas as pd
import numpy as np

---
# 휠라 무신사 리뷰 데이터

## 1. 전처리

In [43]:
# 파일 불러오기
import pandas as pd
import numpy as np

df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv")
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,...,option,helpful,comment_count,has_image,image_urls,survey_size,survey_width,survey_comfort,survey_instep,url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,스타일,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,기발한스웨덴웨지,NaN,...,Grey/White/White · 270,1,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,보통,아주 편안,https://www.musinsa.com/products/3892794#revie...
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,스타일,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,아트텍,NaN,...,Grey/White/White · 260,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,적당,https://www.musinsa.com/products/3892794#revie...
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,스타일,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,신중한하얀단화,NaN,...,Grey/White/White · 255,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,편안,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   collect_date    14100 non-null  str
 1   review_date     14100 non-null  str
 2   product_id      14100 non-null  int64
 3   product_name    14100 non-null  str
 4   review_no       14100 non-null  int64
 5   review_type     14100 non-null  str
 6   rating          14100 non-null  int64
 7   review_text     14090 non-null  str
 8   author          14100 non-null  str
 9   user_height     0 non-null      float64
 10  user_weight     0 non-null      float64
 11  option          14086 non-null  str
 12  helpful         14100 non-null  int64
 13  comment_count   14100 non-null  int64
 14  has_image       14100 non-null  bool
 15  image_urls      8621 non-null   str
 16  survey_size     4227 non-null   str
 17  survey_width    4227 non-null   str
 18  survey_comfort  4227 non-null   str
 19  survey_instep   4227 non-null   str
 20  url             14100 non-null  str
dtypes: bool(1), float64(2), int64(5), str(13)
memory usage: 7.6 MB

None

In [44]:
# =======================================
# 사용할 컬럼만 남기기
# =======================================
df_review_fila_mss = df_review_fila_mss.drop(['review_type', 'author', 'comment_count', 'image_urls', 'survey_size', 'survey_width', 'survey_comfort', 'survey_instep'], axis=1)
df_review_fila_mss.info() # 컬럼 13개

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  14100 non-null  str
 1   review_date   14100 non-null  str
 2   product_id    14100 non-null  int64
 3   product_name  14100 non-null  str
 4   review_no     14100 non-null  int64
 5   rating        14100 non-null  int64
 6   review_text   14090 non-null  str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        14086 non-null  str
 10  helpful       14100 non-null  int64
 11  has_image     14100 non-null  bool
 12  url           14100 non-null  str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 5.4 MB

In [45]:
# =======================================
# 결측치 처리
# =======================================
# 'review_text' => 14090개로 결측치 있음.

# 리뷰 텍스트 분석이 중요
df_review_fila_mss['review_text'].isna().mean()*100 # 0.07% => 행 제거로 결정

df_review_fila_mss = df_review_fila_mss.dropna(subset=['review_text'], axis=0)
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  14090 non-null  str
 1   review_date   14090 non-null  str
 2   product_id    14090 non-null  int64
 3   product_name  14090 non-null  str
 4   review_no     14090 non-null  int64
 5   rating        14090 non-null  int64
 6   review_text   14090 non-null  str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        14076 non-null  str
 10  helpful       14090 non-null  int64
 11  has_image     14090 non-null  bool
 12  url           14090 non-null  str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 5.5 MB

In [46]:
# =======================================
# 중복된 데이터 제거
# =======================================
df_review_fila_mss = df_review_fila_mss.drop_duplicates(subset=[
        'review_date', 'product_id', 'product_name', 'review_no', 'rating', 'review_text', 'user_height', 'user_weight', 'option', 'helpful', 'has_image', 'url'
])

df_review_fila_mss.shape # (8575, 13)

(8575, 13)

In [47]:
pd.set_option('display.max_colwidth', None)
print(df_review_fila_mss.duplicated(subset=['review_date', 'product_id', 'product_name', 'rating', 'review_text', 'user_height', 'user_weight', 'option']).sum())
display(df_review_fila_mss[df_review_fila_mss.duplicated(subset=['review_date', 'product_id', 'product_name', 'rating', 'review_text', 'user_height', 'user_weight', 'option'])].head())

366

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
386,2026-04-21 17:04:23,2024-07-08,3892794,에샤페 실버문(1XM02348H063),62186291,5,"이쁩니다, 맘에 들어요, 배송도 빠르구요~굿 good",NaN,NaN,NaN,0,True,https://www.musinsa.com/products/3892794#review_62186291
709,2026-04-21 17:04:23,2025-08-02,3892794,에샤페 실버문(1XM02348H063),77345201,5,실물이 더 예뻐요 메쉬라서 여름에 신기 좋고 발볼은 살짝 좁게 나와서 넓으면 반사이즈업 추천드립니다,NaN,NaN,Grey/White/White · 240,0,True,https://www.musinsa.com/products/3892794#review_77345201
799,2026-04-21 17:04:23,2025-06-30,3892794,에샤페 실버문(1XM02348H063),76303062,5,너무 이뻐요 발도 너무 편하고 사이즈도 딱 맞아요 ㅎㅎ 굳쟙입니다,NaN,NaN,Grey/White/White · 225,0,True,https://www.musinsa.com/products/3892794#review_76303062
880,2026-04-21 17:04:23,2025-06-19,3892794,에샤페 실버문(1XM02348H063),75601831,5,너무 과한 실버가 아닐까 걱정했는데 실물은 과하지 않고 포인트가 예쁘게 들어가 있는 신발 느낌입니다. 여름에 여기저기 다 잘 신을 것 같아요. 사이즈는 정사이즈 했더니 아주 약간 큰느낌입이다. 그런데 그냥 신고있어용 괜찮 ㅎㅎ,NaN,NaN,Grey/White/White · 240,0,True,https://www.musinsa.com/products/3892794#review_75601831
1040,2026-04-21 17:04:23,2025-05-13,3892794,에샤페 실버문(1XM02348H063),74160796,5,디자인 깔끔하고 착화감 편안해서 아주 맘에 들어요.,NaN,NaN,Grey/White/White · 225,0,True,https://www.musinsa.com/products/3892794#review_74160796

In [48]:
subset_cols = ['review_date', 'product_id', 'product_name', 'rating', 'review_text', 'user_height', 'user_weight', 'option']

# has_image 내림차순, helpful 내림차순 정렬 → 각 그룹에서 첫 번째 행만 남김
df_review_fila_mss = (
    df_review_fila_mss
    .sort_values(['has_image', 'helpful'], ascending=[False, False])
    .drop_duplicates(subset=subset_cols, keep='first')
    .sort_index()
)

df_review_fila_mss.shape # 8575 - 366 = 8209 (잘 지워진 것 확인 완료)

(8209, 13)

In [49]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  8209 non-null   str
 1   review_date   8209 non-null   str
 2   product_id    8209 non-null   int64
 3   product_name  8209 non-null   str
 4   review_no     8209 non-null   int64
 5   rating        8209 non-null   int64
 6   review_text   8209 non-null   str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        8201 non-null   str
 10  helpful       8209 non-null   int64
 11  has_image     8209 non-null   bool
 12  url           8209 non-null   str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 3.1 MB

In [50]:
# =======================================
# 결측치 처리
# =======================================
# option => 8개 결측치 있음
df_review_fila_mss['option'].isna().mean()*100 # 0.097%

# 에샤페 실버문(1XM02348H063) 상품에만 결측치 있음.
df_review_fila_mss[df_review_fila_mss['option'].isna()]

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
385,2026-04-21 17:04:23,2024-07-08,3892794,에샤페 실버문(1XM02348H063),62186309,5,"이쁩니다, 맘에 들어요, 배송도 빠르구요~굿 good",NaN,NaN,NaN,0,True,https://www.musinsa.com/products/3892794#review_62186309
2114,2026-04-21 17:04:23,2024-07-08,3892794,에샤페 실버문(1XM02348H063),62201621,5,에샤페 맨날 기다리다가 드디어 삿네요 ㅎㅎ 색감 넘 이뻐요 국굳,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62201621
2120,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62164947,5,예쁘다는 이야기 많이 들어요 포인트는 좋아요 착화감은 발 모양에 따라 많이 다를거 같아요,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62164947
2121,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62164761,5,전부터 맘에 들어 찜해놓다가 딸 선물로 사줬는데 너무 좋아하네요~발이 편하대요. 디자인도 이쁘구요~^^,NaN,NaN,NaN,1,True,https://www.musinsa.com/products/3892794#review_62164761
2122,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62164656,5,전부터 눈여겨보다가 고민끝에 구매했는데 맘에 들어요~^^,NaN,NaN,NaN,2,False,https://www.musinsa.com/products/3892794#review_62164656
2125,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62145658,5,상품은 생각보다 너무 마음에 들어요. 친구한테 추천도 해줘야지! 굿굿,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62145658
2127,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62136416,5,반짝반짝 너무 예쁘지 않나요?!?? 전 너무 맘에 들어요,NaN,NaN,NaN,0,True,https://www.musinsa.com/products/3892794#review_62136416
2128,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62136386,5,저런 여름 운동화 하나 갖고 싶었는데 무신사에 떠서 너무 좋아요 뜨자마자 바로 샀어요,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62136386

In [51]:
# option이 null인 product_id 추출
null_product_ids = df_review_fila_mss[df_review_fila_mss['option'].isna()]['product_id'].unique()

# 해당 product_id들의 option 분포 확인
df_review_fila_mss[df_review_fila_mss['product_id'].isin(null_product_ids)][['product_id', 'product_name', 'option']].value_counts(dropna=False)
# =>>> option = 범주형 데이터 => 최빈값으로 대체 (Grey/White/White · 240) => 결측치가 8개로 아주 작은 숫자라 대체해도 데이터 왜곡 적을 것임.

product_id  product_name           option
3892794     에샤페 실버문(1XM02348H063)  Grey/White/White · 240    736
                                   Grey/White/White · 235    458
                                   Grey/White/White · 250    454
                                   Grey/White/White · 245    452
                                   Grey/White/White · 230    419
                                   Grey/White/White · 255    169
                                   Grey/White/White · 225    100
                                   Grey/White/White · 260     79
                                   Grey/White/White · 220     54
                                   Grey/White/White · 265     50
                                   Grey/White/White · 270     38
                                   Grey/White/White · 275     32
                                   Grey/White/White · 280     32
                                   Grey/White/White · 290     15
                                   Grey/White/White · 285     11
                                   NaN                         8
                                   GREY/WHITE/WHITE · 245      5
                                   GREY/WHITE/WHITE · 240      4
                                   GREY/WHITE/WHITE · 285      3
                                   GREY/WHITE/WHITE · 230      3
                                   GREY/WHITE/WHITE · 235      3
                                   GREY/WHITE/WHITE · 250      2
                                   GREY/WHITE/WHITE · 265      2
                                   GREY/WHITE/WHITE · 220      1
                                   GREY/WHITE/WHITE · 275      1
Name: count, dtype: int64

In [52]:
df_review_fila_mss.loc[df_review_fila_mss['option'].isna(), 'option'] = 'Grey/White/White · 240'

print("===== 결측치 확인 ======")
print(df_review_fila_mss.info())
print("===== option 값 유지 확인 ======")
print(df_review_fila_mss['option'].value_counts())

===== 결측치 확인 ======
<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  8209 non-null   str
 1   review_date   8209 non-null   str
 2   product_id    8209 non-null   int64
 3   product_name  8209 non-null   str
 4   review_no     8209 non-null   int64
 5   rating        8209 non-null   int64
 6   review_text   8209 non-null   str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        8209 non-null   str
 10  helpful       8209 non-null   int64
 11  has_image     8209 non-null   bool
 12  url           8209 non-null   str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 3.1 MB
None
===== option 값 유지 확인 ======
option
Grey/White/White · 240        744
Brown/Brown/Brown · 240       483
Grey/White/White · 235        458
Grey/White/White · 250        454
Grey/White/White · 245        452
Grey/White/White · 230        419
Brown/Brown/Brown · 230       269
Brown/Brown/Brown · 245       231
Brown/Brown/Brown · 235       225
Brown/Brown/Brown · 250       216
Grey/White/White · 255        169
Beige/Beige/Beige · 240       147
BROWN/BROWN/BROWN · 240       127
Brown/Brown/Brown · 225       104
Grey/White/White · 225        100
Beige/Beige/Beige · 230        87
Black/Black/White · 240        84
Brown/Brown/Brown · 255        82
Grey/White/White · 260         79
Brown/Brown/Brown · 220        72
BROWN/BROWN/BROWN · 235        71
Beige/Beige/Beige · 250        69
Black/Black/Black · 240        69
Beige/Beige/Beige · 245        63
BROWN/BROWN/BROWN · 245        62
Brown/Brown/Brown · 260        62
BROWN/BROWN/BROWN · 230        60
Brown/Brown/Brown · 270        60
Grey/Grey/Grey · 240           58
BROWN/BROWN/BROWN · 250        57
Beige/Beige/Beige · 235        55
Grey/Grey/Grey · 245           55
White/Black/Grey · 240         55
Grey/White/White · 220         54
Grey/White/White · 265         50
Black/Black/Silver · 235       50
White/Black/Grey · 245         49
Brown/Brown/Brown · 265        47
Black/Black/Silver · 240       46
Grey/Grey/Grey · 235           46
Brown/Brown/Brown · 280        44
Black/Black/Black · 235        42
Black/Black/White · 230        41
Black/Black/White · 250        40
GREEN/GREEN/GREEN · 240        39
Grey/White/White · 270         38
White/Black/Grey · 235         38
Black/Black/Black · 230        38
Grey/Grey/Grey · 250           38
Black/Black/Black · 245        36
Black/Black/Black · 250        35
GREEN/GREEN/GREEN · 230        35
Black/Black/Silver · 245       33
Grey/White/White · 275         32
Grey/White/White · 280         32
BROWN/BROWN/BROWN · 255        29
Black/Black/Silver · 230       29
Grey/Grey/Grey · 230           28
GREEN/GREEN/GREEN · 250        28
Black/Grey/Black · 230         27
Black/Black/Silver · 250       26
GREEN/GREEN/GREEN · 245        26
Black/Black/Silver · 255       25
Grey/Grey/Grey · 255           25
BLACK/BLACK/WHITE · 240        25
GRAY/GRAY/GRAY · 240           25
Black/Grey/Black · 250         23
Brown/Brown/Brown · 275        22
White/Black/Grey · 250         22
GRAY/GRAY/GRAY · 245           22
Beige/Beige/Beige · 225        21
Black/Black/Silver · 270       21
Black/Black/Silver · 260       19
GREEN/GREEN/GREEN · 235        19
BROWN/BROWN/BROWN · 260        18
White/Black/Grey · 260         18
White/Black/Grey · 230         18
Grey/Blue/Grey · 240           18
BLACK/BLACK/WHITE · 245        18
GRAY/GRAY/GRAY · 235           18
BROWN/BROWN/BROWN · 225        17
BLACK/BLACK/WHITE · 230        17
Beige/Beige/Beige · 255        16
Beige/Beige/Beige · 265        16
Grey/Blue/Grey · 230           16
Black/Grey/Black · 235         16
Black/Grey/Black · 240         16
GRAY/GRAY/GRAY · 230           16
BEIGE/BEIGE/BEIGE · 240        16
Grey/White/White · 290         15
Beige/Beige/Beige · 220        15
BLACK/BLACK/WHITE · 250        15
Beige/Beige/Beige · 260        14
Grey/Grey/Grey · 225           14
GREEN/GREEN/GREEN · 225        14
BEIGE/BEIGE/BEIGE · 245        13
BLACK/WHITE/BROWN · 240        13
BROWN/BROWN/BROWN · 265        12
BEIGE/BEIGE/BEIGE · 235        12
Black/Black/Silver · 265       12
White/Black/Grey · 270         12
Black/Black/Black · 220        12
Grey/Blue/Grey · 250           12
Grey/White/White · 285         11
BROWN/BROWN/BROWN · 275        11
BROWN/BROWN/BROWN · 270        11
Pink/Pink/Pink · 220           11
BROWN/ORANGE/WHITE · 250       11
BEIGE/BEIGE/BEIGE · 250        11
White/Black/Grey · 255         10
Black/Black/Black · 255        10
Pink/Pink/Pink · 230           10
GREEN/GREEN/GREEN · 255        10
BROWN/ORANGE/WHITE · 240       10
BROWN/ORANGE/WHITE · 245       10
BLACK/WHITE/BROWN · 230        10
Brown/Brown/Brown · 290         9
BROWN/BROWN/BROWN · 220         9
BROWN/BROWN/BROWN · 280         9
White/Black/Grey · 225          9
Black/Black/Black · 225         9
Black/Black/White · 220         9
GRAY/GRAY/GRAY · 250            9
RED/RED/GRAY · 240              9
BLACK/WHITE/BROWN · 235         9
Beige/Beige/Beige · 270         8
Black/Black/Silver · 275        8
Black/Black/Silver · 280        8
White/Black/Grey · 280          8
BLACK/BLACK/WHITE · 235         8
Brown/Brown/Brown · 285         7
Black/Grey/Black · 270          7
GREEN/GREEN/GREEN · 260         7
BLACK/WHITE/BROWN · 245         7
BLACK/BLACK/BLACK · 240         6
Pink/Pink/Pink · 240            6
BLACK/BLACK/BLACK · 230         6
BROWN/ORANGE/YELLOW · 235       6
BROWN/ORANGE/YELLOW · 245       6
BROWN/ORANGE/WHITE · 230        6
BROWN/ORANGE/WHITE · 235        6
GREY/WHITE/WHITE · 245          5
White/Brown/White · 240         5
Beige/Beige/Beige · 280         5
White/Black/Grey · 265          5
Black/Black/White · 260         5
Black/Black/Black · 260         5
BLACK/BLACK/WHITE · 220         5
Pink/Pink/Pink · 250            5
GREEN/GREEN/GREEN · 220         5
BROWN/ORANGE/YELLOW · 250       5
BEIGE/BEIGE/BEIGE · 230         5
GRAY/GRAY/GRAY · 225            5
PINK/PINK/BLACK · 235           5
GREY/WHITE/WHITE · 240          4
Black/Black/Silver · 290        4
White/Black/Grey · 285          4
BLACK/BLACK/BLACK · 245         4
BLACK/BLACK/WHITE · 260         4
Black/Grey/Black · 245          4
Black/Grey/Black · 260          4
BROWN/ORANGE/WHITE · 280        4
BROWN/ORANGE/YELLOW · 240       4
BLACK/WHITE/BROWN · 250         4
BLUE/BLUE/BLUE · 240            4
GREY/WHITE/WHITE · 285          3
GREY/WHITE/WHITE · 230          3
GREY/WHITE/WHITE · 235          3
Beige/Beige/Beige · 290         3
White/Black/Grey · 275          3
White/Black/Grey · 220          3
GREY/GREY/GREY · 235            3
BLACK/BLACK/BLACK · 250         3
Black/Black/White · 280         3
Black/Grey/Black · 280          3
Black/Grey/Black · 255          3
Black/Grey/Black · 225          3
BLACK/BLACK/WHITE · 255         3
BROWN/ORANGE/WHITE · 260        3
BROWN/ORANGE/WHITE · 225        3
BROWN/ORANGE/YELLOW · 265       3
GRAY/GRAY/GRAY · 255            3
PINK/PINK/PINK · 240            3
BEIGE/BEIGE/BEIGE · 260         3
RED/RED/GRAY · 245              3
RED/RED/GRAY · 260              3
GREY/WHITE/WHITE · 250          2
GREY/WHITE/WHITE · 265          2
White/Brown/White · 225         2
White/Brown/White · 245         2
White/Brown/White · 255         2
BEIGE/BEIGE/BEIGE · 225         2
BROWN/BROWN/BROWN · 290         2
BLACK/BLACK/SILVER · 240        2
GREY/GREY/GREY · 250            2
Black/Black/White · 270         2
Black/Black/Black · 290         2
Black/Black/Black · 270         2
BLACK/BLACK/BLACK · 260         2
Green/Green/Green · 255         2
Brown/Orange/Yellow · 250       2
BLACK/BLACK/WHITE · 225         2
GREEN/GREEN/GREEN · 265         2
BROWN/ORANGE/WHITE · 220        2
BROWN/ORANGE/WHITE · 265        2
BROWN/ORANGE/WHITE · 255        2
GRAY/GRAY/GRAY · 260            2
BEIGE/BEIGE/BEIGE · 255         2
PINK/PINK/BLACK · 230           2
PINK/PINK/BLACK · 245           2
RED/RED/GRAY · 250              2
RED/RED/GRAY · 230              2
RED/RED/GRAY · 235              2
BLACK/BLACK/BLACK · 235         2
BLACK/WHITE/BROWN · 220         2
BLUE/BLUE/BLUE · 230            2
BEIGE/BEIGE/BEIGE · 270         2
GREY/WHITE/WHITE · 220          1
GREY/WHITE/WHITE · 275          1
White/Brown/White · 270         1
White/Brown/White · 265         1
White/Brown/White · 250         1
White/Brown/White · 275         1
White/Brown/White · 230         1
White/Brown/White · 235         1
Beige/Beige/Beige · 275         1
BLACK/BLACK/SILVER · 235        1
BLACK/BLACK/SILVER · 280        1
BLACK/BLACK/SILVER · 260        1
Black/Black/Silver · 285        1
BLACK/BLACK/SILVER · 270        1
WHITE/BLACK/GREY · 235          1
GREY/GREY/GREY · 220            1
Grey/Grey/Grey · 220            1
BLACK/BLACK/BLACK · 270         1
Black/Black/Black · 280         1
BLACK/GREY/BLACK · 245          1
GREY/BLUE/GREY · 260            1
Grey/Blue/Grey · 260            1
GREEN/GREEN/GREEN · 270         1
BLACK/BLACK/WHITE · 275         1
BLACK/BLACK/WHITE · 270         1
BROWN/ORANGE/YELLOW · 280       1
BROWN/ORANGE/YELLOW · 255       1
GREEN/GREEN/GREEN · 290         1
BROWN/ORANGE/YELLOW · 275       1
BROWN/ORANGE/WHITE · 270        1
Green/Green/Green · 235         1
Brown/Orange/White · 250        1
BLACK/BLACK/WHITE · 265         1
BROWN/ORANGE/YELLOW · 260       1
GREEN/GREEN/GREEN · 285         1
BEIGE/BEIGE/BEIGE · 220         1
PINK/PINK/PINK · 255            1
PINK/PINK/PINK · 230            1
GRAY/GRAY/GRAY · 220            1
PINK/PINK/BLACK · 250           1
PINK/PINK/BLACK · 240           1
RED/RED/GRAY · 290              1
RED/RED/GRAY · 255              1
YELLOW/YELLOW/YELLOW · 240      1
BLACK/WHITE/BROWN · 260         1
BLUE/BLUE/BLUE · 275            1
Name: count, dtype: int64

In [53]:
# =======================================
# 컬럼명 변경
# =======================================

df_review_fila_mss = df_review_fila_mss.rename(columns={
    'review_no' : 'review_id',
    'review_text' : 'content',
    'option' : 'purchase_option',
    'helpful' : 'helpful_count',
    'url' : 'product_url'
})

df_review_fila_mss.head(3)

,collect_date,review_date,product_id,product_name,review_id,rating,content,user_height,user_weight,purchase_option,helpful_count,has_image,product_url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스랑 반스는 265정도 신는데 휠라는 270으로 구매하니 발도 편안하고 좋아요.,NaN,NaN,Grey/White/White · 270,1,True,https://www.musinsa.com/products/3892794#review_79849708
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감이 있는 듯하지만 편하다네요!,NaN,NaN,Grey/White/White · 260,0,True,https://www.musinsa.com/products/3892794#review_79753882
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,"여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로 바꿔 꼈더니 더 예쁜 느낌이네요! 캐주얼, 슬랙스, 스커트 가리지 않고 다 잘 어울려서 손이 자주 가고, 요즘 실버색상 유행이라 마음에 더 쏙 들어요!",NaN,NaN,Grey/White/White · 255,0,True,https://www.musinsa.com/products/3892794#review_79033605

In [54]:
# =======================================
# 없는 컬럼 추가
# =======================================

# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_mss.columns:
        df_review_fila_mss[col] = None

# =======================================
# 컬럼 순서 정리
# =======================================
df_review_fila_mss = df_review_fila_mss[required_columns]

df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       8209 non-null   str
 1   platform           0 non-null      object
 2   review_id          8209 non-null   int64
 3   product_id         8209 non-null   int64
 4   product_name       8209 non-null   str
 5   review_date        8209 non-null   str
 6   year               0 non-null      object
 7   month              0 non-null      object
 8   content            8209 non-null   str
 9   rating             8209 non-null   int64
 10  helpful_count      8209 non-null   int64
 11  has_image          8209 non-null   bool
 12  purchase_option    8209 non-null   str
 13  user_size          0 non-null      object
 14  user_height        0 non-null      float64
 15  user_weight        0 non-null      float64
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        8209 non-null   str
dtypes: bool(1), float64(2), int64(4), object(6), str(6)
memory usage: 3.5+ MB

In [55]:
# =======================================
# year, month 다시 생성하기
# =======================================
# 날짜 컬럼 형변환
df_review_fila_mss['collect_date'] = pd.to_datetime(df_review_fila_mss['collect_date']).dt.normalize()
df_review_fila_mss['review_date'] = pd.to_datetime(df_review_fila_mss['review_date']).dt.normalize()

# 기존 year, month 제거
df_review_fila_mss = df_review_fila_mss.drop(['year', 'month'], axis=1)

# 파생컬럼 생성
df_review_fila_mss['year'] = df_review_fila_mss['review_date'].dt.year
df_review_fila_mss['month'] = df_review_fila_mss['review_date'].dt.month

In [56]:
# =======================================
# platform = 무신사
# =======================================
df_review_fila_mss['platform'] = '무신사'
df_review_fila_mss['platform'].value_counts()

platform
무신사    8209
Name: count, dtype: int64

In [57]:
# =======================================
# 고객 신체 정보 None으로 채우기
# =======================================
df_review_fila_mss[['user_height', 'user_weight', 'user_height_group', 'user_weight_group']] = (
    df_review_fila_mss[['user_height', 'user_weight', 'user_height_group', 'user_weight_group']].astype(object).fillna(None)
)

In [58]:
# =======================================
# has_image => 0, 1로 변환하기
# =======================================
df_review_fila_mss['has_image'] = df_review_fila_mss['has_image'].map({
    True : 1,
    False : 0
})
df_review_fila_mss['has_image'].value_counts()

has_image
1    4970
0    3239
Name: count, dtype: int64

In [59]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       8209 non-null   datetime64[us]
 1   platform           8209 non-null   str
 2   review_id          8209 non-null   int64
 3   product_id         8209 non-null   int64
 4   product_name       8209 non-null   str
 5   review_date        8209 non-null   datetime64[us]
 6   content            8209 non-null   str
 7   rating             8209 non-null   int64
 8   helpful_count      8209 non-null   int64
 9   has_image          8209 non-null   int64
 10  purchase_option    8209 non-null   str
 11  user_size          0 non-null      object
 12  user_height        0 non-null      object
 13  user_weight        0 non-null      object
 14  user_height_group  0 non-null      object
 15  user_weight_group  0 non-null      object
 16  product_url        8209 non-null   str
 17  year               8209 non-null   int32
 18  month              8209 non-null   int32
dtypes: datetime64[us](2), int32(2), int64(5), object(5), str(5)
memory usage: 3.4+ MB

In [60]:
# =======================================
# 데이터 타입 정리하기
# =======================================
df_review_fila_mss['platform'] = df_review_fila_mss['platform'].astype('category')
df_review_fila_mss['purchase_option'] = df_review_fila_mss['purchase_option'].astype('category')

df_review_fila_mss[['platform', 'purchase_option']].info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   platform         8209 non-null   category
 1   purchase_option  8209 non-null   category
dtypes: category(2)
memory usage: 96.3 KB

In [61]:
# =======================================
# 컬럼 순서 변경
# =======================================
df_review_fila_mss = df_review_fila_mss[['collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url']]

df_review_fila_mss.head(3)

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,무신사,79849708,3892794,에샤페 실버문(1XM02348H063),2025-11-16,2025,11,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스랑 반스는 265정도 신는데 휠라는 270으로 구매하니 발도 편안하고 좋아요.,5,1,1,Grey/White/White · 270,None,None,None,None,None,https://www.musinsa.com/products/3892794#review_79849708
1,2026-04-21,무신사,79753882,3892794,에샤페 실버문(1XM02348H063),2025-11-11,2025,11,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감이 있는 듯하지만 편하다네요!,5,0,1,Grey/White/White · 260,None,None,None,None,None,https://www.musinsa.com/products/3892794#review_79753882
2,2026-04-21,무신사,79033605,3892794,에샤페 실버문(1XM02348H063),2025-10-15,2025,10,"여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로 바꿔 꼈더니 더 예쁜 느낌이네요! 캐주얼, 슬랙스, 스커트 가리지 않고 다 잘 어울려서 손이 자주 가고, 요즘 실버색상 유행이라 마음에 더 쏙 들어요!",5,0,1,Grey/White/White · 255,None,None,None,None,None,https://www.musinsa.com/products/3892794#review_79033605

In [62]:
# =======================================
# 이상치 확인
# =======================================
min(df_review_fila_mss['review_date']) # 2024-02-27
max(df_review_fila_mss['review_date']) # 2026-04-13

df_review_fila_mss['platform'].value_counts() # 무신사

df_review_fila_mss['review_id'].value_counts(ascending=False) # 모든 값 1

df_review_fila_mss['product_id'].value_counts(ascending=False)

df_review_fila_mss['product_name'].value_counts(ascending=False)

min(df_review_fila_mss['year']) # 2024
max(df_review_fila_mss['year']) # 2026

min(df_review_fila_mss['month']) # 1
max(df_review_fila_mss['month']) # 12

12

In [63]:
# =======================================
# 저장
# =======================================
df_review_fila_mss_2024 = df_review_fila_mss[df_review_fila_mss['year'] >= 2024]

df_review_fila_mss.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_musinsa_review_final.csv", encoding='utf-8-sig', index=False)
df_review_fila_mss_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_musinsa_review_final_s2024.csv", encoding='utf-8-sig', index=False)

## 2. 중복제거

In [89]:
# ===============================
# 제품명 매칭 확인
# ===============================
multi_name = df_review_fila_mss.groupby('product_id')['product_name'].nunique()
multi_url = df_review_fila_mss.groupby('product_id')['product_url'].nunique()

# product_name 매핑 확인
print(multi_name.gt(1).sum(), "개의 product_id가 여러 product_name에 매핑됨")
display(
    df_review_fila_mss[df_review_fila_mss['product_id'].isin(multi_name[multi_name > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

# product_url 매핑 확인
print(multi_url.gt(1).sum(), "개의 product_id가 여러 product_url에 매핑됨")
display(
    df_review_fila_mss[df_review_fila_mss['product_id'].isin(multi_url[multi_url > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

0 개의 product_id가 여러 product_name에 매핑됨

Empty DataFrame
Columns: [product_id, product_name, product_url]
Index: []

30 개의 product_id가 여러 product_url에 매핑됨

       product_id                    product_name  \
10274     3892778           에샤페 레이스(1XM02347H004)
10271     3892778           에샤페 레이스(1XM02347H004)
10154     3892778           에샤페 레이스(1XM02347H004)
10278     3892778           에샤페 레이스(1XM02347H004)
10152     3892778           에샤페 레이스(1XM02347H004)
10283     3892778           에샤페 레이스(1XM02347H004)
10150     3892778           에샤페 레이스(1XM02347H004)
10284     3892778           에샤페 레이스(1XM02347H004)
10286     3892778           에샤페 레이스(1XM02347H004)
10146     3892778           에샤페 레이스(1XM02347H004)
10145     3892778           에샤페 레이스(1XM02347H004)
10287     3892778           에샤페 레이스(1XM02347H004)
10143     3892778           에샤페 레이스(1XM02347H004)
10158     3892778           에샤페 레이스(1XM02347H004)
10142     3892778           에샤페 레이스(1XM02347H004)
10289     3892778           에샤페 레이스(1XM02347H004)
10291     3892778           에샤페 레이스(1XM02347H004)
10293     3892778           에샤페 레이스(1XM02347H004)
10136     3892778           에샤페 레이스(1XM02347H004)
10296     3892778           에샤페 레이스(1XM02347H004)
10302     3892778           에샤페 레이스(1XM02347H004)
10305     3892778           에샤페 레이스(1XM02347H004)
10128     3892778           에샤페 레이스(1XM02347H004)
10204     3892778           에샤페 레이스(1XM02347H004)
10124     3892778           에샤페 레이스(1XM02347H004)
10123     3892778           에샤페 레이스(1XM02347H004)
10311     3892778           에샤페 레이스(1XM02347H004)
10288     3892778           에샤페 레이스(1XM02347H004)
10269     3892778           에샤페 레이스(1XM02347H004)
10161     3892778           에샤페 레이스(1XM02347H004)
10268     3892778           에샤페 레이스(1XM02347H004)
10203     3892778           에샤페 레이스(1XM02347H004)
10207     3892778           에샤페 레이스(1XM02347H004)
10215     3892778           에샤페 레이스(1XM02347H004)
10217     3892778           에샤페 레이스(1XM02347H004)
10197     3892778           에샤페 레이스(1XM02347H004)
10219     3892778           에샤페 레이스(1XM02347H004)
10221     3892778           에샤페 레이스(1XM02347H004)
10224     3892778           에샤페 레이스(1XM02347H004)
10191     3892778           에샤페 레이스(1XM02347H004)
10188     3892778           에샤페 레이스(1XM02347H004)
10234     3892778           에샤페 레이스(1XM02347H004)
10239     3892778           에샤페 레이스(1XM02347H004)
10241     3892778           에샤페 레이스(1XM02347H004)
10181     3892778           에샤페 레이스(1XM02347H004)
10261     3892778           에샤페 레이스(1XM02347H004)
10262     3892778           에샤페 레이스(1XM02347H004)
10263     3892778           에샤페 레이스(1XM02347H004)
10172     3892778           에샤페 레이스(1XM02347H004)
10171     3892778           에샤페 레이스(1XM02347H004)
10264     3892778           에샤페 레이스(1XM02347H004)
10169     3892778           에샤페 레이스(1XM02347H004)
10168     3892778           에샤페 레이스(1XM02347H004)
10167     3892778           에샤페 레이스(1XM02347H004)
10265     3892778           에샤페 레이스(1XM02347H004)
10165     3892778           에샤페 레이스(1XM02347H004)
10164     3892778           에샤페 레이스(1XM02347H004)
10163     3892778           에샤페 레이스(1XM02347H004)
10312     3892778           에샤페 레이스(1XM02347H004)
10313     3892778           에샤페 레이스(1XM02347H004)
10306     3892778           에샤페 레이스(1XM02347H004)
10361     3892778           에샤페 레이스(1XM02347H004)
10352     3892778           에샤페 레이스(1XM02347H004)
10355     3892778           에샤페 레이스(1XM02347H004)
10090     3892778           에샤페 레이스(1XM02347H004)
10089     3892778           에샤페 레이스(1XM02347H004)
10088     3892778           에샤페 레이스(1XM02347H004)
10315     3892778           에샤페 레이스(1XM02347H004)
10366     3892778           에샤페 레이스(1XM02347H004)
10369     3892778           에샤페 레이스(1XM02347H004)
10083     3892778           에샤페 레이스(1XM02347H004)
10081     3892778           에샤페 레이스(1XM02347H004)
10077     3892778           에샤페 레이스(1XM02347H004)
10074     3892778           에샤페 레이스(1XM02347H004)
10072     3892778           에샤페 레이스(1XM02347H004)
10093     3892778           에샤페 레이스(1XM02347H004)
10071     3892778           에샤페 레이스(1XM02347H004)
10377     3892778           에샤페 레이스(1XM02347H004)
10068     3892778           에샤페 레이스(1XM02347H004)
10386     3892778           에샤페 레이스(1XM02347H004)
10388     3892778           에샤페 레이스(1XM02347H004)
10390     3892778           에샤페 레이스(1XM02347H004)
10394     3892778           에샤페 레이스(1XM02347H004)
10063     3892778           에샤페 레이스(1XM02347H004)
10395     3892778           에샤페 레이스(1XM02347H004)
10398     3892778           에샤페 레이스(1XM02347H004)
10399     3892778           에샤페 레이스(1XM02347H004)
10400     3892778           에샤페 레이스(1XM02347H004)
10404     3892778           에샤페 레이스(1XM02347H004)
10408     3892778           에샤페 레이스(1XM02347H004)
10070     3892778           에샤페 레이스(1XM02347H004)
10346     3892778           에샤페 레이스(1XM02347H004)
10206     3892778           에샤페 레이스(1XM02347H004)
10345     3892778           에샤페 레이스(1XM02347H004)
10115     3892778           에샤페 레이스(1XM02347H004)
10114     3892778           에샤페 레이스(1XM02347H004)
10316     3892778           에샤페 레이스(1XM02347H004)
10112     3892778           에샤페 레이스(1XM02347H004)
10317     3892778           에샤페 레이스(1XM02347H004)
10319     3892778           에샤페 레이스(1XM02347H004)
10320     3892778           에샤페 레이스(1XM02347H004)
10323     3892778           에샤페 레이스(1XM02347H004)
10105     3892778           에샤페 레이스(1XM02347H004)
10321     3892778           에샤페 레이스(1XM02347H004)
10344     3892778           에샤페 레이스(1XM02347H004)
10101     3892778           에샤페 레이스(1XM02347H004)
10099     3892778           에샤페 레이스(1XM02347H004)
10290     3892782           에샤페 레이스(1XM02347G256)
10275     3892782           에샤페 레이스(1XM02347G256)
10235     3892782           에샤페 레이스(1XM02347G256)
10318     3892782           에샤페 레이스(1XM02347G256)
10307     3892782           에샤페 레이스(1XM02347G256)
10226     3892782           에샤페 레이스(1XM02347G256)
10225     3892782           에샤페 레이스(1XM02347G256)
10308     3892782           에샤페 레이스(1XM02347G256)
10339     3892782           에샤페 레이스(1XM02347G256)
10309     3892782           에샤페 레이스(1XM02347G256)
10310     3892782           에샤페 레이스(1XM02347G256)
10340     3892782           에샤페 레이스(1XM02347G256)
10402     3892782           에샤페 레이스(1XM02347G256)
10341     3892782           에샤페 레이스(1XM02347G256)
10245     3892782           에샤페 레이스(1XM02347G256)
10246     3892782           에샤페 레이스(1XM02347G256)
10303     3892782           에샤페 레이스(1XM02347G256)
10247     3892782           에샤페 레이스(1XM02347G256)
10329     3892782           에샤페 레이스(1XM02347G256)
10325     3892782           에샤페 레이스(1XM02347G256)
10370     3892782           에샤페 레이스(1XM02347G256)
10331     3892782           에샤페 레이스(1XM02347G256)
10372     3892782           에샤페 레이스(1XM02347G256)
10373     3892782           에샤페 레이스(1XM02347G256)
10374     3892782           에샤페 레이스(1XM02347G256)
10294     3892782           에샤페 레이스(1XM02347G256)
10375     3892782           에샤페 레이스(1XM02347G256)
10295     3892782           에샤페 레이스(1XM02347G256)
10376     3892782           에샤페 레이스(1XM02347G256)
10270     3892782           에샤페 레이스(1XM02347G256)
10299     3892782           에샤페 레이스(1XM02347G256)
10285     3892782           에샤페 레이스(1XM02347G256)
10259     3892782           에샤페 레이스(1XM02347G256)
10257     3892782           에샤페 레이스(1XM02347G256)
10256     3892782           에샤페 레이스(1XM02347G256)
10365     3892782           에샤페 레이스(1XM02347G256)
10314     3892782           에샤페 레이스(1XM02347G256)
10322     3892782           에샤페 레이스(1XM02347G256)
10166     3892782           에샤페 레이스(1XM02347G256)
10086     3892782           에샤페 레이스(1XM02347G256)
10057     3892782           에샤페 레이스(1XM02347G256)
10144     3892782           에샤페 레이스(1XM02347G256)
10157     3892782           에샤페 레이스(1XM02347G256)
10080     3892782           에샤페 레이스(1XM02347G256)
10106     3892782           에샤페 레이스(1XM02347G256)
10073     3892782           에샤페 레이스(1XM02347G256)
10075     3892782           에샤페 레이스(1XM02347G256)
10190     3892782           에샤페 레이스(1XM02347G256)
10202     3892785           에샤페 레이스(1XM02347H920)
10343     3892785           에샤페 레이스(1XM02347H920)
10096     3892785           에샤페 레이스(1XM02347H920)
10095     3892785           에샤페 레이스(1XM02347H920)
10094     3892785           에샤페 레이스(1XM02347H920)
10349     3892785           에샤페 레이스(1XM02347H920)
10351     3892785           에샤페 레이스(1XM02347H920)
10342     3892785           에샤페 레이스(1XM02347H920)
10092     3892785           에샤페 레이스(1XM02347H920)
10353     3892785           에샤페 레이스(1XM02347H920)
10354     3892785           에샤페 레이스(1XM02347H920)
10091     3892785           에샤페 레이스(1XM02347H920)
10356     3892785           에샤페 레이스(1XM02347H920)
10350     3892785           에샤페 레이스(1XM02347H920)
10097     3892785           에샤페 레이스(1XM02347H920)
10338     3892785           에샤페 레이스(1XM02347H920)
10100     3892785           에샤페 레이스(1XM02347H920)
10118     3892785           에샤페 레이스(1XM02347H920)
10117     3892785           에샤페 레이스(1XM02347H920)
10116     3892785           에샤페 레이스(1XM02347H920)
10113     3892785           에샤페 레이스(1XM02347H920)
10111     3892785           에샤페 레이스(1XM02347H920)
10110     3892785           에샤페 레이스(1XM02347H920)
10109     3892785           에샤페 레이스(1XM02347H920)
10108     3892785           에샤페 레이스(1XM02347H920)
10107     3892785           에샤페 레이스(1XM02347H920)
10324     3892785           에샤페 레이스(1XM02347H920)
10104     3892785           에샤페 레이스(1XM02347H920)
10326     3892785           에샤페 레이스(1XM02347H920)
10327     3892785           에샤페 레이스(1XM02347H920)
10103     3892785           에샤페 레이스(1XM02347H920)
10102     3892785           에샤페 레이스(1XM02347H920)
10333     3892785           에샤페 레이스(1XM02347H920)
10334     3892785           에샤페 레이스(1XM02347H920)
10335     3892785           에샤페 레이스(1XM02347H920)
10205     3892785           에샤페 레이스(1XM02347H920)
10098     3892785           에샤페 레이스(1XM02347H920)
10358     3892785           에샤페 레이스(1XM02347H920)
10362     3892785           에샤페 레이스(1XM02347H920)
10087     3892785           에샤페 레이스(1XM02347H920)
10391     3892785           에샤페 레이스(1XM02347H920)
10392     3892785           에샤페 레이스(1XM02347H920)
10393     3892785           에샤페 레이스(1XM02347H920)
10064     3892785           에샤페 레이스(1XM02347H920)
10062     3892785           에샤페 레이스(1XM02347H920)
10396     3892785           에샤페 레이스(1XM02347H920)
10397     3892785           에샤페 레이스(1XM02347H920)
10061     3892785           에샤페 레이스(1XM02347H920)
10060     3892785           에샤페 레이스(1XM02347H920)
10059     3892785           에샤페 레이스(1XM02347H920)
10401     3892785           에샤페 레이스(1XM02347H920)
10058     3892785           에샤페 레이스(1XM02347H920)
10403     3892785           에샤페 레이스(1XM02347H920)
10405     3892785           에샤페 레이스(1XM02347H920)
10406     3892785           에샤페 레이스(1XM02347H920)
10407     3892785           에샤페 레이스(1XM02347H920)
10056     3892785           에샤페 레이스(1XM02347H920)
10065     3892785           에샤페 레이스(1XM02347H920)
10389     3892785           에샤페 레이스(1XM02347H920)
10066     3892785           에샤페 레이스(1XM02347H920)
10387     3892785           에샤페 레이스(1XM02347H920)
10119     3892785           에샤페 레이스(1XM02347H920)
10363     3892785           에샤페 레이스(1XM02347H920)
10085     3892785           에샤페 레이스(1XM02347H920)
10367     3892785           에샤페 레이스(1XM02347H920)
10368     3892785           에샤페 레이스(1XM02347H920)
10084     3892785           에샤페 레이스(1XM02347H920)
10082     3892785           에샤페 레이스(1XM02347H920)
10079     3892785           에샤페 레이스(1XM02347H920)
10359     3892785           에샤페 레이스(1XM02347H920)
10078     3892785           에샤페 레이스(1XM02347H920)
10379     3892785           에샤페 레이스(1XM02347H920)
10380     3892785           에샤페 레이스(1XM02347H920)
10381     3892785           에샤페 레이스(1XM02347H920)
10382     3892785           에샤페 레이스(1XM02347H920)
10383     3892785           에샤페 레이스(1XM02347H920)
10384     3892785           에샤페 레이스(1XM02347H920)
10385     3892785           에샤페 레이스(1XM02347H920)
10067     3892785           에샤페 레이스(1XM02347H920)
10069     3892785           에샤페 레이스(1XM02347H920)
10120     3892785           에샤페 레이스(1XM02347H920)
10357     3892785           에샤페 레이스(1XM02347H920)
10122     3892785           에샤페 레이스(1XM02347H920)
10186     3892785           에샤페 레이스(1XM02347H920)
10236     3892785           에샤페 레이스(1XM02347H920)
10237     3892785           에샤페 레이스(1XM02347H920)
10238     3892785           에샤페 레이스(1XM02347H920)
10185     3892785           에샤페 레이스(1XM02347H920)
10240     3892785           에샤페 레이스(1XM02347H920)
10184     3892785           에샤페 레이스(1XM02347H920)
10243     3892785           에샤페 레이스(1XM02347H920)
10187     3892785           에샤페 레이스(1XM02347H920)
10183     3892785           에샤페 레이스(1XM02347H920)
10180     3892785           에샤페 레이스(1XM02347H920)
10248     3892785           에샤페 레이스(1XM02347H920)
10249     3892785           에샤페 레이스(1XM02347H920)
10250     3892785           에샤페 레이스(1XM02347H920)
10252     3892785           에샤페 레이스(1XM02347H920)
10253     3892785           에샤페 레이스(1XM02347H920)
10255     3892785           에샤페 레이스(1XM02347H920)
10178     3892785           에샤페 레이스(1XM02347H920)
10182     3892785           에샤페 레이스(1XM02347H920)
10233     3892785           에샤페 레이스(1XM02347H920)
10232     3892785           에샤페 레이스(1XM02347H920)
10231     3892785           에샤페 레이스(1XM02347H920)
10208     3892785           에샤페 레이스(1XM02347H920)
10121     3892785           에샤페 레이스(1XM02347H920)
10213     3892785           에샤페 레이스(1XM02347H920)
10214     3892785           에샤페 레이스(1XM02347H920)
10199     3892785           에샤페 레이스(1XM02347H920)
10216     3892785           에샤페 레이스(1XM02347H920)
10198     3892785           에샤페 레이스(1XM02347H920)
10218     3892785           에샤페 레이스(1XM02347H920)
10196     3892785           에샤페 레이스(1XM02347H920)
10220     3892785           에샤페 레이스(1XM02347H920)
10195     3892785           에샤페 레이스(1XM02347H920)
10222     3892785           에샤페 레이스(1XM02347H920)
10223     3892785           에샤페 레이스(1XM02347H920)
10192     3892785           에샤페 레이스(1XM02347H920)
10189     3892785           에샤페 레이스(1XM02347H920)
10227     3892785           에샤페 레이스(1XM02347H920)
10228     3892785           에샤페 레이스(1XM02347H920)
10229     3892785           에샤페 레이스(1XM02347H920)
10230     3892785           에샤페 레이스(1XM02347H920)
10177     3892785           에샤페 레이스(1XM02347H920)
10176     3892785           에샤페 레이스(1XM02347H920)
10212     3892785           에샤페 레이스(1XM02347H920)
10175     3892785           에샤페 레이스(1XM02347H920)
10141     3892785           에샤페 레이스(1XM02347H920)
10140     3892785           에샤페 레이스(1XM02347H920)
10139     3892785           에샤페 레이스(1XM02347H920)
10138     3892785           에샤페 레이스(1XM02347H920)
10137     3892785           에샤페 레이스(1XM02347H920)
10135     3892785           에샤페 레이스(1XM02347H920)
10134     3892785           에샤페 레이스(1XM02347H920)
10133     3892785           에샤페 레이스(1XM02347H920)
10147     3892785           에샤페 레이스(1XM02347H920)
10297     3892785           에샤페 레이스(1XM02347H920)
10132     3892785           에샤페 레이스(1XM02347H920)
10301     3892785           에샤페 레이스(1XM02347H920)
10131     3892785           에샤페 레이스(1XM02347H920)
10130     3892785           에샤페 레이스(1XM02347H920)
10129     3892785           에샤페 레이스(1XM02347H920)
10127     3892785           에샤페 레이스(1XM02347H920)
10126     3892785           에샤페 레이스(1XM02347H920)
10260     3892785           에샤페 레이스(1XM02347H920)
10298     3892785           에샤페 레이스(1XM02347H920)
10148     3892785           에샤페 레이스(1XM02347H920)
10125     3892785           에샤페 레이스(1XM02347H920)
10151     3892785           에샤페 레이스(1XM02347H920)
10174     3892785           에샤페 레이스(1XM02347H920)
10149     3892785           에샤페 레이스(1XM02347H920)
10170     3892785           에샤페 레이스(1XM02347H920)
10266     3892785           에샤페 레이스(1XM02347H920)
10267     3892785           에샤페 레이스(1XM02347H920)
10162     3892785           에샤페 레이스(1XM02347H920)
10160     3892785           에샤페 레이스(1XM02347H920)
10156     3892785           에샤페 레이스(1XM02347H920)
10272     3892785           에샤페 레이스(1XM02347H920)
10173     3892785           에샤페 레이스(1XM02347H920)
10282     3892785           에샤페 레이스(1XM02347H920)
10155     3892785           에샤페 레이스(1XM02347H920)
10276     3892785           에샤페 레이스(1XM02347H920)
10277     3892785           에샤페 레이스(1XM02347H920)
10153     3892785           에샤페 레이스(1XM02347H920)
10279     3892785           에샤페 레이스(1XM02347H920)
10281     3892785           에샤페 레이스(1XM02347H920)
10273     3892785           에샤페 레이스(1XM02347H920)
2339      3892794           에샤페 실버문(1XM02348H063)
2318      3892794           에샤페 실버문(1XM02348H063)
2319      3892794           에샤페 실버문(1XM02348H063)
2322      3892794           에샤페 실버문(1XM02348H063)
2323      3892794           에샤페 실버문(1XM02348H063)
2325      3892794           에샤페 실버문(1XM02348H063)
2326      3892794           에샤페 실버문(1XM02348H063)
2327      3892794           에샤페 실버문(1XM02348H063)
2330      3892794           에샤페 실버문(1XM02348H063)
2329      3892794           에샤페 실버문(1XM02348H063)
2332      3892794           에샤페 실버문(1XM02348H063)
2333      3892794           에샤페 실버문(1XM02348H063)
2334      3892794           에샤페 실버문(1XM02348H063)
2335      3892794           에샤페 실버문(1XM02348H063)
2337      3892794           에샤페 실버문(1XM02348H063)
2317      3892794           에샤페 실버문(1XM02348H063)
2340      3892794           에샤페 실버문(1XM02348H063)
2328      3892794           에샤페 실버문(1XM02348H063)
2316      3892794           에샤페 실버문(1XM02348H063)
2301      3892794           에샤페 실버문(1XM02348H063)
2310      3892794           에샤페 실버문(1XM02348H063)
2284      3892794           에샤페 실버문(1XM02348H063)
2286      3892794           에샤페 실버문(1XM02348H063)
2341      3892794           에샤페 실버문(1XM02348H063)
2287      3892794           에샤페 실버문(1XM02348H063)
2288      3892794           에샤페 실버문(1XM02348H063)
2290      3892794           에샤페 실버문(1XM02348H063)
2291      3892794           에샤페 실버문(1XM02348H063)
2292      3892794           에샤페 실버문(1XM02348H063)
2295      3892794           에샤페 실버문(1XM02348H063)
2297      3892794           에샤페 실버문(1XM02348H063)
2298      3892794           에샤페 실버문(1XM02348H063)
2299      3892794           에샤페 실버문(1XM02348H063)
2300      3892794           에샤페 실버문(1XM02348H063)
2303      3892794           에샤페 실버문(1XM02348H063)
2304      3892794           에샤페 실버문(1XM02348H063)
2305      3892794           에샤페 실버문(1XM02348H063)
2306      3892794           에샤페 실버문(1XM02348H063)
2307      3892794           에샤페 실버문(1XM02348H063)
2308      3892794           에샤페 실버문(1XM02348H063)
2313      3892794           에샤페 실버문(1XM02348H063)
2342      3892794           에샤페 실버문(1XM02348H063)
2368      3892794           에샤페 실버문(1XM02348H063)
2347      3892794           에샤페 실버문(1XM02348H063)
2374      3892794           에샤페 실버문(1XM02348H063)
2375      3892794           에샤페 실버문(1XM02348H063)
2376      3892794           에샤페 실버문(1XM02348H063)
2377      3892794           에샤페 실버문(1XM02348H063)
2378      3892794           에샤페 실버문(1XM02348H063)
2380      3892794           에샤페 실버문(1XM02348H063)
2381      3892794           에샤페 실버문(1XM02348H063)
2382      3892794           에샤페 실버문(1XM02348H063)
2373      3892794           에샤페 실버문(1XM02348H063)
2383      3892794           에샤페 실버문(1XM02348H063)
2386      3892794           에샤페 실버문(1XM02348H063)
2387      3892794           에샤페 실버문(1XM02348H063)
2389      3892794           에샤페 실버문(1XM02348H063)
2390      3892794           에샤페 실버문(1XM02348H063)
2391      3892794           에샤페 실버문(1XM02348H063)
2393      3892794           에샤페 실버문(1XM02348H063)
2395      3892794           에샤페 실버문(1XM02348H063)
2283      3892794           에샤페 실버문(1XM02348H063)
2385      3892794           에샤페 실버문(1XM02348H063)
2345      3892794           에샤페 실버문(1XM02348H063)
2372      3892794           에샤페 실버문(1XM02348H063)
2370      3892794           에샤페 실버문(1XM02348H063)
2348      3892794           에샤페 실버문(1XM02348H063)
2349      3892794           에샤페 실버문(1XM02348H063)
2350      3892794           에샤페 실버문(1XM02348H063)
2351      3892794           에샤페 실버문(1XM02348H063)
2352      3892794           에샤페 실버문(1XM02348H063)
2353      3892794           에샤페 실버문(1XM02348H063)
2354      3892794           에샤페 실버문(1XM02348H063)
2355      3892794           에샤페 실버문(1XM02348H063)
2371      3892794           에샤페 실버문(1XM02348H063)

In [84]:
# ===============================
# 리뷰 내용 중복 확인
# ===============================
# 2-1. product_id 같고 content 중복인 데이터 확인
dup_mask = df_review_fila_mss.duplicated(subset=['product_id', 'content'], keep=False)
print("product_id는 같고 content가 중복 개수: ", dup_mask.sum())
display(df_review_fila_mss[dup_mask][['product_id', 'product_name', 'review_date', 'content']].sort_values(['product_id', 'content']))

# 2-2. 위 경우 중 review_date까지 완전히 동일한 경우 개수
print(
    "review_date까지 완전히 동일한 경우 개수: "
    , df_review_fila_mss[dup_mask].duplicated(subset=['product_id', 'content', 'review_date'], keep=False).sum()
)

# 2-3. product_id, content, review_date, purchase_option 까지 모두 중복인 경우
dup_mask_full = df_review_fila_naverstore.duplicated(
    subset=['product_id', 'content', 'review_date', 'purchase_option'],
    keep=False
)
print("purchase_option까지 완전히 동일한 경우 개수: ", dup_mask_full.sum())
display(
    df_review_fila_naverstore[dup_mask_full][['product_id', 'product_name', 'review_date', 'purchase_option', 'content']]
    .sort_values(['product_id', 'review_date'])
)

product_id는 같고 content가 중복 개수:  287

,product_id,product_name,review_date,content
10063,3892778,에샤페 레이스(1XM02347H004),2024-06-14,기대 이상이에요 진짜 넘 예쁘고 코디도 쉽고 짱짱!! 너무너무 맘에드는 신발입니다💓💓
10207,3892778,에샤페 레이스(1XM02347H004),2024-06-16,기대 이상이에요 진짜 넘 예쁘고 코디도 쉽고 짱짱!! 너무너무 맘에드는 신발입니다💓💓
10114,3892778,에샤페 레이스(1XM02347H004),2025-03-06,신발자체가 이쁘고 다른컬러로 또사고싶어요 완전추천
10115,3892778,에샤페 레이스(1XM02347H004),2025-03-06,신발자체가 이쁘고 다른컬러로 또사고싶어요 완전추천
10156,3892785,에샤페 레이스(1XM02347H920),2024-08-10,"갖고 싶은 제품이였는데, 계속 품절이라 못사고 있다가 재고 풀려서 바로 구매했어요 너무 이쁩니다"
10229,3892785,에샤페 레이스(1XM02347H920),2024-06-06,"갖고 싶은 제품이였는데, 계속 품절이라 못사고 있다가 재고 풀려서 바로 구매했어요 너무 이쁩니다"
10338,3892785,에샤페 레이스(1XM02347H920),2024-04-11,살짝 큰 느낌이 있어요. 색조합이 너무 예쁘고 폭신해서 편하게 신을 수 있어서 좋아요. 봄이랑 너무 잘 어울리네요!
10349,3892785,에샤페 레이스(1XM02347H920),2024-04-04,살짝 큰 느낌이 있어요. 색조합이 너무 예쁘고 폭신해서 편하게 신을 수 있어서 좋아요. 봄이랑 너무 잘 어울리네요!
10186,3892785,에샤페 레이스(1XM02347H920),2024-06-25,예쁩니다 사이즈 250 하나 남아서 겟했는데 아식스 250인 저한테는 조금 널널해서 꽉끈했어요 실물은 좀 어둡지마누예뻐요
10187,3892785,에샤페 레이스(1XM02347H920),2024-06-25,예쁩니다 사이즈 250 하나 남아서 겟했는데 아식스 250인 저한테는 조금 널널해서 꽉끈했어요 실물은 좀 어둡지마누예뻐요
10222,3892785,에샤페 레이스(1XM02347H920),2024-06-10,처음 신어보는 스타일인데 사이즈는 많이 큽니다. 두사이즈 줄였는데도 동생은 크다고 하네요. 저는 원래 약간 크게 신는 편이라 그냥 귀찮아서 신어요. 발은 생각보다 엄청 편하긴 합니다.
10223,3892785,에샤페 레이스(1XM02347H920),2024-06-10,처음 신어보는 스타일인데 사이즈는 많이 큽니다. 두사이즈 줄였는데도 동생은 크다고 하네요. 저는 원래 약간 크게 신는 편이라 그냥 귀찮아서 신어요. 발은 생각보다 엄청 편하긴 합니다.
1953,3892794,에샤페 실버문(1XM02348H063),2024-07-28,Thank you for the fast delivery so happy
2076,3892794,에샤페 실버문(1XM02348H063),2024-07-14,Thank you for the fast delivery so happy
2228,3892794,에샤페 실버문(1XM02348H063),2024-06-30,굿!!맘에 듬!! 빠른배송과 실착 좋음!나중에 선물할때도 여기서 구입할거에요!
2229,3892794,에샤페 실버문(1XM02348H063),2024-06-30,굿!!맘에 듬!! 빠른배송과 실착 좋음!나중에 선물할때도 여기서 구입할거에요!
1287,3892794,에샤페 실버문(1XM02348H063),2025-03-26,귀여운 신발이에요! 주위에 생일인 사람이 있어서 구매했슴이당
1288,3892794,에샤페 실버문(1XM02348H063),2025-03-26,귀여운 신발이에요! 주위에 생일인 사람이 있어서 구매했슴이당
3327,3892794,에샤페 실버문(1XM02348H063),2024-09-23,너무 깔끔하고 너무 보기 좋아요 진짜 강추합니다
3328,3892794,에샤페 실버문(1XM02348H063),2024-09-23,너무 깔끔하고 너무 보기 좋아요 진짜 강추합니다
2556,3892794,에샤페 실버문(1XM02348H063),2024-05-28,너무 좋아요 잘 어울려요 색깔이 너무 예뻐요 너무 좋아요 너무 좋아요
2557,3892794,에샤페 실버문(1XM02348H063),2024-05-28,너무 좋아요 잘 어울려요 색깔이 너무 예뻐요 너무 좋아요 너무 좋아요
2473,3892794,에샤페 실버문(1XM02348H063),2024-06-04,너무이쁘고 컬러 매칭하기가쉬운 아이템으로 휘뚜루 마뚜루 잘 사용할것 같아요. 다른컬러나오면 재구매하고깊네요!
2474,3892794,에샤페 실버문(1XM02348H063),2024-06-04,너무이쁘고 컬러 매칭하기가쉬운 아이템으로 휘뚜루 마뚜루 잘 사용할것 같아요. 다른컬러나오면 재구매하고깊네요!
2209,3892794,에샤페 실버문(1XM02348H063),2024-07-02,데일리로 신기 좋은거 같아요 너무나도 추천드립니다.
2210,3892794,에샤페 실버문(1XM02348H063),2024-07-02,데일리로 신기 좋은거 같아요 너무나도 추천드립니다.
1964,3892794,에샤페 실버문(1XM02348H063),2024-07-27,디자인도 이쁘고 색감도 너무 이뻐서 마음에 들어요 자주 애용할 것 같아요
1965,3892794,에샤페 실버문(1XM02348H063),2024-07-27,디자인도 이쁘고 색감도 너무 이뻐서 마음에 들어요 자주 애용할 것 같아요
1932,3892794,에샤페 실버문(1XM02348H063),2024-07-29,디자인이 너무 예쁘고 착화감이 편안해요. 발에 잘 맞고 걸을 때도 편안하고 데일리 착용 시 부담이 없습니다!
1933,3892794,에샤페 실버문(1XM02348H063),2024-07-29,디자인이 너무 예쁘고 착화감이 편안해요. 발에 잘 맞고 걸을 때도 편안하고 데일리 착용 시 부담이 없습니다!
2509,3892794,에샤페 실버문(1XM02348H063),2024-06-02,디자인이 너무 예쁘고 착화감이 편안해요. 발에 잘 맞고 걸을 때도 편안하고 데일리 착용 시 부담이 없습니다!
2036,3892794,에샤페 실버문(1XM02348H063),2024-07-22,디자인이 무난하고 어디에나 잘 어울려서 맘에 들어요!!
2037,3892794,에샤페 실버문(1XM02348H063),2024-07-22,디자인이 무난하고 어디에나 잘 어울려서 맘에 들어요!!
332,3892794,에샤페 실버문(1XM02348H063),2024-08-13,반사이즈 업 했더니 여유롭게 남으면서 딱 좋은 거 같아요~! 실버라 여름에 신기 좋고 디자인도 흠잡을 데 없이 깔끔해요
1808,3892794,에샤페 실버문(1XM02348H063),2024-08-12,반사이즈 업 했더니 여유롭게 남으면서 딱 좋은 거 같아요~! 실버라 여름에 신기 좋고 디자인도 흠잡을 데 없이 깔끔해요
1958,3892794,에샤페 실버문(1XM02348H063),2024-07-27,반사이즈 업 했더니 여유롭게 남으면서 딱 좋은 거 같아요~! 실버라 여름에 신기 좋고 디자인도 흠잡을 데 없이 깔끔해요
340,3892794,에샤페 실버문(1XM02348H063),2024-08-06,발도 편하고 예쁘고 여기저기 막 신을 수 있어서 좋어요!! 신발 휠라꺼라고 하면 다들 놀랍니다 ㅎㅎ 실버 운동화 저렴하게 잘 샀어요!
1871,3892794,에샤페 실버문(1XM02348H063),2024-08-05,발도 편하고 예쁘고 여기저기 막 신을 수 있어서 좋어요!! 신발 휠라꺼라고 하면 다들 놀랍니다 ㅎㅎ 실버 운동화 저렴하게 잘 샀어요!
1772,3892794,에샤페 실버문(1XM02348H063),2024-08-14,발모양 작고 슬림해보이게 잡아주는 것도 좋은데 발이 왜 이렇게 편해요?? 예쁜데 가볍고 편하기까지 하니까 단점이 없으요
1804,3892794,에샤페 실버문(1XM02348H063),2024-08-12,발모양 작고 슬림해보이게 잡아주는 것도 좋은데 발이 왜 이렇게 편해요?? 예쁜데 가볍고 편하기까지 하니까 단점이 없으요
317,3892794,에샤페 실버문(1XM02348H063),2024-08-19,발볼 넓으면 무조건 반업 추천합니다 넉넉히 신는 사이즈로 주문했는데 앞쪽 여유가 없는 느낌이에요! 그거 빼고는 편하고 예쁘고 다합니다
318,3892794,에샤페 실버문(1XM02348H063),2024-08-19,발볼 넓으면 무조건 반업 추천합니다 넉넉히 신는 사이즈로 주문했는데 앞쪽 여유가 없는 느낌이에요! 그거 빼고는 편하고 예쁘고 다합니다
1746,3892794,에샤페 실버문(1XM02348H063),2024-08-17,발볼 넓은 분들은 무조건 반업 해야할 것 같아오 신발 크게 신는 편인데 이건 알맞게 잘 맞구요 굉장히 가뱝규 편해요 예쁨 + 편함이라니 안살 이유 없네요
1748,3892794,에샤페 실버문(1XM02348H063),2024-08-17,발볼 넓은 분들은 무조건 반업 해야할 것 같아오 신발 크게 신는 편인데 이건 알맞게 잘 맞구요 굉장히 가뱝규 편해요 예쁨 + 편함이라니 안살 이유 없네요
504,3892794,에샤페 실버문(1XM02348H063),2024-05-03,발볼 엄청 좁네요.. 전 왕발볼러라 .. 발볼 거의 바닥에 닿을 정도에요 내 발볼 흑흑 그래도 신발은 예쁘네요
2756,3892794,에샤페 실버문(1XM02348H063),2024-05-12,발볼 엄청 좁네요.. 전 왕발볼러라 .. 발볼 거의 바닥에 닿을 정도에요 내 발볼 흑흑 그래도 신발은 예쁘네요
2819,3892794,에샤페 실버문(1XM02348H063),2024-05-03,발볼 엄청 좁네요.. 전 왕발볼러라 .. 발볼 거의 바닥에 닿을 정도에요 내 발볼 흑흑 그래도 신발은 예쁘네요
2112,3892794,에샤페 실버문(1XM02348H063),2024-07-08,발볼이 넓어서 반업했는데 너무 딱 맞나 싶긴 하지만 불편하진 않아요 신으니 더 예뻐서 맘에 듭니다
2139,3892794,에샤페 실버문(1XM02348H063),2024-07-06,발볼이 넓어서 반업했는데 너무 딱 맞나 싶긴 하지만 불편하진 않아요 신으니 더 예뻐서 맘에 듭니다
472,3892794,에샤페 실버문(1XM02348H063),2024-05-26,발볼이 넓은편이고 평소 240-250 까지도 신는 사람이에요 발볼 있으시면 무조건 반업 추천&hellip;. 생각보다 신발 발볼이 좁아서 처음 신는데 발이 좀 아팠어요ㅜ 그래도 이정도면 굽도 편하고 좋아요 실버 색상 너무 이뻐요🖤
2591,3892794,에샤페 실버문(1XM02348H063),2024-05-26,발볼이 넓은편이고 평소 240-250 까지도 신는 사람이에요 발볼 있으시면 무조건 반업 추천&hellip;. 생각보다 신발 발볼이 좁아서 처음 신는데 발이 좀 아팠어요ㅜ 그래도 이정도면 굽도 편하고 좋아요 실버 색상 너무 이뻐요🖤
1232,3892794,에샤페 실버문(1XM02348H063),2025-04-06,배송 매우 빠릅니다. 상품 좋아요. 많이 판매하세요.
1234,3892794,에샤페 실버문(1XM02348H063),2025-04-06,배송 매우 빠릅니다. 상품 좋아요. 많이 판매하세요.
1895,3892794,에샤페 실버문(1XM02348H063),2024-08-03,배송빠르고 좋습니다 감사합ㄴ디ㅏ 품질도 좋고 배송도 좋고 다 좋습니다 앞으로도 자주 사용할게요 감사합니다 잘쓸게요
1896,3892794,에샤페 실버문(1XM02348H063),2024-08-03,배송빠르고 좋습니다 감사합ㄴ디ㅏ 품질도 좋고 배송도 좋고 다 좋습니다 앞으로도 자주 사용할게요 감사합니다 잘쓸게요
1873,3892794,에샤페 실버문(1XM02348H063),2024-08-05,배송이 빨라서 너무 좋았어요 선물 받은 친구도 좋아하네요 ㅎㅎ 감사합니다
1874,3892794,에샤페 실버문(1XM02348H063),2024-08-05,배송이 빨라서 너무 좋았어요 선물 받은 친구도 좋아하네요 ㅎㅎ 감사합니다
3372,3892794,에샤페 실버문(1XM02348H063),2024-09-06,빠르게 배송해 주셔서 감사합니다. 다음에도 잘 부탁드립니다.
3373,3892794,에샤페 실버문(1XM02348H063),2024-09-06,빠르게 배송해 주셔서 감사합니다. 다음에도 잘 부탁드립니다.
2649,3892794,에샤페 실버문(1XM02348H063),2024-05-22,사이즈 너무 마음에 들고 좋습니다 감사합니다 또구매하고싶어요
2671,3892794,에샤페 실버문(1XM02348H063),2024-05-21,사이즈 너무 마음에 들고 좋습니다 감사합니다 또구매하고싶어요
2672,3892794,에샤페 실버문(1XM02348H063),2024-05-21,사이즈 너무 마음에 들고 좋습니다 감사합니다 또구매하고싶어요
2673,3892794,에샤페 실버문(1XM02348H063),2024-05-21,사이즈 너무 마음에 들고 좋습니다 감사합니다 또구매하고싶어요
2674,3892794,에샤페 실버문(1XM02348H063),2024-05-21,사이즈 너무 마음에 들고 좋습니다 감사합니다 또구매하고싶어요
1687,3892794,에샤페 실버문(1XM02348H063),2024-08-25,상품 디자인도 맘에들고 퀄리티도 괜찮은거 같아요
2093,3892794,에샤페 실버문(1XM02348H063),2024-07-11,상품 디자인도 맘에들고 퀄리티도 괜찮은거 같아요
2537,3892794,에샤페 실버문(1XM02348H063),2024-05-30,상품 디자인도 맘에들고 퀄리티도 괜찮은거 같아요
2577,3892794,에샤페 실버문(1XM02348H063),2024-05-27,상품 디자인도 맘에들고 퀄리티도 괜찮은거 같아요
310,3892794,에샤페 실버문(1XM02348H063),2024-08-26,상품 입고 알림 받자마자 바로 구매했어요. 살짝 구매욕구 떨어졌었는데 사길 잘 했습니다. 이렇게 예쁜 걸. 착화감이 편한 건 아니지만 불편하지도 않아 가볍게 잘 신고 다녀요 ㅎㅎ
1799,3892794,에샤페 실버문(1XM02348H063),2024-08-13,상품 입고 알림 받자마자 바로 구매했어요. 살짝 구매욕구 떨어졌었는데 사길 잘 했습니다. 이렇게 예쁜 걸. 착화감이 편한 건 아니지만 불편하지도 않아 가볍게 잘 신고 다녀요 ㅎㅎ
1805,3892794,에샤페 실버문(1XM02348H063),2024-08-12,상품 입고 알림 받자마자 바로 구매했어요. 살짝 구매욕구 떨어졌었는데 사길 잘 했습니다. 이렇게 예쁜 걸. 착화감이 편한 건 아니지만 불편하지도 않아 가볍게 잘 신고 다녀요 ㅎㅎ
3338,3892794,에샤페 실버문(1XM02348H063),2024-09-21,상품 잘 받았습니다 퀄리티도 괜찮아보이고 디자인도 맘에들어서 자주 사용할 것 같아요 좋은상품 감사합니다 잘 쓰겠습니다
3383,3892794,에샤페 실버문(1XM02348H063),2024-09-01,상품 잘 받았습니다 퀄리티도 괜찮아보이고 디자인도 맘에들어서 자주 사용할 것 같아요 좋은상품 감사합니다 잘 쓰겠습니다
502,3892794,에샤페 실버문(1XM02348H063),2024-05-05,세련되고 힙하고 필라에서 역대급 예쁜 신상신발이 나왔네요 실버 블랙 칼라좋고 쿠션감도좋아요
503,3892794,에샤페 실버문(1XM02348H063),2024-05-05,세련되고 힙하고 필라에서 역대급 예쁜 신상신발이 나왔네요 실버 블랙 칼라좋고 쿠션감도좋아요
2867,3892794,에샤페 실버문(1XM02348H063),2024-03-31,세련되고 힙하고 필라에서 역대급 예쁜 신상신발이 나왔네요 실버 블랙 칼라좋고 쿠션감도좋아요
2742,3892794,에샤페 실버문(1XM02348H063),2024-05-14,솔직히 너무 예쁨 옆태 앞태 장난 없음 근데 255 신으면 거의 다 여유롭게 맞았는데 얜 딱맞음 .. 260 살 걸 하는 아쉬움 .. 요새 널널한 신발에 길들여져 있어서 ㅜ 그래도 작진 않아서 다행 .. 무조건 반업 하세요 착화감 좋음 쫀쫀함!
2776,3892794,에샤페 실버문(1XM02348H063),2024-05-10,솔직히 너무 예쁨 옆태 앞태 장난 없음 근데 255 신으면 거의 다 여유롭게 맞았는데 얜 딱맞음 .. 260 살 걸 하는 아쉬움 .. 요새 널널한 신발에 길들여져 있어서 ㅜ 그래도 작진 않아서 다행 .. 무조건 반업 하세요 착화감 좋음 쫀쫀함!
378,3892794,에샤페 실버문(1XM02348H063),2024-07-15,신발 너무 편하고 색상도 너무 예뻐요! 요즘 이 신발만 산고 다녀요!
379,3892794,에샤페 실버문(1XM02348H063),2024-07-15,신발 너무 편하고 색상도 너무 예뻐요! 요즘 이 신발만 산고 다녀요!
2475,3892794,에샤페 실버문(1XM02348H063),2024-06-04,신발 너무 편하고 색상도 너무 예뻐요! 요즘 이 신발만 산고 다녀요!
2476,3892794,에샤페 실버문(1XM02348H063),2024-06-04,신발 너무 편하고 색상도 너무 예뻐요! 요즘 이 신발만 산고 다녀요!
1398,3892794,에샤페 실버문(1XM02348H063),2025-03-13,신발이 너무 마음에 들어서 옷이랑 잘 어울려요 닝닝 모델이라서 바로 샀어요
1399,3892794,에샤페 실버문(1XM02348H063),2025-03-13,신발이 너무 마음에 들어서 옷이랑 잘 어울려요 닝닝 모델이라서 바로 샀어요
1863,3892794,에샤페 실버문(1XM02348H063),2024-08-06,신발이 너무 예쁘고 배송도 빨라서 좋았습니다 감사합니다
1864,3892794,에샤페 실버문(1XM02348H063),2024-08-06,신발이 너무 예쁘고 배송도 빨라서 좋았습니다 감사합니다
3066,3892794,에샤페 실버문(1XM02348H063),2025-05-22,신발이 너무 잘 어울리고 예쁘고 신기 편해서 추천드려요 색깔도 너무 예쁘고
3067,3892794,에샤페 실버문(1XM02348H063),2025-05-22,신발이 너무 잘 어울리고 예쁘고 신기 편해서 추천드려요 색깔도 너무 예쁘고
359,3892794,에샤페 실버문(1XM02348H063),2024-07-29,"실물 진짜 영롱하고 예뻐요. 매장에서 신어본게 아니라 사이즈 걱정이 많았는데, 리뷰만 의지해서 주문한건데도 잘 맞아 다행이네요. 짝발이고 240~245 신는데 발 넣을 땐 힘들지만 자리 잡으면 발볼은 딱 좋고 길이는 여유 있는 정도예요. 첫 개시 하는 날 만보 걸었는데 길이 안든 운동화임에도 발피로도 적었어요."
2086,3892794,에샤페 실버문(1XM02348H063),2024-07-12,"실물 진짜 영롱하고 예뻐요. 매장에서 신어본게 아니라 사이즈 걱정이 많았는데, 리뷰만 의지해서 주문한건데도 잘 맞아 다행이네요. 짝발이고 240~245 신는데 발 넣을 땐 힘들지만 자리 잡으면 발볼은 딱 좋고 길이는 여유 있는 정도예요. 첫 개시 하는 날 만보 걸었는데 길이 안든 운동화임에도 발피로도 적었어요."
2098,3892794,에샤페 실버문(1XM02348H063),2024-07-10,"실물 진짜 영롱하고 예뻐요. 매장에서 신어본게 아니라 사이즈 걱정이 많았는데, 리뷰만 의지해서 주문한건데도 잘 맞아 다행이네요. 짝발이고 240~245 신는데 발 넣을 땐 힘들지만 자리 잡으면 발볼은 딱 좋고 길이는 여유 있는 정도예요. 첫 개시 하는 날 만보 걸었는데 길이 안든 운동화임에도 발피로도 적었어요."
2369,3892794,에샤페 실버문(1XM02348H063),2024-06-16,실물이 더 이뻐서 놀랐어요!! 발볼이 타이트해서 1업했더니 아주 굿임다
2527,3892794,에샤페 실버문(1XM02348H063),2024-05-31,실물이 더 이뻐서 놀랐어요!! 발볼이 타이트해서 1업했더니 아주 굿임다
2580,3892794,에샤페 실버문(1XM02348H063),2024-05-27,실물이 더 이쁘네요. 저렴하게 구입해서 만족합니다~!
2581,3892794,에샤페 실버문(1XM02348H063),2024-05-27,실물이 더 이쁘네요. 저렴하게 구입해서 만족합니다~!
500,3892794,에샤페 실버문(1XM02348H063),2024-05-07,실버색상이라 여름에 포인트 주기 너무 좋을것 같고 사이즈는 반업 추천드립니다 생각보다 편안한거 같아요
501,3892794,에샤페 실버문(1XM02348H063),2024-05-07,실버색상이라 여름에 포인트 주기 너무 좋을것 같고 사이즈는 반업 추천드립니다 생각보다 편안한거 같아요
2485,3892794,에샤페 실버문(1XM02348H063),2024-06-03,실버템 하나 장만하고 싶다 하면 추천추천합니도
2494,3892794,에샤페 실버문(1XM02348H063),2024-06-02,실버템 하나 장만하고 싶다 하면 추천추천합니도
854,3892794,에샤페 실버문(1XM02348H063),2025-06-21,아이들이 신을녀고 주문했는데 무신사세일기간에 저렴히 구매했습니다
855,3892794,에샤페 실버문(1XM02348H063),2025-06-21,아이들이 신을녀고 주문했는데 무신사세일기간에 저렴히 구매했습니다
1635,3892794,에샤페 실버문(1XM02348H063),2024-09-11,아주 좋았어요 사이즈도 딱인거 같요아요! 아주 강추해요!! 색감도 조아
1636,3892794,에샤페 실버문(1XM02348H063),2024-09-11,아주 좋았어요 사이즈도 딱인거 같요아요! 아주 강추해요!! 색감도 조아
1951,3892794,에샤페 실버문(1XM02348H063),2024-07-28,엄청 편해요 생각보가 반딱거리지만 이쁩니다 추천해요
1986,3892794,에샤페 실버문(1XM02348H063),2024-07-25,엄청 편해요 생각보가 반딱거리지만 이쁩니다 추천해요
2753,3892794,에샤페 실버문(1XM02348H063),2024-05-13,에어포스 250 널널 컨버스 250 널널 뉴발 250 널널 발볼넓고 발등높은 사람인데 이 제품은 255가 널널하지도 꼭 맞지도 않는 적당한 느낌이에요 색은 반짝하니 예쁘고 흰끈이 겉도는 느낌이라 신발끈 제가 가지고 있는 걸로 바꿔 끼워서 신어요
2789,3892794,에샤페 실버문(1XM02348H063),2024-05-08,에어포스 250 널널 컨버스 250 널널 뉴발 250 널널 발볼넓고 발등높은 사람인데 이 제품은 255가 널널하지도 꼭 맞지도 않는 적당한 느낌이에요 색은 반짝하니 예쁘고 흰끈이 겉도는 느낌이라 신발끈 제가 가지고 있는 걸로 바꿔 끼워서 신어요
1725,3892794,에샤페 실버문(1XM02348H063),2024-08-18,여름엔 실버템만 몇개씩 사는건지... 이 신발이 예쁘고 핫하길래 사봤는데 한번은 고민하다가 다 품절났던.. 지금은 그냥 살수있네요ㅋㅋ 유행을 많이 탈것같아서 고민이 컸는데 받아보면 다 잊음ㅠㅠ 뭘 입어도 포인트가 되고~ 투박한데 여성스러움. 발도 편하고 꼼꼼히 검수해봐도 마감도 깔끔한편! 유행끝나도 오래오래 신을래요..ㅎㅎ
1875,3892794,에샤페 실버문(1XM02348H063),2024-08-05,여름엔 실버템만 몇개씩 사는건지... 이 신발이 예쁘고 핫하길래 사봤는데 한번은 고민하다가 다 품절났던.. 지금은 그냥 살수있네요ㅋㅋ 유행을 많이 탈것같아서 고민이 컸는데 받아보면 다 잊음ㅠㅠ 뭘 입어도 포인트가 되고~ 투박한데 여성스러움. 발도 편하고 꼼꼼히 검수해봐도 마감도 깔끔한편! 유행끝나도 오래오래 신을래요..ㅎㅎ
3300,3892794,에샤페 실버문(1XM02348H063),2024-10-04,여전히 너무 이쁘고 전혀 질리지 않아요 ㅎ 너무 잘 산듯요! 나 자신에게 칭찬합니다ㅋㅋ
3302,3892794,에샤페 실버문(1XM02348H063),2024-10-04,여전히 너무 이쁘고 전혀 질리지 않아요 ㅎ 너무 잘 산듯요! 나 자신에게 칭찬합니다ㅋㅋ
437,3892794,에샤페 실버문(1XM02348H063),2024-06-12,예쁜디자인에 색인데 유니크하고 남들과 겹치지도않는데 가격까지 착한가격이라 너무좋네요 착화감도 편하고 완벽해요
2731,3892794,에샤페 실버문(1XM02348H063),2024-05-16,예쁜디자인에 색인데 유니크하고 남들과 겹치지도않는데 가격까지 착한가격이라 너무좋네요 착화감도 편하고 완벽해요
507,3892794,에샤페 실버문(1XM02348H063),2024-04-30,오랜만에 휠라신발신으니 새롭고 신선합니다 질감이좋고 예쁘고 길이도 좀 있어서 발가락도 숨잘쉬어집니다
508,3892794,에샤페 실버문(1XM02348H063),2024-04-30,오랜만에 휠라신발신으니 새롭고 신선합니다 질감이좋고 예쁘고 길이도 좀 있어서 발가락도 숨잘쉬어집니다
509,3892794,에샤페 실버문(1XM02348H063),2024-04-30,오랜만에 휠라신발신으니 새롭고 신선합니다 질감이좋고 예쁘고 길이도 좀 있어서 발가락도 숨잘쉬어집니다
2860,3892794,에샤페 실버문(1XM02348H063),2024-04-07,오랜만에 휠라신발신으니 새롭고 신선합니다 질감이좋고 예쁘고 길이도 좀 있어서 발가락도 숨잘쉬어집니다
2861,3892794,에샤페 실버문(1XM02348H063),2024-04-07,오랜만에 휠라신발신으니 새롭고 신선합니다 질감이좋고 예쁘고 길이도 좀 있어서 발가락도 숨잘쉬어집니다
2862,3892794,에샤페 실버문(1XM02348H063),2024-04-07,오랜만에 휠라신발신으니 새롭고 신선합니다 질감이좋고 예쁘고 길이도 좀 있어서 발가락도 숨잘쉬어집니다
2416,3892794,에샤페 실버문(1XM02348H063),2024-06-11,오빠 사줬는데 갖고있는 신발 중에 제일 가볍대요 실버라서 너무 이뻐요
2443,3892794,에샤페 실버문(1XM02348H063),2024-06-08,오빠 사줬는데 갖고있는 신발 중에 제일 가볍대요 실버라서 너무 이뻐요
1664,3892794,에샤페 실버문(1XM02348H063),2024-08-30,완전 잘 산 것 같아요! 디자인이 너무 마음에 들고 제품 색감도 너무 이쁩니다 :) 적극 추천합니다!
1709,3892794,에샤페 실버문(1XM02348H063),2024-08-19,완전 잘 산 것 같아요! 디자인이 너무 마음에 들고 제품 색감도 너무 이쁩니다 :) 적극 추천합니다!
607,3892794,에샤페 실버문(1XM02348H063),2025-12-07,완전 제스타일이라 너무 마음에 들어요 잘 사용하겠습니다 감사합니다
608,3892794,에샤페 실버문(1XM02348H063),2025-12-07,완전 제스타일이라 너무 마음에 들어요 잘 사용하겠습니다 감사합니다
613,3892794,에샤페 실버문(1XM02348H063),2025-12-03,완전 제스타일이라 너무 마음에 들어요 잘 사용하겠습니다 감사합니다
2683,3892794,에샤페 실버문(1XM02348H063),2024-05-20,우선 배송이 너무 빨라서 좋았고 발볼 넓은 분은 한사이즈 업하는게 좋을 것 같아요 꽉끈하는게 편해요
2684,3892794,에샤페 실버문(1XM02348H063),2024-05-20,우선 배송이 너무 빨라서 좋았고 발볼 넓은 분은 한사이즈 업하는게 좋을 것 같아요 꽉끈하는게 편해요
516,3892794,에샤페 실버문(1XM02348H063),2024-03-28,은색 디자인이 너무 이쁘고 어디에 신어도 잘 어울려요
517,3892794,에샤페 실버문(1XM02348H063),2024-03-28,은색 디자인이 너무 이쁘고 어디에 신어도 잘 어울려요
339,3892794,에샤페 실버문(1XM02348H063),2024-08-07,일단 컬러 넘 맘에 들고요 ㅎㅎ디자인도 귀여워요 발이 엄청 편한지는 모르겠지만 ..ㅎㅎ여름 쯤에 포인트로 신으면 참 좋은 아이템 입니당
1723,3892794,에샤페 실버문(1XM02348H063),2024-08-18,일단 컬러 넘 맘에 들고요 ㅎㅎ디자인도 귀여워요 발이 엄청 편한지는 모르겠지만 ..ㅎㅎ여름 쯤에 포인트로 신으면 참 좋은 아이템 입니당
280,3892794,에샤페 실버문(1XM02348H063),2024-10-09,재고가 없어 기다리다 주문했는데 넘 맘에 드네요~~디자인 세련되고 착화감도 좋아 하루종일 다녀도 발이 편해요~ 평소 240신는데 245 좋아요^^
1579,3892794,에샤페 실버문(1XM02348H063),2024-10-09,재고가 없어 기다리다 주문했는데 넘 맘에 드네요~~디자인 세련되고 착화감도 좋아 하루종일 다녀도 발이 편해요~ 평소 240신는데 245 좋아요^^
1843,3892794,에샤페 실버문(1XM02348H063),2024-08-08,저는 발볼이 좁은편이에요 컨버스 230 오니츠카 타이거 230 신어요 후기 보고 반 사이즈 크게 살까 하다가 정사이즈 샀는데 길이는 좀 남고 볼은 딱 맞아요 ! 두꺼운 양말 신으면 너무 꽉 맞는 느낌이에용
1948,3892794,에샤페 실버문(1XM02348H063),2024-07-28,저는 발볼이 좁은편이에요 컨버스 230 오니츠카 타이거 230 신어요 후기 보고 반 사이즈 크게 살까 하다가 정사이즈 샀는데 길이는 좀 남고 볼은 딱 맞아요 ! 두꺼운 양말 신으면 너무 꽉 맞는 느낌이에용
424,3892794,에샤페 실버문(1XM02348H063),2024-06-18,절대 한소희때문에산거아니에요🤣 실물이 더이뿌고 신엇을때가 꾸안꾸신발이라서 치마에도 반바지에도 찰떡이네요. 실버색이랴 여름에도 시원하게보이는게장점이고 대신 시원한건 잘몰......고프코어와 발레코어 중간쯤이라 여성스럽게 아님 걸크러쉬하게도 스타일내기 딱이네요.재입고 기다리다 산보람이 있어좋아요.사이즈는 운동화 245신는데 발볼때문에 250했더니 발볼딱맞아요.그래도 발이 커보이진않아요.
2467,3892794,에샤페 실버문(1XM02348H063),2024-06-05,절대 한소희때문에산거아니에요🤣 실물이 더이뿌고 신엇을때가 꾸안꾸신발이라서 치마에도 반바지에도 찰떡이네요. 실버색이랴 여름에도 시원하게보이는게장점이고 대신 시원한건 잘몰......고프코어와 발레코어 중간쯤이라 여성스럽게 아님 걸크러쉬하게도 스타일내기 딱이네요.재입고 기다리다 산보람이 있어좋아요.사이즈는 운동화 245신는데 발볼때문에 250했더니 발볼딱맞아요.그래도 발이 커보이진않아요.
1897,3892794,에샤페 실버문(1XM02348H063),2024-08-03,좋아요 잘 어울리고 좋습니다 배송도 빠르구요 그리고 또 내구성이 좋아보이네요 감사합니다 번창하세요
1898,3892794,에샤페 실버문(1XM02348H063),2024-08-03,좋아요 잘 어울리고 좋습니다 배송도 빠르구요 그리고 또 내구성이 좋아보이네요 감사합니다 번창하세요
327,3892794,에샤페 실버문(1XM02348H063),2024-08-17,좋은 상품 저렴하게 구매했어요. 마음에 들어요. 또 이용할게요.
328,3892794,에샤페 실버문(1XM02348H063),2024-08-17,좋은 상품 저렴하게 구매했어요. 마음에 들어요. 또 이용할게요.
380,3892794,에샤페 실버문(1XM02348H063),2024-07-14,지금 사기엔 조금 뒤늦은 감이 없지 않나 싶지만 사이즈 고민과 여러번의 품절로 이제야 산 에샤페!! 뉴발이랑 아디다스의 실버템과 함께 고민의 고민을 하다가 에샤페가 조금 더 제가 가진 옷들과 매치하기 좋을 것 같고 가격이 싸서 샀는데 너무너무 예뻐서 좋은 선택이었다고 생각해요&gt;&lt;!! 밑창 푹신하고 전체적으로 발을 폭삭 감는 느낌이에요. 발볼이 좁게 나온 것 같아서 발볼 넓은 분들은 사이즈 크게 사면 좋을 듯 합니다. 235 정사이즈인데 245 사니까 끈 너비 넓힘 없이 받은 그대로 착용 가능했어요!!ㅋㅋㅎㅎㅋㅎ
2134,3892794,에샤페 실버문(1XM02348H063),2024-07-06,지금 사기엔 조금 뒤늦은 감이 없지 않나 싶지만 사이즈 고민과 여러번의 품절로 이제야 산 에샤페!! 뉴발이랑 아디다스의 실버템과 함께 고민의 고민을 하다가 에샤페가 조금 더 제가 가진 옷들과 매치하기 좋을 것 같고 가격이 싸서 샀는데 너무너무 예뻐서 좋은 선택이었다고 생각해요&gt;&lt;!! 밑창 푹신하고 전체적으로 발을 폭삭 감는 느낌이에요. 발볼이 좁게 나온 것 같아서 발볼 넓은 분들은 사이즈 크게 사면 좋을 듯 합니다. 235 정사이즈인데 245 사니까 끈 너비 넓힘 없이 받은 그대로 착용 가능했어요!!ㅋㅋㅎㅎㅋㅎ
373,3892794,에샤페 실버문(1XM02348H063),2024-07-20,착용햇을때 쿠션감이 바로 느껴집니다 그만큼 편하고요 스타일까지 챙길슈잇어 만족해요
2166,3892794,에샤페 실버문(1XM02348H063),2024-07-03,착용햇을때 쿠션감이 바로 느껴집니다 그만큼 편하고요 스타일까지 챙길슈잇어 만족해요
463,3892794,에샤페 실버문(1XM02348H063),2024-05-31,츄리닝에 같이매치하니 잘어울려요 가격괜찮고 품질좋아요 보는친구들 전부 신발예쁘다고합니다
464,3892794,에샤페 실버문(1XM02348H063),2024-05-31,츄리닝에 같이매치하니 잘어울려요 가격괜찮고 품질좋아요 보는친구들 전부 신발예쁘다고합니다
2153,3892794,에샤페 실버문(1XM02348H063),2024-07-04,친척 동생들 생일이라서 신발 하나 사주려고 찾아보다가 휠라가 가성비도 좋고 요즘 유행하는 실버라서 선착순 구매에 성공했습니다.! 다행히도 양품이 도착했구요 스포티한 패턴이라서 고프코어룩인가 하는 코디에 잘 어울릴 것 같아요 제가 신을 건 아니고 선물용이라서 착화감은 물어보지 않았는데 아마 편하지 않을까 싶어요 요즘 물가가 다 비싼데 정가도 너무 합리적이라고 생각하구요 사이즈는 반업하면 더 편하게 신을 수 있다고 하네요 원래 저는 되게 힘겹게 선착순 구매에 성공했느데 지금 살펴보니깐 재입고가 되었는지 모든 사이즈가 있네요 다들 여름에 포인트주기 좋은 신발 하나 사시거나 또 선물용으로도 너무 좋은 선택이 될거라고 생각합니다.!
2236,3892794,에샤페 실버문(1XM02348H063),2024-06-29,친척 동생들 생일이라서 신발 하나 사주려고 찾아보다가 휠라가 가성비도 좋고 요즘 유행하는 실버라서 선착순 구매에 성공했습니다.! 다행히도 양품이 도착했구요 스포티한 패턴이라서 고프코어룩인가 하는 코디에 잘 어울릴 것 같아요 제가 신을 건 아니고 선물용이라서 착화감은 물어보지 않았는데 아마 편하지 않을까 싶어요 요즘 물가가 다 비싼데 정가도 너무 합리적이라고 생각하구요 사이즈는 반업하면 더 편하게 신을 수 있다고 하네요 원래 저는 되게 힘겹게 선착순 구매에 성공했느데 지금 살펴보니깐 재입고가 되었는지 모든 사이즈가 있네요 다들 여름에 포인트주기 좋은 신발 하나 사시거나 또 선물용으로도 너무 좋은 선택이 될거라고 생각합니다.!
2197,3892794,에샤페 실버문(1XM02348H063),2024-07-02,쿠폰 적용해서 저렴하게 잘삿습니다 선물용으로 구매한건데 받은사람이 너무 좋아하네요 감사합니당
2198,3892794,에샤페 실버문(1XM02348H063),2024-07-02,쿠폰 적용해서 저렴하게 잘삿습니다 선물용으로 구매한건데 받은사람이 너무 좋아하네요 감사합니당
2199,3892794,에샤페 실버문(1XM02348H063),2024-07-02,쿠폰 적용해서 저렴하게 잘삿습니다 선물용으로 구매한건데 받은사람이 너무 좋아하네요 감사합니당
2205,3892794,에샤페 실버문(1XM02348H063),2024-07-02,쿠폰 적용해서 저렴하게 잘삿습니다 선물용으로 구매한건데 받은사람이 너무 좋아하네요 감사합니당
484,3892794,에샤페 실버문(1XM02348H063),2024-05-20,편하고좋아요 예뻐요 배송도빨랐어요! 아무데나잘어울려용
2709,3892794,에샤페 실버문(1XM02348H063),2024-05-19,편하고좋아요 예뻐요 배송도빨랐어요! 아무데나잘어울려용
1803,3892794,에샤페 실버문(1XM02348H063),2024-08-12,평소 230-235를 신는데 235사이즈 1개 남아있어서 바로 구매했습니다 다행히 사이즈는 잘 맞아요 포인트로 신을 수도 있고 어디든 잘 어울려서 잘 신고 다니고 있어요 무엇보다 너무 편해요 굿굿
2221,3892794,에샤페 실버문(1XM02348H063),2024-07-01,평소 230-235를 신는데 235사이즈 1개 남아있어서 바로 구매했습니다 다행히 사이즈는 잘 맞아요 포인트로 신을 수도 있고 어디든 잘 어울려서 잘 신고 다니고 있어요 무엇보다 너무 편해요 굿굿
428,3892794,에샤페 실버문(1XM02348H063),2024-06-16,평소 운동화도 240-250 왔다갔다 할 정도로 브랜드에 따라 사이즈 변화가 심한 사람인데 245로 사고싶었지만 품절이었어서 그냥 250으로 구매했어요. 배송은 이틀만에 왔고 진짜 예뻐요!! 근데 역시 250은 좀 많이 커요ㅠㅜㅠ 엄지 마디 하나가 남을정도로 큰데 그 사이에 250마저 품절이 된걸보니 후회는 안 되는거같아요 꽉끈하고 신으니까 크게 불편하지도 않고 무엇보다 예쁘니까!! 잘 신고다닐거같아요 :)
2391,3892794,에샤페 실버문(1XM02348H063),2024-06-13,평소 운동화도 240-250 왔다갔다 할 정도로 브랜드에 따라 사이즈 변화가 심한 사람인데 245로 사고싶었지만 품절이었어서 그냥 250으로 구매했어요. 배송은 이틀만에 왔고 진짜 예뻐요!! 근데 역시 250은 좀 많이 커요ㅠㅜㅠ 엄지 마디 하나가 남을정도로 큰데 그 사이에 250마저 품절이 된걸보니 후회는 안 되는거같아요 꽉끈하고 신으니까 크게 불편하지도 않고 무엇보다 예쁘니까!! 잘 신고다닐거같아요 :)
212,3892794,에샤페 실버문(1XM02348H063),2025-03-31,"평소 칼발 235이고 구두235 반스,컨버스230 나이키,아디다스,뉴발235 살로몬240 신는데 240하니 앞코는 조금남고 볼은 칼발인데도 딱이에요. 정사도 괜찮을거 같은데 꽉끈 안될거 같아서 핏은 안이쁠거 같아요 반업 추천합니다."
1317,3892794,에샤페 실버문(1XM02348H063),2025-03-23,"평소 칼발 235이고 구두235 반스,컨버스230 나이키,아디다스,뉴발235 살로몬240 신는데 240하니 앞코는 조금남고 볼은 칼발인데도 딱이에요. 정사도 괜찮을거 같은데 꽉끈 안될거 같아서 핏은 안이쁠거 같아요 반업 추천합니다."
337,3892794,에샤페 실버문(1XM02348H063),2024-08-09,평소에 280신는데 똑같이하면 될거같아요 이뻐요
2020,3892794,에샤페 실버문(1XM02348H063),2024-07-23,평소에 280신는데 똑같이하면 될거같아요 이뻐요
440,3892794,에샤페 실버문(1XM02348H063),2024-06-10,폭은 얇고 길이는 길어보이게 나온 모양이 예뻐요 올블랙 트레이닝복입을때 포인트로 편하게 신기 좋네요
441,3892794,에샤페 실버문(1XM02348H063),2024-06-10,폭은 얇고 길이는 길어보이게 나온 모양이 예뻐요 올블랙 트레이닝복입을때 포인트로 편하게 신기 좋네요
499,3892794,에샤페 실버문(1XM02348H063),2024-05-07,품절 재입고 기다리다 포기하고 있었는데 알림 뜨자마자 결제했어요ㅠㅠ배송도 다다음날에 바로 왔고 실물이 더 예쁘고 화사합니다 평소 245-250 신는데 250이 좀 널널하게 맞고 발볼은 제가 좁은 편인데도 딱 맞네요!!
2749,3892794,에샤페 실버문(1XM02348H063),2024-05-13,품절 재입고 기다리다 포기하고 있었는데 알림 뜨자마자 결제했어요ㅠㅠ배송도 다다음날에 바로 왔고 실물이 더 예쁘고 화사합니다 평소 245-250 신는데 250이 좀 널널하게 맞고 발볼은 제가 좁은 편인데도 딱 맞네요!!
202,3892794,에샤페 실버문(1XM02348H063),2025-04-07,할인받아서 저렴하게 잘샀는데 디자인도 마음이 들어요
203,3892794,에샤페 실버문(1XM02348H063),2025-04-07,할인받아서 저렴하게 잘샀는데 디자인도 마음이 들어요
2854,3892794,에샤페 실버문(1XM02348H063),2024-04-15,항상 무신사 애용하고있습니다! 상품도 야무지게 잘 도착했고 항상 만족해요! 다음에도 무신사 이용할게요!
2856,3892794,에샤페 실버문(1XM02348H063),2024-04-15,항상 무신사 애용하고있습니다! 상품도 야무지게 잘 도착했고 항상 만족해요! 다음에도 무신사 이용할게요!

review_date까지 완전히 동일한 경우 개수:  174
purchase_option까지 완전히 동일한 경우 개수:  0

Empty DataFrame
Columns: [product_id, product_name, review_date, purchase_option, content]
Index: []