In [1]:
import pandas as pd
import numpy as np

---
# 안다르 자사몰 리뷰 데이터

## 1. 전처리

In [2]:
# 안다르
df_review_andar_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/andar_reviews_final_new.csv")
display(df_review_andar_D2C.head(3))
display(df_review_andar_D2C.info())

,review_id,product_id,post_date,post_time,platform,brand,search_keyword,content,source_url,rating,...,media_count,main_content_type,upload_from,labels,topics,키,몸무게,평소사이즈,사이즈_평가,사이즈_한줄평
0,48724074,5147,2026-04-14,03:48:43,자사몰리뷰,안다르,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요....",https://andar.co.kr/product/detail.html?produc...,5,...,2,image,vreview-board,[],"['functionality', 'activity', 'color']",155~159cm,45~49kg,S,잘 맞아요,마사지하기 딱 좋은 사이즈!
1,48590531,5147,2026-04-07,17:50:41,네이버페이,안다르,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...,https://andar.co.kr/product/detail.html?produc...,3,...,0,text,api-ingest,[],['material'],NaN,NaN,NaN,NaN,NaN
2,48535840,5147,2026-04-05,10:10:20,자사몰리뷰,안다르,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...,https://andar.co.kr/product/detail.html?produc...,5,...,1,image,vreview-board,['재구매'],"['activity', 'color']",165~169cm,55~59kg,M,잘 맞아요,좋아요

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   review_id          925663 non-null  int64
 1   product_id         925663 non-null  int64
 2   post_date          925663 non-null  str
 3   post_time          925663 non-null  str
 4   platform           925663 non-null  str
 5   brand              925663 non-null  str
 6   search_keyword     925663 non-null  str
 7   content            918763 non-null  str
 8   source_url         925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  purchased_option   750889 non-null  str
 12  has_image          925663 non-null  int64
 13  collect_date       925663 non-null  str
 14  title              676233 non-null  str
 15  user_nickname      925663 non-null  str
 16  media_count        925663 non-null  int64
 17  main_content_type  925663 non-null  str
 18  upload_from        925663 non-null  str
 19  labels             925663 non-null  str
 20  topics             925663 non-null  str
 21  키                  633734 non-null  str
 22  몸무게                624861 non-null  str
 23  평소사이즈              620967 non-null  str
 24  사이즈_평가             677892 non-null  str
 25  사이즈_한줄평            654363 non-null  str
dtypes: int64(6), str(20)
memory usage: 630.4 MB

None

In [3]:
# =======================================
# 사용할 컬럼만 선택
# =======================================
df_review_andar_D2C = df_review_andar_D2C.drop(['post_time', 'brand', 'user_nickname', 'media_count', 'main_content_type', 'upload_from', 'labels', 'topics', '평소사이즈', '사이즈_평가'], axis=1)
df_review_andar_D2C.head(3)

,review_id,product_id,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,collect_date,title,키,몸무게,사이즈_한줄평
0,48724074,5147,2026-04-14,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요....",https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,릴렉스 마사지 듀얼볼 Ⅱ 후기,155~159cm,45~49kg,마사지하기 딱 좋은 사이즈!
1,48590531,5147,2026-04-07,네이버페이,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...,https://andar.co.kr/product/detail.html?produc...,3,0,NaN,0,2026-04-21,보통,NaN,NaN,NaN
2,48535840,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,릴렉스 마사지 듀얼볼 Ⅱ 후기,165~169cm,55~59kg,좋아요

In [4]:
# =======================================
# 리뷰 본문 합치기 => content + title, 사이즈_한줄평
# =======================================
# 합치기
df_review_andar_D2C['content'] = df_review_andar_D2C[['content', 'title', '사이즈_한줄평']].fillna('').agg(' '.join, axis=1).str.strip()

# 합친 컬럼 삭제하기
df_review_andar_D2C = df_review_andar_D2C.drop(['title', '사이즈_한줄평'], axis=1)

display(df_review_andar_D2C.head())

,review_id,product_id,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,collect_date,키,몸무게
0,48724074,5147,2026-04-14,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요....",https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,155~159cm,45~49kg
1,48590531,5147,2026-04-07,네이버페이,릴렉스 마사지 듀얼볼 Ⅱ,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등...,https://andar.co.kr/product/detail.html?produc...,3,0,NaN,0,2026-04-21,NaN,NaN
2,48535840,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워...,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,165~169cm,55~59kg
3,48535469,5147,2026-04-05,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",0,2026-04-21,160~164cm,50~54kg
4,48521693,5147,2026-04-03,자사몰리뷰,릴렉스 마사지 듀얼볼 Ⅱ,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴...,https://andar.co.kr/product/detail.html?produc...,5,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",1,2026-04-21,160~164cm,55~59kg

In [5]:
display(df_review_andar_D2C.info())

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   review_id         925663 non-null  int64
 1   product_id        925663 non-null  int64
 2   post_date         925663 non-null  str
 3   platform          925663 non-null  str
 4   search_keyword    925663 non-null  str
 5   content           925663 non-null  str
 6   source_url        925663 non-null  str
 7   rating            925663 non-null  int64
 8   helpful_count     925663 non-null  int64
 9   purchased_option  750889 non-null  str
 10  has_image         925663 non-null  int64
 11  collect_date      925663 non-null  str
 12  키                 633734 non-null  str
 13  몸무게               624861 non-null  str
dtypes: int64(5), str(9)
memory usage: 477.4 MB

None

In [6]:
df_review_andar_D2C['키'].isna().mean()*100

np.float64(31.53728732810969)

In [7]:
# =======================================
# review_id 중복 확인
# =======================================
df_review_andar_D2C['review_id'].duplicated().sum()

np.int64(0)

In [8]:
# =======================================
# 결측치 처리
# =======================================
# purchased_option => 18.8%
# 키 => 31.5%
# 몸무게 => 32.4%

In [9]:
# purchased_option => 18.8%
pd.set_option('display.max_colwidth', None) # 컬럼 안 텍스트 잘림 제거
df_review_andar_D2C[['search_keyword', 'source_url', 'purchased_option']].drop_duplicates().head(20)
# ‘product_id’와 제품 옵션이 1:1로 매칭되지 않음. 결측치 그대로 유지

,search_keyword,source_url,purchased_option
0,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02DPK] 샤이 핑크, F (Free)"
1,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,NaN
6,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02NAV] 마린 네이비, F (Free)"
28,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02PNK] 블라썸핑크, F (Free)"
58,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02MNT] 파스텔민트, F (Free)"
75,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLU] 마일드 블루, F (Free)"
313,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLK] 블랙, F (Free)"
314,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02GRN] 포레스트 그린, F (Free)"
976,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02GRY] 올리브그레이, F (Free)"
1429,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07CRM] 치즈크림, F (Free)"
1462,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07GRY] 올리브그레이, F (Free)"
1564,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07PNK] 블라썸핑크, F (Free)"
1766,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02LVD] 페털 라일락, F (Free)"
1964,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJPMB-07MNT] 파스텔민트, F (Free)"
2355,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EJFMB-02BLK] 시크 블랙, F (Free)"
2506,릴렉스 마사지 듀얼볼 Ⅱ,https://andar.co.kr/product/detail.html?product_no=5147,"[EKRMB-02LVD] 페털 라일락, F (Free)"
4115,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01GRN] 아카시아그린, F (Free)"
4117,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,NaN
4121,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01DGY] 프로스트그레이, F (Free)"
4123,요가매트 스트랩 위드,https://andar.co.kr/product/detail.html?product_no=5361,"[EJSST-01BLK] 블랙, F (Free)"

In [10]:
# 키 => 31.5%
df_review_andar_D2C['키'] = df_review_andar_D2C['키'].astype(object)
df_review_andar_D2C['키'] = df_review_andar_D2C['키'].fillna(None) # None으로 잘 대체 됨.

# 몸무게 => 32.4%
df_review_andar_D2C['몸무게'] = df_review_andar_D2C['몸무게'].astype(object)
df_review_andar_D2C['몸무게'] = df_review_andar_D2C['몸무게'].fillna(None) # None으로 잘 대체 됨.

# display(df_review_andar_D2C['키'].value_counts(dropna=False))
# display(df_review_andar_D2C['몸무게'].value_counts(dropna=False))

In [17]:
# =======================================
# 파생컬럼 생성 (year, month)
# =======================================
df_review_andar_D2C['post_date'] = pd.to_datetime(df_review_andar_D2C['post_date'])

df_review_andar_D2C['year'] = df_review_andar_D2C['post_date'].dt.year
df_review_andar_D2C['month'] = df_review_andar_D2C['post_date'].dt.month

In [19]:
# =======================================
# 컬럼 이름 통일
# =======================================

df_review_andar_D2C = df_review_andar_D2C.rename(columns={
    'post_date' : 'review_date', 
    'search_keyword' : 'product_name',
    'content' : 'review_body',
    'source_url' : 'product_url',
    'purchased_option' : 'purchase_option',
    '키' : 'user_height',
    '몸무게' : 'user_weight'
})

In [20]:
# =======================================
# 없는 컬럼 추가
# =======================================

required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'review_body', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_andar_D2C.columns:
        df_review_andar_D2C[col] = None

# 컬럼 순서 정리
df_review_andar_D2C = df_review_andar_D2C[required_columns]

In [50]:
df_review_andar_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   collect_date       925663 non-null  datetime64[us]
 1   platform           925663 non-null  category
 2   review_id          925663 non-null  int64
 3   product_id         925663 non-null  int64
 4   product_name       925663 non-null  str
 5   review_date        925663 non-null  datetime64[us]
 6   year               925663 non-null  int32
 7   month              925663 non-null  int32
 8   review_body        925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  has_image          925663 non-null  int64
 12  purchase_option    750889 non-null  category
 13  user_height        0 non-null       object
 14  user_weight        0 non-null       object
 15  user_height_group  633734 non-null  category
 16  user_weight_group  624861 non-null  category
 17  product_url        925663 non-null  str
dtypes: category(4), datetime64[us](2), int32(2), int64(5), object(2), str(3)
memory usage: 398.1+ MB

In [45]:
# =======================================
# 데이터 타입 통일
# =======================================

df_review_andar_D2C['collect_date'] = pd.to_datetime(df_review_andar_D2C['collect_date'])
df_review_andar_D2C['platform'] = df_review_andar_D2C['collect_date'].astype('category')
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype('category')
# df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype('category')

In [40]:
# =======================================
# 데이터 값 정리
# =======================================

# platform 데이터 => 자사몰
df_review_andar_D2C['platform'] = '자사몰'

# purchase_option => None
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype(object)
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].fillna(None)

# 신체정보 컬럼이름 바꾸기, 순서 변경하기
df_review_andar_D2C = df_review_andar_D2C.rename(columns={
    'user_height': 'user_height_temp',
    'user_weight': 'user_weight_temp',
    'user_height_group': 'user_height',
    'user_weight_group': 'user_weight',
    'user_height_temp': 'user_height_group',
    'user_weight_temp': 'user_weight_group',
})

In [42]:
# 신체정보 컬럼이름 바꾸기, 순서 변경하기
df_review_andar_D2C = df_review_andar_D2C.rename(columns={
    'user_height_temp': 'user_height',
    'user_weight_temp': 'user_weight',
})

df_review_andar_D2C = df_review_andar_D2C[required_columns]

In [ ]:
# 데이터 값  확인
df_review_andar_D2C['purchase_option'].value_counts(dropna=False)

purchase_option
NaN                                                174774
[EMTBG-03BLK] 블랙, F (Free)                           1858
[EMTBG-03BEG] 카키베이지, F (Free)                        1280
[EJPMS-05PNK] 블라썸핑크, F (Free)                         993
[ALTBP-02BEG] 베이지, F (Free)                           971
                                                    ...
후크형, XL (80C/85A~C/90A), [ANFIB-04BLK] 후크형 블랙           1
후크형, XL (80C/85A~C/90A), [ANFIB-04PNK] 후크형 코지핑크         1
후크형, XL (85C~E), [AOPIB-01BEG] 후크형 핑크베이지                1
후크형, XS (65A~C), [ANFIB-04LGN] 후크형 소프트그린                1
후크형, XS (65A~C), [ANFIB-04PNK] 후크형 코지핑크                 1
Name: count, Length: 118568, dtype: int64

In [76]:
df_review_andar_D2C.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,review_body,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,자사몰,48724074,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-14,2026,4,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕 릴렉스 마사지 듀얼볼 Ⅱ 후기 마사지하기 딱 좋은 사이즈!",5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,155~159cm,45~49kg,https://andar.co.kr/product/detail.html?product_no=5147
1,2026-04-21,자사몰,48590531,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-07,2026,4,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등록된 네이버 페이 구매평) 보통,3,0,0,NaN,None,None,NaN,NaN,https://andar.co.kr/product/detail.html?product_no=5147
2,2026-04-21,자사몰,48535840,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-05,2026,4,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워요 핑크조아~ 릴렉스 마사지 듀얼볼 Ⅱ 후기 좋아요,5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,165~169cm,55~59kg,https://andar.co.kr/product/detail.html?product_no=5147
3,2026-04-21,자사몰,48535469,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-05,2026,4,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈,5,0,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,160~164cm,50~54kg,https://andar.co.kr/product/detail.html?product_no=5147
4,2026-04-21,자사몰,48521693,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-03,2026,4,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 사이즈 딱 좋아요,5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,160~164cm,55~59kg,https://andar.co.kr/product/detail.html?product_no=5147

In [75]:
# platform 데이터 => 자사몰
df_review_andar_D2C['platform'] = '자사몰'

In [47]:
# =======================================
# 데이터 타입 통일
# =======================================

df_review_andar_D2C['user_height_group'] = df_review_andar_D2C['user_height_group'].astype('category')
df_review_andar_D2C['user_weight_group'] = df_review_andar_D2C['user_weight_group'].astype('category')

In [ ]:
# =======================================
# user_height_group, user_weight_group => 데이터 확인
# =======================================
display(df_review_andar_D2C['user_height_group'].value_counts())
display(df_review_andar_D2C['user_weight_group'].value_counts())

user_height_group
160~164cm    196826
155~159cm    132055
165~169cm    118817
170~174cm     78276
175~179cm     43072
150~154cm     36726
180~184cm     18156
185~189cm      3426
145~149cm      2941
139cm 이하       2036
140~144cm       949
190cm 이상        454
Name: count, dtype: int64

user_weight_group
50~54kg    147281
55~59kg    123792
60~64kg     90099
45~49kg     71134
65~69kg     50532
70~74kg     45790
75~79kg     30015
80~84kg     26262
44kg 이하     15892
90kg 이상     12570
85~89kg     11494
Name: count, dtype: int64

In [124]:
# ====================================================================================
# purchase_option, user_height_group, user_weight_group => fillna(None)
# ====================================================================================
df_review_andar_D2C[['purchase_option', 'user_height_group', 'user_weight_group']] = (
    df_review_andar_D2C[['purchase_option', 'user_height_group', 'user_weight_group']]
    .astype(object)
    .fillna(None)
)

In [127]:
# =======================================
# 'is_outlet' 제거
# =======================================

df_review_andar_D2C = df_review_andar_D2C.drop(['is_outlet'], axis=1)

In [129]:
# =======================================
# dtype
# =======================================

df_review_andar_D2C['platform'] = df_review_andar_D2C['platform'].astype('category')
df_review_andar_D2C['purchase_option'] = df_review_andar_D2C['purchase_option'].astype('category')
df_review_andar_D2C['user_height_group'] = df_review_andar_D2C['user_height_group'].astype('category')
df_review_andar_D2C['user_weight_group'] = df_review_andar_D2C['user_weight_group'].astype('category')

In [235]:
# =======================================
# review_body => content로 컬럼명 변경
# =======================================
df_review_andar_D2C = df_review_andar_D2C.rename(columns={
    'review_body' : 'content'
})

In [236]:
# =======================================
# 최종확인
# =======================================
display(df_review_andar_D2C.head(5))
print(df_review_andar_D2C.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,자사몰,48724074,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-14,2026,4,"러닝 후 몸 풀어주는 용으로 아주 좋아요. 종아리나 등, 목 뒤에 사용하기 좋아요. 색깔도 파스텔톤이라 질리지 않고 너무 예뻐요💕 릴렉스 마사지 듀얼볼 Ⅱ 후기 마사지하기 딱 좋은 사이즈!",5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,155~159cm,45~49kg,https://andar.co.kr/product/detail.html?product_no=5147
1,2026-04-21,자사몰,48590531,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-07,2026,4,딱딱하네요\n저는 말랑말랑 한줄 알았어요(2026-04-07 20:15:59 에 등록된 네이버 페이 구매평) 보통,3,0,0,NaN,None,None,NaN,NaN,https://andar.co.kr/product/detail.html?product_no=5147
2,2026-04-21,자사몰,48535840,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-05,2026,4,요가링이랑 폼롤러랑 같이 사서 집에서 잘 굴려주고 있어요 색깔도 너무 예쁘고 귀여워요 핑크조아~ 릴렉스 마사지 듀얼볼 Ⅱ 후기 좋아요,5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,165~169cm,55~59kg,https://andar.co.kr/product/detail.html?product_no=5147
3,2026-04-21,자사몰,48535469,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-05,2026,4,묵직하니 사용하기 편하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 정사이즈,5,0,0,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,160~164cm,50~54kg,https://andar.co.kr/product/detail.html?product_no=5147
4,2026-04-21,자사몰,48521693,5147,릴렉스 마사지 듀얼볼 Ⅱ,2026-04-03,2026,4,시원하게 마사지가되요 여기저기 쉽게 문지르고 아픈 부위 꾹꾹 눌러주니 시원하네요 릴렉스 마사지 듀얼볼 Ⅱ 후기 사이즈 딱 좋아요,5,0,1,"[EJFMB-02DPK] 샤이 핑크, F (Free)",None,None,160~164cm,55~59kg,https://andar.co.kr/product/detail.html?product_no=5147

<class 'pandas.DataFrame'>
RangeIndex: 925663 entries, 0 to 925662
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   collect_date       925663 non-null  datetime64[us]
 1   platform           925663 non-null  category
 2   review_id          925663 non-null  int64
 3   product_id         925663 non-null  int64
 4   product_name       925663 non-null  str
 5   review_date        925663 non-null  datetime64[us]
 6   year               925663 non-null  int32
 7   month              925663 non-null  int32
 8   content            925663 non-null  str
 9   rating             925663 non-null  int64
 10  helpful_count      925663 non-null  int64
 11  has_image          925663 non-null  int64
 12  purchase_option    750889 non-null  category
 13  user_height        0 non-null       object
 14  user_weight        0 non-null       object
 15  user_height_group  633734 non-null  category
 16  user_weight_group  624861 non-null  category
 17  product_url        925663 non-null  str
dtypes: category(4), datetime64[us](2), int32(2), int64(5), object(2), str(3)
memory usage: 398.1+ MB
None

In [237]:
# =======================================
# 저장
# =======================================

df_review_andar_D2C_2024 = df_review_andar_D2C[df_review_andar_D2C['year'] >= 2024]

df_review_andar_D2C.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_homepage_review_final.csv", encoding='utf-8-sig', index=False)
df_review_andar_D2C_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_homepage_review_final_s2024.csv", encoding='utf-8-sig', index=False)

### 중복제거

In [116]:
df_review_andar_D2C_copy = df_review_andar_D2C.copy()

In [ ]:
# =================================================
# product_id, product_name, review_body (완료)
# =================================================

# 1) 중복 데이터 확인

df_review_andar_D2C[df_review_andar_D2C.duplicated(subset=['product_id', 'product_name', 'review_body'], keep=False)]\
    .sort_values(['product_id', 'review_body'])[['product_id', 'product_name', 'review_body']].head(10)

,product_id,product_name,review_body
565548,5144,릴렉스 마사지 스틱 Ⅱ,가격대비 정말 견고하고 마감도 깔끔하네요 대근육 근막 마사지에 정말 활용도가 높아요 이쁜 색감은 덤이구요🥰 감사합니다
565551,5144,릴렉스 마사지 스틱 Ⅱ,가격대비 정말 견고하고 마감도 깔끔하네요 대근육 근막 마사지에 정말 활용도가 높아요 이쁜 색감은 덤이구요🥰 감사합니다
558455,5144,릴렉스 마사지 스틱 Ⅱ,딱좋아요 요기조기 불편한곳에 사용중입니다!! 릴렉스 마사지 스틱 Ⅱ 후기 딱
558456,5144,릴렉스 마사지 스틱 Ⅱ,딱좋아요 요기조기 불편한곳에 사용중입니다!! 릴렉스 마사지 스틱 Ⅱ 후기 딱
560511,5144,릴렉스 마사지 스틱 Ⅱ,리뷰가 많아서 한 번 구매해봤어요 \n어머!! 너무 시원해서 집에도 하나 놓고\n사무실에서도 꾸준히 하러고 하나 더 샀어요\n주변에도 선물로 주려고 추가 구매했답니다 \n너무 시원하고 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 너무 시원해요👍
560512,5144,릴렉스 마사지 스틱 Ⅱ,리뷰가 많아서 한 번 구매해봤어요 \n어머!! 너무 시원해서 집에도 하나 놓고\n사무실에서도 꾸준히 하러고 하나 더 샀어요\n주변에도 선물로 주려고 추가 구매했답니다 \n너무 시원하고 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 너무 시원해요👍
560513,5144,릴렉스 마사지 스틱 Ⅱ,리뷰가 많아서 한 번 구매해봤어요 \n어머!! 너무 시원해서 집에도 하나 놓고\n사무실에서도 꾸준히 하러고 하나 더 샀어요\n주변에도 선물로 주려고 추가 구매했답니다 \n너무 시원하고 좋아요 릴렉스 마사지 스틱 Ⅱ 후기 너무 시원해요👍
559386,5144,릴렉스 마사지 스틱 Ⅱ,릴렉스 마사지 스틱 Ⅱ 후기
559754,5144,릴렉스 마사지 스틱 Ⅱ,릴렉스 마사지 스틱 Ⅱ 후기
560034,5144,릴렉스 마사지 스틱 Ⅱ,릴렉스 마사지 스틱 Ⅱ 후기

In [118]:
# 2) 중복제거
df_review_andar_D2C_copy = (
    df_review_andar_D2C_copy[df_review_andar_D2C_copy.duplicated(
        subset=['product_id', 'product_name', 'review_body'],
        keep=False
    )]#[
        # ['product_id', 'product_name', 'review_body', 'rating', 'helpful_count','has_image'] # 보일 컬럼
    #]
    .sort_values(['product_id', 'rating', 'helpful_count','has_image'], ascending=[True, False, False, False]) # 정렬
    .drop_duplicates(subset=['product_id', 'product_name', 'review_body'], keep='first')
)

In [120]:
# 3) 중복제거 확인
df_review_andar_D2C_copy.duplicated(
    subset=['product_id', 'product_name', 'review_body']
).sum()

np.int64(0)

In [ ]:
# =================================================
# review_body (하는 중이었음)
# =================================================

# 1) 데이터 확인
(
    df_review_andar_D2C_copy[df_review_andar_D2C_copy.duplicated(
    subset=['review_body', 'product_name'],
    keep=False)]
    .sort_values(['product_name', 'review_body'])
)

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,review_body,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url,is_outlet
762109,2026-04-21,자사몰,13356670,8583,[1&1] 에어쿨링 3부 레깅스,2023-09-14,2023,9,[1&1] 에어쿨링 3부 레깅스 후기,5,0,1,"사이즈 1)=M (55반~66), 색상 1)=[ALP3L-02BLK] 블랙, 사이즈 2)=M (55반~66), 색상 2)=[ALP3L-02CHA] 벨루가차콜",None,None,160~164cm,50~54kg,https://andar.co.kr/product/detail.html?product_no=8583,False
383717,2026-04-21,자사몰,18328657,9198,[1&1] 에어쿨링 3부 레깅스,2024-02-09,2024,2,[1&1] 에어쿨링 3부 레깅스 후기,5,0,1,"사이즈 1)=L (66반~77), 색상 1)=[ALP3L-02BLK] 블랙, 사이즈 2)=L (66반~77), 색상 2)=[ALP3L-02BLK] 블랙",None,None,160~164cm,50~54kg,https://andar.co.kr/product/detail.html?product_no=9198,False
760890,2026-04-21,자사몰,39222463,8583,[1&1] 에어쿨링 3부 레깅스,2025-06-24,2025,6,옷이 너무 마음에 들고 마음에 들어요. 항상 andar 옷을 입고 있어요. 매번 구매할 때마다 너무 많아요. 많은 자매들이 같이 구매해요. 전지현 씨가 광고하는 상품이 너무 좋아요.활동할 때 수지가 맞고 항상 복지 활동이 있었으면 좋겠습니다. andar가 점점 더 좋아지길 바랍니다. [1&1] 에어쿨링 3부 레깅스 후기 사이즈 선택이 딱 맞아서 상체 효과가 좋아요.,5,0,1,"사이즈 2)=L (66반~77), 색상 2)=[ALP3L-02BLK] 블랙, 사이즈 1)=S (44~55), 색상 1)=[ALP3L-02AGR] 앤트러사이트그레이",None,None,165~169cm,NaN,https://andar.co.kr/product/detail.html?product_no=8583,False
383120,2026-04-21,자사몰,43682745,9198,[1&1] 에어쿨링 3부 레깅스,2025-10-15,2025,10,옷이 너무 마음에 들고 마음에 들어요. 항상 andar 옷을 입고 있어요. 매번 구매할 때마다 너무 많아요. 많은 자매들이 같이 구매해요. 전지현 씨가 광고하는 상품이 너무 좋아요.활동할 때 수지가 맞고 항상 복지 활동이 있었으면 좋겠습니다. andar가 점점 더 좋아지길 바랍니다. [1&1] 에어쿨링 3부 레깅스 후기 사이즈 선택이 딱 맞아서 상체 효과가 좋아요.,5,0,1,"사이즈 1)=M (55반~66), 색상 1)=[ALP3L-02KHK] 바질머스타드, 사이즈 2)=M (55반~66), 색상 2)=[ALP3L-02BLK] 블랙",None,None,160~164cm,NaN,https://andar.co.kr/product/detail.html?product_no=9198,False
389780,2026-04-21,자사몰,43682789,9197,[1&1] 에어쿨링 4.5부 레깅스,2025-10-15,2025,10,옷이 너무 마음에 들고 마음에 들어요. 항상 andar 옷을 입고 있어요. 매번 구매할 때마다 너무 많아요. 많은 자매들이 같이 구매해요. 전지현 씨가 광고하는 상품이 너무 좋아요.활동할 때 수지가 맞고 항상 복지 활동이 있었으면 좋겠습니다. andar가 점점 더 좋아지길 바랍니다. [1&1] 에어쿨링 4.5부 레깅스 후기 사이즈 선택이 딱 맞아서 상체 효과가 좋아요.,5,0,1,"사이즈 1)=S (44~55), 색상 1)=[AMP4L-08BLK] 블랙, 사이즈 2)=S (44~55), 색상 2)=[AMP4L-08BLK] 블랙",None,None,160~164cm,NaN,https://andar.co.kr/product/detail.html?product_no=9197,False
527545,2026-04-21,자사몰,41215151,13515,[1&1] 에어쿨링 4.5부 레깅스,2025-07-30,2025,7,옷이 너무 마음에 들고 마음에 들어요. 항상 andar 옷을 입고 있어요. 매번 구매할 때마다 너무 많아요. 많은 자매들이 같이 구매해요. 전지현 씨가 광고하는 상품이 너무 좋아요.활동할 때 수지가 맞고 항상 복지 활동이 있었으면 좋겠습니다. andar가 점점 더 좋아지길 바랍니다. [1&1] 에어쿨링 4.5부 레깅스 후기 사이즈 선택이 딱 맞아서 상체 효과가 좋아요.,5,0,1,"사이즈 1)=M (55반~66), 색상 1)=[AMP4L-08BLK] 블랙, 사이즈 2)=M (55반~66), 색상 2)=[AMP4L-08BLK] 블랙",None,None,165~169cm,NaN,https://andar.co.kr/product/detail.html?product_no=13515,False
905534,2026-04-21,자사몰,35493871,5752,[1+1] 에어쿨링 지니 시그니처 레깅스,2025-01-13,2025,1,편하게 잘 맞아요~\n색감도 예쁘고 마음에 들어요~~~\n두께감도 적당하고 기장도 적당해서 잘 맞아요~~! [1+1] 에어쿨링 지니 시그니처 레깅스 후기 편하게 잘 맞아요~ 색감도 예쁘고 마음에 들어요~~~,5,0,1,"사이즈 1)=XL (88), 색상 1)=[AJF8L-10BLK] 8.2부 블랙, 사이즈 2)=XL (88), 색상 2)=[AJF8L-10BLK] 8.2부 블랙",None,None,170~174cm,60~64kg,https://andar.co.kr/product/detail.html?product_no=5752,False
386759,2026-04-21,자사몰,23074833,9196,[1+1] 에어쿨링 지니 시그니처 레깅스,2024-04-28,2024,4,편하게 잘 맞아요~\n색감도 예쁘고 마음에 들어요~~~\n두께감도 적당하고 기장도 적당해서 잘 맞아요~~! [1+1] 에어쿨링 지니 시그니처 레깅스 후기 편하게 잘 맞아요~ 색감도 예쁘고 마음에 들어요~~~,5,1,1,"사이즈 1)=L (66반~77), 색상 1)=[AJF8L-10DNV] 8.2부 다크데님, 사이즈 2)=L (66반~77), 색상 2)=[AJF8L-10DNV] 8.2부 다크데님",None,None,160~164cm,60~64kg,https://andar.co.kr/product/detail.html?product_no=9196,False

In [ ]:
df_review_andar_D2C_copy['product_id']

In [ ]:
# =========================================
# product_name & product_id 매창, 중복 확인 (하는 중이었음)
# =========================================

# 1) product_id, product_name 1:1 매칭 확인
# product_id에 2개 매칭된 거 데이터 확인
df_review_andar_D2C.groupby('product_id')['product_name'].nunique().sort_values(ascending=False)

product_id
8576     2
8732     2
10768    2
10951    2
7297     2
        ..
10882    1
10881    1
10880    1
10879    1
17564    1
Name: product_name, Length: 1403, dtype: int64

In [ ]:
# 2) product_name이 2개인 product_id 추출

duplicated_product_ids = df_review_andar_D2C.groupby('product_id')['product_name'].nunique()
duplicated_product_ids = duplicated_product_ids[duplicated_product_ids == 2].index

# 실제 데이터 확인
df_review_andar_D2C[df_review_andar_D2C['product_id'].isin(duplicated_product_ids)][['product_id', 'product_name', 'product_url']].drop_duplicates().sort_values('product_id')

,product_id,product_name,product_url
347824,7259,[아울렛] 에어리핏 오버핏 롱슬리브,https://andar.co.kr/product/detail.html?product_no=7259
909794,7259,에어리핏 오버핏 롱슬리브,https://andar.co.kr/product/detail.html?product_no=7259
67512,7297,[아울렛] 에어터치 페이스 숏슬리브 크롭티,https://andar.co.kr/product/detail.html?product_no=7297
925545,7297,에어터치 페이스 숏슬리브 크롭티,https://andar.co.kr/product/detail.html?product_no=7297
144647,8576,[아울렛] 에어리핏 맨즈 폴로 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8576
921273,8576,에어리핏 맨즈 폴로 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8576
412018,8732,[아울렛] 에어로코튼 슬림핏 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8732
917833,8732,에어로코튼 슬림핏 숏슬리브,https://andar.co.kr/product/detail.html?product_no=8732
333333,10768,[아울렛] [워셔블] 니트 플러스 맨즈 숏슬리브,https://andar.co.kr/product/detail.html?product_no=10768
917747,10768,[워셔블] 니트 플러스 맨즈 숏슬리브,https://andar.co.kr/product/detail.html?product_no=10768
363924,10951,[아울렛] 안다르 맨즈 심리스 드로즈,https://andar.co.kr/product/detail.html?product_no=10951
923303,10951,안다르 맨즈 심리스 드로즈,https://andar.co.kr/product/detail.html?product_no=10951

---
# 안다르 무신사 리뷰 데이터

## 1. 전처리

In [156]:
import pandas as pd
import numpy as np

df_review_andar_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_andar_reviews.csv", encoding='utf-8')
display(df_review_andar_mss.head())
display(df_review_andar_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,user_weight,option,helpful,comment_count,has_image,image_urls,survey_json,url
0,2026-04-21 23:09:37,2024-07-09,3297519,릴렉스 에어소프트 요가매트 (8mm),62257472,스타일,5,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,Whg_,0,0,F · 포그 그레이[EJFMT-01LGY],0,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_668cfde61e980.jpg,NaN,https://www.musinsa.com/products/3297519#review_62257472
1,2026-04-21 23:09:37,2024-06-25,3297519,릴렉스 에어소프트 요가매트 (8mm),61262848,스타일,5,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느낌에 손톱자국 잘남아요,엔나짱,0,0,F · 포그 그레이[EJFMT-01LGY],0,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_667abd78371f4.jpg,NaN,https://www.musinsa.com/products/3297519#review_61262848
2,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59417236,스타일,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,183_80,0,0,F · 포레스트 그린[EJFMT-01GRN],0,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_664446e8c0984.jpg,NaN,https://www.musinsa.com/products/3297519#review_59417236
3,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59408897,스타일,5,"아침에 스트레칭 하거나 아이가 닌텐도 링핏 할때도 사용하는데 완전 좋아요,,,",애너벨리33,0,0,F · 포그 그레이[EJFMT-01LGY],1,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_664413a54ba16.jpg,NaN,https://www.musinsa.com/products/3297519#review_59408897
4,2026-04-21 23:09:37,2024-04-19,3297519,릴렉스 에어소프트 요가매트 (8mm),58192969,스타일,5,아기가 따라 운동 하고 폭싱 폭싱 하니까 점프 점프 하고 놀아요 ㅎㅎ,Bajga,0,0,F · 파스텔 민트[EJFMT-01MNT],22,0,True,https://www.musinsa.com/data/estimate/3297519_0/gallery_66222386b7e46.jpg,NaN,https://www.musinsa.com/products/3297519#review_58192969

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   collect_date   7552 non-null   str
 1   review_date    7552 non-null   str
 2   product_id     7552 non-null   int64
 3   product_name   7552 non-null   str
 4   review_no      7552 non-null   int64
 5   review_type    7552 non-null   str
 6   rating         7552 non-null   int64
 7   review_text    7552 non-null   str
 8   author         7552 non-null   str
 9   user_height    7552 non-null   int64
 10  user_weight    7552 non-null   int64
 11  option         7546 non-null   str
 12  helpful        7552 non-null   int64
 13  comment_count  7552 non-null   int64
 14  has_image      7552 non-null   bool
 15  image_urls     3007 non-null   str
 16  survey_json    1 non-null      str
 17  url            7552 non-null   str
dtypes: bool(1), int64(7), str(10)
memory usage: 3.5 MB

None

In [ ]:
# ======================
# 사용할 컬럼만 남기기
# ======================
df_review_andar_mss = df_review_andar_mss.drop(['review_type', 'author', 'comment_count', 'image_urls', 'survey_json'], axis=1, errors='ignore')
df_review_andar_mss.head(3) # (7552, 13)

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
0,2026-04-21 23:09:37,2024-07-09,3297519,릴렉스 에어소프트 요가매트 (8mm),62257472,5,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,0,0,F · 포그 그레이[EJFMT-01LGY],0,True,https://www.musinsa.com/products/3297519#review_62257472
1,2026-04-21 23:09:37,2024-06-25,3297519,릴렉스 에어소프트 요가매트 (8mm),61262848,5,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느낌에 손톱자국 잘남아요,0,0,F · 포그 그레이[EJFMT-01LGY],0,True,https://www.musinsa.com/products/3297519#review_61262848
2,2026-04-21 23:09:37,2024-05-15,3297519,릴렉스 에어소프트 요가매트 (8mm),59417236,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,0,0,F · 포레스트 그린[EJFMT-01GRN],0,True,https://www.musinsa.com/products/3297519#review_59417236

In [166]:
# ======================
# 데이터 타입 통일
# ======================
df_review_andar_mss['collect_date'] = pd.to_datetime(df_review_andar_mss['collect_date'])
df_review_andar_mss['review_date'] = pd.to_datetime(df_review_andar_mss['review_date'])
df_review_andar_mss['product_id'] = df_review_andar_mss['product_id'].astype(int)
df_review_andar_mss['has_image'] = df_review_andar_mss['has_image'].astype(int)

In [167]:
# ===========================
# 파생 컬럼 생성 (year, month)
# ===========================
df_review_andar_mss['year'] = df_review_andar_mss['review_date'].dt.year
df_review_andar_mss['month'] = df_review_andar_mss['review_date'].dt.month

In [168]:
df_review_andar_mss.info()

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  7552 non-null   datetime64[us]
 1   review_date   7552 non-null   datetime64[us]
 2   product_id    7552 non-null   int64
 3   product_name  7552 non-null   str
 4   review_no     7552 non-null   int64
 5   rating        7552 non-null   int64
 6   review_text   7552 non-null   str
 7   user_height   7552 non-null   int64
 8   user_weight   7552 non-null   int64
 9   option        7546 non-null   str
 10  helpful       7552 non-null   int64
 11  has_image     7552 non-null   int64
 12  url           7552 non-null   str
 13  year          7552 non-null   int32
 14  month         7552 non-null   int32
dtypes: datetime64[us](2), int32(2), int64(7), str(4)
memory usage: 2.7 MB

In [169]:
# ===========================
# option 결측치 처리 (0.079%)
# ===========================

# option 컬럼의 결측치 비율 확인
df_review_andar_mss['option'].isna().mean()*100

# 실제 option 컬럼의 값 확인 (6개 행)
pd.set_option('display.max_rows', None) # 행 보이기
df_review_andar_mss[df_review_andar_mss['option'].isna()] #.value_counts(dropna=False)

# >>>>> 제품 아이디 & 옵션 1:1 매칭이 아니라 대체값 없이 결측 유지 <<<<<

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url,year,month
1681,2026-04-21 23:10:53,2024-07-07,3414542,[2 PACK] 에어쿨링 지니 시그니처 레깅스 (9부),62129779,5,쫀쫀하고 사이즈도 딱 맞고 운동할때 너무 좋은거 같아요,159,54,NaN,0,0,https://www.musinsa.com/products/3414542#review_62129779,2024,7
2170,2026-04-21 23:11:24,2024-07-11,3351097,[2 PACK] 비 프리 올데이 크롭탑,62114238,5,이게 가장 입고 벗기 편하고 여러번 세탁해도 큰변형없이 오래입을 수 있어서 재구매합니다!,176,70,NaN,0,1,https://www.musinsa.com/products/3351097#review_62114238,2024,7
2174,2026-04-21 23:11:24,2024-07-06,3351097,[2 PACK] 비 프리 올데이 크롭탑,62114264,5,이게 가장 입고 벗기 편하고 여러번 세탁해도 큰변형없이 오래입을 수 있어서 재구매합니다!,0,0,NaN,0,0,https://www.musinsa.com/products/3351097#review_62114264,2024,7
2588,2026-04-21 23:11:51,2024-07-07,2722562,릴렉스 폼롤러 II (L),62130071,5,잘 받았습니다. 저렴하게 잘 구입하였습니다. 디자인도 마음에 들고 좋아요,0,0,NaN,0,0,https://www.musinsa.com/products/2722562#review_62130071,2024,7
3810,2026-04-21 23:13:32,2024-07-07,4225369,에어스트 밴딩 3.5부 쇼츠,62121303,5,"색감도 진하고, 마감처리도 어디하나 문제가 없네요! 특히 재질이 너무 부드럽고 쫀쫀해서 좋은거 같아여!",161,48,NaN,1,1,https://www.musinsa.com/products/4225369#review_62121303,2024,7
3811,2026-04-21 23:13:32,2024-07-07,4225369,에어스트 밴딩 3.5부 쇼츠,62121261,5,"여름맞이 숏한 팬츠중에 안다르 제품 추찬받아서 구매해봤는데, 너무 이쁘네요.",161,48,NaN,0,0,https://www.musinsa.com/products/4225369#review_62121261,2024,7

In [ ]:
# ===========================
# 컬럼 이름 변환
# ===========================
df_review_andar_mss = df_review_andar_mss.rename(columns={
    'review_no': 'review_id',
    'review_text' : 'content',
    'option' : 'purchase_option',
    'helpful' : 'helpful_count',
    'url' : 'product_url'
})

# 컬럼명 잘 변환된 거 확인 완료!
# Index(['collect_date', 'review_date', 'product_id', 'product_name',
#        'review_id', 'rating', 'review_body', 'user_height', 'user_weight',
#        'purchase_option', 'helpful_count', 'has_image', 'product_url', 'year',
#        'month'],
#       dtype='str')

In [172]:
# ===========================
# 컬럼 추가
# ===========================
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'review_body', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_andar_mss.columns:
        df_review_andar_mss[col] = None

# ===========================
# 컬럼 순서 정리
# ===========================
df_review_andar_mss = df_review_andar_mss[required_columns]

In [188]:
# ===========================
# 데이터 값 확인
# ===========================
df_review_andar_mss['collect_date'].value_counts(dropna=False)
df_review_andar_mss['platform'].value_counts(dropna=False)
df_review_andar_mss['user_height_group'].value_counts(dropna=False)
df_review_andar_mss['user_weight_group'].value_counts(dropna=False)
df_review_andar_mss['product_url'].value_counts(dropna=False).sort_values(ascending=False).head(10)

# collect_date 시간 제거해야 함
# platform 데이터 => 무신사 
# user_height_group => 세그먼트 해야 함
# user_weight_group => 세그먼트 해야 함

product_url
https://www.musinsa.com/products/3297519#review_62257472    1
https://www.musinsa.com/products/4505859#review_76474830    1
https://www.musinsa.com/products/4505859#review_72903531    1
https://www.musinsa.com/products/4505859#review_73883466    1
https://www.musinsa.com/products/4505859#review_74114809    1
https://www.musinsa.com/products/4505859#review_74258060    1
https://www.musinsa.com/products/4505859#review_74323158    1
https://www.musinsa.com/products/4505859#review_74828388    1
https://www.musinsa.com/products/4505859#review_74828416    1
https://www.musinsa.com/products/4505859#review_74829308    1
Name: count, dtype: int64

In [ ]:
# 1) collect_date 시간 제거
df_review_andar_mss['collect_date'] = pd.to_datetime(df_review_andar_mss['collect_date']) # dtype('<M8[us]')
df_review_andar_mss['collect_date'] = df_review_andar_mss['collect_date'].dt.normalize() # 시간 제거

In [ ]:
# 2) platform 데이터 => 무신사
df_review_andar_mss['platform'] = '무신사' # 확인 완료

In [225]:
# 3-1) user_height, user_weight == 0 => NaN으로 변경
df_review_andar_mss['user_height'] = df_review_andar_mss['user_height'].replace(0, np.nan)
df_review_andar_mss['user_weight'] = df_review_andar_mss['user_weight'].replace(0, np.nan)

In [ ]:
# 3) user_height_group 세그먼트
# 왼 미포함, 오른 포함
height_bins = [0, 139, 144, 149, 154, 159, 164, 169, 174, 179, 184, 189, 999]
height_labels = [
    '139cm 이하',
    '140~144cm',
    '145~149cm',
    '150~154cm',
    '155~159cm',
    '160~164cm',
    '165~169cm',
    '170~174cm',
    '175~179cm',
    '180~184cm',
    '185~189cm',
    '190cm 이상'
]
df_review_andar_mss['user_height_group'] = pd.cut(df_review_andar_mss['user_height'], bins=height_bins, labels=height_labels, right=True)

# 데이터 확인 완료

In [226]:
# user_height_group => NaN 데이터 생긴 이유 확인
a = df_review_andar_mss[df_review_andar_mss['user_height_group'].isna()][['user_height', 'user_height_group']]
a.value_counts(dropna=False)

# >>>>> 'user_height', 'user_weight' 데이터가 없어서 NaN이 생김 = 정상 <<<<<

user_height  user_height_group
NaN          nan                  2091
             139cm 이하                0
             140~144cm               0
             145~149cm               0
             150~154cm               0
             155~159cm               0
             160~164cm               0
             165~169cm               0
             170~174cm               0
             175~179cm               0
             180~184cm               0
             185~189cm               0
             190cm 이상                0
Name: count, dtype: int64

In [ ]:
# 4) user_weight_group 세그먼트
weight_bins = [0, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 999]
weight_labels = [
    '44kg 이하',
    '45~49kg',
    '50~54kg',
    '55~59kg',
    '60~64kg',
    '65~69kg',
    '70~74kg',
    '75~79kg',
    '80~84kg',
    '85~89kg',
    '90kg 이상'
]
df_review_andar_mss['user_weight_group'] = pd.cut(df_review_andar_mss['user_weight'], bins=weight_bins, labels=weight_labels, right=True)

# 데이터 확인 완료

In [227]:
# user_weight_group => NaN 데이터 생긴 이유 확인
b = df_review_andar_mss[df_review_andar_mss['user_weight_group'].isna()][['user_weight', 'user_weight_group']]
b.value_counts(dropna=False)

# >>>>> 'user_height', 'user_weight' 데이터가 없어서 NaN이 생김 = 정상 <<<<<

user_weight  user_weight_group
NaN          nan                  2101
             44kg 이하                 0
             45~49kg                 0
             50~54kg                 0
             55~59kg                 0
             60~64kg                 0
             65~69kg                 0
             70~74kg                 0
             75~79kg                 0
             80~84kg                 0
             85~89kg                 0
             90kg 이상                 0
Name: count, dtype: int64

In [232]:
# ======================
# 데이터 타입 통일
# ======================
df_review_andar_mss['platform'] = df_review_andar_mss['platform'].astype('category')
df_review_andar_mss['purchase_option'] = df_review_andar_mss['purchase_option'].astype('category')
df_review_andar_mss['user_weight'] = pd.to_numeric(df_review_andar_mss['user_weight'], errors='coerce').astype('Int64')
df_review_andar_mss['user_height'] = pd.to_numeric(df_review_andar_mss['user_height'], errors='coerce').astype('Int64')

In [230]:
df_review_andar_mss['user_weight'].isna().mean()*100

np.float64(27.82044491525424)

In [233]:
# ===========================
# 실시간 데이터 확인
# ===========================
df_review_andar_mss.info()
df_review_andar_mss.head(30)

<class 'pandas.DataFrame'>
RangeIndex: 7552 entries, 0 to 7551
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       7552 non-null   datetime64[us]
 1   platform           7552 non-null   category
 2   review_id          7552 non-null   int64
 3   product_id         7552 non-null   int64
 4   product_name       7552 non-null   str
 5   review_date        7552 non-null   datetime64[us]
 6   year               7552 non-null   int32
 7   month              7552 non-null   int32
 8   content            7552 non-null   str
 9   rating             7552 non-null   int64
 10  helpful_count      7552 non-null   int64
 11  has_image          7552 non-null   int64
 12  purchase_option    7546 non-null   category
 13  user_height        5461 non-null   Int64
 14  user_weight        5451 non-null   Int64
 15  user_height_group  5461 non-null   category
 16  user_weight_group  5451 non-null   category
 17  product_url        7552 non-null   str
dtypes: Int64(2), category(4), datetime64[us](2), int32(2), int64(5), str(3)
memory usage: 2.5 MB

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,무신사,62257472,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-07-09,2024,7,색깔이 그레이에 초록 한스푼 넣은 느낌이에요 디자인이 깔끔해서 너무 맘에 듭니다 두께가 딱이어서 운동하는데 편할 거 같아요!,5,0,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_62257472
1,2026-04-21,무신사,61262848,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-06-25,2024,6,뭔가 바닥 매트 같은 소재여서 로고나 디자인은 예쁘나 조금 아쉽.. 뻐덩뻐덩 한 느낌에 손톱자국 잘남아요,5,0,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_61262848
2,2026-04-21,무신사,59417236,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-05-15,2024,5,안다르 매트 너무 부드럽고 색감도 이뻐요 재질 좋은거쓰시는듯,5,0,1,F · 포레스트 그린[EJFMT-01GRN],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_59417236
3,2026-04-21,무신사,59408897,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-05-15,2024,5,"아침에 스트레칭 하거나 아이가 닌텐도 링핏 할때도 사용하는데 완전 좋아요,,,",5,1,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_59408897
4,2026-04-21,무신사,58192969,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-04-19,2024,4,아기가 따라 운동 하고 폭싱 폭싱 하니까 점프 점프 하고 놀아요 ㅎㅎ,5,22,1,F · 파스텔 민트[EJFMT-01MNT],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_58192969
5,2026-04-21,무신사,56437260,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-03-06,2024,3,아주 좋습니다 여기꺼 좋다고 그러던데 한번 써볼게요,5,0,1,F · 로즈 핑크[EJFMT-01IPK],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_56437260
6,2026-04-21,무신사,56421311,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-03-05,2024,3,좋아요.색감도 좋고 크게 냄새도 나지 않는 것 같아요. 아이와 함께 하려고 구매했네요. 빠른배송에 포장도 꼼꼼하고 좋아요,5,1,1,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_56421311
7,2026-04-21,무신사,56421194,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-03-05,2024,3,마음에 들어요. 빠른 배송에 상품도 마음에 너무 들어요. 그런데 스크레치에는 취약한것같아서 그것은 아쉽네요,5,0,1,F · 페털 라일락[EJFMT-01LVD],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_56421194
8,2026-04-21,무신사,56323514,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-03-03,2024,3,그냥 일반 러그에서 스트레칭 할때는 항상 꼬리뼈가 너무 아팠는데 확실히 요가매트 하나는 집이 있는게 좋은것 같아용 푹신하고 너무 마음에 드는데 고양이도 좋아하네요! ㅋㅋ 컬러도 진짜 너무 예쁘고 두께도 딱좋아요 안다르는 처음인데 안다르에서 요가복도 몇개 구매해볼까봐오,5,5,1,F · 파스텔 민트[EJFMT-01MNT],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_56323514
9,2026-04-21,무신사,54718407,3297519,릴렉스 에어소프트 요가매트 (8mm),2024-02-20,2024,2,생각보다 폭신하지않고 딱딱하네요. 단단해서 오래 사용할 수 있지만 지난번에 사용했던거는 폭신폭신해서 좋았는데... 좀 아쉽네요,4,1,1,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_54718407
10,2026-04-21,무신사,53511507,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-12-22,2023,12,제 잠옷 색과 깔맞춤으로 샀어용 ㅎㅎ 양면이라 좋고 저는 저 안다르 이름 써있는것도 맘에 들어용! 가끔 집에서 스트레칭 할때 유용하게 쓰고있습니당,5,3,1,F · 포레스트 그린[EJFMT-01GRN],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_53511507
11,2026-04-21,무신사,51291369,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-11-18,2023,11,적당히 딱딱하면서 겉은 부드러운 재질입니다 컬러도 예뻐요~,5,0,1,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_51291369
12,2026-04-21,무신사,51270312,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-11-17,2023,11,너무 좋습니다 추천해요 이뻐요 언능 구매하세요,5,0,1,F · 무드 네이비[EJFMT-01NAV],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_51270312
13,2026-04-21,무신사,49081428,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-10-03,2023,10,소재가 좋아서 그런지 냄새도 안나고 안 미끌리고 좋아요,5,0,1,F · 페털 라일락[EJFMT-01LVD],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_49081428
14,2026-04-21,무신사,48805903,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-09-26,2023,9,8mm가 은근 두꺼워서 위에서 무슨 자세를 해도 아프지 않고 좋습니다! 냄새도 거의 안나고 좋네요!,5,3,1,F · 피치 코랄[EJFMT-01COR],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_48805903
15,2026-04-21,무신사,47840062,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-09-01,2023,9,운동열심히 하려고 구매했습니다 운동 화이팅입니다!!,5,0,1,F · 로즈 핑크[EJFMT-01IPK],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_47840062
16,2026-04-21,무신사,47840025,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-09-01,2023,9,좋습니다 운동 열심히 하께요 좋습니다 운동파이팅,5,3,1,F · 페털 라일락[EJFMT-01LVD],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_47840025
17,2026-04-21,무신사,47775159,3297519,릴렉스 에어소프트 요가매트 (8mm),2023-08-30,2023,8,"색이이뻐요,,, 그러나 품질이 아쉽내요. 첨엔 부들하고 색도 이뻐서 만족햇는데 하루 거실에 깔아놓고 앉아잇으니 얼룩도 잘 생기고 재질이 좀 약해서 오래 쓸만한 건 아닌거같아요. 그냥 전문가용으로 튼튼한걸사면 일정한품질로 쓸것같은데 삼만원 안되개 사서 그냥 둡니다. 두께는 도톰하고 폭신한편이애요. 필테센터에선 얇고 단단한 매트를 써서 비교되서 그런거같아요. 오래 펼쳐놓을만한 매트는 아닌거같아요. 그냥 초보자가 가끔 펼쳐서 운동할만한 간단한 매트. 디쟌은 이뻣어요. 보관시에 두번 접어놧더니 모양잡혀서 잘 말아두셔야할듯.",2,2,1,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_47775159
18,2026-04-21,무신사,83678231,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-04-14,2026,4,새 상품인데도 고무냄새가 하나도 나지 않아 좋아요 이곳저곳 가격비교를 많이 했는데 무신사가 가장 저렴했습니다. 사진이 어둡게 나왔지만 로즈핑크 색상도 예쁘고 만족도 높아요,5,0,1,F · 로즈 핑크[EJFMT-01IPK],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83678231
19,2026-04-21,무신사,83576706,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-04-10,2026,4,가격대가 있는 편이지만 색감이 예쁘고 품질이 좋은 것 같아요,5,0,1,F · 로즈 핑크[EJFMT-01IPK],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83576706
20,2026-04-21,무신사,83333478,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-31,2026,3,마음에 쏙 들어요. 배송도 빨리와서 더 좋고 마음에 드네요.,5,0,0,F · 페털 라일락[EJFMT-01LVD],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83333478
21,2026-04-21,무신사,83298550,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-29,2026,3,말랑말랑 폭신하고 보관하기에도 용이합니다 굿굿,5,0,0,F · 로즈 핑크[EJFMT-01IPK],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83298550
22,2026-04-21,무신사,83283280,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-28,2026,3,핑크색이라 이뻐서 좋아요! 안다르라 믿고 주문했는데 안정감있어서 잘 쓰고있어요~ 미끄러지않아서 스트레칭하기에 좋아요,5,0,1,F · 블라썸 핑크[EJFMT-01PNK],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83283280
23,2026-04-21,무신사,83220753,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-25,2026,3,좋네여 폭신하고 미끄러지지않아좋아요~ 맘에듭니다,5,0,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83220753
24,2026-04-21,무신사,83098662,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-20,2026,3,공홈 보다 할인도 많이되고 배송도 빨랐어요 도톰하니 무릎 안아파서 좋을 것 같아요!! 색깔 고민 많이 했는데 깔끔하니 좋은 것 같아요! 묶을 수 있는 끈이 별도로 구매해야해서 아쉽 ㅠㅠ,5,0,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83098662
25,2026-04-21,무신사,83008563,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-17,2026,3,전에 쓰던 매트는 쿠팡에서 저렴한 것 대충 샀더니 밀리고 늘어나고 해서 사봤는데 안정감있고 좋습니다~!,5,0,1,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_83008563
26,2026-04-21,무신사,82947890,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-14,2026,3,집에서 스트레칭을 하는 일이 많아져서 구매했어요. 색깔도 예쁘고 무릎이나 팔을 사용하는 동작에서도 충분히 쿠션감이 있어서 아프지 않고 좋네요.,5,0,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_82947890
27,2026-04-21,무신사,82897906,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-12,2026,3,좋아요 배송 빠르고 만족합니다 재구매 의사 있어요 굿,5,0,1,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_82897906
28,2026-04-21,무신사,82837607,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-09,2026,3,살짝 딱딱한 감은 있으나 색상도 다양해서 골라 구매하는 재미가 있네요^^,5,0,1,F · 포그 그레이[EJFMT-01LGY],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_82837607
29,2026-04-21,무신사,82830180,3297519,릴렉스 에어소프트 요가매트 (8mm),2026-03-09,2026,3,가격도 좋고 배송도 빠르고 잘산것 같아요. 너무 만족합니다..,5,0,0,F · 클라우드 바이올렛[EJFMT-01VOL],<NA>,<NA>,NaN,NaN,https://www.musinsa.com/products/3297519#review_82830180

In [234]:
df_review_andar_mss_2024 = df_review_andar_mss[df_review_andar_mss['year'] >= 2024]

df_review_andar_mss.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_musinsa_review_final.csv", encoding='utf-8-sig', index=False)
df_review_andar_mss_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/andar_musinsa_review_final_s2024.csv", encoding='utf-8-sig', index=False)