In [4]:
import pandas as pd
import numpy as np

---
# 휠라 네이버스토어 리뷰 데이터

## 1. 전처리

In [1]:
# ===============================
# 데이터 불러오기
# ===============================
import pandas as pd
import numpy as np

df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv")
display(df_review_fila_naverstore.head())

,Unnamed: 0,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,reviewer_id,review_content_class,extra_id,extra_reviewContentClassType,extra_reviewScore,extra_reviewContent,extra_createDate,extra_writerId,extra_productName,extra_productOptionContent,extra_reviewTopics
0,3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,mini******,PHOTO,4.669237e+09,PHOTO,5.0,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,2025-02-24 13:14:50.302000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
1,4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,mini******,PHOTO,4.652212e+09,PHOTO,5.0,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,2025-01-31 13:07:37.398000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
2,5,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,ex****,PHOTO,4.652239e+09,PHOTO,5.0,넘 귀야워요 만족ㅎㅎ,2025-01-31 14:23:34.326000+00:00,ex****,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
3,6,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,youn*******,PHOTO,4.634973e+09,PHOTO,5.0,깜찍합니다.이뿌구요^^,2025-01-03 23:36:57.419000+00:00,youn*******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도""..."
4,7,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,yoon*******,PHOTO,4.944300e+09,PHOTO,4.0,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,2026-04-02 04:45:38.825000+00:00,yoon*******,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,"[{""topicCode"": ""size"", ""topicCodeName"": ""사이즈"",..."

In [2]:
# ===============================
# 필요한 컬럼 선택
# ===============================
df_review_fila_naverstore = df_review_fila_naverstore[[
    'product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'review_content_class', 'extra_productName', 'extra_productOptionContent'
]] # 10개

display(df_review_fila_naverstore.head())
display(df_review_fila_naverstore.info())

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,0.0,2026-04-02 04:45:38.825000+00:00,PHOTO,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   str
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 444.0 KB

None

In [3]:
# ===============================
# review_content_class 변환
# ===============================
df_review_fila_naverstore['review_content_class'].value_counts() # PHOTO, TEXT, VIDEO

# PHOTO, VIDEO = 1
# TEXT = 0
df_review_fila_naverstore['review_content_class'] = df_review_fila_naverstore['review_content_class'].map({
    'PHOTO' : 1,
    'TEXT' : 0,
    'VIDEO' : 1
})

print(df_review_fila_naverstore['review_content_class'].value_counts())
print(df_review_fila_naverstore.info())

review_content_class
1    887
0    390
Name: count, dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 438.2 KB
None

In [4]:
# ===============================
# 데이터 타입 변환
# ===============================
# rating, helpful_count, review_date
df_review_fila_naverstore['rating'] = df_review_fila_naverstore['rating'].astype(int)
df_review_fila_naverstore['helpful_count'] = df_review_fila_naverstore['helpful_count'].astype(int)
df_review_fila_naverstore['review_date'] = pd.to_datetime(df_review_fila_naverstore['review_date']).dt.normalize().dt.tz_localize(None)

print(df_review_fila_naverstore.info())

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: datetime64[us](1), float64(1), int64(4), str(4)
memory usage: 398.3 KB
None

In [5]:
# ===============================
# 파생컬럼 생성 -> year, month
# ===============================
df_review_fila_naverstore['year'] = df_review_fila_naverstore['review_date'].dt.year
df_review_fila_naverstore['month'] = df_review_fila_naverstore['review_date'].dt.month

df_review_fila_naverstore.head(3)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1

In [19]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
 10  year                        1277 non-null   int32
 11  month                       1277 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), str(4)
memory usage: 408.3 KB

In [6]:
# ===============================
# 컬럼명 정리
# ===============================
df_review_fila_naverstore = df_review_fila_naverstore.rename(columns={
    'review_content_class' : 'has_image',
    'extra_productName' : 'product_name',
    'extra_productOptionContent' : 'purchase_option',
    'review_body' : 'content'
})

df_review_fila_naverstore.head(1)

,product_url,product_id,review_id,content,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2

In [7]:
# ===============================
# 없는 컬럼 추가하기
# ===============================
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_naverstore.columns:
        df_review_fila_naverstore[col] = None

df_review_fila_naverstore.head()

,product_url,product_id,review_id,content,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month,collect_date,platform,user_size,user_height,user_weight,user_height_group,user_weight_group
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2,None,None,None,None,None,None,None
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None,None
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None,None
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5,0,2025-01-03,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None,None
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,0,2026-04-02,1,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,2026,4,None,None,None,None,None,None,None

In [8]:
# ===============================
# 컬럼 순서 정리
# ===============================
df_review_fila_naverstore = df_review_fila_naverstore[required_columns]
df_review_fila_naverstore.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,None,None,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,None,None,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,None,None,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940
3,None,None,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다.이뿌구요^^,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940
4,None,None,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,0,1,색상: Beige / 사이즈: 220,None,None,None,None,None,https://brand.naver.com/fila/products/11293482675

In [25]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       0 non-null      object
 1   platform           0 non-null      object
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   content            1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        1277 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), object(6), str(4)
memory usage: 468.1+ KB

In [9]:
# ===============================
# 이상치 확인
# ===============================
df_review_fila_naverstore['platform'].value_counts(dropna=False)

platform
None    1277
Name: count, dtype: int64

In [10]:
# ===============================
# 'platform' 데이터 '네이버스토어'로 넣기
# ===============================
df_review_fila_naverstore['platform'] = '네이버스토어'
df_review_fila_naverstore['platform'].value_counts()

platform
네이버스토어    1277
Name: count, dtype: int64

In [11]:
# ===============================
# review_id 중복 확인
# ===============================
df_review_fila_naverstore['review_id'].duplicated().sum()

np.int64(0)

In [12]:
# ===============================
# category 타입으로 변환
# ===============================
df_review_fila_naverstore['platform'] = df_review_fila_naverstore['platform'].astype('category')
df_review_fila_naverstore['purchase_option'] = df_review_fila_naverstore['purchase_option'].astype('category')

In [13]:
# ===============================
# collect_date 컬럼에 데이터 넣기 => '2026-04-21'로 넣기
# ===============================
df_review_fila_naverstore['collect_date'] = '2026-04-21'
df_review_fila_naverstore['collect_date'] = pd.to_datetime(df_review_fila_naverstore['collect_date'])

In [14]:
display(df_review_fila_naverstore.head(3))
print(df_review_fila_naverstore.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,네이버스토어,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,2026-04-21,네이버스토어,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,2026-04-21,네이버스토어,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,None,https://brand.naver.com/fila/products/10769719940

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       1277 non-null   datetime64[us]
 1   platform           1277 non-null   category
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   content            1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   category
 13  user_size          0 non-null      object
 14  user_height        0 non-null      object
 15  user_weight        0 non-null      object
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        1277 non-null   str
dtypes: category(2), datetime64[us](2), float64(1), int32(2), int64(4), object(5), str(3)
memory usage: 437.0+ KB
None

In [15]:
# ===============================
# 저장하기
# ===============================
df_review_fila_naverstore_2024 = df_review_fila_naverstore[df_review_fila_naverstore['year'] >= 2024]

df_review_fila_naverstore.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_naverstore_review_final.csv", encoding='utf-8-sig', index=False)
df_review_fila_naverstore_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_naverstore_review_final_s2024.csv", encoding='utf-8-sig', index=False)

---
# 휠라 자사몰 리뷰 데이터

## 1. 전처리

In [16]:
import pandas as pd

In [18]:
# ===============================
# 데이터 불러오기
# ===============================
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_final_unique_260425.csv", encoding='utf-8')
display(df_review_fila_D2C.head(1))

df_product_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/products/fila_snapshot_master_260422.csv", encoding='utf-8')
display(df_product_fila_D2C.head(1))

,review_id,collect_date,post_date,platform,brand,search_keyword,reviewer_id,content,source_url,rating,helpful_count,purchased_option,has_image
0,110919,2026-04-23,2024-09-11,자사몰리뷰,휠라,1100fs253od03x012217,amy****,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,https://www.fila.co.kr/product/1100fs253od03x0...,5,1,NaN,1

,category1,category2,category3,collect_date,brand,product_id,product_name,product_type,category,gender,original_price,discount_price,color_count,raw_colors,review_count,launch_year,launch_season
0,상의,긴팔티셔츠,일반,2026-04-20,FILA,1100fs261rl01x001001,베이직 긴팔 티셔츠,의류,긴팔,공용,49900,49900,3,블랙,1,2026,SPRING

In [19]:
print(df_review_fila_D2C.info())
display(df_review_fila_D2C.head())

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_id         10355 non-null  int64
 1   collect_date      10355 non-null  str
 2   post_date         10355 non-null  str
 3   platform          10355 non-null  str
 4   brand             10355 non-null  str
 5   search_keyword    10355 non-null  str
 6   reviewer_id       10355 non-null  str
 7   content           10355 non-null  str
 8   source_url        10355 non-null  str
 9   rating            10355 non-null  int64
 10  helpful_count     10355 non-null  int64
 11  purchased_option  1655 non-null   str
 12  has_image         10355 non-null  int64
dtypes: int64(4), str(9)
memory usage: 4.2 MB
None

,review_id,collect_date,post_date,platform,brand,search_keyword,reviewer_id,content,source_url,rating,helpful_count,purchased_option,has_image
0,110919,2026-04-23,2024-09-11,자사몰리뷰,휠라,1100fs253od03x012217,amy****,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,https://www.fila.co.kr/product/1100fs253od03x0...,5,1,NaN,1
1,139596,2026-04-23,2026-03-22,자사몰리뷰,휠라,1100fs261tn02x001660,eui****,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,10,사이즈:250,1
2,128715,2026-04-23,2025-10-07,자사몰리뷰,휠라,1100fs253od03x012260,yun****,"""실물이 훨씬 예뻐요"", ""어떤 룩에도 잘 매치되어서 활용도가 높습니다.""",https://www.fila.co.kr/product/1100fs253od03x0...,5,0,NaN,0
3,139042,2026-04-23,2026-03-15,자사몰리뷰,휠라,1100fs261tn02x001660,Tim****,"""킹 리차드"" 영화에서 나왔던 테니스 선수들의 필라 스포츠 웨어들을 보며 필라의 클...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,3,사이즈:275,1
4,141366,2026-04-23,2026-03-31,자사몰리뷰,휠라,1100fs261tn02x001660,lee****,"""휠라 스피드서브 2.0은 견고한 '힐 카운터' 설계 덕분에 베이스라인에서의 격렬한...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,2,사이즈:265,1

In [20]:
# ===============================
# 필요한 컬럼 선택
# ===============================

df_review_fila_D2C = df_review_fila_D2C[[
    'review_id', 'collect_date', 'post_date', 'platform', 'search_keyword', 'content', 'source_url', 'rating', 'helpful_count', 'purchased_option', 'has_image'
]] # 11개

display(df_review_fila_D2C.head(3))
display(df_review_fila_D2C.info())

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image
0,110919,2026-04-23,2024-09-11,자사몰리뷰,1100fs253od03x012217,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,https://www.fila.co.kr/product/1100fs253od03x0...,5,1,NaN,1
1,139596,2026-04-23,2026-03-22,자사몰리뷰,1100fs261tn02x001660,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,10,사이즈:250,1
2,128715,2026-04-23,2025-10-07,자사몰리뷰,1100fs253od03x012260,"""실물이 훨씬 예뻐요"", ""어떤 룩에도 잘 매치되어서 활용도가 높습니다.""",https://www.fila.co.kr/product/1100fs253od03x0...,5,0,NaN,0

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   review_id         10355 non-null  int64
 1   collect_date      10355 non-null  str
 2   post_date         10355 non-null  str
 3   platform          10355 non-null  str
 4   search_keyword    10355 non-null  str
 5   content           10355 non-null  str
 6   source_url        10355 non-null  str
 7   rating            10355 non-null  int64
 8   helpful_count     10355 non-null  int64
 9   purchased_option  1655 non-null   str
 10  has_image         10355 non-null  int64
dtypes: int64(4), str(7)
memory usage: 3.8 MB

None

In [21]:
# ===============================
# merge 전 product_id 매칭 확인하기
# ===============================
# 제품 리스트의 product_id
product_ids = set(df_product_fila_D2C['product_id'])

# 리뷰 데이터의 search_keyword
search_keywords = set(df_review_fila_D2C['search_keyword'])

# 매칭 확인
matched = product_ids & search_keywords
unmatched = search_keywords - product_ids

print(f"매칭되는 값: {len(matched)}개")
print(f"매칭 안 되는 search_keyword: {len(unmatched)}개")
print(unmatched)

매칭되는 값: 785개
매칭 안 되는 search_keyword: 0개
set()

In [22]:
# =========================================
# 제품 데이터에서 product_name, raw_colors 추가
# =========================================
df_review_fila_D2C = df_review_fila_D2C.merge(
    df_product_fila_D2C[['product_id', 'product_name', 'raw_colors']],  # 필요한 컬럼만 선택
    left_on='search_keyword',
    right_on='product_id',
    how='left'  # 리뷰 데이터 기준으로 merge
)

df_review_fila_D2C.head(2)

# merge 확인
# df_review_fila_D2C['product_id'].isna().sum() =>>>>>> product_id => null 없음
# df_review_fila_D2C[df_review_fila_D2C['search_keyword'] != df_review_fila_D2C['product_id']] =>>>>>> 'search_keyword'와 'product_id'가 잘 매칭 됐는지 확인 완료!
# df_product_fila_D2C['raw_colors'].isna().sum() =>>>>>>>>>> raw_colors 원래 null 값 있었는지 확인 완료!

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,product_id,product_name,raw_colors
0,110919,2026-04-23,2024-09-11,자사몰리뷰,1100fs253od03x012217,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,https://www.fila.co.kr/product/1100fs253od03x0...,5,1,NaN,1,1100fs253od03x012217,<차정원 착용> 휠라 에샤페 LX 브릭,브라운
1,139596,2026-04-23,2026-03-22,자사몰리뷰,1100fs261tn02x001660,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,10,사이즈:250,1,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,핑크

In [23]:
# =========================================
# raw_colors + purchased_option
# =========================================
import numpy as np

df_review_fila_D2C['purchase_option_combined'] = np.where(
    df_review_fila_D2C['purchased_option'].isna(),
    
    # 1) purchased_option이 NaN이면 → raw_colors 그대로
    df_review_fila_D2C['raw_colors'],
    
    # 2) purchased_option이 있으면
    np.where(
        df_review_fila_D2C['raw_colors'].isna(),
        
        # raw_colors도 NaN이면 → purchased_option만
        df_review_fila_D2C['purchased_option'],
        
        # 둘 다 있으면 → 합치기
        df_review_fila_D2C['purchased_option'] + ' / 컬러:' + df_review_fila_D2C['raw_colors']
    )
)

pd.set_option('display.max_rows', None)
df_review_fila_D2C['purchase_option_combined'].value_counts(dropna=False)

purchase_option_combined
블랙                                   2350
그레이                                  1570
브라운                                  1012
화이트                                   636
베이지                                   623
그린                                    417
핑크                                    330
NaN                                   230
블루                                    199
라이트멜란지                                189
크림                                    138
퍼플                                    102
더스티그린                                 102
페일블루                                   82
레드                                     79
우드                                     72
옐로우                                    66
다크레드                                   63
라이트베이지                                 55
민트                                     50
오트밀                                    50
드라이로즈                                  37
라이트브라운                                 37
내추럴베이지                                 35
페일베이지                                  33
인디안핑크                                  29
다크베이지                                  27
오렌지                                    23
사이즈:240 / 컬러:그레이                       21
컬러:001 / 사이즈:000(Free) / 컬러:화이트        17
사이즈:095                                14
민트, 블루                                 12
컬러:001 / 사이즈:000(Free) / 컬러:블랙         12
사이즈:240 / 컬러:화이트                       12
사이즈:245 / 컬러:베이지                       11
사이즈:100(L) / 컬러:블랙                     11
사이즈:270 / 컬러:화이트                       10
사이즈:250 / 컬러:그레이                       10
사이즈:95(M) / 컬러:블랙                      10
사이즈:95(M) / 컬러:핑크                      10
사이즈:000(Free) / 컬러:블랙                  10
페일핑크                                    9
사이즈:095 / 컬러:라이트멜란지                     9
사이즈:235 / 컬러:그레이                        9
사이즈:105                                 9
사이즈:105(XL) / 컬러:블랙                     9
사이즈:240 / 컬러:베이지                        9
오프화이트                                   8
사이즈:240 / 컬러:핑크                         8
사이즈:270 / 컬러:핑크                         8
사이즈:250 / 컬러:화이트                        8
사이즈:100(L) / 컬러:베이지                     8
사이즈:235 / 컬러:블랙                         8
사이즈:235 / 컬러:베이지                        8
사이즈:240 / 컬러:블랙                         8
사이즈:090                                 8
다크그린                                    8
사이즈:265 / 컬러:화이트                        7
사이즈:L(100) / 컬러:블루                      7
사이즈:95(M) / 컬러:그린                       7
더스트그린                                   7
사이즈:235 / 컬러:핑크                         7
사이즈:250 / 컬러:블랙                         7
사이즈:230 / 컬러:핑크                         7
사이즈:250 / 컬러:핑크                         6
사이즈:90(S) / 컬러:블랙                       6
사이즈:255 / 컬러:그레이                        6
퍼플리시블루                                  6
사이즈:XL(105) / 컬러:블랙                     6
사이즈:095 / 컬러:블랙                         6
사이즈:240 / 컬러:001 / 컬러:옐로우               6
사이즈:WM(W80) / 컬러:블랙                     6
사이즈:230 / 컬러:그레이                        6
사이즈:090 / 컬러:화이트                        6
사이즈:90(S) / 컬러:핑크                       6
size:95(M) / 컬러:블랙                      6
사이즈:100 / 컬러:블랙                         6
사이즈:265 / 컬러:핑크                         5
사이즈:245 / 컬러:219 / 컬러:브라운               5
사이즈:95(M) / 컬러:베이지                      5
사이즈:280 / 컬러:화이트                        5
사이즈:275 / 컬러:화이트                        5
컬러:150 / 사이즈:000(Free) / 컬러:화이트         5
사이즈:000(Free) / 컬러:블루                   5
size:000(Free) / 컬러:화이트                 5
사이즈:90(S) / 컬러:그린                       5
사이즈:270 / 컬러:001 / 컬러:블랙                5
사이즈:WM(W90) / 컬러:블루                     5
사이즈:90(S) / 컬러:화이트                      5
size:000(Free) / 컬러:그린                  5
사이즈:240 / 컬러:219 / 컬러:브라운               5
사이즈:100(L) / 컬러:화이트                     5
사이즈:230 / 컬러:블랙                         5
사이즈:L(90) / 컬러:블랙                       5
사이즈:95(M) / 컬러:그레이                      5
사이즈:240 / 컬러:브라운                        5
사이즈:245 / 컬러:그레이                        5
사이즈:245 / 컬러:블랙                         5
사이즈:000(Free) / 컬러:370 / 컬러:그린          5
컬러:001 / 사이즈:M(085) / 컬러:블랙             5
사이즈:000 / 컬러:BLK / 컬러:블랙                4
사이즈:240 / 컬러:001 / 컬러:블랙                4
사이즈:260 / 컬러:핑크                         4
플럼                                      4
사이즈:XL(105) / 컬러:블루                     4
사이즈:260 / 컬러:블루                         4
사이즈:000(Free) / 컬러:217 / 컬러:블랙          4
사이즈:245 / 컬러:화이트                        4
사이즈:WM(W90) / 컬러:브라운                    4
사이즈:260 / 컬러:블랙                         4
사이즈:100(L) / 컬러:핑크                      4
사이즈:90(S) / 컬러:크림                       4
사이즈:100(L) / 컬러:그린                      4
사이즈:105(XL) / 컬러:그린                     4
사이즈:260 / 컬러:001 / 컬러:블랙                4
사이즈:095 / 컬러:페일베이지                      4
사이즈:090 / 컬러:BLK / 컬러:블랙                4
사이즈:L(100) / 컬러:화이트                     4
사이즈:100 / 컬러:BLK / 컬러:블랙                4
사이즈:WM(W90) / 컬러:화이트                    4
사이즈:235 / 컬러:화이트                        4
사이즈:WM(W90) / 컬러:레드                     4
size:105(XL) / 컬러:블랙                    4
사이즈:105(XL) / 컬러:베이지                    4
사이즈:000(Free) / 컬러:화이트                  4
사이즈:105 / 컬러:BLK / 컬러:블랙                4
사이즈:230 / 컬러:화이트                        4
사이즈:230 / 컬러:베이지                        4
사이즈:260 / 컬러:화이트                        3
사이즈:270 / 컬러:그레이                        3
사이즈:280 / 컬러:핑크                         3
사이즈:290 / 컬러:화이트                        3
스카이블루                                   3
사이즈:WS(W85) / 컬러:화이트                    3
사이즈:280 / 컬러:블랙                         3
사이즈:245 / 컬러:001 / 컬러:그린                3
사이즈:275 / 컬러:브라운                        3
사이즈:090 / 컬러:LML / 컬러:라이트멜란지            3
컬러:001 / 사이즈:100(L) / 컬러:그레이            3
사이즈:265 / 컬러:블랙                         3
사이즈:105 / 컬러:DRD / 컬러:다크레드              3
size:240 / 컬러:그레이                       3
사이즈:000(Free) / 컬러:217 / 컬러:화이트         3
사이즈:245 / 컬러:핑크                         3
사이즈:100 / 컬러:NBG / 컬러:내추럴베이지            3
사이즈:105(XL)                             3
size:000(Free) / 컬러:블랙                  3
사이즈:95(M) / 컬러:크림                       3
컬러:001 / 사이즈:90(S) / 컬러:크림              3
사이즈:100(L) / 컬러:블루                      3
사이즈:220 / 컬러:그레이                        3
size:105(XL) / 컬러:크림                    3
사이즈:095 / 컬러:LML / 컬러:라이트멜란지            3
사이즈:090 / 컬러:레드                         3
사이즈:245 / 컬러:브라운                        3
size:260 / 컬러:블랙                        3
사이즈:090 / 컬러:다크그린                       3
사이즈:105 / 컬러:블랙                         3
사이즈:265 / 컬러:그레이                        3
사이즈:105(XL) / 컬러:핑크                     3
사이즈:240 / 컬러:370 / 컬러:블랙                3
사이즈:095 / 컬러:BLK / 컬러:화이트               3
사이즈:090 / 컬러:DRO / 컬러:드라이로즈             3
사이즈:L(90) / 컬러:블루                       3
size:240 / 컬러:브라운                       3
사이즈:250 / 컬러:베이지                        3
사이즈:250 / 컬러:219 / 컬러:블랙                3
사이즈:095 / 컬러:다크레드                       3
사이즈:235 / 컬러:063 / 컬러:그레이               3
컬러:001 / 사이즈:105(XL) / 컬러:블랙            3
사이즈:235 / 컬러:219 / 컬러:브라운               3
사이즈:240 / 컬러:블루                         3
사이즈:110 / 컬러:BLK / 컬러:블랙                3
사이즈:L(90) / 컬러:그레이                      3
사이즈:000(Free) / 컬러:핑크                   3
사이즈:090 / 컬러:라이트멜란지                     3
사이즈:240 / 컬러:219 / 컬러:베이지               3
사이즈:L(100) / 컬러:블랙                      3
사이즈:225 / 컬러:그레이                        3
사이즈:270 / 컬러:블랙                         3
사이즈:240 / 컬러:옐로우                        3
컬러:001 / 사이즈:XL(95) / 컬러:블랙             3
컬러:032 / 사이즈:90(S) / 컬러:블랙              3
사이즈:090 / 컬러:BLK / 컬러:라이트멜란지            3
사이즈:275 / 컬러:핑크                         2
사이즈:WM / 컬러:블루                          2
사이즈:260 / 컬러:100 / 컬러:화이트               2
컬러:001 / 사이즈:L(100) / 컬러:블랙             2
네이비                                     2
사이즈:270 / 컬러:924 / 컬러:그레이               2
사이즈:000(Free) / 컬러:브라운                  2
사이즈:240 / 컬러:217 / 컬러:브라운               2
사이즈:250 / 컬러:920 / 컬러:블랙                2
사이즈:090 / 컬러:BLK / 컬러:다크그린              2
사이즈:235 / 컬러:219 / 컬러:화이트               2
사이즈:240 / 컬러:031 / 컬러:그레이               2
컬러:150 / 사이즈:000(Free) / 컬러:블랙          2
size:250 / 컬러:브라운                       2
사이즈:245 / 컬러:010 / 컬러:블랙                2
사이즈:255 / 컬러:219 / 컬러:브라운               2
사이즈:100 / 컬러:WHI                        2
사이즈:245 / 컬러:217 / 컬러:핑크                2
사이즈:250 / 컬러:370 / 컬러:브라운               2
사이즈:255 / 컬러:화이트                        2
사이즈:250 / 컬러:001 / 컬러:블랙                2
사이즈:230 / 컬러:001 / 컬러:블랙                2
사이즈:WL(W95) / 컬러:화이트                    2
사이즈:235 / 컬러:001 / 컬러:블랙                2
컬러:031 / 사이즈:90(S)                      2
사이즈:255 / 컬러:031 / 컬러:그레이               2
size:95(M) / 컬러:브라운                     2
사이즈:240 / 컬러:001 / 컬러:화이트               2
사이즈:235 / 컬러:옐로우                        2
사이즈:240 / 컬러:260 / 컬러:베이지               2
사이즈:255 / 컬러:001 / 컬러:화이트               2
사이즈:2XL(110) / 컬러:블랙                    2
사이즈:240 / 컬러:452 / 컬러:블루                2
size:230 / 컬러:블랙                        2
사이즈:XL(95) / 컬러:블랙                      2
사이즈:240 / 컬러:219 / 컬러:그린                2
사이즈:235 / 컬러:001 / 컬러:화이트               2
컬러:234 / 사이즈:000(Free) / 컬러:블랙          2
사이즈:225 / 컬러:블랙                         2
컬러:031 / 사이즈:105(XL) / 컬러:크림            2
컬러:001 / 사이즈:WM(W90) / 컬러:화이트           2
사이즈:255 / 컬러:블랙                         2
컬러:031 / 사이즈:95(M) / 컬러:블랙              2
사이즈:90(S) / 컬러:베이지                      2
사이즈:235 / 컬러:370 / 컬러:화이트               2
사이즈:75A / 컬러:블랙                         2
size:235 / 컬러:블랙                        2
사이즈:100(L) / 컬러:066 / 컬러:핑크             2
컬러:001 / 사이즈:L(100) / 컬러:블루             2
사이즈:235 / 컬러:219 / 컬러:블랙                2
컬러:422 / 사이즈:95(M) / 컬러:블루              2
사이즈:WL(W95) / 컬러:블랙                     2
사이즈:240 / 컬러:001 / 컬러:브라운               2
사이즈:270 / 컬러:001 / 컬러:베이지               2
사이즈:285 / 컬러:블루                         2
사이즈:000 / 컬러:BLK / 컬러:스카이블루             2
사이즈:240 / 컬러:924 / 컬러:그레이               2
컬러:001 / 사이즈:100(L) / 컬러:블랙             2
사이즈:230 / 컬러:920 / 컬러:베이지               2
size:250 / 컬러:베이지                       2
size:230 / 컬러:핑크                        2
사이즈:245 / 컬러:217 / 컬러:브라운               2
사이즈:WS(W85) / 컬러:레드                     2
size:240 / 컬러:베이지                       2
사이즈:245 / 컬러:001 / 컬러:블랙                2
size:105 / 컬러:블랙                        2
사이즈:235 / 컬러:031 / 컬러:그레이               2
사이즈:90(S) / 컬러:370 / 컬러:그린              2
사이즈:255 / 컬러:베이지                        2
사이즈:090 / 컬러:RED / 컬러:화이트               2
사이즈:240 / 컬러:370 / 컬러:그린                2
사이즈:100 / 컬러:LML / 컬러:블랙                2
사이즈:240 / 컬러:102 / 컬러:화이트               2
사이즈:100 / 컬러:페일베이지                      2
사이즈:270 / 컬러:베이지                        2
사이즈:XL(105) / 컬러:화이트                    2
사이즈:230 / 컬러:260 / 컬러:핑크                2
size:100 / 컬러:블랙                        2
사이즈:100 / 컬러:다크레드                       2
사이즈:095 / 컬러:크림                         2
사이즈:95(M) / 컬러:퍼플                       2
사이즈:090 / 컬러:PBE / 컬러:크림                2
사이즈:235 / 컬러:217 / 컬러:옐로우               2
사이즈:230 / 컬러:217 / 컬러:브라운               2
컬러:001 / 사이즈:WS(W75) / 컬러:브라운           2
사이즈:WL(W85) / 컬러:베이지                    2
사이즈:230 / 컬러:219 / 컬러:그린                2
사이즈:290 / 컬러:그레이                        2
사이즈:250 / 컬러:101 / 컬러:화이트               2
사이즈:270 / 컬러:100 / 컬러:화이트               2
사이즈:240 / 컬러:001 / 컬러:그레이               2
사이즈:90(S)                               2
사이즈:235 / 컬러:브라운                        2
사이즈:090 / 컬러:LML / 컬러:화이트               2
size:100(L) / 컬러:블랙                     2
사이즈:255 / 컬러:핑크                         2
사이즈:100 / 컬러:라이트멜란지                     2
size:105(XL)                            2
size:100(L) / 컬러:크림                     2
사이즈:260 / 컬러:370 / 컬러:그린                2
컬러:001 / 사이즈:90(S) / 컬러:화이트             2
사이즈:L(100) / 컬러:레드                      2
컬러:031 / 사이즈:90(S) / 컬러:블랙              2
사이즈:235 / 컬러:001 / 컬러:그린                2
사이즈:095 / 컬러:LML / 컬러:퍼플                2
컬러:001 / 사이즈:95(M) / 컬러:블랙              2
사이즈:100(L) / 컬러:370 / 컬러:그린             2
사이즈:225 / 컬러:219 / 컬러:그린                2
사이즈:090 / 컬러:오렌지                        2
사이즈:245 / 컬러:370 / 컬러:그린                2
사이즈:WL(W95) / 컬러:브라운                    2
사이즈:265 / 컬러:001 / 컬러:화이트               2
사이즈:090 / 컬러:블랙                         2
size:090 / 컬러:레드                        2
사이즈:WS(W85) / 컬러:브라운                    2
사이즈:250 / 컬러:옐로우                        2
사이즈:265 / 컬러:001 / 컬러:블랙                2
사이즈:275 / 컬러:001 / 컬러:블랙                2
사이즈:XL(105) / 컬러:브라운                    2
사이즈:WS(W75) / 컬러:브라운                    2
컬러:472 / 사이즈:XL(105) / 컬러:블루            2
사이즈:240 / 컬러:100 / 컬러:화이트               2
사이즈:090 / 컬러:LML / 컬러:레드                2
컬러:001 / 사이즈:100(L) / 컬러:라이트브라운         2
사이즈:090 / 컬러:DTG / 컬러:드라이로즈             2
사이즈:110 / 컬러:블랙                         2
사이즈:S(090) / 컬러:레드                      2
size:230 / 컬러:그레이                       2
사이즈:WL(W85) / 컬러:블랙                     2
사이즈:240 / 컬러:370 / 컬러:브라운               2
사이즈:240 / 컬러:217 / 컬러:블랙                2
사이즈:270 / 컬러:블루                         2
사이즈:L(100) / 컬러:베이지                     2
사이즈:105(XL) / 컬러:452 / 컬러:블랙            2
사이즈:M(095) / 컬러:블랙                      2
사이즈:000 / 컬러:BLK / 컬러:크림                2
size:245 / 컬러:화이트                       2
사이즈:090 / 컬러:LML / 컬러:블랙                2
사이즈:XL(95) / 컬러:블루                      2
사이즈:095 / 컬러:BLK / 컬러:블랙                2
사이즈:095 / 컬러:BLK / 컬러:라이트베이지            2
size:275 / 컬러:화이트                       1
사이즈:255 / 컬러:032 / 컬러:그레이               1
사이즈:270 / 컬러:브라운                        1
사이즈:285 / 컬러:화이트                        1
size:255 / 컬러:화이트                       1
사이즈:245 / 컬러:734 / 컬러:그린                1
컬러:290 / 사이즈:S(090) / 컬러:블루             1
사이즈:000 / 컬러:OWH / 컬러:스카이블루             1
사이즈:000 / 컬러:브라운                        1
사이즈:095 / 컬러:내추럴베이지                     1
size:245 / 컬러:핑크                        1
컬러:001 / 사이즈:WL(W95) / 컬러:레드            1
사이즈:000 / 컬러:오프화이트                      1
사이즈:000(Free) / 컬러:260 / 컬러:브라운         1
사이즈:240 / 컬러:920 / 컬러:그레이               1
컬러:066 / 사이즈:M(095) / 컬러:블랙             1
사이즈:000 / 컬러:BLK / 컬러:오프화이트             1
사이즈:250 / 컬러:452 / 컬러:그레이               1
사이즈:XL(105) / 컬러:레드                     1
사이즈:270 / 컬러:031 / 컬러:핑크                1
컬러:234 / 사이즈:000(Free) / 컬러:브라운         1
size:240 / 컬러:블랙                        1
컬러:001 / 사이즈:000(Free) / 컬러:브라운         1
컬러:067 / 사이즈:100(L) / 컬러:화이트            1
사이즈:100(L) / 컬러:412 / 컬러:핑크             1
사이즈:280 / 컬러:001 / 컬러:블루                1
컬러:290 / 사이즈:M(095) / 컬러:베이지            1
size:250 / 컬러:그린                        1
사이즈:265 / 컬러:100 / 컬러:블랙                1
size:110(2XL) / 컬러:블랙                   1
size:95(M) / 컬러:라이트브라운                  1
사이즈:250 / 컬러:217 / 컬러:브라운               1
사이즈:WL(W95) / 컬러:블루                     1
사이즈:230 / 컬러:924 / 컬러:베이지               1
컬러:472 / 사이즈:M(095) / 컬러:베이지            1
사이즈:230 / 컬러:260 / 컬러:블랙                1
사이즈:95(M) / 컬러:브라운                      1
사이즈:090 / 컬러:BLK / 컬러:베이지               1
컬러:175 / 사이즈:S(090) / 컬러:퍼플             1
컬러:442 / 사이즈:S(090) / 컬러:블루             1
사이즈:80A / 컬러:LSA / 컬러:페일베이지             1
사이즈:80A / 컬러:PBG / 컬러:페일베이지             1
사이즈:L(90) / 컬러:화이트                      1
사이즈:M(085) / 컬러:블랙                      1
사이즈:250 / 컬러:001 / 컬러:브라운               1
사이즈:225 / 컬러:001 / 컬러:블랙                1
사이즈:80A / 컬러:블랙                         1
컬러:234 / 사이즈:M(095) / 컬러:브라운            1
사이즈:260 / 컬러:924 / 컬러:베이지               1
사이즈:S(080) / 컬러:블랙                      1
size:235 / 컬러:옐로우                       1
사이즈:265 / 컬러:001 / 컬러:브라운               1
사이즈:270 / 컬러:219 / 컬러:베이지               1
사이즈:000 / 컬러:OWH / 컬러:오프화이트             1
사이즈:95(M) / 컬러:217 / 컬러:브라운             1
size:105 / 컬러:내추럴베이지                    1
사이즈:235 / 컬러:219 / 컬러:베이지               1
사이즈:250 / 컬러:217 / 컬러:핑크                1
컬러:001 / 사이즈:100(L) / 컬러:크림             1
size:W85(WS) / 컬러:브라운                   1
사이즈:M(095) / 컬러:화이트                     1
컬러:001 / 사이즈:100(L) / 컬러:화이트            1
size:095 / 컬러:블랙                        1
컬러:001 / 사이즈:90(S)                      1
size:95(M) / 컬러:민트                      1
사이즈:100 / 컬러:라이트베이지                     1
사이즈:크림 WS, 블루 WL / 컬러:브라운               1
사이즈:000(Free) / 컬러:442 / 컬러:블루          1
사이즈:100(L) / 컬러:260 / 컬러:핑크             1
컬러:001 / 사이즈:2XL(100) / 컬러:블랙           1
사이즈:245 / 컬러:001 / 컬러:옐로우               1
사이즈:230 / 컬러:004 / 컬러:베이지               1
사이즈:280 / 컬러:001 / 컬러:화이트               1
사이즈:WXS(W80) / 컬러:레드                    1
사이즈:WS(W75) / 컬러:화이트                    1
사이즈:75A / 컬러:PBG / 컬러:페일베이지             1
사이즈:2XL(110) / 컬러:화이트                   1
사이즈:090 / 컬러:WHI / 컬러:오렌지               1
컬러:650 / 사이즈:95(M) / 컬러:그레이             1
사이즈:95(M) / 컬러:066 / 컬러:그레이             1
컬러:004 / 사이즈:000(Free) / 컬러:그레이         1
사이즈:240 / 컬러:217 / 컬러:옐로우               1
컬러:661 / 사이즈:95(M) / 컬러:그레이             1
컬러:234 / 사이즈:WS(W85) / 컬러:화이트           1
size:100(L) / 컬러:브라운                    1
사이즈:260 / 컬러:260 / 컬러:그린                1
사이즈:090 / 컬러:BLK / 컬러:화이트               1
사이즈:100 / 컬러:LML / 컬러:라이트멜란지            1
사이즈:80A / 컬러:001 / 컬러:블랙                1
컬러:001 / 사이즈:WS(W75) / 컬러:핑크            1
컬러:472 / 사이즈:2XL(110) / 컬러:핑크           1
사이즈:280 / 컬러:블루                         1
사이즈:90(S) / 컬러:452 / 컬러:브라운             1
컬러:001 / 사이즈:XL(105) / 컬러:블루            1
사이즈:260 / 컬러:219 / 컬러:블랙                1
사이즈:095 / 컬러:다크그린                       1
size:090 / 컬러:라이트멜란지                    1
사이즈:280 / 컬러:001 / 컬러:옐로우               1
컬러:001 / 사이즈:M(085) / 컬러:브라운            1
사이즈:255 / 컬러:217 / 컬러:그레이               1
사이즈:270 / 컬러:001 / 컬러:그레이               1
사이즈:245 / 컬러:217 / 컬러:베이지               1
사이즈:90(S) / 컬러:072 / 컬러:그레이             1
사이즈:70B / 컬러:071 / 컬러:그레이               1
사이즈:095 / 컬러:LML / 컬러:레드                1
사이즈:095 / 컬러:오렌지                        1
사이즈:270 / 컬러:050 / 컬러:블랙                1
사이즈:260 / 컬러:200 / 컬러:베이지               1
사이즈:245 / 컬러:218 / 컬러:브라운               1
사이즈:240 / 컬러:031 / 컬러:옐로우               1
size:90(S)                              1
사이즈:250 / 컬러:050 / 컬러:그레이               1
사이즈:WS(W75) / 컬러:핑크                     1
컬러:175 / 사이즈:WM(W90) / 컬러:레드            1
사이즈:270 / 컬러:217 / 컬러:그레이               1
사이즈:240 / 컬러:001 / 컬러:그린                1
컬러:650 / 사이즈:90(S) / 컬러:핑크              1
사이즈:230 / 컬러:217 / 컬러:옐로우               1
사이즈:230 / 컬러:블루                         1
컬러:234 / 사이즈:WS(W85) / 컬러:블루            1
사이즈:265 / 컬러:베이지                        1
사이즈:235 / 컬러:219 / 컬러:핑크                1
사이즈:230 / 컬러:820 / 컬러:오렌지               1
사이즈:230 / 컬러:001 / 컬러:화이트               1
사이즈:275 / 컬러:260 / 컬러:브라운               1
사이즈:270 / 컬러:260 / 컬러:오렌지               1
사이즈:095 / 컬러:IDB / 컬러:블랙                1
사이즈:270 / 컬러:101 / 컬러:화이트               1
사이즈:260 / 컬러:100 / 컬러:브라운               1
사이즈:270 / 컬러:그린                         1
사이즈:100 / 컬러:RED / 컬러:라이트멜란지            1
사이즈:240 / 컬러:063 / 컬러:그레이               1
사이즈:100 / 컬러:MLY / 컬러:딥틸                1
사이즈:235 / 컬러:217 / 컬러:브라운               1
사이즈:220 / 컬러:블랙                         1
size:95(M) / 컬러:크림                      1
컬러:650 / 사이즈:90(S) / 컬러:블랙              1
컬러:650 / 사이즈:95(M) / 컬러:민트, 블루          1
사이즈:095 / 컬러:BLK / 컬러:레드                1
사이즈:105 / 컬러:라이트베이지                     1
사이즈:250 / 컬러:031 / 컬러:그레이               1
사이즈:235 / 컬러:001 / 컬러:브라운               1
사이즈:100 / 컬러:MIT / 컬러:민트                1
사이즈:095 / 컬러:LML / 컬러:블루                1
사이즈:95(M) / 컬러:066 / 컬러:블루              1
사이즈:270 / 컬러:오렌지                        1
사이즈:95(M) / 컬러:613 / 컬러:크림              1
컬러:101 / 사이즈:95(M) / 컬러:민트              1
사이즈:100(L) / 컬러:412 / 컬러:화이트            1
사이즈:240 / 컬러:100 / 컬러:블랙                1

In [24]:
# =========================================
# 데이터 타입 정리
# =========================================
display(df_review_fila_D2C.info())
display(df_review_fila_D2C.head(2))

# collect_date, post_date
df_review_fila_D2C['collect_date'] = pd.to_datetime(df_review_fila_D2C['collect_date']).dt.normalize().dt.tz_localize(None)
df_review_fila_D2C['post_date'] = pd.to_datetime(df_review_fila_D2C['post_date']).dt.normalize().dt.tz_localize(None)

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 10355 non-null  int64
 1   collect_date              10355 non-null  str
 2   post_date                 10355 non-null  str
 3   platform                  10355 non-null  str
 4   search_keyword            10355 non-null  str
 5   content                   10355 non-null  str
 6   source_url                10355 non-null  str
 7   rating                    10355 non-null  int64
 8   helpful_count             10355 non-null  int64
 9   purchased_option          1655 non-null   str
 10  has_image                 10355 non-null  int64
 11  product_id                10355 non-null  str
 12  product_name              10355 non-null  str
 13  raw_colors                10068 non-null  str
 14  purchase_option_combined  10125 non-null  str
dtypes: int64(4), str(11)
memory usage: 4.8 MB

None

,review_id,collect_date,post_date,platform,search_keyword,content,source_url,rating,helpful_count,purchased_option,has_image,product_id,product_name,raw_colors,purchase_option_combined
0,110919,2026-04-23,2024-09-11,자사몰리뷰,1100fs253od03x012217,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,https://www.fila.co.kr/product/1100fs253od03x0...,5,1,NaN,1,1100fs253od03x012217,<차정원 착용> 휠라 에샤페 LX 브릭,브라운,브라운
1,139596,2026-04-23,2026-03-22,자사몰리뷰,1100fs261tn02x001660,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,10,사이즈:250,1,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,핑크,사이즈:250 / 컬러:핑크

In [25]:
# =========================================
# platform 데이터 변경
# =========================================
df_review_fila_D2C['platform'].value_counts()

df_review_fila_D2C['platform'] = df_review_fila_D2C['platform'].map({
    '자사몰리뷰' : '자사몰',
    '무신사리뷰' : '무신사',
    '네이버리뷰' : '네이버스토어',
    '인스타그램' : '인스타그램'
})

# <기존 데이터>
# platform
# 자사몰리뷰    23130
# 무신사리뷰    14663
# 네이버리뷰     8317
# 인스타그램     2134

# <변경 후 데이터>
# 자사몰       23130
# 무신사       14663
# 네이버스토어     8317
# 인스타그램      2134

In [26]:
# =============================================================================
# purchase_option_combined만 남기고 raw_colors, purchased_option는 지우기
# =============================================================================
df_review_fila_D2C = df_review_fila_D2C.drop(['raw_colors', 'purchased_option'], axis=1)

df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 10355 non-null  int64
 1   collect_date              10355 non-null  datetime64[us]
 2   post_date                 10355 non-null  datetime64[us]
 3   platform                  10355 non-null  str
 4   search_keyword            10355 non-null  str
 5   content                   10355 non-null  str
 6   source_url                10355 non-null  str
 7   rating                    10355 non-null  int64
 8   helpful_count             10355 non-null  int64
 9   has_image                 10355 non-null  int64
 10  product_id                10355 non-null  str
 11  product_name              10355 non-null  str
 12  purchase_option_combined  10125 non-null  str
dtypes: datetime64[us](2), int64(4), str(7)
memory usage: 4.3 MB

In [27]:
# ====================================
# post_date 파생컬럼 만들기 year, month
# ====================================
df_review_fila_D2C['year'] = df_review_fila_D2C['post_date'].dt.year
df_review_fila_D2C['month'] = df_review_fila_D2C['post_date'].dt.month

In [28]:
# ======================================================
# search_keyword 컬럼 삭제하기 (product_id와 중복되는 정보)
# ======================================================
df_review_fila_D2C = df_review_fila_D2C.drop(['search_keyword'], axis=1)

In [80]:
df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   review_id                 10355 non-null  int64
 1   collect_date              10355 non-null  datetime64[us]
 2   post_date                 10355 non-null  datetime64[us]
 3   platform                  10355 non-null  str
 4   content                   10355 non-null  str
 5   source_url                10355 non-null  str
 6   rating                    10355 non-null  int64
 7   helpful_count             10355 non-null  int64
 8   has_image                 10355 non-null  int64
 9   product_id                10355 non-null  str
 10  product_name              10355 non-null  str
 11  purchase_option_combined  10125 non-null  str
 12  year                      10355 non-null  int32
 13  month                     10355 non-null  int32
dtypes: datetime64[us](2), int32(2), int64(4), str(6)
memory usage: 4.1 MB

In [29]:
# ==================
# 컬럼명 수정
# ==================
df_review_fila_D2C = df_review_fila_D2C.rename(columns={
    'post_date' : 'review_date',
    'source_url' : 'product_url',
    'purchase_option_combined' : 'purchase_option',
})

df_review_fila_D2C.head(2)

,review_id,collect_date,review_date,platform,content,product_url,rating,helpful_count,has_image,product_id,product_name,purchase_option,year,month
0,110919,2026-04-23,2024-09-11,자사몰,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,https://www.fila.co.kr/product/1100fs253od03x0...,5,1,1,1100fs253od03x012217,<차정원 착용> 휠라 에샤페 LX 브릭,브라운,2024,9
1,139596,2026-04-23,2026-03-22,자사몰,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",https://www.fila.co.kr/product/1100fs261tn02x0...,5,10,1,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,사이즈:250 / 컬러:핑크,2026,3

In [30]:
# ====================================
# 없는 컬럼 추가하기
# ====================================
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_D2C.columns:
        df_review_fila_D2C[col] = None

# 컬럼 순서 정리
df_review_fila_D2C = df_review_fila_D2C[required_columns]

In [31]:
# 확인
df_review_fila_D2C.info()
df_review_fila_D2C.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       10355 non-null  datetime64[us]
 1   platform           10355 non-null  str
 2   review_id          10355 non-null  int64
 3   product_id         10355 non-null  str
 4   product_name       10355 non-null  str
 5   review_date        10355 non-null  datetime64[us]
 6   year               10355 non-null  int32
 7   month              10355 non-null  int32
 8   content            10355 non-null  str
 9   rating             10355 non-null  int64
 10  helpful_count      10355 non-null  int64
 11  has_image          10355 non-null  int64
 12  purchase_option    10125 non-null  str
 13  user_size          0 non-null      object
 14  user_height        0 non-null      object
 15  user_weight        0 non-null      object
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        10355 non-null  str
dtypes: datetime64[us](2), int32(2), int64(4), object(5), str(6)
memory usage: 4.5+ MB

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-23,자사몰,110919,1100fs253od03x012217,<차정원 착용> 휠라 에샤페 LX 브릭,2024-09-11,2024,9,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,5,1,1,브라운,None,None,None,None,None,https://www.fila.co.kr/product/1100fs253od03x0...
1,2026-04-23,자사몰,139596,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,2026-03-22,2026,3,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",5,10,1,사이즈:250 / 컬러:핑크,None,None,None,None,None,https://www.fila.co.kr/product/1100fs261tn02x0...
2,2026-04-23,자사몰,128715,1100fs253od03x012260,휠라 에샤페 LX 모카,2025-10-07,2025,10,"""실물이 훨씬 예뻐요"", ""어떤 룩에도 잘 매치되어서 활용도가 높습니다.""",5,0,0,베이지,None,None,None,None,None,https://www.fila.co.kr/product/1100fs253od03x0...

In [32]:
# 'purchase_option' NaN -> None으로 처리
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].astype(object)
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].fillna(None)

df_review_fila_D2C['purchase_option'].value_counts(dropna=False)

purchase_option
블랙                                   2350
그레이                                  1570
브라운                                  1012
화이트                                   636
베이지                                   623
그린                                    417
핑크                                    330
None                                  230
블루                                    199
라이트멜란지                                189
크림                                    138
퍼플                                    102
더스티그린                                 102
페일블루                                   82
레드                                     79
우드                                     72
옐로우                                    66
다크레드                                   63
라이트베이지                                 55
민트                                     50
오트밀                                    50
드라이로즈                                  37
라이트브라운                                 37
내추럴베이지                                 35
페일베이지                                  33
인디안핑크                                  29
다크베이지                                  27
오렌지                                    23
사이즈:240 / 컬러:그레이                       21
컬러:001 / 사이즈:000(Free) / 컬러:화이트        17
사이즈:095                                14
민트, 블루                                 12
컬러:001 / 사이즈:000(Free) / 컬러:블랙         12
사이즈:240 / 컬러:화이트                       12
사이즈:245 / 컬러:베이지                       11
사이즈:100(L) / 컬러:블랙                     11
사이즈:270 / 컬러:화이트                       10
사이즈:250 / 컬러:그레이                       10
사이즈:95(M) / 컬러:블랙                      10
사이즈:95(M) / 컬러:핑크                      10
사이즈:000(Free) / 컬러:블랙                  10
페일핑크                                    9
사이즈:095 / 컬러:라이트멜란지                     9
사이즈:235 / 컬러:그레이                        9
사이즈:105                                 9
사이즈:105(XL) / 컬러:블랙                     9
사이즈:240 / 컬러:베이지                        9
오프화이트                                   8
사이즈:240 / 컬러:핑크                         8
사이즈:270 / 컬러:핑크                         8
사이즈:250 / 컬러:화이트                        8
사이즈:100(L) / 컬러:베이지                     8
사이즈:235 / 컬러:블랙                         8
사이즈:235 / 컬러:베이지                        8
사이즈:240 / 컬러:블랙                         8
사이즈:090                                 8
다크그린                                    8
사이즈:265 / 컬러:화이트                        7
사이즈:L(100) / 컬러:블루                      7
사이즈:95(M) / 컬러:그린                       7
더스트그린                                   7
사이즈:235 / 컬러:핑크                         7
사이즈:250 / 컬러:블랙                         7
사이즈:230 / 컬러:핑크                         7
사이즈:250 / 컬러:핑크                         6
사이즈:90(S) / 컬러:블랙                       6
사이즈:255 / 컬러:그레이                        6
퍼플리시블루                                  6
사이즈:XL(105) / 컬러:블랙                     6
사이즈:095 / 컬러:블랙                         6
사이즈:240 / 컬러:001 / 컬러:옐로우               6
사이즈:WM(W80) / 컬러:블랙                     6
사이즈:230 / 컬러:그레이                        6
사이즈:090 / 컬러:화이트                        6
사이즈:90(S) / 컬러:핑크                       6
size:95(M) / 컬러:블랙                      6
사이즈:100 / 컬러:블랙                         6
사이즈:265 / 컬러:핑크                         5
사이즈:245 / 컬러:219 / 컬러:브라운               5
사이즈:95(M) / 컬러:베이지                      5
사이즈:280 / 컬러:화이트                        5
사이즈:275 / 컬러:화이트                        5
컬러:150 / 사이즈:000(Free) / 컬러:화이트         5
사이즈:000(Free) / 컬러:블루                   5
size:000(Free) / 컬러:화이트                 5
사이즈:90(S) / 컬러:그린                       5
사이즈:270 / 컬러:001 / 컬러:블랙                5
사이즈:WM(W90) / 컬러:블루                     5
사이즈:90(S) / 컬러:화이트                      5
size:000(Free) / 컬러:그린                  5
사이즈:240 / 컬러:219 / 컬러:브라운               5
사이즈:100(L) / 컬러:화이트                     5
사이즈:230 / 컬러:블랙                         5
사이즈:L(90) / 컬러:블랙                       5
사이즈:95(M) / 컬러:그레이                      5
사이즈:240 / 컬러:브라운                        5
사이즈:245 / 컬러:그레이                        5
사이즈:245 / 컬러:블랙                         5
사이즈:000(Free) / 컬러:370 / 컬러:그린          5
컬러:001 / 사이즈:M(085) / 컬러:블랙             5
사이즈:000 / 컬러:BLK / 컬러:블랙                4
사이즈:240 / 컬러:001 / 컬러:블랙                4
사이즈:260 / 컬러:핑크                         4
플럼                                      4
사이즈:XL(105) / 컬러:블루                     4
사이즈:260 / 컬러:블루                         4
사이즈:000(Free) / 컬러:217 / 컬러:블랙          4
사이즈:245 / 컬러:화이트                        4
사이즈:WM(W90) / 컬러:브라운                    4
사이즈:260 / 컬러:블랙                         4
사이즈:100(L) / 컬러:핑크                      4
사이즈:90(S) / 컬러:크림                       4
사이즈:100(L) / 컬러:그린                      4
사이즈:105(XL) / 컬러:그린                     4
사이즈:260 / 컬러:001 / 컬러:블랙                4
사이즈:095 / 컬러:페일베이지                      4
사이즈:090 / 컬러:BLK / 컬러:블랙                4
사이즈:L(100) / 컬러:화이트                     4
사이즈:100 / 컬러:BLK / 컬러:블랙                4
사이즈:WM(W90) / 컬러:화이트                    4
사이즈:235 / 컬러:화이트                        4
사이즈:WM(W90) / 컬러:레드                     4
size:105(XL) / 컬러:블랙                    4
사이즈:105(XL) / 컬러:베이지                    4
사이즈:000(Free) / 컬러:화이트                  4
사이즈:105 / 컬러:BLK / 컬러:블랙                4
사이즈:230 / 컬러:화이트                        4
사이즈:230 / 컬러:베이지                        4
사이즈:260 / 컬러:화이트                        3
사이즈:270 / 컬러:그레이                        3
사이즈:280 / 컬러:핑크                         3
사이즈:290 / 컬러:화이트                        3
스카이블루                                   3
사이즈:WS(W85) / 컬러:화이트                    3
사이즈:280 / 컬러:블랙                         3
사이즈:245 / 컬러:001 / 컬러:그린                3
사이즈:275 / 컬러:브라운                        3
사이즈:090 / 컬러:LML / 컬러:라이트멜란지            3
컬러:001 / 사이즈:100(L) / 컬러:그레이            3
사이즈:265 / 컬러:블랙                         3
사이즈:105 / 컬러:DRD / 컬러:다크레드              3
size:240 / 컬러:그레이                       3
사이즈:000(Free) / 컬러:217 / 컬러:화이트         3
사이즈:245 / 컬러:핑크                         3
사이즈:100 / 컬러:NBG / 컬러:내추럴베이지            3
사이즈:105(XL)                             3
size:000(Free) / 컬러:블랙                  3
사이즈:95(M) / 컬러:크림                       3
컬러:001 / 사이즈:90(S) / 컬러:크림              3
사이즈:100(L) / 컬러:블루                      3
사이즈:220 / 컬러:그레이                        3
size:105(XL) / 컬러:크림                    3
사이즈:095 / 컬러:LML / 컬러:라이트멜란지            3
사이즈:090 / 컬러:레드                         3
사이즈:245 / 컬러:브라운                        3
size:260 / 컬러:블랙                        3
사이즈:090 / 컬러:다크그린                       3
사이즈:105 / 컬러:블랙                         3
사이즈:265 / 컬러:그레이                        3
사이즈:105(XL) / 컬러:핑크                     3
사이즈:240 / 컬러:370 / 컬러:블랙                3
사이즈:095 / 컬러:BLK / 컬러:화이트               3
사이즈:090 / 컬러:DRO / 컬러:드라이로즈             3
사이즈:L(90) / 컬러:블루                       3
size:240 / 컬러:브라운                       3
사이즈:250 / 컬러:베이지                        3
사이즈:250 / 컬러:219 / 컬러:블랙                3
사이즈:095 / 컬러:다크레드                       3
사이즈:235 / 컬러:063 / 컬러:그레이               3
컬러:001 / 사이즈:105(XL) / 컬러:블랙            3
사이즈:235 / 컬러:219 / 컬러:브라운               3
사이즈:240 / 컬러:블루                         3
사이즈:110 / 컬러:BLK / 컬러:블랙                3
사이즈:L(90) / 컬러:그레이                      3
사이즈:000(Free) / 컬러:핑크                   3
사이즈:090 / 컬러:라이트멜란지                     3
사이즈:240 / 컬러:219 / 컬러:베이지               3
사이즈:L(100) / 컬러:블랙                      3
사이즈:225 / 컬러:그레이                        3
사이즈:270 / 컬러:블랙                         3
사이즈:240 / 컬러:옐로우                        3
컬러:001 / 사이즈:XL(95) / 컬러:블랙             3
컬러:032 / 사이즈:90(S) / 컬러:블랙              3
사이즈:090 / 컬러:BLK / 컬러:라이트멜란지            3
사이즈:275 / 컬러:핑크                         2
사이즈:WM / 컬러:블루                          2
사이즈:260 / 컬러:100 / 컬러:화이트               2
컬러:001 / 사이즈:L(100) / 컬러:블랙             2
네이비                                     2
사이즈:270 / 컬러:924 / 컬러:그레이               2
사이즈:000(Free) / 컬러:브라운                  2
사이즈:240 / 컬러:217 / 컬러:브라운               2
사이즈:250 / 컬러:920 / 컬러:블랙                2
사이즈:090 / 컬러:BLK / 컬러:다크그린              2
사이즈:235 / 컬러:219 / 컬러:화이트               2
사이즈:240 / 컬러:031 / 컬러:그레이               2
컬러:150 / 사이즈:000(Free) / 컬러:블랙          2
size:250 / 컬러:브라운                       2
사이즈:245 / 컬러:010 / 컬러:블랙                2
사이즈:255 / 컬러:219 / 컬러:브라운               2
사이즈:100 / 컬러:WHI                        2
사이즈:245 / 컬러:217 / 컬러:핑크                2
사이즈:250 / 컬러:370 / 컬러:브라운               2
사이즈:255 / 컬러:화이트                        2
사이즈:250 / 컬러:001 / 컬러:블랙                2
사이즈:230 / 컬러:001 / 컬러:블랙                2
사이즈:WL(W95) / 컬러:화이트                    2
사이즈:235 / 컬러:001 / 컬러:블랙                2
컬러:031 / 사이즈:90(S)                      2
사이즈:255 / 컬러:031 / 컬러:그레이               2
size:95(M) / 컬러:브라운                     2
사이즈:240 / 컬러:001 / 컬러:화이트               2
사이즈:235 / 컬러:옐로우                        2
사이즈:240 / 컬러:260 / 컬러:베이지               2
사이즈:255 / 컬러:001 / 컬러:화이트               2
사이즈:2XL(110) / 컬러:블랙                    2
사이즈:240 / 컬러:452 / 컬러:블루                2
size:230 / 컬러:블랙                        2
사이즈:XL(95) / 컬러:블랙                      2
사이즈:240 / 컬러:219 / 컬러:그린                2
사이즈:235 / 컬러:001 / 컬러:화이트               2
컬러:234 / 사이즈:000(Free) / 컬러:블랙          2
사이즈:225 / 컬러:블랙                         2
컬러:031 / 사이즈:105(XL) / 컬러:크림            2
컬러:001 / 사이즈:WM(W90) / 컬러:화이트           2
사이즈:255 / 컬러:블랙                         2
컬러:031 / 사이즈:95(M) / 컬러:블랙              2
사이즈:90(S) / 컬러:베이지                      2
사이즈:235 / 컬러:370 / 컬러:화이트               2
사이즈:75A / 컬러:블랙                         2
size:235 / 컬러:블랙                        2
사이즈:100(L) / 컬러:066 / 컬러:핑크             2
컬러:001 / 사이즈:L(100) / 컬러:블루             2
사이즈:235 / 컬러:219 / 컬러:블랙                2
컬러:422 / 사이즈:95(M) / 컬러:블루              2
사이즈:WL(W95) / 컬러:블랙                     2
사이즈:240 / 컬러:001 / 컬러:브라운               2
사이즈:270 / 컬러:001 / 컬러:베이지               2
사이즈:285 / 컬러:블루                         2
사이즈:000 / 컬러:BLK / 컬러:스카이블루             2
사이즈:240 / 컬러:924 / 컬러:그레이               2
컬러:001 / 사이즈:100(L) / 컬러:블랙             2
사이즈:230 / 컬러:920 / 컬러:베이지               2
size:250 / 컬러:베이지                       2
size:230 / 컬러:핑크                        2
사이즈:245 / 컬러:217 / 컬러:브라운               2
사이즈:WS(W85) / 컬러:레드                     2
size:240 / 컬러:베이지                       2
사이즈:245 / 컬러:001 / 컬러:블랙                2
size:105 / 컬러:블랙                        2
사이즈:235 / 컬러:031 / 컬러:그레이               2
사이즈:90(S) / 컬러:370 / 컬러:그린              2
사이즈:255 / 컬러:베이지                        2
사이즈:090 / 컬러:RED / 컬러:화이트               2
사이즈:240 / 컬러:370 / 컬러:그린                2
사이즈:100 / 컬러:LML / 컬러:블랙                2
사이즈:240 / 컬러:102 / 컬러:화이트               2
사이즈:100 / 컬러:페일베이지                      2
사이즈:270 / 컬러:베이지                        2
사이즈:XL(105) / 컬러:화이트                    2
사이즈:230 / 컬러:260 / 컬러:핑크                2
size:100 / 컬러:블랙                        2
사이즈:100 / 컬러:다크레드                       2
사이즈:095 / 컬러:크림                         2
사이즈:95(M) / 컬러:퍼플                       2
사이즈:090 / 컬러:PBE / 컬러:크림                2
사이즈:235 / 컬러:217 / 컬러:옐로우               2
사이즈:230 / 컬러:217 / 컬러:브라운               2
컬러:001 / 사이즈:WS(W75) / 컬러:브라운           2
사이즈:WL(W85) / 컬러:베이지                    2
사이즈:230 / 컬러:219 / 컬러:그린                2
사이즈:290 / 컬러:그레이                        2
사이즈:250 / 컬러:101 / 컬러:화이트               2
사이즈:270 / 컬러:100 / 컬러:화이트               2
사이즈:240 / 컬러:001 / 컬러:그레이               2
사이즈:90(S)                               2
사이즈:235 / 컬러:브라운                        2
사이즈:090 / 컬러:LML / 컬러:화이트               2
size:100(L) / 컬러:블랙                     2
사이즈:255 / 컬러:핑크                         2
사이즈:100 / 컬러:라이트멜란지                     2
size:105(XL)                            2
size:100(L) / 컬러:크림                     2
사이즈:260 / 컬러:370 / 컬러:그린                2
컬러:001 / 사이즈:90(S) / 컬러:화이트             2
사이즈:L(100) / 컬러:레드                      2
컬러:031 / 사이즈:90(S) / 컬러:블랙              2
사이즈:235 / 컬러:001 / 컬러:그린                2
사이즈:095 / 컬러:LML / 컬러:퍼플                2
컬러:001 / 사이즈:95(M) / 컬러:블랙              2
사이즈:100(L) / 컬러:370 / 컬러:그린             2
사이즈:225 / 컬러:219 / 컬러:그린                2
사이즈:090 / 컬러:오렌지                        2
사이즈:245 / 컬러:370 / 컬러:그린                2
사이즈:WL(W95) / 컬러:브라운                    2
사이즈:265 / 컬러:001 / 컬러:화이트               2
사이즈:090 / 컬러:블랙                         2
size:090 / 컬러:레드                        2
사이즈:WS(W85) / 컬러:브라운                    2
사이즈:250 / 컬러:옐로우                        2
사이즈:265 / 컬러:001 / 컬러:블랙                2
사이즈:275 / 컬러:001 / 컬러:블랙                2
사이즈:XL(105) / 컬러:브라운                    2
사이즈:WS(W75) / 컬러:브라운                    2
컬러:472 / 사이즈:XL(105) / 컬러:블루            2
사이즈:240 / 컬러:100 / 컬러:화이트               2
사이즈:090 / 컬러:LML / 컬러:레드                2
컬러:001 / 사이즈:100(L) / 컬러:라이트브라운         2
사이즈:090 / 컬러:DTG / 컬러:드라이로즈             2
사이즈:110 / 컬러:블랙                         2
사이즈:S(090) / 컬러:레드                      2
size:230 / 컬러:그레이                       2
사이즈:WL(W85) / 컬러:블랙                     2
사이즈:240 / 컬러:370 / 컬러:브라운               2
사이즈:240 / 컬러:217 / 컬러:블랙                2
사이즈:270 / 컬러:블루                         2
사이즈:L(100) / 컬러:베이지                     2
사이즈:105(XL) / 컬러:452 / 컬러:블랙            2
사이즈:M(095) / 컬러:블랙                      2
사이즈:000 / 컬러:BLK / 컬러:크림                2
size:245 / 컬러:화이트                       2
사이즈:090 / 컬러:LML / 컬러:블랙                2
사이즈:XL(95) / 컬러:블루                      2
사이즈:095 / 컬러:BLK / 컬러:블랙                2
사이즈:095 / 컬러:BLK / 컬러:라이트베이지            2
size:275 / 컬러:화이트                       1
사이즈:255 / 컬러:032 / 컬러:그레이               1
사이즈:270 / 컬러:브라운                        1
사이즈:285 / 컬러:화이트                        1
size:255 / 컬러:화이트                       1
사이즈:245 / 컬러:734 / 컬러:그린                1
컬러:290 / 사이즈:S(090) / 컬러:블루             1
사이즈:000 / 컬러:OWH / 컬러:스카이블루             1
사이즈:000 / 컬러:브라운                        1
사이즈:095 / 컬러:내추럴베이지                     1
size:245 / 컬러:핑크                        1
컬러:001 / 사이즈:WL(W95) / 컬러:레드            1
사이즈:000 / 컬러:오프화이트                      1
사이즈:000(Free) / 컬러:260 / 컬러:브라운         1
사이즈:240 / 컬러:920 / 컬러:그레이               1
컬러:066 / 사이즈:M(095) / 컬러:블랙             1
사이즈:000 / 컬러:BLK / 컬러:오프화이트             1
사이즈:250 / 컬러:452 / 컬러:그레이               1
사이즈:XL(105) / 컬러:레드                     1
사이즈:270 / 컬러:031 / 컬러:핑크                1
컬러:234 / 사이즈:000(Free) / 컬러:브라운         1
size:240 / 컬러:블랙                        1
컬러:001 / 사이즈:000(Free) / 컬러:브라운         1
컬러:067 / 사이즈:100(L) / 컬러:화이트            1
사이즈:100(L) / 컬러:412 / 컬러:핑크             1
사이즈:280 / 컬러:001 / 컬러:블루                1
컬러:290 / 사이즈:M(095) / 컬러:베이지            1
size:250 / 컬러:그린                        1
사이즈:265 / 컬러:100 / 컬러:블랙                1
size:110(2XL) / 컬러:블랙                   1
size:95(M) / 컬러:라이트브라운                  1
사이즈:250 / 컬러:217 / 컬러:브라운               1
사이즈:WL(W95) / 컬러:블루                     1
사이즈:230 / 컬러:924 / 컬러:베이지               1
컬러:472 / 사이즈:M(095) / 컬러:베이지            1
사이즈:230 / 컬러:260 / 컬러:블랙                1
사이즈:95(M) / 컬러:브라운                      1
사이즈:090 / 컬러:BLK / 컬러:베이지               1
컬러:175 / 사이즈:S(090) / 컬러:퍼플             1
컬러:442 / 사이즈:S(090) / 컬러:블루             1
사이즈:80A / 컬러:LSA / 컬러:페일베이지             1
사이즈:80A / 컬러:PBG / 컬러:페일베이지             1
사이즈:L(90) / 컬러:화이트                      1
사이즈:M(085) / 컬러:블랙                      1
사이즈:250 / 컬러:001 / 컬러:브라운               1
사이즈:225 / 컬러:001 / 컬러:블랙                1
사이즈:80A / 컬러:블랙                         1
컬러:234 / 사이즈:M(095) / 컬러:브라운            1
사이즈:260 / 컬러:924 / 컬러:베이지               1
사이즈:S(080) / 컬러:블랙                      1
size:235 / 컬러:옐로우                       1
사이즈:265 / 컬러:001 / 컬러:브라운               1
사이즈:270 / 컬러:219 / 컬러:베이지               1
사이즈:000 / 컬러:OWH / 컬러:오프화이트             1
사이즈:95(M) / 컬러:217 / 컬러:브라운             1
size:105 / 컬러:내추럴베이지                    1
사이즈:235 / 컬러:219 / 컬러:베이지               1
사이즈:250 / 컬러:217 / 컬러:핑크                1
컬러:001 / 사이즈:100(L) / 컬러:크림             1
size:W85(WS) / 컬러:브라운                   1
사이즈:M(095) / 컬러:화이트                     1
컬러:001 / 사이즈:100(L) / 컬러:화이트            1
size:095 / 컬러:블랙                        1
컬러:001 / 사이즈:90(S)                      1
size:95(M) / 컬러:민트                      1
사이즈:100 / 컬러:라이트베이지                     1
사이즈:크림 WS, 블루 WL / 컬러:브라운               1
사이즈:000(Free) / 컬러:442 / 컬러:블루          1
사이즈:100(L) / 컬러:260 / 컬러:핑크             1
컬러:001 / 사이즈:2XL(100) / 컬러:블랙           1
사이즈:245 / 컬러:001 / 컬러:옐로우               1
사이즈:230 / 컬러:004 / 컬러:베이지               1
사이즈:280 / 컬러:001 / 컬러:화이트               1
사이즈:WXS(W80) / 컬러:레드                    1
사이즈:WS(W75) / 컬러:화이트                    1
사이즈:75A / 컬러:PBG / 컬러:페일베이지             1
사이즈:2XL(110) / 컬러:화이트                   1
사이즈:090 / 컬러:WHI / 컬러:오렌지               1
컬러:650 / 사이즈:95(M) / 컬러:그레이             1
사이즈:95(M) / 컬러:066 / 컬러:그레이             1
컬러:004 / 사이즈:000(Free) / 컬러:그레이         1
사이즈:240 / 컬러:217 / 컬러:옐로우               1
컬러:661 / 사이즈:95(M) / 컬러:그레이             1
컬러:234 / 사이즈:WS(W85) / 컬러:화이트           1
size:100(L) / 컬러:브라운                    1
사이즈:260 / 컬러:260 / 컬러:그린                1
사이즈:090 / 컬러:BLK / 컬러:화이트               1
사이즈:100 / 컬러:LML / 컬러:라이트멜란지            1
사이즈:80A / 컬러:001 / 컬러:블랙                1
컬러:001 / 사이즈:WS(W75) / 컬러:핑크            1
컬러:472 / 사이즈:2XL(110) / 컬러:핑크           1
사이즈:280 / 컬러:블루                         1
사이즈:90(S) / 컬러:452 / 컬러:브라운             1
컬러:001 / 사이즈:XL(105) / 컬러:블루            1
사이즈:260 / 컬러:219 / 컬러:블랙                1
사이즈:095 / 컬러:다크그린                       1
size:090 / 컬러:라이트멜란지                    1
사이즈:280 / 컬러:001 / 컬러:옐로우               1
컬러:001 / 사이즈:M(085) / 컬러:브라운            1
사이즈:255 / 컬러:217 / 컬러:그레이               1
사이즈:270 / 컬러:001 / 컬러:그레이               1
사이즈:245 / 컬러:217 / 컬러:베이지               1
사이즈:90(S) / 컬러:072 / 컬러:그레이             1
사이즈:70B / 컬러:071 / 컬러:그레이               1
사이즈:095 / 컬러:LML / 컬러:레드                1
사이즈:095 / 컬러:오렌지                        1
사이즈:270 / 컬러:050 / 컬러:블랙                1
사이즈:260 / 컬러:200 / 컬러:베이지               1
사이즈:245 / 컬러:218 / 컬러:브라운               1
사이즈:240 / 컬러:031 / 컬러:옐로우               1
size:90(S)                              1
사이즈:250 / 컬러:050 / 컬러:그레이               1
사이즈:WS(W75) / 컬러:핑크                     1
컬러:175 / 사이즈:WM(W90) / 컬러:레드            1
사이즈:270 / 컬러:217 / 컬러:그레이               1
사이즈:240 / 컬러:001 / 컬러:그린                1
컬러:650 / 사이즈:90(S) / 컬러:핑크              1
사이즈:230 / 컬러:217 / 컬러:옐로우               1
사이즈:230 / 컬러:블루                         1
컬러:234 / 사이즈:WS(W85) / 컬러:블루            1
사이즈:265 / 컬러:베이지                        1
사이즈:235 / 컬러:219 / 컬러:핑크                1
사이즈:230 / 컬러:820 / 컬러:오렌지               1
사이즈:230 / 컬러:001 / 컬러:화이트               1
사이즈:275 / 컬러:260 / 컬러:브라운               1
사이즈:270 / 컬러:260 / 컬러:오렌지               1
사이즈:095 / 컬러:IDB / 컬러:블랙                1
사이즈:270 / 컬러:101 / 컬러:화이트               1
사이즈:260 / 컬러:100 / 컬러:브라운               1
사이즈:270 / 컬러:그린                         1
사이즈:100 / 컬러:RED / 컬러:라이트멜란지            1
사이즈:240 / 컬러:063 / 컬러:그레이               1
사이즈:100 / 컬러:MLY / 컬러:딥틸                1
사이즈:235 / 컬러:217 / 컬러:브라운               1
사이즈:220 / 컬러:블랙                         1
size:95(M) / 컬러:크림                      1
컬러:650 / 사이즈:90(S) / 컬러:블랙              1
컬러:650 / 사이즈:95(M) / 컬러:민트, 블루          1
사이즈:095 / 컬러:BLK / 컬러:레드                1
사이즈:105 / 컬러:라이트베이지                     1
사이즈:250 / 컬러:031 / 컬러:그레이               1
사이즈:235 / 컬러:001 / 컬러:브라운               1
사이즈:100 / 컬러:MIT / 컬러:민트                1
사이즈:095 / 컬러:LML / 컬러:블루                1
사이즈:95(M) / 컬러:066 / 컬러:블루              1
사이즈:270 / 컬러:오렌지                        1
사이즈:95(M) / 컬러:613 / 컬러:크림              1
컬러:101 / 사이즈:95(M) / 컬러:민트              1
사이즈:100(L) / 컬러:412 / 컬러:화이트            1
사이즈:240 / 컬러:100 / 컬러:블랙                1

In [33]:
df_review_fila_D2C['purchase_option'].info()

<class 'pandas.Series'>
RangeIndex: 10355 entries, 0 to 10354
Series name: purchase_option
Non-Null Count  Dtype
--------------  -----
10125 non-null  object
dtypes: object(1)
memory usage: 81.0+ KB

In [34]:
# ==================================
# 'purchase_option' == None
# ==================================
# 1) 데이터 확인 # 230개
df_review_fila_D2C[df_review_fila_D2C['purchase_option'].isna()][['product_id', 'product_name', 'purchase_option', 'product_url']].head(10)

,product_id,product_name,purchase_option,product_url
28,1170fi253fz13f003031,버터소프트 집업 후드,None,https://www.fila.co.kr/product/1170fi253fz13f0...
33,1170fi4rsh1145mdid,<FILA UNDERWEAR X BALANSA> 오버핏 티셔츠,None,https://www.fila.co.kr/product/1170fi4rsh1145mdid
158,1170fi4tkh1143mdid,<FILA UNDERWEAR X BALANSA> 트렁크 3팩,None,https://www.fila.co.kr/product/1170fi4tkh1143mdid
305,1170fi253br01f008031,에센셜 클래식 노와이어 브라,None,https://www.fila.co.kr/product/1170fi253br01f0...
509,1170fi4bah2450fwhi,<큰컵추천> 썸머 벨로 에어로쿨 브라탑,None,https://www.fila.co.kr/product/1170fi4bah2450fwhi
519,1170fi4bah2450flle,<큰컵추천> 썸머 벨로 에어로쿨 브라탑,None,https://www.fila.co.kr/product/1170fi4bah2450flle
698,1170fi253fz13f004031,<최화정 착용> 버터소프트 스트링 자켓,None,https://www.fila.co.kr/product/1170fi253fz13f0...
699,1170fi4bah2450flle,<큰컵추천> 썸머 벨로 에어로쿨 브라탑,None,https://www.fila.co.kr/product/1170fi4bah2450flle
747,1170fi253mp13f005031,버터소프트 조거 팬츠,None,https://www.fila.co.kr/product/1170fi253mp13f0...
759,1170fi253dr01f008031,에센셜 클래식 사각 드로즈,None,https://www.fila.co.kr/product/1170fi253dr01f0...

In [35]:
# =============================
# 'purchase_option' == None
# =============================
# 1) 검색해서 값 매칭
mapping = {
    '1170fi253sk13f001031' : '컬러:MOCHA',
    '1170fi253mp13f003032' : '컬러:MOCHA', 
    '1170fi253fz13f003031' : '컬러:MOCHA', 
    '1170fi253mp13f005031' : '컬러:MOCHA',
    '1170fi253fz13f004031' : '컬러:MOCHA',
    '1170fi253dr01f008031' : '컬러:LIGHT SAND', # 에센셜 클래식 사각 드로즈
    '1170fi4bah2450fwhi' : '컬러:화이트',
    '1170fi4bah2450flle' : '컬러:라이트레몬',
    '1170fi4bah2450fblk' : '컬러:블랙',
    '1170fi4bah2450fmab' : '컬러:마린블루',
    '1170fi253br01f008031' : '컬러:LIGHT SAND', # 에센셜 클래식 노와이어 브라
    '1170fi4rsh1145mdid' : '컬러:다크인디고',
    '1170fi253dr01f007031' : '컬러:LIGHT SAND', # 에센셜 클래식 햄 팬티
    '1170fi4poh1146mdid' : '컬러:다크인디고',
    '1170fi4drh2657fsad' : '컬러:샌드',
    '1170fi4drh2657fblk' : '컬러:블랙',
    '1170fi253br01f011031' : '컬러:LIGHT SAND', # 에센셜 클래식 베이직 브라
    '1170fi4ith2659flsa' : '컬러:라이트샌드', # 에어플러스 라이트 스트랩 브라탑
    '1170fi4ith2659fdid' : '컬러:다크인디고',
    '1170fi253br01f010031' : '컬러:LIGHT SAND', # 에센셜 클래식 하프컵 브라
    '1170fi253br01f001031' : '컬러:LIGHT SAND', # 에센셜 클래식 오프숄더 브라
    '1170fi4drh2450fwhi' : '컬러:화이트',
    '1170fi4drh2450flle' : '컬러:라이트레몬',
    '1170fi4drh2656fsad' : '컬러:샌드',
    '1170fi4drh2656flvy' : '컬러:라벤더그레이',
    '1170fi4drh2450fmab' : '컬러:마린블루',
    '1170fi4drh2656fblk' : '컬러:블랙',
    '1170fi4tkh1143mdid' : '컬러:다크인디고',
    '1170fi4drh2450fblk' : '컬러:블랙',
    '1170fi4cah1148mdid' : '컬러:다크인디고',
    '1170fi4ith2656flvy' : '컬러:라벤더그레이',
    '1170fi4ith2656fblk' : '컬러:블랙',
    '1170fi4ith2656fsad' : '컬러:샌드',
    '1170fi253bf01f003031' : '컬러:LIGHT SAND',
    '1170fi4pjh2645flde' : '컬러:라이트데님',
    '1170fi4drh2658flsa' : '컬러:라이트샌드', # 에어플러스 라이트 팬티
    '1170fi4pjh2612mdpt' : '컬러:딥틸',
    '1170fi4drh2658fdid' : '컬러:다크인디고',
    '1170fi261mt13f002031' : '컬러:MOCHA',
    '1170fi4pjh2609mblk' : '컬러:블랙',
    '1170fi4pjh2650fnay' : '컬러:네이비',
    '1170fi4pjh2651frop' : '컬러:로즈핑크',
    '1170fi4oph2649frop' : '컬러:로즈핑크',
    '1170fi4pjh2641ftgr' : '컬러:틸그린',
    '1170fi4drh1142mdid' : '컬러:다크인디고',
    '1170fi4pjh2608midb' : '컬러:인디고블루',
    '1170fi4pjh2642ftgr' : '컬러:틸그린',
    '1170fi4pjh2643ftgr' : '컬러:틸그린',
    '1170fi4pjh2648fidb' : '컬러:인디고블루',
    '1170fi4bah2657fblk' : '컬러:블랙',
    '1170fi4pjh2609mdst' : '컬러:다크스틸',
    '1170fi4bah2657fsad' : '컬러:샌드',
    '1170fi261mp13f004031' : '컬러:GRAY',
    '1100fs253od03x012217' : '컬러:브라운', # 여기서부터 새로 매핑한 데이터
    '1100fs261tn02x001660' : '컬러:핑크',
    '1100fs253od03x012260' : '컬러:베이지',
    '1100fs261tn02x001106' : '컬러:화이트',
    '1100fs3bph1003xowh' : '컬러:오프화이트',
    '1100fs262jk01u003442' : '컬러:블루',
    '11001xm02367h102' : '컬러:화이트',
    '1170fi4bah1102fblk' : '컬러:블랙',
    '11001xm02348h063' : '컬러:그레이',
    '11001xm02854h040' : '컬러:블랙',
    '1100fs261od03x040032' : '컬러:그레이',
    '1100fs253od03x014218' : '컬러:브라운',
    '1170fi261br01f033250' : '컬러:베이지',
    '1170fi261br01f033100' : '컬러:화이트',
    '1100fs262sd03x004260' : '컬러:베이지',
    '1100fs261od03x008370' : '컬러:그린',
    '1100fs261tn02x001103' : '컬러:화이트',
    '1260fv254br17f002260' : '컬러:베이지',
    '1100fs262sd03x004660' : '컬러:핑크',
    '1100fs253ru02x002002' : '컬러:블랙',
    '1170fi4drh1141mblk' : '컬러:블랙',
    '1100fs262rs01x020472' : '컬러:블루',
    '1170fi4tkh1101fblk' : '컬러:블랙',
    '1170fi261dr01m024001' : '컬러:블랙',
    '1170fi4drg1106mblk' : '컬러:블랙',
    '1170fi4bfh1102fblk' : '컬러:블랙',
    '1170fi261dr01m023001' : '컬러:블랙',
    '1100fs261bp01x001234' : '컬러:브라운',
    '1100fs261ft01f005001' : '컬러:블랙',
    '1170fi253jt13u002370' : '컬러:그린',
    '1170fi253dr01m010001' : '컬러:블랙',
    '1100fs3bph1004xowh' : '컬러:오프화이트',
    '1170fi261dr01m012452' : '컬러:블루',
    '1100fs262rs02x004007' : '컬러:블랙',
    '1170fi4drh1120mblk' : '컬러:블랙',
    '1100fs261od03x087001' : '컬러:블랙',
    '11001xm02369h001' : '컬러:블랙',
    '1100fs261od03x005102' : '컬러:화이트',
    '11001xm02348h010' : '컬러:블랙',
    '11001xm02369h050' : '컬러:그레이',
    '11001rm02946h010' : '컬러:블랙',
    '1100fs262sd03x004031' : '컬러:그레이',
    '1100fs262sd03x004013' : '컬러:블랙',
    '1100fs261od03x087219' : '컬러:브라운',
    '1100fs261od03x032031' : '컬러:그레이',
    '1100fs261od03x095734' : '컬러:옐로우',
    '1100fs261od03x087100' : '컬러:화이트',
    '1100fs261od03x008001' : '컬러:블랙',
    '1100fs261od03x087370' : '컬러:그린',
    '11001xm02347h920' : '컬러:베이지',
    '1100fs261od03x032660' : '컬러:핑크',
    '1100fs261od03x046031' : '컬러:그레이',
    '1100fs261od03x087456' : '컬러:블루',
    '1100fs261od03x087218' : '컬러:브라운',
    '11001rm02946h050' : '컬러:그레이',
    '1100fs261od03x045217' : '컬러:브라운',
    '1100fs261od03x032260' : '컬러:베이지',
    '11001rm02942h071' : '컬러:그레이',
    '11001jm02786h924' : '컬러:베이지',
    '1100fs253ru03x014001' : '컬러:블랙',
    '1100fs261ft01f005175' : '컬러:화이트',
    '1100fs261ft01f005626' : '컬러:레드',
    '1100fs253ru03x004260' : '컬러:베이지',
    '1100fs261ru03x012100' : '컬러:화이트',
    '1100fs261ru04x003031' : '컬러:그레이',
    '1100fs261po01x004442' : '컬러:블루',
    '1170fi4bah1122fepk' : '컬러:페일핑크',
    '1170fi253br12f003260' : '컬러:베이지',
    '1100fs3bph1003xsbu' : '컬러:스카이블루',
    '1170fi261dr01m013001' : '컬러:블랙',
    '1100fs261tn02x005100' : '컬러:화이트',
    '1100fs3bph1003xblk' : '컬러:블랙',
    '11001jm02787h001' : '컬러:블랙',
    '1170fi4drh1122mblk' : '컬러:블랙',
    '1170fi261br01f010066' : '컬러:그레이',
    '1170fi261br01f033661' : '컬러:레드',
    '1260fv254br17f001370' : '컬러:그린',
    '1170fi4bah1115flml' : '컬러:라이트멜란지',
    '1100fs261od03x095100' : '컬러:화이트',
    '1170fi4bah1104fdro' : '컬러:드라이로즈',
    '1170fi261br01f009100' : '컬러:화이트',
    '1170fi253br01f001260' : '컬러:다크베이지',
    '1170fi261br01f010650' : '컬러:핑크',
    '1170fi253br01f011001' : '컬러:블랙',
    '1170fi261br01f010100' : '컬러:화이트',
    '1170fi4bfg3171fpbl' : '컬러:퍼플',
    '1170fi253lg12f002260' : '컬러:베이지',
    '1170fi4bfg3171flml' : '컬러:라이트멜란지',
    '1170fi253sk13f001001' : '컬러:블랙',
    '1170fi4bag3171fdtg' : '컬러:더스티그린',
    '1170fi253br12f002032' : '컬러:그레이',
    '1170fi253pj13u001370' : '컬러:그린',
    '1170fi4bfh1102fdtg' : '컬러:더스트그린',
    '1170fi4drh1151mnbg' : '컬러:내추럴베이지',
    '1170fi4drg3172mblk' : '컬러:블랙',
    '1170fi4bah1115fwhi' : '컬러:화이트',
    '11001rm02844g100' : '컬러:화이트',
    '1170fi4bah1102fpbl' : '컬러:퍼플',
    '1170fi253mp13f004001' : '컬러:블랙',
    '1170fi253sk13f001032' : '컬러:크림',
    '1100fs261ft01x001001' : '컬러:블랙',
    '1100fs262jk01u003626' : '컬러:레드',
    '1100fs3bph1002xblk' : '컬러:블랙',
    '1170fi253dr01m011001' : '컬러:블랙',
    '1170fi253lg12m001100' : '컬러:화이트',
    '1170fi253br12f001032' : '컬러:그레이',
    '1170fi253br12f002650' : '컬러:핑크',
    '1170fi253lg12f003001' : '컬러:블랙',
    '1170fi253br12f003032' : '컬러:그레이',
    '1170fi253lg12f003650' : '컬러:핑크',
    '1170fi253lg12m002031' : '컬러:그레이',
    '1170fi253br12f003031' : '컬러:플럼',
    '1170fi253lg12f002001' : '컬러:블랙',
    '1170fi253lg12m001001' : '컬러:블랙',
    '1170fi253lg12f002650' : '컬러:핑크',
    '1170fi253lg12f001032' : '컬러:그레이',
    '1170fi253lg12m001031' : '컬러:그레이',
    '1170fi253lg12f001001' : '컬러:블랙',
    '1170fi253br12f003001' : '컬러:블랙',
    '1170fi253lg12f002031' : '컬러:플럼',
    '1170fi253br12f001001' : '컬러:블랙',
    '1170fi253lg12m002100' : '컬러:화이트',
    '1170fi253br12f003650' : '컬러:핑크',
    '1170fi253br12f001031' : '컬러:플럼',
    '1170fi253lg12m002001' : '컬러:블랙',
    '1170fi253lg12f002032' : '컬러:그레이',
    '1170fi261bf01f013175' : '컬러:화이트',
    '1170fi253jb13f001613' : '컬러:레드',
    '1170fi253jo13f002001' : '컬러:블랙',
    '1170fi4bah1105flml' : '컬러:라이트멜란지',
    '1170fi4bah1450flbe' : '컬러:라이트베이지',
    '1100fs262rs01x002472' : '컬러:블루',
    '1100fs261od03x009452' : '컬러:블루',
    '1170fi261br01f025541' : '컬러:퍼플',
    '1170fi261bf01f012071' : '컬러:블랙',
    '1170fi4bah1103flbe' : '컬러:라이트베이지',
    '1170fi4hph1005mdtg' : '컬러:더스티그린',
    '1170fi4drh1103mdrd' : '컬러:다크레드',
    '1170fi4bfg3177fwod' : '컬러:우드',
    '1170fi261bf01f006412' : '컬러:민트, 블루',
    '1100fs261ft01x001234' : '컬러:브라운',
    '1100fs253ru03x014031' : '컬러:그레이',
    '1100fs254rb01f002150' : '컬러:화이트',
    '1170fi4tkh1627mfna' : '컬러:네이비',
    '1170fi4drh1450flbe' : '컬러:라이트베이지',
    '1100fs262jk01f001150' : '컬러:화이트',
    '1100fs253od03x014660' : '컬러:핑크',
    '1170fi253dr01f007260' : '컬러:다크베이지',
    '1170fi4drh1450flml' : '컬러:라이트멜란지',
    '1260fv254br17f002001' : '컬러:블랙',
    '1170fi4bag1448fpbg' : '컬러:페일베이지',
    '1100fs261tn03x001001' : '컬러:블랙',
    '11001jm02786h067' : '컬러:그레이',
    '1100fs254rb01f002001' : '컬러:블랙',
    '1100fs261bc01x004234' : '컬러:브라운',
    '1100fs261eq01x001234' : '컬러:브라운',
    '1100fs261bp01x001150' : '컬러:화이트',
    '1100fs261cp01x013002' : '컬러:블루',
    '1100fs261bp01x001001' : '컬러:블랙',
    '1100fs261bs01f001001' : '컬러:블랙',
    '1100fs261od03x095217' : '컬러:브라운',
    '1100fs262jk01x008496' : '컬러:블루',
    '1100fs253ru03x004100' : '컬러:화이트',
    '1170fi4drh1102fwod' : '컬러:우드',
    '1100fs261ft01x006001' : '컬러:블랙',
    '1100fs261bp01f001001' : '컬러:블랙',
    '1170fi4bfh1112fdgr' : '컬러:다크그린',
    '1100fs253od03x033100' : '컬러:화이트',
    '1100fs253ru02x001031' : '컬러:그레이',
    '11001jm02787h925' : '컬러:베이지',
    '11001jm02787h050' : '컬러:그레이',
    '1100fs261od03x006031' : '컬러:그레이',
    '1100fs262rs02x002626' : '컬러:레드',
    '1100fs253ru02x001001' : '컬러:블랙',
    '1170fi261br01f010067' : '컬러:블랙',
    '1170fi261bf01f005412' : '컬러:민트',
    '1100fs261ru03x002660' : '컬러:핑크',
    '1170fi261br01f010412' : '컬러:민트',
    '1170fi4bah1102fpbe' : '컬러:페일블루',
    '1170fi4drh1450fdrd' : '컬러:다크레드',
    '1100fs261ru03x002031' : '컬러:그레이',
    '11001tm01987g475' : '컬러:블루',
    '1100fs261sl03x004001' : '컬러:블랙',
    '1260fv254dr17f001260' : '컬러:베이지',
    '11001rm02723h001' : '컬러:블랙',
    '1100fs261bc01f002001' : '컬러:블랙',
    '1100fs261ru02x002217' : '컬러:브라운',
    '11001rm02844g001' : '컬러:블랙',
    '1100fs261ru03x076217' : '컬러:브라운',
    '1100fs261ru02x022031' : '컬러:그레이',
    '1170fi4bfh1102fpbl' : '컬러:퍼플리시블루',
    '1100fs261ft01f005496' : '컬러:블루',
    '1170fi4bah1104fblk' : '컬러:블랙',
    '1170fi261dr01m022001' : '컬러:블랙',
    '11001rm02844g102' : '컬러:화이트',
    '1170fi4bfh1102fdro' : '컬러:드라이로즈',
    '1170fi4bfh1102fcrm' : '컬러:크림',
    '1170fi4bag3171fpbe' : '컬러:페일블루',
    '1170fi261br07f006250' : '컬러:베이지',
    '1170fi4bah1450fdrd' : '컬러:다크레드',
    '1260fv254br17f001660' : '컬러:핑크',
    '1170fi253br01f010260' : '컬러:다크베이지',
    '1170fi4bah1103flml' : '컬러:라이트멜란지',
    '1100fs261od03x087661' : '컬러:핑크',
    '1170fi253jb13u002217' : '컬러:브라운',
    '1100fs261ft01f005234' : '컬러:브라운',
    '11001xm02854h400' : '컬러:블루',
    '1100fs261po01x002290' : '컬러:베이지',
    '1100fs262jk01x001001' : '컬러:블랙',
    '1170fi4tkh1124mblk' : '컬러:블랙',
    '1170fi4drg3173mblk' : '컬러:블랙',
    '1170fi4tkh1101fcrm' : '컬러:크림',
    '1170fi261bf07f001071' : '컬러:그레이',
    '1170fi261dr01f024001' : '컬러:블랙',
    '1170fi261br01f024452' : '컬러:블루',
    '1170fi253dr01f008820' : '컬러:내추럴베이지',
    '1170fi261br01f008067' : '컬러:블랙',
    '1100fs261tn03x001260' : '컬러:베이지',
    '1170fi253mp13f004032' : '컬러:크림',
    '1170fi253mp13f005001' : '컬러:블랙',
    '1170fi4drg3178fwhi' : '컬러:화이트',
    '1100fs3bph1002xcrm' : '컬러:크림',
    '1170fi4drh1450fblk' : '컬러:블랙',
    '1170fi4bah1102fdtg' : '컬러:더스티그린',
    '1170fi4bah1102fcrm' : '컬러:크림',
    '1170fi4drg3410mblk' : '컬러:블랙',
    '11001tm01987h125' : '컬러:화이트',
    '1170fi253dr01f007217' : '컬러:라이트브라운',
    '1170fi4bah1121fmit' : '컬러:민트',
    '1170fi261bf01f007066' : '컬러:그레이',
    '1170fi253fz13f003001' : '컬러:블랙',
    '11001rm02942h112' : '컬러:화이트',
    '1170fi253br01f008001' : '컬러:블랙',
    '1100fs261sc01x010001' : '컬러:블랙',
    '1170fi253mp13f005032' : '컬러:크림',
    '11001xm02854h001' : '컬러:블랙',
    '1100fs261tn03x007001' : '컬러:블랙',
    '11001xm02853h920' : '컬러:베이지',
    '1170fi4bfh1123mblk' : '컬러:블랙',
    '1100fs262ts11u003452' : '컬러:블루',
    '1100fs262rs01f012191' : '컬러:화이트',
    '1100fs261od03x005100' : '컬러:화이트',
    '1100fs253od03x017001' : '컬러:블랙',
    '1100fs262jk01u003234' : '컬러:브라운',
    '1100fs261eq01x001001' : '컬러:블랙',
    '1170fi261bf07f001217' : '컬러:브라운',
    '1170fi4bah1450flml' : '컬러:라이트멜란지',
    '1170fi4bah1105fwod' : '컬러:우드',
    '1100fs261tn03x007100' : '컬러:화이트',
    '1100fs261od03x008734' : '컬러:옐로우',
    '1100fs261sc01x009001' : '컬러:블랙',
    '1170fi4bfh1121fwhi' : '컬러:화이트',
    '1100fs261ru02x003031' : '컬러:그레이',
    '1170fi261bf01f013660' : '컬러:그레이',
    '1170fi261br01f022100' : '컬러:화이트',
    '11001rm02942h002' : '컬러:블랙',
    '1170fi4bah1450fblk' : '컬러:블랙',
    '1100fs261rl01x001581' : '컬러:퍼플',
    '1170fi261dr01f025217' : '컬러:브라운',
    '1170fi261bf01f007001' : '컬러:블랙',
    '1170fi4bfg3171fotl' : '컬러:오트밀',
    '1170fi253br01f008260' : '컬러:다크베이지',
    '1170fi4bah1103fwhi' : '컬러:화이트',
    '1170fi253fz13f004032' : '컬러:크림',
    '1100fs262tr11m008191' : '컬러:화이트',
    '1100fs261fp01u001001' : '컬러:블랙',
    '1100fs261od03x009613' : '컬러:레드',
    '1100fs261cp01x002001' : '컬러:블랙',
    '1100fs261fp02u001001' : '컬러:블랙',
    '1100fs261od03x006260' : '컬러:베이지',
    '1100fs261od03x010110' : '컬러:화이트',
    '1260fv254dr17f001660' : '컬러:핑크',
    '1170fi261br01f023100' : '컬러:화이트',
    '1170fi261bf01f009100' : '컬러:화이트',
    '1170fi4ith1116fblk' : '컬러:블랙',
    '11001tm01987h822' : '컬러:오렌지',
    '1100fs261bc01f002150' : '컬러:화이트',
    '1100fs261ru03x052031' : '컬러:그레이',
    '1100fs262wp01x002002' : '컬러:블랙',
    '1100fs261ft01x001496' : '컬러:블루',
    '1170fi253jb13u001260' : '컬러:크림',
    '1170fi261dr01m015001' : '컬러:블랙',
    '1170fi261br01f009066' : '컬러:그레이',
    '1100fs261ru02x022100' : '컬러:화이트',
    '1100fs261eq01x001150' : '컬러:화이트',
    '1170fi261br01f023660' : '컬러:핑크',
    '11001xm02852h600' : '컬러:레드',
    '1170fi4cmh1124fmit' : '컬러:민트',
    '1170fi261wr01u001217' : '컬러:브라운',
    '1170fi4drh1103fwod' : '컬러:우드',
    '1170fi253fz13f003032' : '컬러:크림',
    '1170fi261br01f009613' : '컬러:레드',
    '1170fi261br01f009001' : '컬러:블랙',
    '1170fi253jb13u002452' : '컬러:블루',
    '1100fs261bs01f001442' : '컬러:블루',
    '1170fi4bah1113fwhi' : '컬러:화이트',
    '11001xm02854h100' : '컬러:화이트',
    '1170fi4drh1101fdrd' : '컬러:다크레드',
    '1170fi4bag3171fpbl' : '컬러:퍼플',
    '1170fi4bah1102fdro' : '컬러:드라이로즈',
    '1170fi4bah1123fmit' : '컬러:민트',
    '1170fi253mp13f003034' : '컬러:크림',
    '1170fi261br01f033217' : '컬러:브라운',
    '1170fi4drg3177fwod' : '컬러:우드',
    '1100fs262rs01u001191' : '컬러:화이트',
    '1170fi4bah1112fblk' : '컬러:블랙',
    '1170fi261bf01f006100' : '컬러:화이트',
    '1170fi253fz13f004001' : '컬러:블랙',
    '1170fi4tkg3171flml' : '컬러:라이트멜란지',
    '1170fi4bah1103fwod' : '컬러:우드',
    '1170fi261bf01f007412' : '컬러:민트',
    '1170fi261bf01f006650' : '컬러:핑크',
    '1170fi4tkg3171fblk' : '컬러:블랙',
    '1170fi4tkg3171fdtg' : '컬러:더스티그린',
    '1170fi4tkh1101flml' : '컬러:라이트멜란지',
    '1260fv254dr17f001370' : '컬러:그린',
    '1100fs261eq01x001442' : '컬러:블루',
    '1170fi253mp13f003001' : '컬러:블랙',
    '1170fi4bah1123fblk' : '컬러:블랙',
    '1170fi253jt13u001613' : '컬러:레드',
    '1170fi253jb13u001371' : '컬러:그린',
    '1170fi253jb13f001452' : '컬러:블루',
    '1170fi253jb13u002371' : '컬러:그린',
    '1170fi261mt13f002032' : '컬러:크림',
    '1100fs261fp01x003001' : '컬러:블랙',
    '1170fi4rsh1145mwhi' : '컬러:화이트',
    '1170fi4drg1448fpbg' : '컬러:페일베이지',
    '1170fi261br01f009452' : '컬러:블루',
    '1170fi261br01f024100' : '컬러:화이트',
    '1170fi4drh1102flml' : '컬러:라이트멜란지',
    '1170fi253dr01f008217' : '컬러:라이트브라운',
    '1100fs262rs02u001472' : '컬러:블루',
    '1170fi4rnh1101fcrm' : '컬러:크림',
    '1100fs261tl01f001626' : '컬러:레드',
    '1100fs262sk01f001175' : '컬러:화이트',
    '1100fs262jk11x001191' : '컬러:화이트',
    '1170fi4bah1112fore' : '컬러:오렌지',
    '1170fi261bf01f006066' : '컬러:그레이',
    '1170fi253br01f008820' : '컬러:내추럴베이지',
    '1170fi253br01f001001' : '컬러:블랙',
    '1100fs261bp01x003022' : '컬러:그레이',
    '1170fi261dr01f025071' : '컬러:그레이',
    '1170fi4drg3178flbr' : '컬러:라이트브라운',
    '1100fs261sl03x002370' : '컬러:그린',
    '1100fs253ru02x001217' : '컬러:브라운',
    '1100fs262jk02f005442' : '컬러:블루',
    '1170fi4drh1103flml' : '컬러:라이트멜란지',
    '1170fi253br01f001820' : '컬러:내추럴베이지',
    '1170fi261br07f005-32001' : '컬러:블랙',
    '1100fs261fp01f003650' : '컬러:핑크',
    '1170fi4bfh1123fred' : '컬러:레드',
    '1100fs261po01x002650' : '컬러:핑크',
    '1170fi253dr01f008260' : '컬러:다크베이지',
    '11001jm02570h001' : '컬러:블랙',
    '1170fi253jo13f002217' : '컬러:브라운',
    '1170fi261bf07f001660' : '컬러:핑크',
    '1170fi261br07f006100' : '컬러:화이트',
    '1170fi253dr01f007820' : '컬러:내추럴베이지',
    '1170fi261bf01f010175' : '컬러:화이트',
    '1100fs261bs01f001670' : '컬러:핑크',
    '1100fs261po01x005442' : '컬러:블루',
    '1100fs262jk01x001191' : '컬러:화이트',
    '1170fi4bfh1112fblk' : '컬러:블랙',
    '1100fs262su11x002472' : '컬러:블루',
    '1170fi4bah1114fred' : '컬러:레드',
    '1170fi4drh1103fwhi' : '컬러:화이트',
    '1170fi4drg3178fipk' : '컬러:인디안핑크',
    '1170fi4bah1111fdgr' : '컬러:다크그린',
    '1170fi4bah1111flml' : '컬러:라이트멜란지',
    '1100fs3bph1004xblk' : '컬러:블랙',
    '1170fi253dr07f006-35452' : '컬러:블루',
    '1100fs262rs01f005001' : '컬러:블랙',
    '1170fi4bfh1122fmit' : '컬러:민트',
    '1100fs261fp01u001234' : '컬러:브라운',
    '1100fs261tn03x005031' : '컬러:그레이',
    '1100fs253od03x017260' : '컬러:베이지',
    '1100fs261tn03x002001' : '컬러:블랙',
    '1170fi261dr07f004-32072' : '컬러:그레이',
    '1170fi261br07f005-32071' : '컬러:그레이',
    '1170fi4bfh1112fred' : '컬러:레드',
    '1170fi4bah1121fepk' : '컬러:페일핑크',
    '1170fi4bah1111fore' : '컬러:오렌지',
    '1170fi4bah1123fwhi' : '컬러:화이트',
    '1100fs261ru02x004002' : '컬러:블랙',
    '1100fs261ru03x045001' : '컬러:블랙',
    '1100fs261ru02x049002' : '컬러:블랙',
    '1100fs262wp01x004001' : '컬러:블랙',
    '1100fs261ru03x012147' : '컬러:화이트',
    '1100fs262jk01u003175' : '컬러:화이트',
    '1100fs261bc01x005001' : '컬러:블랙',
    '1100fs261ru03x052734' : '컬러:옐로우',
    '1170fi261br01f023101' : '컬러:블루',
    '11001tm01987h117' : '컬러:화이트',
    '1170fi253dr07f006-35422' : '컬러:블루',
    '1100fs261od03x006452' : '컬러:블루',
    '1100fs261ru02x005660' : '컬러:핑크',
    '1100fs261tn03x006820' : '컬러:오렌지',
    '11001xm02852h050' : '컬러:그레이',
    '1100fs262rs01f012001' : '컬러:블랙',
    '1170fi261bf01f007101' : '컬러:레드',
    '1170fi4bah1121fblk' : '컬러:블랙',
    '1170fi4bfh1112flml' : '컬러:라이트멜란지',
    '1170fi4hph1002mdpt' : '컬러:딥틸',
    '1170fi4ith1116fdgr' : '컬러:다크그린',
    '1170fi4bfh1112fwhi' : '컬러:화이트',
    '1170fi253dr01f007001' : '컬러:블랙',
    '1170fi4ith1116fwhi' : '컬러:화이트',
    '1170fi4rnh1101fpbl' : '컬러:퍼플',
    '1170fi4bah1105fblk' : '컬러:블랙',
    '1170fi4bfh1102flml' : '컬러:라이트멜란지',
    '1170fi4bfh1113fred' : '컬러:레드',
    '1100fs261cp01x016476' : '컬러:블루',
    '1100fs262rs01x021001' : '컬러:블랙',
    '1170fi4bah1113fblk' : '컬러:블랙',
    '1170fi261br01f033660' : '컬러:핑크',
    '1100fs261ru02x049261' : '컬러:베이지',
    '1170fi261cm01f001067' : '컬러:블랙',
    '1170fi4bfh1103flbe' : '컬러:라이트베이지',
    '1170fi261cm01f001412' : '컬러:민트',
    '1170fi4cmh1124fidb' : '컬러:블루',
    '1170fi261bf01f006456' : '컬러:블루',
    '1100fs261ru02x001820' : '컬러:오렌지',
    '1170fi253jt13u001260' : '컬러:크림',
    '1170fi261bf01f013100' : '컬러:화이트',
    '1170fi261br01f023661' : '컬러:그레이',
    '1170fi261bf01f007100' : '컬러:화이트',
    '1170fi4bfh1122fblk' : '컬러:블랙',
    '1100fs262rs01x018191' : '컬러:화이트',
    '1100fs261ru02x002001' : '컬러:블랙',
    '1170fi253dr01f008001' : '컬러:블랙',
    '1260fv254dr17f001261' : '컬러:블랙',
    '1170fi4bah1104flml' : '컬러:라이트멜란지',
    '1170fi4tkg3171fotl' : '컬러:오트밀',
    '1100fs262rs01x021380' : '컬러:그린',
    '1100fs261fp01f003290' : '컬러:베이지',
    '1170fi4bah1122fwhi' : '컬러:화이트',
    '1100fs261od03x005101' : '컬러:화이트',
    '1100fs261bp01x011450' : '컬러:블루',
    '1100fs262tr02u002001' : '컬러:블랙',
    '1100fs261po01x009626' : '컬러:레드',
    '1170fi4hph1005mcgy' : '컬러:차콜그레이',
    '1170fi261bf01f012151' : '컬러:그레이',
    '1170fi261bf01f012541' : '컬러:퍼플',
    '1170fi4bah1102flml' : '컬러:라이트멜란지',
    '1170fi261br01f009652' : '컬러:핑크',
    '1170fi4bah1104fcrm' : '컬러:크림',
    '1170fi4drh1111flml' : '컬러:라이트멜란지',
    '1100fs261ru02x005260' : '컬러:베이지',
    '1170fi4drh1103flbr' : '컬러:라이트브라운',
    '1170fi253br01f008217' : '컬러:라이트브라운',
    '1170fi261br01f025442' : '컬러:블루',
    '1170fi4drh1103flbe' : '컬러:라이트베이지',
    '1100fs262bc01x001001' : '컬러:블랙',
    '1100fs261ru02x022001' : '컬러:블랙',
    '1100fs262cp11x002191' : '컬러:화이트',
    '1170fi4bfh1102fpbe' : '컬러:페일블루',
    '1100fs262rs01f020650' : '컬러:핑크',
    '1170fi253jb13f001001' : '컬러:블랙',
    '1100fs262tr02u001476' : '컬러:블루',
    '1100fs262rs01x018001' : '컬러:블랙',
    '1100fs261sl03x002260' : '컬러:베이지',
    '1170fi253br12f002001' : '컬러:블랙',
    '1170fi261br01f022661' : '컬러:화이트',
    '1170fi253br01f009217' : '컬러:브라운',
    '1170fi4bfh1122flml' : '컬러:라이트멜란지',
    '1170fi4cmh1124fepk' : '컬러:페일핑크',
    '1170fi4ith1041flpm' : '컬러:라이트플럼',
    '1100fs261sk01f002234' : '컬러:브라운',
    '1100fs261cp01x012001' : '컬러:블랙',
    '1170fi261bf01f010660' : '컬러:핑크',
    '1100fs261sk01f001260' : '컬러:베이지',
    '1100fs261bp01x005191' : '컬러:화이트',
    '1100fs262tr11m002462' : '컬러:블루',
    '1170fi261br01f023175' : '컬러:화이트',
    '1100fs261ru02x004660' : '컬러:핑크',
    '1170fi261br01f032250' : '컬러:베이지',
    '1170fi4sch1148xblk' : '컬러:블랙',
    '1100fs261od03x100031' : '컬러:그레이',
    '1100fs261od03x100100' : '컬러:화이트',
    '1100fs261sc01x005191' : '컬러:화이트',
    '1170fi4bfh1123fmit' : '컬러:민트',
    '1100fs3bsh1201xowh' : '컬러:오프화이트',
    '1170fi253jb13f001371' : '컬러:그린',
    '1170fi253jt13u001371' : '컬러:그린',
    '1170fi4drh1111fwhi' : '컬러:화이트',
    '1170fi4drh1111fdgr' : '컬러:다크그린',
    '1170fi4drh1111fblk' : '컬러:블랙',
    '1170fi4bah1113fdgr' : '컬러:다크그린',
    '1170fi4drh1103fipk' : '컬러:인디안핑크',
    '1170fi261dr01f025001' : '컬러:블랙',
    '1170fi261br07f006001' : '컬러:블랙',
    '1170fi4bah1103fipk' : '컬러:인디안핑크',
    '1170fi4bah1103flbr' : '컬러:라이트브라운',
    '1100fs262bd11x006175' : '컬러:화이트',
    '1100fs262sd03x001031' : '컬러:그레이',
    '1100fs262tr01u001066' : '컬러:그레이',
    '1100fs261ru02x003001' : '컬러:블랙',
    '1170fi4ith1116flml' : '컬러:라이트멜란지',
    '1170fi261bf01f012371' : '컬러:블루',
    '1170fi4drg3178flml' : '컬러:라이트멜란지',
    '1170fi4bfh1121fmit' : '컬러:민트',
    '1170fi4tkh1626mmao' : '컬러:망고',
    '1170fi4bah1122fblk' : '컬러:블랙',
    '1100fs262ft02u003651' : '컬러:핑크',
    '1170fi4drh1102fblk' : '컬러:블랙',
    '1170fi261br01f025660' : '컬러:핑크',
    '1170fi261br01f009412' : '컬러:민트, 블루',
    '1170fi261bf01f014001' : '컬러:블랙',
    '1170fi261bf01f010031' : '컬러:그레이',
    '1170fi261dr07f004-32001' : '컬러:블랙',
    '1170fi261bf01f012660' : '컬러:핑크',
    '1170fi4drh1102fipk' : '컬러:인디안핑크',
    '1170fi261bf07f001250' : '컬러:베이지',
    '1170fi261br01f008066' : '컬러:그레이',
    '1100fs261tn03x006260' : '컬러:베이지',
    '11001xm02853h200' : '컬러:브라운',
    '1100fs261bc01f001260' : '컬러:베이지',
    '1170fi4bfh1113fwhi' : '컬러:화이트',
    '1170fi253br07f015-35452' : '컬러:블루',
    '1100fs261fp02u003066' : '컬러:그레이',
    '1170fi4drh1041flpm' : '컬러:라이트플럼',
    '1100fs262rs01x022041' : '컬러:그레이',
    '1170fi261br01f008650' : '컬러:핑크',
    '1170fi253bf01f003820' : '컬러:내추럴베이지',
    '1170fi253dr01m009260' : '컬러:내추럴베이지',
    '1170fi253br01f001217' : '컬러:라이트브라운',
    '1100fs261bc01x001234' : '컬러:브라운',
    '1170fi4tkg3171fpbe' : '컬러:페일블루',
    '1170fi4acg0002xwhi' : '컬러:화이트',
    '1100fs261ru03x045217' : '컬러:브라운',
    '1170fi4bah1103fblk' : '컬러:블랙',
    '1170fi4drg3178flbe' : '컬러:라이트베이지',
    '1100fs261ft01f004290' : '컬러:베이지',
    '1100fs262rs02x012191' : '컬러:화이트',
    '1100fs262op11f004191' : '컬러:화이트',
    '1170fi261bf01f012150' : '컬러:화이트',
    '1170fi261mt13f002001' : '컬러:블랙',
    '1170fi261br01f025071' : '컬러:그레이',
    '1170fi261bf01f007452' : '컬러:블루',
    '1100fs262tr02u002021' : '컬러:그레이',
    '1170fi253br12f002031' : '컬러:플럼',
    '1100fs262tr02u001001' : '컬러:블랙',
    '1100fs262rs01x023660' : '컬러:핑크',
    '1100fs261po01x004001' : '컬러:블랙',
    '1170fi261bf01f005001' : '컬러:블랙',
    '1170fi4bah1114fore' : '컬러:오렌지',
    '1100fs262rs01x027650' : '컬러:핑크',
    '1170fi4drh1111fred' : '컬러:레드',
    '1100fs253od03x033101' : '컬러:화이트',
    '1100fs261ft02u001472' : '컬러:블루',
    '1100fs261bc01f009650' : '컬러:핑크',
    '1170fi4bah1114flml' : '컬러:라이트멜란지',
    '1100fs261po01f002442' : '컬러:블루',
    '1170fi4drh1410mdrd' : '컬러:다크레드',
    '1170fi4bah1114fblk' : '컬러:블랙',
    '1100fs262wp02u001001' : '컬러:블랙',
    '11001rm02723h050' : '컬러:그레이',
    '1100fs262jk01f001521' : '컬러:퍼플',
    '1170fi253br01f009001' : '컬러:블랙',
    '11001xm02852h001' : '컬러:블랙',
    '1170fi253br01f009031' : '컬러:그레이',
    '1170fi4ith1116fred' : '컬러:레드',
    '1170fi4ith1042fsbu' : '컬러:스카이블루',
    '1170fi4acg0001xwhi' : '컬러:화이트',
    '1100fs262rs01x007061' : '컬러:그레이',
    '1170fi4bfh1113fblk' : '컬러:블랙',
    '1100fs261fp01f002001' : '컬러:블랙',
    '1100fs261ft01f004650' : '컬러:핑크',
    '1170fi261dr01f025100' : '컬러:화이트',
    '1170fi253bf01f003001' : '컬러:블랙',
    '1170fi4cmh1124fblk' : '컬러:블랙',
    '1170fi4rnh1101fdro' : '컬러:드라이로즈',
    '1100fs262fp02u002234' : '컬러:브라운',
    '1100fs262rs01x013001' : '컬러:블랙',
    '1170fi261br01f025370' : '컬러:그린',
    '1170fi261bf01f012370' : '컬러:그린',
    '1170fi4bfh1113fore' : '컬러:오렌지',
    '1100fs253od03x033001' : '컬러:블랙',
    '1170fi253jo13f002452' : '컬러:블루',
    '1170fi4hph1005mhpk' : '컬러:핫핑크',
    '1100fs261sc01x010191' : '컬러:화이트',
    '1100fs262sd03x001734' : '컬러:옐로우',
    '1170fi4tkh1638mnbe' : '컬러:네이비블루',
    '1170fi261br01f028100' : '컬러:화이트',
    '1100fs262tr02u001234' : '컬러:브라운',
    '1100fs262fp02u003001' : '컬러:블랙',
    '1100fs262wp01x003380' : '컬러:그린',
    '1100fs261tn03x002101' : '컬러:화이트',
    '1100fs262rs02u007234' : '컬러:브라운',
    '1100fs261sl03x003660' : '컬러:핑크',
    '1100fs261od03x007260' : '컬러:베이지',
    '1100fs262tr02u002626' : '컬러:레드',
    '1170fi261dr01f025661' : '컬러:레드',
    '1100fs261bc01f008650' : '컬러:핑크',
    '1100fs261bc01x001001' : '컬러:블랙',
    '1170fi4bfh1112fore' : '컬러:오렌지',
    '1170fi261bf01f007650' : '컬러:핑크',
    '1170fi261bf07f001001' : '컬러:블랙',
    '1170fi261br07f006660' : '컬러:핑크',
    '1170fi261br07f006071' : '컬러:그레이',
    '1170fi261bf01f014100' : '컬러:화이트',
    '1170fi4bah1111fred' : '컬러:레드',
    '1170fi261br01f028001' : '컬러:블랙',
    '1100fs261fp01x003066' : '컬러:그레이',
    '1100fs261sc01x005217' : '컬러:브라운',
    '1100fs262sc11x001191' : '컬러:화이트',
    '1100fs262sc11x001014' : '컬러:블랙',
    '1170fi253br01f011217' : '컬러:라이트브라운',
    '1170fi261bf01f005650' : '컬러:핑크',
    '1170fi4bah1113flml' : '컬러:라이트멜란지',
    '1170fi4bah1111fblk' : '컬러:블랙',
    '1170fi261bf07f001002' : '컬러:화이트',
    '1170fi253br01f009820' : '컬러:오렌지',
    '1170fi4cmh1124flml' : '컬러:라이트멜란지',
    '1100fs262cp02x002191' : '컬러:화이트',
    '1170fi261br01f029001' : '컬러:블랙',
    '1170fi4tkg3171fdro' : '컬러:드라이로즈',
    '1100fs261fp02u003001' : '컬러:블랙',
    '1170fi4ith1116fore' : '컬러:오렌지',
    '1170fi4bah1121fwhi' : '컬러:화이트',
    '1100fs261po01x002472' : '컬러:블루',
    '1100fs261tn03x002100' : '컬러:화이트',
    '1100fs261od03x039021' : '컬러:그레이',
    '1170fi4poh1147mblk' : '컬러:블랙',
    '1100fs262jk02x001001' : '컬러:블랙',
    '1100fs262ft02u003234' : '컬러:브라운',
    '1100fs262jk02f001442' : '컬러:블루',
    '1100fs262fp02f001001' : '컬러:블랙',
    '1170fi4hth1001mcgy' : '컬러:차콜그레이',
    '1100fs262fp02u002001' : '컬러:블랙',
    '1100fs261ru04x006452' : '컬러:블루',
    '1170fi4cmh1124fwhi' : '컬러:화이트',
    '1170fi261br01f028260' : '컬러:베이지',
    '1170fi4bah1122flml' : '컬러:라이트멜란지',
    '1170fi261bf01f005066' : '컬러:그레이',
    '1170fi253br12f001650' : '컬러:핑크',
    '1100fs262jk02u002191' : '컬러:화이트',
    '1170fi253br01f010001' : '컬러:블랙',
    '1100fs261bp01x007150' : '컬러:화이트',
    '1170fi253br01f010820' : '컬러:내추럴베이지',
    '1100fs261bs01f001260' : '컬러:베이지',
    '1170fi4bfg3177fwhi' : '컬러:화이트',
    '1100fs261fp02u002001' : '컬러:블랙',
    '1170fi4ith1041fdem' : '컬러:데님',
    '1170fi261dr01f021456' : '컬러:블루',
    '1170fi4rnh1101flml' : '컬러:라이트멜란지',
    '1170fi261br01f022101' : '컬러:블루',
    '1170fi261br01f029456' : '컬러:블루',
    '1170fi261bf01f014101' : '컬러:베이지',
    '1170fi261bf01f016071' : '컬러:그레이',
    '1100fs261cp01x010442' : '컬러:블루',
    '1170fi4rnh1117flml' : '컬러:라이트멜란지',
    '1170fi4drh1111fore' : '컬러:오렌지',
    '1170fi4bah1111fwhi' : '컬러:화이트',
    '1100fs262tr01u001001' : '컬러:블랙',
    '1170fi4bfh1113flml' : '컬러:라이트멜란지',
    '1170fi261br01f008456' : '컬러:블루',
    '1100fs261bp01x002001' : '컬러:블랙',
    '1100fs261ru02x004370' : '컬러:그린',
    '1170fi261br01f025001' : '컬러:블랙',
    '1170fi4bah1122fmit' : '컬러:민트',
    '1100fs261sc01x005001' : '컬러:블랙',
    '1100fs262sd03x001001' : '컬러:블랙',
    '1100fs262rs01x021191' : '컬러:화이트',
    '1100fs261ft01x002293' : '컬러:베이지',
    '1170fi261br01f027100' : '컬러:화이트',
    '1170fi261bf01f015101' : '컬러:베이지',
    '1170fi253jb13u002001' : '컬러:블랙',
    '1100fs261ft01x005001' : '컬러:블랙',
    '1100fs262wp02u001472' : '컬러:블루',
    '1100fs261fp01f002234' : '컬러:브라운',
    '1170fi261dr01f025250' : '컬러:베이지',
    '1170fi253jt13u001452' : '컬러:블루',
    '1170fi261cm01f001100' : '컬러:화이트',
    '1100fs262rs02u001001' : '컬러:블랙',
    '1100fs261fp01x002001' : '컬러:블랙',
    '1100fs261ft02u003001' : '컬러:블랙',
    '1100fs262po02x001001' : '컬러:블랙',
    '1100fs262fp02f002001' : '컬러:블랙',
    '1100fs261od03x046001' : '컬러:블랙',
    '1100fs261ru02x005100' : '컬러:화이트',
    '1100fs261od03x010001' : '컬러:블랙',
    '1170fi4rnh1101fblk' : '컬러:블랙',
    '1100fs262rs01x033452' : '컬러:블루',
    '1170fi4bfh1122fwhi' : '컬러:화이트',
    '1100fs261ru02x001100' : '컬러:화이트',
    '1170fi261bf01f010100' : '컬러:화이트',
    '1170fi4bah1112flml' : '컬러:라이트멜란지',
    '1170fi253jt13u001217' : '컬러:브라운',
    '1170fi4rnh1101fdtg' : '컬러:더스티그린',
    '1170fi4ewh1148mblk' : '컬러:블랙',
    '1170fi4tkg3171fpbl' : '컬러:퍼플',
    '1100fs262bd11x003191' : '컬러:화이트',
    '1170fi261bf01f016001' : '컬러:블랙',
    '1170fi261br01f022031' : '컬러:그레이',
    '1170fi261cm01f001066' : '컬러:그레이',
    '1170fi4bah1112fwhi' : '컬러:화이트',
    '1100fs261ft01f004001' : '컬러:블랙',
    '1100fs261ru02x001370' : '컬러:그린',
    '1100fs261bc01f007150' : '컬러:화이트',
    '1170fi4hph1002mmly' : '컬러:멜란지그레이',
    '1170fi253dr07f006-35296' : '컬러:베이지',
    '1100fs261ru02x049370' : '컬러:그린',
    '1170fi253dr12m001100' : '컬러:화이트',
    '1100fs262ft02u002001' : '컬러:블랙',
    '1170fi4rnh1101fpbe' : '컬러:페일블루',
    '1100fs261po01x004290' : '컬러:베이지',
    '1100fs261sl03x004452' : '컬러:블루',
    '1100fs262fp02u001001' : '컬러:블랙',
    '1100fs262tr02u002442' : '컬러:블루',
    '1170fi261br01f029260' : '컬러:베이지',
    '1100fs261bp01x003650' : '컬러:핑크',
    '1100fs261po01x005001' : '컬러:블랙',
    '1170fi4drh1042fsbu' : '컬러:스카이블루',
    '1100fs261jk01f001217' : '컬러:브라운',
    '1170fi4drh1042fblk' : '컬러:블랙',
    '1100fs261sc01x005717' : '컬러:옐로우',
    '1170fi253bf01f003260' : '컬러:다크베이지',
    '1170fi253br07f015-35296' : '컬러:베이지',
    '1170fi4bah1121flml' : '컬러:라이트멜란지',
    '1100fs262rs01u009001' : '컬러:블랙',
    '1100fs261sl03x003001' : '컬러:블랙',
    '1100fs261ru04x003100' : '컬러:화이트',
    '1170fi4drh1121mblk' : '컬러:블랙',
    '1100fs261bp01x007001' : '컬러:블랙',
    '1100fs262rs02u007001' : '컬러:블랙',
    '1100fs262fp02u003443' : '컬러:블루',
    '1170fi253jb13u002613' : '컬러:레드',
    '1170fi4bfh1113fdgr' : '컬러:다크그린',
    '1100fs261od03x007031' : '컬러:그레이',
    '1100fs261rl02u001001' : '컬러:블랙',
    '1170fi4bah1114fdgr' : '컬러:다크그린',
    '1170fi253jb13u001452' : '컬러:블루',
    '1170fi253jb13u001217' : '컬러:브라운',
    '1100fs262rs02x011400' : '컬러:블루',
    '1100fs262fp02u003476' : '컬러:블루',
}

mask = df_review_fila_D2C['purchase_option'].isna()

df_review_fila_D2C.loc[mask, 'purchase_option'] = (
    df_review_fila_D2C.loc[mask, 'product_id'].map(mapping)
)

# df_review_fila_D2C['purchase_option'].isna().sum() >>>>>>>>>>> 결측치 사라진 것 확인 완료

In [36]:
# 2) mapping에 없는 product_id 확인하기
# >>>>>>>>>> 없는 거 추가 매핑 하기 전의 데이터
not_in_mapping = df_review_fila_D2C[
    ~df_review_fila_D2C['product_id'].isin(mapping.keys())
]['product_id'].unique()

pd.set_option('display.max_rows', None) # 행 보이기
print(f"mapping에 없는 product_id: {len(not_in_mapping)}개")
print(not_in_mapping)

mapping에 없는 product_id: 0개
<ArrowStringArray>
[]
Length: 0, dtype: str

In [37]:
# 3) 전체 출력 (안 잘리게)

not_in_mapping_list = pd.Series(not_in_mapping).tolist()

print(f"mapping에 없는 product_id: {len(not_in_mapping_list)}개")
for pid in not_in_mapping_list:
    print(pid)

mapping에 없는 product_id: 0개

In [38]:
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].astype(str)
df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       10355 non-null  datetime64[us]
 1   platform           10355 non-null  str
 2   review_id          10355 non-null  int64
 3   product_id         10355 non-null  str
 4   product_name       10355 non-null  str
 5   review_date        10355 non-null  datetime64[us]
 6   year               10355 non-null  int32
 7   month              10355 non-null  int32
 8   content            10355 non-null  str
 9   rating             10355 non-null  int64
 10  helpful_count      10355 non-null  int64
 11  has_image          10355 non-null  int64
 12  purchase_option    10355 non-null  str
 13  user_size          0 non-null      object
 14  user_height        0 non-null      object
 15  user_weight        0 non-null      object
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        10355 non-null  str
dtypes: datetime64[us](2), int32(2), int64(4), object(5), str(6)
memory usage: 4.5+ MB

In [39]:
# ============================
# 데이터 타입 변경하기
# ============================
df_review_fila_D2C['platform'] = df_review_fila_D2C['platform'].astype('category')
df_review_fila_D2C['purchase_option'] = df_review_fila_D2C['purchase_option'].astype('category')

In [41]:
# ====================
# 실시간 데이터 확인
# ====================
df_review_fila_D2C.info()
df_review_fila_D2C.head()

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       10355 non-null  datetime64[us]
 1   platform           10355 non-null  category
 2   review_id          10355 non-null  int64
 3   product_id         10355 non-null  str
 4   product_name       10355 non-null  str
 5   review_date        10355 non-null  datetime64[us]
 6   year               10355 non-null  int32
 7   month              10355 non-null  int32
 8   content            10355 non-null  str
 9   rating             10355 non-null  int64
 10  helpful_count      10355 non-null  int64
 11  has_image          10355 non-null  int64
 12  purchase_option    10355 non-null  category
 13  user_size          0 non-null      object
 14  user_height        0 non-null      object
 15  user_weight        0 non-null      object
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        10355 non-null  str
dtypes: category(2), datetime64[us](2), int32(2), int64(4), object(5), str(4)
memory usage: 4.2+ MB

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-23,자사몰,110919,1100fs253od03x012217,<차정원 착용> 휠라 에샤페 LX 브릭,2024-09-11,2024,9,! 올 가을 운동화는 에샤페 초코가 답이다 ! 초코 색감은 실제로 보면 더 이쁘구요...,5,1,1,브라운,None,None,None,None,None,https://www.fila.co.kr/product/1100fs253od03x0...
1,2026-04-23,자사몰,139596,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,2026-03-22,2026,3,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰""\n \n 01. 코트...",5,10,1,사이즈:250 / 컬러:핑크,None,None,None,None,None,https://www.fila.co.kr/product/1100fs261tn02x0...
2,2026-04-23,자사몰,128715,1100fs253od03x012260,휠라 에샤페 LX 모카,2025-10-07,2025,10,"""실물이 훨씬 예뻐요"", ""어떤 룩에도 잘 매치되어서 활용도가 높습니다.""",5,0,0,베이지,None,None,None,None,None,https://www.fila.co.kr/product/1100fs253od03x0...
3,2026-04-23,자사몰,139042,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,2026-03-15,2026,3,"""킹 리차드"" 영화에서 나왔던 테니스 선수들의 필라 스포츠 웨어들을 보며 필라의 클...",5,3,1,사이즈:275 / 컬러:핑크,None,None,None,None,None,https://www.fila.co.kr/product/1100fs261tn02x0...
4,2026-04-23,자사몰,141366,1100fs261tn02x001660,휠라 스피드서브 T9 2.0,2026-03-31,2026,3,"""휠라 스피드서브 2.0은 견고한 '힐 카운터' 설계 덕분에 베이스라인에서의 격렬한...",5,2,1,사이즈:265 / 컬러:핑크,None,None,None,None,None,https://www.fila.co.kr/product/1100fs261tn02x0...

In [42]:
# ============================
# 저장하기
# ============================

df_review_fila_D2C_2024 = df_review_fila_D2C[df_review_fila_D2C['year'] >= 2024]

df_review_fila_D2C.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final.csv", encoding='utf-8-sig', index=False)
df_review_fila_D2C_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final_s2024.csv", encoding='utf-8-sig', index=False)

---
# 휠라 무신사 리뷰 데이터

## 1. 전처리

In [43]:
# 파일 불러오기
import pandas as pd
import numpy as np

df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv")
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,...,option,helpful,comment_count,has_image,image_urls,survey_size,survey_width,survey_comfort,survey_instep,url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,스타일,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,기발한스웨덴웨지,NaN,...,Grey/White/White · 270,1,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,보통,아주 편안,https://www.musinsa.com/products/3892794#revie...
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,스타일,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,아트텍,NaN,...,Grey/White/White · 260,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,적당,https://www.musinsa.com/products/3892794#revie...
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,스타일,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,신중한하얀단화,NaN,...,Grey/White/White · 255,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,편안,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   collect_date    14100 non-null  str
 1   review_date     14100 non-null  str
 2   product_id      14100 non-null  int64
 3   product_name    14100 non-null  str
 4   review_no       14100 non-null  int64
 5   review_type     14100 non-null  str
 6   rating          14100 non-null  int64
 7   review_text     14090 non-null  str
 8   author          14100 non-null  str
 9   user_height     0 non-null      float64
 10  user_weight     0 non-null      float64
 11  option          14086 non-null  str
 12  helpful         14100 non-null  int64
 13  comment_count   14100 non-null  int64
 14  has_image       14100 non-null  bool
 15  image_urls      8621 non-null   str
 16  survey_size     4227 non-null   str
 17  survey_width    4227 non-null   str
 18  survey_comfort  4227 non-null   str
 19  survey_instep   4227 non-null   str
 20  url             14100 non-null  str
dtypes: bool(1), float64(2), int64(5), str(13)
memory usage: 7.6 MB

None

In [44]:
# =======================================
# 사용할 컬럼만 남기기
# =======================================
df_review_fila_mss = df_review_fila_mss.drop(['review_type', 'author', 'comment_count', 'image_urls', 'survey_size', 'survey_width', 'survey_comfort', 'survey_instep'], axis=1)
df_review_fila_mss.info() # 컬럼 13개

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  14100 non-null  str
 1   review_date   14100 non-null  str
 2   product_id    14100 non-null  int64
 3   product_name  14100 non-null  str
 4   review_no     14100 non-null  int64
 5   rating        14100 non-null  int64
 6   review_text   14090 non-null  str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        14086 non-null  str
 10  helpful       14100 non-null  int64
 11  has_image     14100 non-null  bool
 12  url           14100 non-null  str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 5.4 MB

In [45]:
# =======================================
# 결측치 처리
# =======================================
# 'review_text' => 14090개로 결측치 있음.

# 리뷰 텍스트 분석이 중요
df_review_fila_mss['review_text'].isna().mean()*100 # 0.07% => 행 제거로 결정

df_review_fila_mss = df_review_fila_mss.dropna(subset=['review_text'], axis=0)
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  14090 non-null  str
 1   review_date   14090 non-null  str
 2   product_id    14090 non-null  int64
 3   product_name  14090 non-null  str
 4   review_no     14090 non-null  int64
 5   rating        14090 non-null  int64
 6   review_text   14090 non-null  str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        14076 non-null  str
 10  helpful       14090 non-null  int64
 11  has_image     14090 non-null  bool
 12  url           14090 non-null  str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 5.5 MB

In [46]:
# =======================================
# 중복된 데이터 제거
# =======================================
df_review_fila_mss = df_review_fila_mss.drop_duplicates(subset=[
        'review_date', 'product_id', 'product_name', 'review_no', 'rating', 'review_text', 'user_height', 'user_weight', 'option', 'helpful', 'has_image', 'url'
])

df_review_fila_mss.shape # (8575, 13)

(8575, 13)

In [47]:
pd.set_option('display.max_colwidth', None)
print(df_review_fila_mss.duplicated(subset=['review_date', 'product_id', 'product_name', 'rating', 'review_text', 'user_height', 'user_weight', 'option']).sum())
display(df_review_fila_mss[df_review_fila_mss.duplicated(subset=['review_date', 'product_id', 'product_name', 'rating', 'review_text', 'user_height', 'user_weight', 'option'])].head())

366

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
386,2026-04-21 17:04:23,2024-07-08,3892794,에샤페 실버문(1XM02348H063),62186291,5,"이쁩니다, 맘에 들어요, 배송도 빠르구요~굿 good",NaN,NaN,NaN,0,True,https://www.musinsa.com/products/3892794#review_62186291
709,2026-04-21 17:04:23,2025-08-02,3892794,에샤페 실버문(1XM02348H063),77345201,5,실물이 더 예뻐요 메쉬라서 여름에 신기 좋고 발볼은 살짝 좁게 나와서 넓으면 반사이즈업 추천드립니다,NaN,NaN,Grey/White/White · 240,0,True,https://www.musinsa.com/products/3892794#review_77345201
799,2026-04-21 17:04:23,2025-06-30,3892794,에샤페 실버문(1XM02348H063),76303062,5,너무 이뻐요 발도 너무 편하고 사이즈도 딱 맞아요 ㅎㅎ 굳쟙입니다,NaN,NaN,Grey/White/White · 225,0,True,https://www.musinsa.com/products/3892794#review_76303062
880,2026-04-21 17:04:23,2025-06-19,3892794,에샤페 실버문(1XM02348H063),75601831,5,너무 과한 실버가 아닐까 걱정했는데 실물은 과하지 않고 포인트가 예쁘게 들어가 있는 신발 느낌입니다. 여름에 여기저기 다 잘 신을 것 같아요. 사이즈는 정사이즈 했더니 아주 약간 큰느낌입이다. 그런데 그냥 신고있어용 괜찮 ㅎㅎ,NaN,NaN,Grey/White/White · 240,0,True,https://www.musinsa.com/products/3892794#review_75601831
1040,2026-04-21 17:04:23,2025-05-13,3892794,에샤페 실버문(1XM02348H063),74160796,5,디자인 깔끔하고 착화감 편안해서 아주 맘에 들어요.,NaN,NaN,Grey/White/White · 225,0,True,https://www.musinsa.com/products/3892794#review_74160796

In [48]:
subset_cols = ['review_date', 'product_id', 'product_name', 'rating', 'review_text', 'user_height', 'user_weight', 'option']

# has_image 내림차순, helpful 내림차순 정렬 → 각 그룹에서 첫 번째 행만 남김
df_review_fila_mss = (
    df_review_fila_mss
    .sort_values(['has_image', 'helpful'], ascending=[False, False])
    .drop_duplicates(subset=subset_cols, keep='first')
    .sort_index()
)

df_review_fila_mss.shape # 8575 - 366 = 8209 (잘 지워진 것 확인 완료)

(8209, 13)

In [49]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  8209 non-null   str
 1   review_date   8209 non-null   str
 2   product_id    8209 non-null   int64
 3   product_name  8209 non-null   str
 4   review_no     8209 non-null   int64
 5   rating        8209 non-null   int64
 6   review_text   8209 non-null   str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        8201 non-null   str
 10  helpful       8209 non-null   int64
 11  has_image     8209 non-null   bool
 12  url           8209 non-null   str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 3.1 MB

In [50]:
# =======================================
# 결측치 처리
# =======================================
# option => 8개 결측치 있음
df_review_fila_mss['option'].isna().mean()*100 # 0.097%

# 에샤페 실버문(1XM02348H063) 상품에만 결측치 있음.
df_review_fila_mss[df_review_fila_mss['option'].isna()]

,collect_date,review_date,product_id,product_name,review_no,rating,review_text,user_height,user_weight,option,helpful,has_image,url
385,2026-04-21 17:04:23,2024-07-08,3892794,에샤페 실버문(1XM02348H063),62186309,5,"이쁩니다, 맘에 들어요, 배송도 빠르구요~굿 good",NaN,NaN,NaN,0,True,https://www.musinsa.com/products/3892794#review_62186309
2114,2026-04-21 17:04:23,2024-07-08,3892794,에샤페 실버문(1XM02348H063),62201621,5,에샤페 맨날 기다리다가 드디어 삿네요 ㅎㅎ 색감 넘 이뻐요 국굳,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62201621
2120,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62164947,5,예쁘다는 이야기 많이 들어요 포인트는 좋아요 착화감은 발 모양에 따라 많이 다를거 같아요,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62164947
2121,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62164761,5,전부터 맘에 들어 찜해놓다가 딸 선물로 사줬는데 너무 좋아하네요~발이 편하대요. 디자인도 이쁘구요~^^,NaN,NaN,NaN,1,True,https://www.musinsa.com/products/3892794#review_62164761
2122,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62164656,5,전부터 눈여겨보다가 고민끝에 구매했는데 맘에 들어요~^^,NaN,NaN,NaN,2,False,https://www.musinsa.com/products/3892794#review_62164656
2125,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62145658,5,상품은 생각보다 너무 마음에 들어요. 친구한테 추천도 해줘야지! 굿굿,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62145658
2127,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62136416,5,반짝반짝 너무 예쁘지 않나요?!?? 전 너무 맘에 들어요,NaN,NaN,NaN,0,True,https://www.musinsa.com/products/3892794#review_62136416
2128,2026-04-21 17:04:23,2024-07-07,3892794,에샤페 실버문(1XM02348H063),62136386,5,저런 여름 운동화 하나 갖고 싶었는데 무신사에 떠서 너무 좋아요 뜨자마자 바로 샀어요,NaN,NaN,NaN,0,False,https://www.musinsa.com/products/3892794#review_62136386

In [51]:
# option이 null인 product_id 추출
null_product_ids = df_review_fila_mss[df_review_fila_mss['option'].isna()]['product_id'].unique()

# 해당 product_id들의 option 분포 확인
df_review_fila_mss[df_review_fila_mss['product_id'].isin(null_product_ids)][['product_id', 'product_name', 'option']].value_counts(dropna=False)
# =>>> option = 범주형 데이터 => 최빈값으로 대체 (Grey/White/White · 240) => 결측치가 8개로 아주 작은 숫자라 대체해도 데이터 왜곡 적을 것임.

product_id  product_name           option
3892794     에샤페 실버문(1XM02348H063)  Grey/White/White · 240    736
                                   Grey/White/White · 235    458
                                   Grey/White/White · 250    454
                                   Grey/White/White · 245    452
                                   Grey/White/White · 230    419
                                   Grey/White/White · 255    169
                                   Grey/White/White · 225    100
                                   Grey/White/White · 260     79
                                   Grey/White/White · 220     54
                                   Grey/White/White · 265     50
                                   Grey/White/White · 270     38
                                   Grey/White/White · 275     32
                                   Grey/White/White · 280     32
                                   Grey/White/White · 290     15
                                   Grey/White/White · 285     11
                                   NaN                         8
                                   GREY/WHITE/WHITE · 245      5
                                   GREY/WHITE/WHITE · 240      4
                                   GREY/WHITE/WHITE · 285      3
                                   GREY/WHITE/WHITE · 230      3
                                   GREY/WHITE/WHITE · 235      3
                                   GREY/WHITE/WHITE · 250      2
                                   GREY/WHITE/WHITE · 265      2
                                   GREY/WHITE/WHITE · 220      1
                                   GREY/WHITE/WHITE · 275      1
Name: count, dtype: int64

In [52]:
df_review_fila_mss.loc[df_review_fila_mss['option'].isna(), 'option'] = 'Grey/White/White · 240'

print("===== 결측치 확인 ======")
print(df_review_fila_mss.info())
print("===== option 값 유지 확인 ======")
print(df_review_fila_mss['option'].value_counts())

===== 결측치 확인 ======
<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   collect_date  8209 non-null   str
 1   review_date   8209 non-null   str
 2   product_id    8209 non-null   int64
 3   product_name  8209 non-null   str
 4   review_no     8209 non-null   int64
 5   rating        8209 non-null   int64
 6   review_text   8209 non-null   str
 7   user_height   0 non-null      float64
 8   user_weight   0 non-null      float64
 9   option        8209 non-null   str
 10  helpful       8209 non-null   int64
 11  has_image     8209 non-null   bool
 12  url           8209 non-null   str
dtypes: bool(1), float64(2), int64(4), str(6)
memory usage: 3.1 MB
None
===== option 값 유지 확인 ======
option
Grey/White/White · 240        744
Brown/Brown/Brown · 240       483
Grey/White/White · 235        458
Grey/White/White · 250        454
Grey/White/White · 245        452
Grey/White/White · 230        419
Brown/Brown/Brown · 230       269
Brown/Brown/Brown · 245       231
Brown/Brown/Brown · 235       225
Brown/Brown/Brown · 250       216
Grey/White/White · 255        169
Beige/Beige/Beige · 240       147
BROWN/BROWN/BROWN · 240       127
Brown/Brown/Brown · 225       104
Grey/White/White · 225        100
Beige/Beige/Beige · 230        87
Black/Black/White · 240        84
Brown/Brown/Brown · 255        82
Grey/White/White · 260         79
Brown/Brown/Brown · 220        72
BROWN/BROWN/BROWN · 235        71
Beige/Beige/Beige · 250        69
Black/Black/Black · 240        69
Beige/Beige/Beige · 245        63
BROWN/BROWN/BROWN · 245        62
Brown/Brown/Brown · 260        62
BROWN/BROWN/BROWN · 230        60
Brown/Brown/Brown · 270        60
Grey/Grey/Grey · 240           58
BROWN/BROWN/BROWN · 250        57
Beige/Beige/Beige · 235        55
Grey/Grey/Grey · 245           55
White/Black/Grey · 240         55
Grey/White/White · 220         54
Grey/White/White · 265         50
Black/Black/Silver · 235       50
White/Black/Grey · 245         49
Brown/Brown/Brown · 265        47
Black/Black/Silver · 240       46
Grey/Grey/Grey · 235           46
Brown/Brown/Brown · 280        44
Black/Black/Black · 235        42
Black/Black/White · 230        41
Black/Black/White · 250        40
GREEN/GREEN/GREEN · 240        39
Grey/White/White · 270         38
White/Black/Grey · 235         38
Black/Black/Black · 230        38
Grey/Grey/Grey · 250           38
Black/Black/Black · 245        36
Black/Black/Black · 250        35
GREEN/GREEN/GREEN · 230        35
Black/Black/Silver · 245       33
Grey/White/White · 275         32
Grey/White/White · 280         32
BROWN/BROWN/BROWN · 255        29
Black/Black/Silver · 230       29
Grey/Grey/Grey · 230           28
GREEN/GREEN/GREEN · 250        28
Black/Grey/Black · 230         27
Black/Black/Silver · 250       26
GREEN/GREEN/GREEN · 245        26
Black/Black/Silver · 255       25
Grey/Grey/Grey · 255           25
BLACK/BLACK/WHITE · 240        25
GRAY/GRAY/GRAY · 240           25
Black/Grey/Black · 250         23
Brown/Brown/Brown · 275        22
White/Black/Grey · 250         22
GRAY/GRAY/GRAY · 245           22
Beige/Beige/Beige · 225        21
Black/Black/Silver · 270       21
Black/Black/Silver · 260       19
GREEN/GREEN/GREEN · 235        19
BROWN/BROWN/BROWN · 260        18
White/Black/Grey · 260         18
White/Black/Grey · 230         18
Grey/Blue/Grey · 240           18
BLACK/BLACK/WHITE · 245        18
GRAY/GRAY/GRAY · 235           18
BROWN/BROWN/BROWN · 225        17
BLACK/BLACK/WHITE · 230        17
Beige/Beige/Beige · 255        16
Beige/Beige/Beige · 265        16
Grey/Blue/Grey · 230           16
Black/Grey/Black · 235         16
Black/Grey/Black · 240         16
GRAY/GRAY/GRAY · 230           16
BEIGE/BEIGE/BEIGE · 240        16
Grey/White/White · 290         15
Beige/Beige/Beige · 220        15
BLACK/BLACK/WHITE · 250        15
Beige/Beige/Beige · 260        14
Grey/Grey/Grey · 225           14
GREEN/GREEN/GREEN · 225        14
BEIGE/BEIGE/BEIGE · 245        13
BLACK/WHITE/BROWN · 240        13
BROWN/BROWN/BROWN · 265        12
BEIGE/BEIGE/BEIGE · 235        12
Black/Black/Silver · 265       12
White/Black/Grey · 270         12
Black/Black/Black · 220        12
Grey/Blue/Grey · 250           12
Grey/White/White · 285         11
BROWN/BROWN/BROWN · 275        11
BROWN/BROWN/BROWN · 270        11
Pink/Pink/Pink · 220           11
BROWN/ORANGE/WHITE · 250       11
BEIGE/BEIGE/BEIGE · 250        11
White/Black/Grey · 255         10
Black/Black/Black · 255        10
Pink/Pink/Pink · 230           10
GREEN/GREEN/GREEN · 255        10
BROWN/ORANGE/WHITE · 240       10
BROWN/ORANGE/WHITE · 245       10
BLACK/WHITE/BROWN · 230        10
Brown/Brown/Brown · 290         9
BROWN/BROWN/BROWN · 220         9
BROWN/BROWN/BROWN · 280         9
White/Black/Grey · 225          9
Black/Black/Black · 225         9
Black/Black/White · 220         9
GRAY/GRAY/GRAY · 250            9
RED/RED/GRAY · 240              9
BLACK/WHITE/BROWN · 235         9
Beige/Beige/Beige · 270         8
Black/Black/Silver · 275        8
Black/Black/Silver · 280        8
White/Black/Grey · 280          8
BLACK/BLACK/WHITE · 235         8
Brown/Brown/Brown · 285         7
Black/Grey/Black · 270          7
GREEN/GREEN/GREEN · 260         7
BLACK/WHITE/BROWN · 245         7
BLACK/BLACK/BLACK · 240         6
Pink/Pink/Pink · 240            6
BLACK/BLACK/BLACK · 230         6
BROWN/ORANGE/YELLOW · 235       6
BROWN/ORANGE/YELLOW · 245       6
BROWN/ORANGE/WHITE · 230        6
BROWN/ORANGE/WHITE · 235        6
GREY/WHITE/WHITE · 245          5
White/Brown/White · 240         5
Beige/Beige/Beige · 280         5
White/Black/Grey · 265          5
Black/Black/White · 260         5
Black/Black/Black · 260         5
BLACK/BLACK/WHITE · 220         5
Pink/Pink/Pink · 250            5
GREEN/GREEN/GREEN · 220         5
BROWN/ORANGE/YELLOW · 250       5
BEIGE/BEIGE/BEIGE · 230         5
GRAY/GRAY/GRAY · 225            5
PINK/PINK/BLACK · 235           5
GREY/WHITE/WHITE · 240          4
Black/Black/Silver · 290        4
White/Black/Grey · 285          4
BLACK/BLACK/BLACK · 245         4
BLACK/BLACK/WHITE · 260         4
Black/Grey/Black · 245          4
Black/Grey/Black · 260          4
BROWN/ORANGE/WHITE · 280        4
BROWN/ORANGE/YELLOW · 240       4
BLACK/WHITE/BROWN · 250         4
BLUE/BLUE/BLUE · 240            4
GREY/WHITE/WHITE · 285          3
GREY/WHITE/WHITE · 230          3
GREY/WHITE/WHITE · 235          3
Beige/Beige/Beige · 290         3
White/Black/Grey · 275          3
White/Black/Grey · 220          3
GREY/GREY/GREY · 235            3
BLACK/BLACK/BLACK · 250         3
Black/Black/White · 280         3
Black/Grey/Black · 280          3
Black/Grey/Black · 255          3
Black/Grey/Black · 225          3
BLACK/BLACK/WHITE · 255         3
BROWN/ORANGE/WHITE · 260        3
BROWN/ORANGE/WHITE · 225        3
BROWN/ORANGE/YELLOW · 265       3
GRAY/GRAY/GRAY · 255            3
PINK/PINK/PINK · 240            3
BEIGE/BEIGE/BEIGE · 260         3
RED/RED/GRAY · 245              3
RED/RED/GRAY · 260              3
GREY/WHITE/WHITE · 250          2
GREY/WHITE/WHITE · 265          2
White/Brown/White · 225         2
White/Brown/White · 245         2
White/Brown/White · 255         2
BEIGE/BEIGE/BEIGE · 225         2
BROWN/BROWN/BROWN · 290         2
BLACK/BLACK/SILVER · 240        2
GREY/GREY/GREY · 250            2
Black/Black/White · 270         2
Black/Black/Black · 290         2
Black/Black/Black · 270         2
BLACK/BLACK/BLACK · 260         2
Green/Green/Green · 255         2
Brown/Orange/Yellow · 250       2
BLACK/BLACK/WHITE · 225         2
GREEN/GREEN/GREEN · 265         2
BROWN/ORANGE/WHITE · 220        2
BROWN/ORANGE/WHITE · 265        2
BROWN/ORANGE/WHITE · 255        2
GRAY/GRAY/GRAY · 260            2
BEIGE/BEIGE/BEIGE · 255         2
PINK/PINK/BLACK · 230           2
PINK/PINK/BLACK · 245           2
RED/RED/GRAY · 250              2
RED/RED/GRAY · 230              2
RED/RED/GRAY · 235              2
BLACK/BLACK/BLACK · 235         2
BLACK/WHITE/BROWN · 220         2
BLUE/BLUE/BLUE · 230            2
BEIGE/BEIGE/BEIGE · 270         2
GREY/WHITE/WHITE · 220          1
GREY/WHITE/WHITE · 275          1
White/Brown/White · 270         1
White/Brown/White · 265         1
White/Brown/White · 250         1
White/Brown/White · 275         1
White/Brown/White · 230         1
White/Brown/White · 235         1
Beige/Beige/Beige · 275         1
BLACK/BLACK/SILVER · 235        1
BLACK/BLACK/SILVER · 280        1
BLACK/BLACK/SILVER · 260        1
Black/Black/Silver · 285        1
BLACK/BLACK/SILVER · 270        1
WHITE/BLACK/GREY · 235          1
GREY/GREY/GREY · 220            1
Grey/Grey/Grey · 220            1
BLACK/BLACK/BLACK · 270         1
Black/Black/Black · 280         1
BLACK/GREY/BLACK · 245          1
GREY/BLUE/GREY · 260            1
Grey/Blue/Grey · 260            1
GREEN/GREEN/GREEN · 270         1
BLACK/BLACK/WHITE · 275         1
BLACK/BLACK/WHITE · 270         1
BROWN/ORANGE/YELLOW · 280       1
BROWN/ORANGE/YELLOW · 255       1
GREEN/GREEN/GREEN · 290         1
BROWN/ORANGE/YELLOW · 275       1
BROWN/ORANGE/WHITE · 270        1
Green/Green/Green · 235         1
Brown/Orange/White · 250        1
BLACK/BLACK/WHITE · 265         1
BROWN/ORANGE/YELLOW · 260       1
GREEN/GREEN/GREEN · 285         1
BEIGE/BEIGE/BEIGE · 220         1
PINK/PINK/PINK · 255            1
PINK/PINK/PINK · 230            1
GRAY/GRAY/GRAY · 220            1
PINK/PINK/BLACK · 250           1
PINK/PINK/BLACK · 240           1
RED/RED/GRAY · 290              1
RED/RED/GRAY · 255              1
YELLOW/YELLOW/YELLOW · 240      1
BLACK/WHITE/BROWN · 260         1
BLUE/BLUE/BLUE · 275            1
Name: count, dtype: int64

In [53]:
# =======================================
# 컬럼명 변경
# =======================================

df_review_fila_mss = df_review_fila_mss.rename(columns={
    'review_no' : 'review_id',
    'review_text' : 'content',
    'option' : 'purchase_option',
    'helpful' : 'helpful_count',
    'url' : 'product_url'
})

df_review_fila_mss.head(3)

,collect_date,review_date,product_id,product_name,review_id,rating,content,user_height,user_weight,purchase_option,helpful_count,has_image,product_url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스랑 반스는 265정도 신는데 휠라는 270으로 구매하니 발도 편안하고 좋아요.,NaN,NaN,Grey/White/White · 270,1,True,https://www.musinsa.com/products/3892794#review_79849708
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감이 있는 듯하지만 편하다네요!,NaN,NaN,Grey/White/White · 260,0,True,https://www.musinsa.com/products/3892794#review_79753882
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,"여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로 바꿔 꼈더니 더 예쁜 느낌이네요! 캐주얼, 슬랙스, 스커트 가리지 않고 다 잘 어울려서 손이 자주 가고, 요즘 실버색상 유행이라 마음에 더 쏙 들어요!",NaN,NaN,Grey/White/White · 255,0,True,https://www.musinsa.com/products/3892794#review_79033605

In [54]:
# =======================================
# 없는 컬럼 추가
# =======================================

# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_mss.columns:
        df_review_fila_mss[col] = None

# =======================================
# 컬럼 순서 정리
# =======================================
df_review_fila_mss = df_review_fila_mss[required_columns]

df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       8209 non-null   str
 1   platform           0 non-null      object
 2   review_id          8209 non-null   int64
 3   product_id         8209 non-null   int64
 4   product_name       8209 non-null   str
 5   review_date        8209 non-null   str
 6   year               0 non-null      object
 7   month              0 non-null      object
 8   content            8209 non-null   str
 9   rating             8209 non-null   int64
 10  helpful_count      8209 non-null   int64
 11  has_image          8209 non-null   bool
 12  purchase_option    8209 non-null   str
 13  user_size          0 non-null      object
 14  user_height        0 non-null      float64
 15  user_weight        0 non-null      float64
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        8209 non-null   str
dtypes: bool(1), float64(2), int64(4), object(6), str(6)
memory usage: 3.5+ MB

In [55]:
# =======================================
# year, month 다시 생성하기
# =======================================
# 날짜 컬럼 형변환
df_review_fila_mss['collect_date'] = pd.to_datetime(df_review_fila_mss['collect_date']).dt.normalize()
df_review_fila_mss['review_date'] = pd.to_datetime(df_review_fila_mss['review_date']).dt.normalize()

# 기존 year, month 제거
df_review_fila_mss = df_review_fila_mss.drop(['year', 'month'], axis=1)

# 파생컬럼 생성
df_review_fila_mss['year'] = df_review_fila_mss['review_date'].dt.year
df_review_fila_mss['month'] = df_review_fila_mss['review_date'].dt.month

In [56]:
# =======================================
# platform = 무신사
# =======================================
df_review_fila_mss['platform'] = '무신사'
df_review_fila_mss['platform'].value_counts()

platform
무신사    8209
Name: count, dtype: int64

In [57]:
# =======================================
# 고객 신체 정보 None으로 채우기
# =======================================
df_review_fila_mss[['user_height', 'user_weight', 'user_height_group', 'user_weight_group']] = (
    df_review_fila_mss[['user_height', 'user_weight', 'user_height_group', 'user_weight_group']].astype(object).fillna(None)
)

In [58]:
# =======================================
# has_image => 0, 1로 변환하기
# =======================================
df_review_fila_mss['has_image'] = df_review_fila_mss['has_image'].map({
    True : 1,
    False : 0
})
df_review_fila_mss['has_image'].value_counts()

has_image
1    4970
0    3239
Name: count, dtype: int64

In [59]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       8209 non-null   datetime64[us]
 1   platform           8209 non-null   str
 2   review_id          8209 non-null   int64
 3   product_id         8209 non-null   int64
 4   product_name       8209 non-null   str
 5   review_date        8209 non-null   datetime64[us]
 6   content            8209 non-null   str
 7   rating             8209 non-null   int64
 8   helpful_count      8209 non-null   int64
 9   has_image          8209 non-null   int64
 10  purchase_option    8209 non-null   str
 11  user_size          0 non-null      object
 12  user_height        0 non-null      object
 13  user_weight        0 non-null      object
 14  user_height_group  0 non-null      object
 15  user_weight_group  0 non-null      object
 16  product_url        8209 non-null   str
 17  year               8209 non-null   int32
 18  month              8209 non-null   int32
dtypes: datetime64[us](2), int32(2), int64(5), object(5), str(5)
memory usage: 3.4+ MB

In [60]:
# =======================================
# 데이터 타입 정리하기
# =======================================
df_review_fila_mss['platform'] = df_review_fila_mss['platform'].astype('category')
df_review_fila_mss['purchase_option'] = df_review_fila_mss['purchase_option'].astype('category')

df_review_fila_mss[['platform', 'purchase_option']].info()

<class 'pandas.DataFrame'>
Index: 8209 entries, 0 to 13408
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   platform         8209 non-null   category
 1   purchase_option  8209 non-null   category
dtypes: category(2)
memory usage: 96.3 KB

In [61]:
# =======================================
# 컬럼 순서 변경
# =======================================
df_review_fila_mss = df_review_fila_mss[['collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url']]

df_review_fila_mss.head(3)

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,무신사,79849708,3892794,에샤페 실버문(1XM02348H063),2025-11-16,2025,11,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스랑 반스는 265정도 신는데 휠라는 270으로 구매하니 발도 편안하고 좋아요.,5,1,1,Grey/White/White · 270,None,None,None,None,None,https://www.musinsa.com/products/3892794#review_79849708
1,2026-04-21,무신사,79753882,3892794,에샤페 실버문(1XM02348H063),2025-11-11,2025,11,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감이 있는 듯하지만 편하다네요!,5,0,1,Grey/White/White · 260,None,None,None,None,None,https://www.musinsa.com/products/3892794#review_79753882
2,2026-04-21,무신사,79033605,3892794,에샤페 실버문(1XM02348H063),2025-10-15,2025,10,"여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로 바꿔 꼈더니 더 예쁜 느낌이네요! 캐주얼, 슬랙스, 스커트 가리지 않고 다 잘 어울려서 손이 자주 가고, 요즘 실버색상 유행이라 마음에 더 쏙 들어요!",5,0,1,Grey/White/White · 255,None,None,None,None,None,https://www.musinsa.com/products/3892794#review_79033605

In [62]:
# =======================================
# 이상치 확인
# =======================================
min(df_review_fila_mss['review_date']) # 2024-02-27
max(df_review_fila_mss['review_date']) # 2026-04-13

df_review_fila_mss['platform'].value_counts() # 무신사

df_review_fila_mss['review_id'].value_counts(ascending=False) # 모든 값 1

df_review_fila_mss['product_id'].value_counts(ascending=False)

df_review_fila_mss['product_name'].value_counts(ascending=False)

min(df_review_fila_mss['year']) # 2024
max(df_review_fila_mss['year']) # 2026

min(df_review_fila_mss['month']) # 1
max(df_review_fila_mss['month']) # 12

12

In [63]:
# =======================================
# 저장
# =======================================
df_review_fila_mss_2024 = df_review_fila_mss[df_review_fila_mss['year'] >= 2024]

df_review_fila_mss.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_musinsa_review_final.csv", encoding='utf-8-sig', index=False)
df_review_fila_mss_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_musinsa_review_final_s2024.csv", encoding='utf-8-sig', index=False)