In [29]:
import pandas as pd
import numpy as np

In [30]:
# 휠라
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_master_260420.csv", encoding='utf-8')
df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv", encoding='utf-8')
df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv", encoding='utf-8')

---
# 휠라 네이버스토어 리뷰 데이터

## 1. 전처리

In [31]:
# =============================
# 결측값 확인
# =============================

print("===== 전체 컬럼 결측치 확인 =====")
df_review_fila_naverstore.info()

# 1)
# 'Unnamed: 0' : 인덱스였던 데이터 같음 -> 필요 없으니 삭제

# 2)
# 'extra_reviewTopics' 결측치 있음. -> 필요없는 데이터라 컬럼 삭제
print("\n===== 'extra_reviewTopics' 결측치 확인(%) =====")
print(df_review_fila_naverstore['extra_reviewTopics'].isna().mean()*100)

===== 전체 컬럼 결측치 확인 =====
<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    1277 non-null   int64
 1   product_url                   1277 non-null   str
 2   product_id                    1277 non-null   int64
 3   review_id                     1277 non-null   float64
 4   review_body                   1277 non-null   str
 5   rating                        1277 non-null   float64
 6   helpful_count                 1277 non-null   float64
 7   review_date                   1277 non-null   str
 8   reviewer_id                   1277 non-null   str
 9   review_content_class          1277 non-null   str
 10  extra_id                      1277 non-null   float64
 11  extra_reviewContentClassType  1277 non-null   str
 12  extra_reviewScore             1277 non-null   float64
 13  extra_reviewContent           1277 non-null   str
 14  extra_createDate              1277 non-null   str
 15  extra_writerId                1277 non-null   str
 16  extra_productName             1277 non-null   str
 17  extra_productOptionContent    1277 non-null   str
 18  extra_reviewTopics            1031 non-null   str
dtypes: float64(5), int64(2), str(12)
memory usage: 899.4 KB

===== 'extra_reviewTopics' 결측치 확인(%) =====
19.263899765074395

In [32]:
# 필요한 컬럼 선택
# 'product_url', 'product_id', 'review_id', 'review_body', 'rating', 'review_date', 'extra_productName'

# 컬럼 선택
df_review_fila_naverstore = df_review_fila_naverstore[['product_url', 'product_id', 'review_id', 'review_body', 'rating', 'review_date', 'extra_productName']]
df_review_fila_naverstore.head()
# dtype 통일

,product_url,product_id,review_id,review_body,rating,review_date,extra_productName
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,2025-02-24 13:14:50.302000+00:00,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,2025-01-31 13:07:37.398000+00:00,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,2025-01-31 14:23:34.326000+00:00,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,2025-01-03 23:36:57.419000+00:00,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4.0,2026-04-02 04:45:38.825000+00:00,휠라 에샤페 레이스_1XM02347H920

In [33]:
# =============================
# 컬럼 명 통일
# =============================
df_review_fila_naverstore = df_review_fila_naverstore.rename(columns={
    'extra_productName' : 'product_name'
})

In [36]:
# =============================
# dtype 변환
# =============================
# df_review_fila_naverstore.info()

# rating -> int
# 데이터 다 정수 맞음. -> int 변환 가능
df_review_fila_naverstore['rating'] = df_review_fila_naverstore['rating'].astype(int)

# review_date -> datetime
df_review_fila_naverstore['review_date'] = pd.to_datetime(df_review_fila_naverstore['review_date'])
# UTC -> KST(Asia/Seoul)
# df_review_fila_naverstore['review_date'] = df_review_fila_naverstore['review_date'].dt.tz_convert('Asia/Seoul')
# 소수점 초 없애기
df_review_fila_naverstore['review_date'] = df_review_fila_naverstore['review_date'].dt.strftime('%Y-%m-%d %H:%M:%S')
# # review_date -> datetime
df_review_fila_naverstore['review_date'] = pd.to_datetime(df_review_fila_naverstore['review_date'])

print("===== dtype 번환 후 info =====")
display(df_review_fila_naverstore.info())
display(df_review_fila_naverstore.head())

===== dtype 번환 후 info =====
<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_url   1277 non-null   str
 1   product_id    1277 non-null   int64
 2   review_id     1277 non-null   float64
 3   review_body   1277 non-null   str
 4   rating        1277 non-null   int64
 5   review_date   1277 non-null   datetime64[us]
 6   product_name  1277 non-null   str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 321.3 KB

None

,product_url,product_id,review_id,review_body,rating,review_date,product_name
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,2025-02-24 22:14:50,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,2025-01-31 22:07:37,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,2025-01-31 23:23:34,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5,2025-01-04 08:36:57,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK)
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,2026-04-02 13:45:38,휠라 에샤페 레이스_1XM02347H920

In [37]:
# =============================
# 파생컬럼 생성 -> year, month
# =============================
df_review_fila_naverstore['year'] = df_review_fila_naverstore['review_date'].dt.year
df_review_fila_naverstore['month'] = df_review_fila_naverstore['review_date'].dt.month

display(df_review_fila_naverstore[['year', 'month']].info())
df_review_fila_naverstore.head()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    1277 non-null   int32
 1   month   1277 non-null   int32
dtypes: int32(2)
memory usage: 10.1 KB

None

,product_url,product_id,review_id,review_body,rating,review_date,product_name,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,2025-02-24 22:14:50,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025,2
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,2025-01-31 22:07:37,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025,1
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,2025-01-31 23:23:34,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025,1
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5,2025-01-04 08:36:57,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025,1
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,2026-04-02 13:45:38,휠라 에샤페 레이스_1XM02347H920,2026,4

In [38]:
# =============================
# 컬럼 순서 통일
# =============================
df_review_fila_naverstore = df_review_fila_naverstore[['review_id', 'product_id', 'product_name', 'review_date', 'year', 'month', 'review_body', 'rating', 'product_url']]

print("========== 휠라 네이버스토어 리뷰 ==========")
display(df_review_fila_naverstore.head())
display(df_review_fila_naverstore.info())

========== 휠라 네이버스토어 리뷰 ==========

,review_id,product_id,product_name,review_date,year,month,review_body,rating,product_url
0,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24 22:14:50,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,https://brand.naver.com/fila/products/10769719940
1,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31 22:07:37,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,https://brand.naver.com/fila/products/10769719940
2,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31 23:23:34,2025,1,넘 귀야워요 만족ㅎㅎ,5,https://brand.naver.com/fila/products/10769719940
3,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-04 08:36:57,2025,1,깜찍합니다.이뿌구요^^,5,https://brand.naver.com/fila/products/10769719940
4,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02 13:45:38,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\...,4,https://brand.naver.com/fila/products/11293482675

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_id     1277 non-null   float64
 1   product_id    1277 non-null   int64
 2   product_name  1277 non-null   str
 3   review_date   1277 non-null   datetime64[us]
 4   year          1277 non-null   int32
 5   month         1277 non-null   int32
 6   review_body   1277 non-null   str
 7   rating        1277 non-null   int64
 8   product_url   1277 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(2), str(3)
memory usage: 331.2 KB

None

In [47]:
# =============================
# 이상값 확인
# =============================

df_review_fila_naverstore['product_url'].value_counts()

product_url
https://brand.naver.com/fila/products/11293482675    20
https://brand.naver.com/fila/products/11302266780    20
https://brand.naver.com/fila/products/11302331555    20
https://brand.naver.com/fila/products/11333335468    20
https://brand.naver.com/fila/products/11577025542    20
                                                     ..
https://brand.naver.com/fila/products/13237659192     1
https://brand.naver.com/fila/products/13237659305     1
https://brand.naver.com/fila/products/13258132935     1
https://brand.naver.com/fila/products/13268903169     1
https://brand.naver.com/fila/products/13402982542     1
Name: count, Length: 326, dtype: int64

---
# 휠라 자사몰 리뷰 데이터

## 1. 전처리

In [73]:
df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_master_260420.csv", encoding='utf-8')
df_review_fila_D2C.info()

<class 'pandas.DataFrame'>
RangeIndex: 47725 entries, 0 to 47724
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   collect_date      47725 non-null  str
 1   post_date         47725 non-null  str
 2   platform          47725 non-null  str
 3   brand             47725 non-null  str
 4   search_keyword    47725 non-null  str
 5   content           47725 non-null  str
 6   source_url        47725 non-null  str
 7   rating            47725 non-null  int64
 8   helpful_count     47725 non-null  int64
 9   purchased_option  6933 non-null   str
 10  has_image         47725 non-null  int64
dtypes: int64(3), str(8)
memory usage: 17.6 MB

In [74]:
# 사용 컬럼 선택

df_review_fila_D2C = df_review_fila_D2C[['post_date', 'content', 'source_url', 'rating', 'search_keyword']]
display(df_review_fila_D2C.head())
display(df_review_fila_D2C.info())

,post_date,content,source_url,rating,search_keyword
0,2026-04-14,올해는 아주 편하고 세련되고 예뻐용~~~,https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003001
1,2026-03-01,"부들부들 시원한 원단에 입은 듯 안 입은듯 가볍고 활동성이 좋습니다,,입으면 핏이 좋네요",https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003001
2,2026-04-14,올해는 아주 편하고 세련되고 예뻐용~~~,https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003234
3,2026-03-01,"부들부들 시원한 원단에 입은 듯 안 입은듯 가볍고 활동성이 좋습니다,,입으면 핏이 좋네요",https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003234
4,2026-04-14,올해는 아주 편하고 세련되고 예뻐용~~~,https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003651

<class 'pandas.DataFrame'>
RangeIndex: 47725 entries, 0 to 47724
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   post_date       47725 non-null  str
 1   content         47725 non-null  str
 2   source_url      47725 non-null  str
 3   rating          47725 non-null  int64
 4   search_keyword  47725 non-null  str
dtypes: int64(1), str(4)
memory usage: 13.9 MB

None

In [75]:
# dtype 변환

# post_date
df_review_fila_D2C['post_date'] = pd.to_datetime(df_review_fila_D2C['post_date'])
df_review_fila_D2C['post_date'].dtype

dtype('<M8[us]')

In [76]:
# post_date -> year, month 파생컬럼 생성
df_review_fila_D2C['year'] = df_review_fila_D2C['post_date'].dt.year
df_review_fila_D2C['month'] = df_review_fila_D2C['post_date'].dt.month

display(df_review_fila_D2C[['year', 'month']])
display(df_review_fila_D2C[['year', 'month']].info())

       year  month
0      2026      4
1      2026      3
2      2026      4
3      2026      3
4      2026      4
...     ...    ...
47720  2025      2
47721  2025     11
47722  2023      5
47723  2024      6
47724  2023      5

[47725 rows x 2 columns]

<class 'pandas.DataFrame'>
RangeIndex: 47725 entries, 0 to 47724
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    47725 non-null  int32
 1   month   47725 non-null  int32
dtypes: int32(2)
memory usage: 373.0 KB

None

In [77]:
# 컬럼명 통일
df_review_fila_D2C.head()

# post_date -> review_date
# content -> review_body
# source_url -> product_url
df_review_fila_D2C = df_review_fila_D2C.rename(columns={
    'post_date' : 'review_date',
    'content' : 'review_body',
    'source_url' : 'product_url',
    'search_keyword' : 'product_id'
})

df_review_fila_D2C.head()

,review_date,review_body,product_url,rating,product_id,year,month
0,2026-04-14,올해는 아주 편하고 세련되고 예뻐용~~~,https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003001,2026,4
1,2026-03-01,"부들부들 시원한 원단에 입은 듯 안 입은듯 가볍고 활동성이 좋습니다,,입으면 핏이 좋네요",https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003001,2026,3
2,2026-04-14,올해는 아주 편하고 세련되고 예뻐용~~~,https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003234,2026,4
3,2026-03-01,"부들부들 시원한 원단에 입은 듯 안 입은듯 가볍고 활동성이 좋습니다,,입으면 핏이 좋네요",https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003234,2026,3
4,2026-04-14,올해는 아주 편하고 세련되고 예뻐용~~~,https://www.fila.co.kr/product/1100fs262ft02u0...,5,1100fs262ft02u003651,2026,4

In [ ]:
# 컬럼 순서 통일
df_review_fila_D2C = df_review_fila_D2C[['product_id', 'review_date', 'year', 'month', 'review_body', 'rating', 'product_url']]
display(df_review_fila_D2C.head())
display(df_review_fila_D2C.info())

,product_id,review_date,year,month,review_body,rating,product_url
0,1100fs262ft02u003001,2026-04-14,2026,4,올해는 아주 편하고 세련되고 예뻐용~~~,5,https://www.fila.co.kr/product/1100fs262ft02u0...
1,1100fs262ft02u003001,2026-03-01,2026,3,"부들부들 시원한 원단에 입은 듯 안 입은듯 가볍고 활동성이 좋습니다,,입으면 핏이 좋네요",5,https://www.fila.co.kr/product/1100fs262ft02u0...
2,1100fs262ft02u003234,2026-04-14,2026,4,올해는 아주 편하고 세련되고 예뻐용~~~,5,https://www.fila.co.kr/product/1100fs262ft02u0...
3,1100fs262ft02u003234,2026-03-01,2026,3,"부들부들 시원한 원단에 입은 듯 안 입은듯 가볍고 활동성이 좋습니다,,입으면 핏이 좋네요",5,https://www.fila.co.kr/product/1100fs262ft02u0...
4,1100fs262ft02u003651,2026-04-14,2026,4,올해는 아주 편하고 세련되고 예뻐용~~~,5,https://www.fila.co.kr/product/1100fs262ft02u0...

<class 'pandas.DataFrame'>
RangeIndex: 47725 entries, 0 to 47724
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   47725 non-null  str
 1   review_date  47725 non-null  datetime64[us]
 2   year         47725 non-null  int32
 3   month        47725 non-null  int32
 4   review_body  47725 non-null  str
 5   rating       47725 non-null  int64
 6   product_url  47725 non-null  str
dtypes: datetime64[us](1), int32(2), int64(1), str(3)
memory usage: 13.8 MB

None

In [86]:
# 이상치 확인
df_review_fila_D2C['product_url'].value_counts()

product_url
https://www.fila.co.kr/product/11001xm02348h063        1764
https://www.fila.co.kr/product/1100fs261od03x087370    1677
https://www.fila.co.kr/product/1100fs261od03x087219    1677
https://www.fila.co.kr/product/1100fs253od03x012217    1665
https://www.fila.co.kr/product/1100fs253od03x012260    1665
                                                       ...
https://www.fila.co.kr/product/1170fi4pjh2609mdst         1
https://www.fila.co.kr/product/1170fi4pjh2608midb         1
https://www.fila.co.kr/product/1170fi4pjh2609mblk         1
https://www.fila.co.kr/product/1170fi4drh1121mblk         1
https://www.fila.co.kr/product/1170fi4drh1142mdid         1
Name: count, Length: 1187, dtype: int64

---
# 휠라 무신사 리뷰 데이터

## 1. 전처리

In [90]:
df_review_fila_mss = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/musinsa_fila_shoes_reviews.csv", encoding='utf-8')
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,collect_date,review_date,product_id,product_name,review_no,review_type,rating,review_text,author,user_height,...,option,helpful,comment_count,has_image,image_urls,survey_size,survey_width,survey_comfort,survey_instep,url
0,2026-04-21 17:04:23,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,스타일,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,기발한스웨덴웨지,NaN,...,Grey/White/White · 270,1,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,보통,아주 편안,https://www.musinsa.com/products/3892794#revie...
1,2026-04-21 17:04:23,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,스타일,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,아트텍,NaN,...,Grey/White/White · 260,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,적당,https://www.musinsa.com/products/3892794#revie...
2,2026-04-21 17:04:23,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,스타일,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,신중한하얀단화,NaN,...,Grey/White/White · 255,0,0,True,https://www.musinsa.com/data/estimate/3892794_...,정사이즈,적당함,편함,편안,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   collect_date    14100 non-null  str
 1   review_date     14100 non-null  str
 2   product_id      14100 non-null  int64
 3   product_name    14100 non-null  str
 4   review_no       14100 non-null  int64
 5   review_type     14100 non-null  str
 6   rating          14100 non-null  int64
 7   review_text     14090 non-null  str
 8   author          14100 non-null  str
 9   user_height     0 non-null      float64
 10  user_weight     0 non-null      float64
 11  option          14086 non-null  str
 12  helpful         14100 non-null  int64
 13  comment_count   14100 non-null  int64
 14  has_image       14100 non-null  bool
 15  image_urls      8621 non-null   str
 16  survey_size     4227 non-null   str
 17  survey_width    4227 non-null   str
 18  survey_comfort  4227 non-null   str
 19  survey_instep   4227 non-null   str
 20  url             14100 non-null  str
dtypes: bool(1), float64(2), int64(5), str(13)
memory usage: 7.6 MB

None

In [92]:
# 사용 컬럼 선정
df_review_fila_mss = df_review_fila_mss[['review_date', 'product_id', 'product_name', 'review_no', 'rating', 'review_text', 'url']]
display(df_review_fila_mss.head(3))
display(df_review_fila_mss.info())

,review_date,product_id,product_name,review_no,rating,review_text,url
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...

<class 'pandas.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_date   14100 non-null  str
 1   product_id    14100 non-null  int64
 2   product_name  14100 non-null  str
 3   review_no     14100 non-null  int64
 4   rating        14100 non-null  int64
 5   review_text   14090 non-null  str
 6   url           14100 non-null  str
dtypes: int64(3), str(4)
memory usage: 4.3 MB

None

In [94]:
# 결측치 처리
# 리뷰 분석이 중요하기 때문에 review_text가 null인 컬럼은 제거
df_review_fila_mss = df_review_fila_mss.dropna(subset=['review_text'], axis=0)
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_date   14090 non-null  str
 1   product_id    14090 non-null  int64
 2   product_name  14090 non-null  str
 3   review_no     14090 non-null  int64
 4   rating        14090 non-null  int64
 5   review_text   14090 non-null  str
 6   url           14090 non-null  str
dtypes: int64(3), str(4)
memory usage: 4.4 MB

In [98]:
# review_date 파생컬럼
df_review_fila_mss['review_date'] = pd.to_datetime(df_review_fila_mss['review_date'])

df_review_fila_mss['year'] = df_review_fila_mss['review_date'].dt.year
df_review_fila_mss['month'] = df_review_fila_mss['review_date'].dt.month

display(df_review_fila_mss.head())
display(df_review_fila_mss[['review_date', 'year', 'month']].info())

,review_date,product_id,product_name,review_no,rating,review_text,url,year,month
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...,2025,11
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...,2025,11
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...,2025,10
3,2025-10-13,3892794,에샤페 실버문(1XM02348H063),78679747,5,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,https://www.musinsa.com/products/3892794#revie...,2025,10
4,2025-10-12,3892794,에샤페 실버문(1XM02348H063),78939688,5,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,https://www.musinsa.com/products/3892794#revie...,2025,10

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_date  14090 non-null  datetime64[us]
 1   year         14090 non-null  int32
 2   month        14090 non-null  int32
dtypes: datetime64[us](1), int32(2)
memory usage: 330.2 KB

None

In [108]:
# 컬럼명 변경
df_review_fila_mss = df_review_fila_mss.rename(columns={
    'review_no' : 'review_id',
    'review_text' : 'review_body',
    'url' : 'product_url'
})

df_review_fila_mss.head()

,review_date,product_id,product_name,review_id,rating,review_body,product_url,year,month
0,2025-11-16,3892794,에샤페 실버문(1XM02348H063),79849708,5,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,https://www.musinsa.com/products/3892794#revie...,2025,11
1,2025-11-11,3892794,에샤페 실버문(1XM02348H063),79753882,5,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,https://www.musinsa.com/products/3892794#revie...,2025,11
2,2025-10-15,3892794,에샤페 실버문(1XM02348H063),79033605,5,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,https://www.musinsa.com/products/3892794#revie...,2025,10
3,2025-10-13,3892794,에샤페 실버문(1XM02348H063),78679747,5,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,https://www.musinsa.com/products/3892794#revie...,2025,10
4,2025-10-12,3892794,에샤페 실버문(1XM02348H063),78939688,5,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,https://www.musinsa.com/products/3892794#revie...,2025,10

In [109]:
# 컬럼순서 변경
df_review_fila_mss = df_review_fila_mss[['review_id', 'product_id', 'product_name', 'review_date', 'year', 'month', 'review_body', 'rating', 'product_url']]
df_review_fila_mss.head()

,review_id,product_id,product_name,review_date,year,month,review_body,rating,product_url
0,79849708,3892794,에샤페 실버문(1XM02348H063),2025-11-16,2025,11,휠라 신발이 원래 예쁘다는 생각을 안 했는데 이건 너무 예뻐서 구매했어요. 아디다스...,5,https://www.musinsa.com/products/3892794#revie...
1,79753882,3892794,에샤페 실버문(1XM02348H063),2025-11-11,2025,11,아기랑 엄마랑 커플로 신으려고 샀습니다. 요즘 유행하는 스타일?! 아주 살짝 무게감...,5,https://www.musinsa.com/products/3892794#revie...
2,79033605,3892794,에샤페 실버문(1XM02348H063),2025-10-15,2025,10,여기저기 매치하기 편하고 색상도 예뻐요 특히 운동화 끈을 두개 보내주셔서 검정색으로...,5,https://www.musinsa.com/products/3892794#revie...
3,78679747,3892794,에샤페 실버문(1XM02348H063),2025-10-13,2025,10,맣이안되요 개편하고 좋습니다 푸천합니다!!정말로요,5,https://www.musinsa.com/products/3892794#revie...
4,78939688,3892794,에샤페 실버문(1XM02348H063),2025-10-12,2025,10,너무 여름에만 어울리는 신발인가 싶어서 고민고민하다가 샀는데 너무 예뻐서 진작 살껄...,5,https://www.musinsa.com/products/3892794#revie...

In [110]:
df_review_fila_mss.info()

<class 'pandas.DataFrame'>
Index: 14090 entries, 0 to 14099
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_id     14090 non-null  int64
 1   product_id    14090 non-null  int64
 2   product_name  14090 non-null  str
 3   review_date   14090 non-null  datetime64[us]
 4   year          14090 non-null  int32
 5   month         14090 non-null  int32
 6   review_body   14090 non-null  str
 7   rating        14090 non-null  int64
 8   product_url   14090 non-null  str
dtypes: datetime64[us](1), int32(2), int64(3), str(3)
memory usage: 4.4 MB

In [120]:
# 이상치 확인
df_review_fila_mss['product_url'].value_counts()

product_url
https://www.musinsa.com/products/5311939#review_81270327    5
https://www.musinsa.com/products/5312026#review_81244311    5
https://www.musinsa.com/products/5312026#review_81248800    5
https://www.musinsa.com/products/5311939#review_81244528    5
https://www.musinsa.com/products/5312098#review_81069728    5
                                                           ..
https://www.musinsa.com/products/5311984#review_79605475    1
https://www.musinsa.com/products/5311984#review_79258458    1
https://www.musinsa.com/products/5311984#review_79198367    1
https://www.musinsa.com/products/5311984#review_78888434    1
https://www.musinsa.com/products/5311984#review_78378268    1
Name: count, Length: 8575, dtype: int64