In [157]:
import pandas as pd
import numpy as np

---
# 휠라 네이버스토어 리뷰 데이터

## 1. 전처리

In [158]:
# ===============================
# 데이터 불러오기
# ===============================
import pandas as pd
import numpy as np

df_review_fila_naverstore = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/FILA_NaverStore_Review_since2020.csv")
display(df_review_fila_naverstore.shape)
display(df_review_fila_naverstore.head())

(1277, 19)

,Unnamed: 0,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,reviewer_id,review_content_class,extra_id,extra_reviewContentClassType,extra_reviewScore,extra_reviewContent,extra_createDate,extra_writerId,extra_productName,extra_productOptionContent,extra_reviewTopics
0,3,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,mini******,PHOTO,4.669237e+09,PHOTO,5.0,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,2025-02-24 13:14:50.302000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도"", ""patternStartNo"": 20, ""patternEndNo"": 27}, {""topicCode"": ""total"", ""topicCodeName"": ""만족도"", ""patternStartNo"": 29, ""patternEndNo"": 34}]"
1,4,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,mini******,PHOTO,4.652212e+09,PHOTO,5.0,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,2025-01-31 13:07:37.398000+00:00,mini******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도"", ""patternStartNo"": 0, ""patternEndNo"": 7}]"
2,5,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,ex****,PHOTO,4.652239e+09,PHOTO,5.0,넘 귀야워요 만족ㅎㅎ,2025-01-31 14:23:34.326000+00:00,ex****,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도"", ""patternStartNo"": 0, ""patternEndNo"": 8}]"
3,6,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,youn*******,PHOTO,4.634973e+09,PHOTO,5.0,깜찍합니다.이뿌구요^^,2025-01-03 23:36:57.419000+00:00,youn*******,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,"[{""topicCode"": ""total"", ""topicCodeName"": ""만족도"", ""patternStartNo"": 6, ""patternEndNo"": 9}]"
4,7,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\n디자인은 꽃처럼 귀여움!!!!,4.0,0.0,2026-04-02 04:45:38.825000+00:00,yoon*******,PHOTO,4.944300e+09,PHOTO,4.0,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\n디자인은 꽃처럼 귀여움!!!!,2026-04-02 04:45:38.825000+00:00,yoon*******,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,"[{""topicCode"": ""size"", ""topicCodeName"": ""사이즈"", ""patternStartNo"": 0, ""patternEndNo"": 14}, {""topicCode"": ""total"", ""topicCodeName"": ""만족도"", ""patternStartNo"": 45, ""patternEndNo"": 56}, {""topicCode"": ""design"", ""topicCodeName"": ""디자인"", ""patternStartNo"": 50, ""patternEndNo"": 56}]"

In [159]:
# ===============================
# 필요한 컬럼 선택
# ===============================
df_review_fila_naverstore = df_review_fila_naverstore[[
    'product_url', 'product_id', 'review_id', 'review_body', 'rating', 'helpful_count', 'review_date', 'review_content_class', 'extra_productName', 'extra_productOptionContent'
]] # 10개

display(df_review_fila_naverstore.head())
display(df_review_fila_naverstore.info())

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5.0,0.0,2025-02-24 13:14:50.302000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5.0,0.0,2025-01-31 13:07:37.398000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5.0,0.0,2025-01-31 14:23:34.326000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5.0,0.0,2025-01-03 23:36:57.419000+00:00,PHOTO,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\n디자인은 꽃처럼 귀여움!!!!,4.0,0.0,2026-04-02 04:45:38.825000+00:00,PHOTO,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   str
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 444.0 KB

None

In [160]:
# ===============================
# review_content_class 변환
# ===============================
df_review_fila_naverstore['review_content_class'].value_counts() # PHOTO, TEXT, VIDEO

# PHOTO, VIDEO = 1
# TEXT = 0
df_review_fila_naverstore['review_content_class'] = df_review_fila_naverstore['review_content_class'].map({
    'PHOTO' : 1,
    'TEXT' : 0,
    'VIDEO' : 1
})

print(df_review_fila_naverstore['review_content_class'].value_counts())
print(df_review_fila_naverstore.info())

review_content_class
1    887
0    390
Name: count, dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   float64
 5   helpful_count               1277 non-null   float64
 6   review_date                 1277 non-null   str
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: float64(3), int64(2), str(5)
memory usage: 438.2 KB
None

In [161]:
# ===============================
# 데이터 타입 변환
# ===============================
# rating, helpful_count, review_date
df_review_fila_naverstore['rating'] = df_review_fila_naverstore['rating'].astype(int)
df_review_fila_naverstore['helpful_count'] = df_review_fila_naverstore['helpful_count'].astype(int)
df_review_fila_naverstore['review_date'] = pd.to_datetime(df_review_fila_naverstore['review_date']).dt.normalize().dt.tz_localize(None)

print(df_review_fila_naverstore.info())

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
dtypes: datetime64[us](1), float64(1), int64(4), str(4)
memory usage: 398.3 KB
None

In [162]:
# ===============================
# 파생컬럼 생성 -> year, month
# ===============================
df_review_fila_naverstore['year'] = df_review_fila_naverstore['review_date'].dt.year
df_review_fila_naverstore['month'] = df_review_fila_naverstore['review_date'].dt.month

df_review_fila_naverstore.head(3)

,product_url,product_id,review_id,review_body,rating,helpful_count,review_date,review_content_class,extra_productName,extra_productOptionContent,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1

In [163]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_url                 1277 non-null   str
 1   product_id                  1277 non-null   int64
 2   review_id                   1277 non-null   float64
 3   review_body                 1277 non-null   str
 4   rating                      1277 non-null   int64
 5   helpful_count               1277 non-null   int64
 6   review_date                 1277 non-null   datetime64[us]
 7   review_content_class        1277 non-null   int64
 8   extra_productName           1277 non-null   str
 9   extra_productOptionContent  1277 non-null   str
 10  year                        1277 non-null   int32
 11  month                       1277 non-null   int32
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), str(4)
memory usage: 408.3 KB

In [164]:
# ===============================
# 컬럼명 정리
# ===============================
df_review_fila_naverstore = df_review_fila_naverstore.rename(columns={
    'review_content_class' : 'has_image',
    'extra_productName' : 'product_name',
    'extra_productOptionContent' : 'purchase_option',
    'review_body' : 'content'
})

df_review_fila_naverstore.head(1)

,product_url,product_id,review_id,content,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2

In [165]:
# ===============================
# 없는 컬럼 추가하기
# ===============================
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_naverstore.columns:
        df_review_fila_naverstore[col] = None

df_review_fila_naverstore.head()

,product_url,product_id,review_id,content,rating,helpful_count,review_date,has_image,product_name,purchase_option,year,month,collect_date,platform,user_height,user_weight,user_height_group,user_weight_group
0,https://brand.naver.com/fila/products/10769719940,10718496494,4.669237e+09,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,2025-02-24,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,2,None,None,None,None,None,None
1,https://brand.naver.com/fila/products/10769719940,10718496494,4.652212e+09,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
2,https://brand.naver.com/fila/products/10769719940,10718496494,4.652239e+09,넘 귀야워요 만족ㅎㅎ,5,0,2025-01-31,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
3,https://brand.naver.com/fila/products/10769719940,10718496494,4.634973e+09,깜찍합니다.이뿌구요^^,5,0,2025-01-03,1,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),색상: BLACK / 사이즈: 000,2025,1,None,None,None,None,None,None
4,https://brand.naver.com/fila/products/11293482675,11240513968,4.944300e+09,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\n디자인은 꽃처럼 귀여움!!!!,4,0,2026-04-02,1,휠라 에샤페 레이스_1XM02347H920,색상: Beige / 사이즈: 220,2026,4,None,None,None,None,None,None

In [166]:
# ===============================
# 컬럼 순서 정리
# ===============================
df_review_fila_naverstore = df_review_fila_naverstore[required_columns]
df_review_fila_naverstore.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,None,None,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,None,None,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,None,None,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
3,None,None,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다.이뿌구요^^,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
4,None,None,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\n디자인은 꽃처럼 귀여움!!!!,4,0,1,색상: Beige / 사이즈: 220,None,None,None,None,https://brand.naver.com/fila/products/11293482675

In [167]:
df_review_fila_naverstore.info()

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       0 non-null      object
 1   platform           0 non-null      object
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   content            1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   str
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        1277 non-null   str
dtypes: datetime64[us](1), float64(1), int32(2), int64(4), object(6), str(4)
memory usage: 468.1+ KB

In [168]:
# ===============================
# 이상치 확인
# ===============================
df_review_fila_naverstore['platform'].value_counts(dropna=False)

platform
None    1277
Name: count, dtype: int64

In [169]:
# ===============================
# 'platform' 데이터 '네이버스토어'로 넣기
# ===============================
df_review_fila_naverstore['platform'] = '네이버스토어'
df_review_fila_naverstore['platform'].value_counts()

platform
네이버스토어    1277
Name: count, dtype: int64

In [170]:
# ===============================
# review_id 중복 확인
# ===============================
df_review_fila_naverstore['review_id'].duplicated().sum()

np.int64(0)

In [171]:
# ===============================
# category 타입으로 변환
# ===============================
df_review_fila_naverstore['platform'] = df_review_fila_naverstore['platform'].astype('category')
df_review_fila_naverstore['purchase_option'] = df_review_fila_naverstore['purchase_option'].astype('category')

In [172]:
# =========================================================
# collect_date 컬럼에 데이터 넣기 => '2026-04-21'로 넣기
# =========================================================
df_review_fila_naverstore['collect_date'] = '2026-04-21'
df_review_fila_naverstore['collect_date'] = pd.to_datetime(df_review_fila_naverstore['collect_date'])

In [173]:
display(df_review_fila_naverstore.head(3))
print(df_review_fila_naverstore.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,네이버스토어,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,2026-04-21,네이버스토어,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,2026-04-21,네이버스토어,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940

<class 'pandas.DataFrame'>
RangeIndex: 1277 entries, 0 to 1276
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       1277 non-null   datetime64[us]
 1   platform           1277 non-null   category
 2   review_id          1277 non-null   float64
 3   product_id         1277 non-null   int64
 4   product_name       1277 non-null   str
 5   review_date        1277 non-null   datetime64[us]
 6   year               1277 non-null   int32
 7   month              1277 non-null   int32
 8   content            1277 non-null   str
 9   rating             1277 non-null   int64
 10  helpful_count      1277 non-null   int64
 11  has_image          1277 non-null   int64
 12  purchase_option    1277 non-null   category
 13  user_height        0 non-null      object
 14  user_weight        0 non-null      object
 15  user_height_group  0 non-null      object
 16  user_weight_group  0 non-null      object
 17  product_url        1277 non-null   str
dtypes: category(2), datetime64[us](2), float64(1), int32(2), int64(4), object(4), str(3)
memory usage: 427.0+ KB
None

## 2. 중복제거

In [174]:
# ===============================
# 제품명 매칭 확인
# ===============================
multi_name = df_review_fila_naverstore.groupby('product_id')['product_name'].nunique()
multi_url = df_review_fila_naverstore.groupby('product_id')['product_url'].nunique()

# product_name 매핑 확인
print(multi_name.gt(1).sum(), "개의 product_id가 여러 product_name에 매핑됨")
display(
    df_review_fila_naverstore[df_review_fila_naverstore['product_id'].isin(multi_name[multi_name > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

# product_url 매핑 확인
print(multi_url.gt(1).sum(), "개의 product_id가 여러 product_url에 매핑됨")
display(
    df_review_fila_naverstore[df_review_fila_naverstore['product_id'].isin(multi_url[multi_url > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

29 개의 product_id가 여러 product_name에 매핑됨

,product_id,product_name,product_url
24,11249278438,휠라 에샤페 7종 택1_FS261OD03X040 (실버문 베이지 블랙 크림 초코 말차 블루 핑크),https://brand.naver.com/fila/products/11302266780
27,11249278438,휠라 에샤페 7종 택1_FS261OD03X040 (실버문 베이지 크림 말차 블랙 초코 핑크 블루),https://brand.naver.com/fila/products/11302266780
28,11249278438,[한소희 착용] 휠라 에샤페 6종 택1_FS253OD03X012 (초코 말차 카멜 브릭 블랙 모카),https://brand.naver.com/fila/products/11302266780
32,11249278438,휠라 에샤페 6종 택1_FS253OD03X012 (초코 말차 카멜 브릭 블랙 모카),https://brand.naver.com/fila/products/11302266780
65,11280259953,휠라 판테라 99/25_1RM02946H010,https://brand.naver.com/fila/products/11333335468
83,11280259953,[주우재 착용] 휠라 판테라 99/25_1RM02946H010,https://brand.naver.com/fila/products/11333335468
131,11523136350,휠라 레인저 22_1RM02486G100,https://brand.naver.com/fila/products/11577014748
132,11523136350,휠라레인져 22_1RM02486G100,https://brand.naver.com/fila/products/11577014748
138,11523136813,휠라레인져 22_1RM02486G147,https://brand.naver.com/fila/products/11577015209
133,11523136813,휠라 레인저 22_1RM02486G147,https://brand.naver.com/fila/products/11577015209
379,11560257765,휠라 에샤페 벨크로 v2 1XM02369H001,https://brand.naver.com/fila/products/11614267179
380,11560257765,휠라 에샤페 벨크로 v2_1XM02369H001,https://brand.naver.com/fila/products/11614267179
381,11560257765,휠라 에샤페 벨크로 v2_1XM02369H001,https://brand.naver.com/fila/products/11614267179
399,11560811827,휠라 에샤페 벨크로 v2 1XM02369H050,https://brand.naver.com/fila/products/11614823916
401,11560811827,휠라 에샤페 벨크로 v2_1XM02369H050,https://brand.naver.com/fila/products/11614823916
402,11560811827,휠라 에샤페 벨크로 v2_1XM02369H050,https://brand.naver.com/fila/products/11614823916
423,11603941383,휠라 레플리카 02/25 GTX_1XM02854H001,https://brand.naver.com/fila/products/11658100761
419,11603941383,휠라 레플리카 02/25 고어텍스 _1XM02854H001,https://brand.naver.com/fila/products/11658100761
458,11647692451,휠라플러스 인타르시아 에이스 트랙 팬츠_FO252FP10X001217,https://brand.naver.com/fila/products/11702008803
459,11647692451,F+ INTARSIA ACE TRACK PANT,https://brand.naver.com/fila/products/11702008803
461,11647692457,휠라플러스 LA 포켓 반팔 티셔츠_FO252RS10X002452,https://brand.naver.com/fila/products/11702008809
462,11647692457,F+ LA POCKET SS TEE_FO252RS10X002452,https://brand.naver.com/fila/products/11702008809
463,11647692462,휠라플러스 세탄타 타월 니트 쇼츠_FO252TR10X003650,https://brand.naver.com/fila/products/11702008812
465,11647692462,F+ SETTANTA TOWEL KNIT SHORT_FO252TR10X003650,https://brand.naver.com/fila/products/11702008812
498,11694821727,휠라 에샤페 v2 실버_1XM02367H102,https://brand.naver.com/fila/products/11749294127
504,11694821727,[차정원 착용] 휠라 에샤페 v2 실버_1XM02367H102,https://brand.naver.com/fila/products/11749294127
512,11694821727,휠라 에샤페 MS v2_1XM02367H102,https://brand.naver.com/fila/products/11749294127
660,12111377267,[차정원 착용] 휠라 1911 여성 니트트랙 집업_FS261FT01F005001,https://brand.naver.com/fila/products/12167041418
662,12111377267,[한소희 착용] 휠라 1911 여성 니트트랙 집업_FS261FT01F005001,https://brand.naver.com/fila/products/12167041418
663,12111377267,[재입고][한소희 착용] 휠라 [여] 1911 니트 트랙 집업_FS253FT01F001001,https://brand.naver.com/fila/products/12167041418
667,12111377422,[한소희 착용] 휠라 1911 여성 니트트랙 집업_FS261FT01F005234,https://brand.naver.com/fila/products/12167041576
681,12111377422,[고현정 착용] 휠라 1911 여성 니트트랙 집업_FS261FT01F005234,https://brand.naver.com/fila/products/12167041576
682,12111377422,[고현정 착용] 휠라 [여] 1911 니트 트랙 집업_FS253FT01F001234,https://brand.naver.com/fila/products/12167041576
692,12173005085,휠라 FILA WAVY DAY 3종 택1_1RM02850H,https://brand.naver.com/fila/products/12228803947
685,12173005085,휠라 웨이비 데이 3종 택1_1RM02850H,https://brand.naver.com/fila/products/12228803947
737,12177504345,휠라 푸퍼 라지 토트백 3종 택1_FS254RB01F003,https://brand.naver.com/fila/products/12233313443
741,12177504345,휠라 푸퍼 라지 토트백 3종 택1_FS254RB01F003,https://brand.naver.com/fila/products/12233313443
757,12177504738,휠라 푸퍼 버킷백 4종 택1_FS254RB01F004,https://brand.naver.com/fila/products/12233313916
758,12177504738,휠라 푸퍼 버킷백 4종 택1_FS254RB01F004,https://brand.naver.com/fila/products/12233313916
792,12190547674,[김나영 착용] 휠라 에샤페 카멜_FS253OD03X012218,https://brand.naver.com/fila/products/12246385202
795,12190547674,[차정원 착용] 휠라 에샤페 카멜_FS253OD03X012218,https://brand.naver.com/fila/products/12246385202
837,12192187992,[한소희 착용] 휠라 판테라 99/25 LX_FS261RU03X076217,https://brand.naver.com/fila/products/12248029994
838,12192187992,휠라 판테라 99/25 LX_FS261RU03X076217,https://brand.naver.com/fila/products/12248029994
913,12263290327,휠라 여성 러닝 그래픽 긴팔티_FS253RL02F003650,https://brand.naver.com/fila/products/12319319524
914,12263290327,휠라 [여] 러닝 그래픽 긴팔티_FS253RL02F003650,https://brand.naver.com/fila/products/12319319524
918,12263290460,휠라 여성 러닝 메쉬 후드 긴팔티_FS253RL02F005442,https://brand.naver.com/fila/products/12319319657
928,12263290460,휠라 [여] 러닝 메쉬 후드 긴팔티_FS253RL02F005442,https://brand.naver.com/fila/products/12319319657
932,12263290495,휠라 여성 러닝 메쉬 후드 긴팔티_FS253RL02F005670,https://brand.naver.com/fila/products/12319319692
933,12263290495,휠라 [여] 러닝 메쉬 후드 긴팔티_FS253RL02F005670,https://brand.naver.com/fila/products/12319319692
1023,12359265661,[봉태규 착용] 휠라 하레핀 1998 3종 택1_FS253OD03X014,https://brand.naver.com/fila/products/12415547945
1016,12359265661,[봉태규 착용] 휠라 하레핀 1998 3종 택1_FS261OD03X095 FS253OD03X014,https://brand.naver.com/fila/products/12415547945
1014,12359265661,[봉태규 착용] 휠라 하레핀 1998 3종 택1_FS253OD03X014 FS261OD03X095,https://brand.naver.com/fila/products/12415547945
1008,12359265661,[고현정 착용] 휠라 하레핀 1998 3종 택1_FS261OD03X095 FS253OD03X014,https://brand.naver.com/fila/products/12415547945
1006,12359265661,휠라 하레핀 1998 3종 택1_FS261OD03X095,https://brand.naver.com/fila/products/12415547945
1026,12359265796,[고현정 착용] 휠라 하레핀 1998_FS253OD03X014218,https://brand.naver.com/fila/products/12415548082
1037,12359265796,휠라 하레핀 1998_FS253OD03X014218,https://brand.naver.com/fila/products/12415548082
1056,12391574747,휠라 에샤페 초코_FS261OD03X087219,https://brand.naver.com/fila/products/12447942462
1067,12391574747,[차정원 착용] 휠라 에샤페 초코_FS261OD03X087219,https://brand.naver.com/fila/products/12447942462
1103,12810497778,휠라 리트모 슬릭 LX_FS261OD03X008370,https://brand.naver.com/fila/products/12867974773
1105,12810497778,[한소희 착용] 휠라 리트모 슬릭 LX_FS261OD03X008370,https://brand.naver.com/fila/products/12867974773
1108,12810497900,[김나영 착용] 휠라 리트모 슬릭 LX_FS261OD03X008734,https://brand.naver.com/fila/products/12867974892
1110,12810497900,휠라 리트모 슬릭 LX_FS261OD03X008734,https://brand.naver.com/fila/products/12867974892
1111,12810498006,[우즈 착용] 휠라 리트모 슬릭_FS261OD03X009452,https://brand.naver.com/fila/products/12867974998
1113,12810498006,휠라 리트모 슬릭_FS261OD03X009452,https://brand.naver.com/fila/products/12867974998
1194,13031295131,휠라 하레핀 1998_FS261OD03X095100,https://brand.naver.com/fila/products/13089330201
1196,13031295131,[한소희 착용] 휠라 하레핀 1998_FS261OD03X095100,https://brand.naver.com/fila/products/13089330201
1218,13045836670,[차정원 착용] 휠라 글리오 크림_FS261OD03X032260,https://brand.naver.com/fila/products/13103912477
1223,13045836670,휠라 글리오 크림_FS261OD03X032260,https://brand.naver.com/fila/products/13103912477

0 개의 product_id가 여러 product_url에 매핑됨

Empty DataFrame
Columns: [product_id, product_name, product_url]
Index: []

In [175]:
# ===============================
# 리뷰 내용 중복 확인
# ===============================
# 2-1. product_id 같고 content 중복인 데이터 확인
dup_mask = df_review_fila_naverstore.duplicated(subset=['product_id', 'content'], keep=False)
print("product_id는 같고 content가 중복 개수: ", dup_mask.sum())
display(df_review_fila_naverstore[dup_mask][['product_id', 'product_name', 'review_date', 'content']].sort_values(['product_id', 'content']))

# 2-2. 위 경우 중 review_date까지 완전히 동일한 경우 개수
print(
    "review_date까지 완전히 동일한 경우 개수: "
    , df_review_fila_naverstore[dup_mask].duplicated(subset=['product_id', 'content', 'review_date'], keep=False).sum()
)

product_id는 같고 content가 중복 개수:  6

      product_id                     product_name review_date         content
113  11407845389      휠라 디스럽터 2 1998_1FM02739H121  2026-01-29      배송 빠르고 좋아요
114  11407845389      휠라 디스럽터 2 1998_1FM02739H121  2026-01-28      배송 빠르고 좋아요
531  11694824829  휠라 테니스 소로나 카라티셔츠_FS2TSH2302MOWH  2025-08-18      좋아요 만족합니다.
538  11694824829  휠라 테니스 소로나 카라티셔츠_FS2TSH2302MOWH  2025-07-16      좋아요 만족합니다.
860  12244913220     휠라플러스 드릴 부츠_FO253BT99X001217  2025-12-13  빠른 배송 잘 받았습니다.
861  12244913220     휠라플러스 드릴 부츠_FO253BT99X001217  2025-12-10  빠른 배송 잘 받았습니다.

review_date까지 완전히 동일한 경우 개수:  0

## 3. 리뷰본문(content) 텍스트 정제

In [176]:
import copy
df_review_fila_naverstore_copy = copy.deepcopy(df_review_fila_naverstore)

In [177]:
import re

def clean_text(text):
    # 1. 결측치 처리
    if pd.isna(text):
        return ' '

    text = str(text)

    # 2. HTML 태그 제거
    text = re.sub(r'<[^>]+>', ' ', text)

    # 3. URL 제거
    text = re.sub(r'http\S+|www\.\S+', ' ', text)

    # 4. 이메일 제거
    text = re.sub(r'\S+@\S+', ' ', text)

    # 5. 이모지 & 이모티콘 제거
    text = re.sub(r'[^\w\s\uAC00-\uD7A3\u3130-\u318F]', ' ', text)
    # \uAC00-\uD7A3 : 한글 완성형
    # \u3130-\u318F : ㅎ, ㅋ 같은 한글 자모음 (반복 제거 대상이라 유지)

    # 6. 줄바꿈, 탭 → 공백으로 변환
    text = re.sub(r'[\n\r\t]', ' ', text)

    # 7. 반복 문자 1개로 통일 (ㅎㅎㅎ→ㅎ, ㅋㅋㅋ→ㅋ, ~~~→~)
    text = re.sub(r'(.)\1{2,}', r'\1', text)

    # 8. 연속 공백 → 공백 1개로 통일
    text = re.sub(r'\s+', ' ', text)

    # 9. 대소문자 통합 (영문 소문자)
    text = text.lower()

    # 10. 앞뒤 공백 제거
    text = text.strip()

    return text

df_review_fila_naverstore_copy['content'] = df_review_fila_naverstore_copy['content'].apply(clean_text)

In [178]:
pd.set_option('display.max_colwidth', None) # 컬럼 안 텍스트 잘림 제거

print("===== 텍스트 정제 전 리뷰 ======")
display(df_review_fila_naverstore.head())
print("===== 텍스트 정제 후 리뷰 ======")
display(df_review_fila_naverstore_copy.head())

===== 텍스트 정제 전 리뷰 ======

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,네이버스토어,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기\n매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,2026-04-21,네이버스토어,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,2026-04-21,네이버스토어,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
3,2026-04-21,네이버스토어,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다.이뿌구요^^,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
4,2026-04-21,네이버스토어,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요\n그리고 발은 오래신으면 아플것 같아요\n디자인은 꽃처럼 귀여움!!!!,4,0,1,색상: Beige / 사이즈: 220,None,None,None,None,https://brand.naver.com/fila/products/11293482675

===== 텍스트 정제 후 리뷰 ======

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,네이버스토어,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기 매기 딱 좋아요 귀여움은 덤,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
1,2026-04-21,네이버스토어,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
2,2026-04-21,네이버스토어,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
3,2026-04-21,네이버스토어,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다 이뿌구요,5,0,1,색상: BLACK / 사이즈: 000,None,None,None,None,https://brand.naver.com/fila/products/10769719940
4,2026-04-21,네이버스토어,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요 그리고 발은 오래신으면 아플것 같아요 디자인은 꽃처럼 귀여움,4,0,1,색상: Beige / 사이즈: 220,None,None,None,None,https://brand.naver.com/fila/products/11293482675

## 4. 구매옵션(purchase_option) 파싱

In [179]:
pd.set_option('display.max_rows', None) # 행 보이기
df_review_fila_naverstore_copy['purchase_option'].value_counts(dropna=False)

purchase_option
색상: BLACK / 사이즈: 000(Free)                  76
색상: Black / 사이즈: 240                        27
색상: Black / 사이즈: 270                        16
색상: Beige / 사이즈: 235                        15
색상: BLACK / 사이즈: 000                        13
색상: BEIGE/BEIGE/BEIGE / 사이즈: 240            12
색상: BROWN/BROWN/BROWN / 사이즈: 240            12
색상: Black / 사이즈: 260                        12
색상: BLACK / 사이즈: W90(WM)                    11
색상: BLUE/LIGHT BLUE / 사이즈: W90(WM)          11
색상: WHITE/CREAM / 사이즈: 000(Free)            11
색상: BROWN / 사이즈: W85(WS)                    10
색상: BROWN/BROWN/BROWN / 사이즈: 245            10
색상: Black / 사이즈: 235                        10
색상: Black / 사이즈: 245                        10
색상: Black / 사이즈: 250                        10
색상: BEIGE/BEIGE/BEIGE / 사이즈: 235             9
색상: Beige / 사이즈: 240                         9
색상: Black / 사이즈: 280                         9
색상: OFF WHITE / 사이즈: 105                     9
색상: OFF WHITE / 사이즈: 110                     9
색상: BEIGE / 사이즈: 000(Free)                   8
색상: BROWN / 사이즈: 000(Free)                   8
색상: BROWN/BROWN/BROWN / 사이즈: 250             8
색상: GRAY / 사이즈: 000(Free)                    8
색상: Grey / White / Green / 사이즈: 260          8
색상: OFF WHITE / 사이즈: 095                     8
색상: PINK / 사이즈: 000(Free)                    8
색상: WHITE/BROWN/WHITE / 사이즈: 240             8
색상: White / 사이즈: 240                         8
색상: White / 사이즈: 260                         8
색상: 234(다크브라운) / 사이즈: WS(W85)                7
색상: BLACK/BLACK/WHITE / 사이즈: 240             7
색상: BROWN / 사이즈: WM(W90)                     7
색상: Beige / 사이즈: 245                         7
색상: OFF WHITE / 사이즈: 100                     7
색상: OFF WHITE / 사이즈: W85                     7
색상: White / Black / Grey / 사이즈: 245          7
색상: White / Black / Grey / 사이즈: 250          7
색상: White / 사이즈: 250                         7
색상: 217(브라운) / 사이즈: 240                      6
색상: BLACK/BLACK/BLACK / 사이즈: 240             6
색상: Black / 사이즈: 255                         6
색상: Brown/Brown/Brown / 사이즈: 240             6
색상: GREEN/GREEN/GREEN / 사이즈: 240             6
색상: PINK/PINK/PINK / 사이즈: 240                6
색상: White / Black / Grey / 사이즈: 265          6
색상: White / Blue / Blue / 사이즈: 260           6
색상: White / 사이즈: 280                         6
색상: BLACK / 사이즈: 100                         5
색상: BLACK / 사이즈: 105                         5
색상: BLACK/BLACK/WHITE / 사이즈: 245             5
색상: BROWN / 사이즈: W90(WM)                     5
색상: BROWN/BROWN/BROWN / 사이즈: 235             5
색상: Beige / 사이즈: 250                         5
색상: Beige / 사이즈: 260                         5
색상: Black / 사이즈: 230                         5
색상: Black / 사이즈: 265                         5
색상: GRAY/DARK GRAY / 사이즈: 000(Free)          5
색상: GREEN / 사이즈: 105                         5
색상: Grey / Grey / Grey / 사이즈: 240            5
색상: Grey / Grey / Grey / 사이즈: 245            5
색상: Grey / Grey / Grey / 사이즈: 250            5
색상: OFF WHITE / 사이즈: W95                     5
색상: PINK/PINK/BLACK / 사이즈: 240               5
색상: PINK/PINK/BLACK / 사이즈: 245               5
색상: PINK/PINK/BLACK / 사이즈: 250               5
색상: WHITE/IVORY / 사이즈: W95(WL)               5
색상: White / Black / Grey / 사이즈: 255          5
색상: White / Black / Grey / 사이즈: 270          5
색상: BEIGE/BEIGE/BEIGE / 사이즈: 245             4
색상: BLACK / 사이즈: 095                         4
색상: BLACK / 사이즈: W90                         4
색상: BLACK/BLACK/WHITE / 사이즈: 250             4
색상: BLUE/NAVY / 사이즈: 000(Free)               4
색상: BROWN / 사이즈: WS(W85)                     4
색상: BROWN/BEIGE/BEIGE / 사이즈: 235             4
색상: Beige / 사이즈: 220                         4
색상: Beige / 사이즈: 230                         4
색상: Brown/Brown/Brown / 사이즈: 235             4
색상: CREAM / 사이즈: 000                         4
색상: DARK NAVY / 사이즈: W70                     4
색상: GREEN/GREEN/GREEN / 사이즈: 230             4
색상: GREEN/GREEN/GREEN / 사이즈: 245             4
색상: Grey / Grey / Grey / 사이즈: 230            4
색상: Grey / White / Green / 사이즈: 240          4
색상: OFF WHITE / 사이즈: 000                     4
색상: OFF WHITE / 사이즈: 090                     4
색상: OFF WHITE / 사이즈: W75                     4
색상: WHITE/BROWN/WHITE / 사이즈: 235             4
색상: WHITE/IVORY / 사이즈: W85(WS)               4
색상: WHITE/IVORY / 사이즈: W90(WM)               4
색상: WHITE/IVORY / 사이즈: WS(W85)               4
색상: White / Black / Grey / 사이즈: 240          4
색상: White / Black / Grey / 사이즈: 260          4
색상: White / Blue / Blue / 사이즈: 240           4
색상: White / Blue / Blue / 사이즈: 250           4
색상: White / Blue / Blue / 사이즈: 255           4
색상: White / Blue / Blue / 사이즈: 275           4
색상: White / White / Red / 사이즈: 255           4
색상: White / 사이즈: 230                         4
색상: White / 사이즈: 255                         4
색상: 100(크림) / 사이즈: 240                       3
색상: 217(브라운) / 사이즈: 235                      3
색상: 217(브라운) / 사이즈: 260                      3
색상: 234(다크브라운) / 사이즈: WL(W95)                3
색상: BEIGE/BEIGE/BEIGE / 사이즈: 225             3
색상: BEIGE/BEIGE/BEIGE / 사이즈: 250             3
색상: BLACK / 사이즈: 105(XL)                     3
색상: BLACK / 사이즈: 110                         3
색상: BLACK / 사이즈: L(100)                      3
색상: BLACK / 사이즈: W95                         3
색상: BLACK/BLACK/BLACK / 사이즈: 260             3
색상: BLACK/BLACK/BLACK / 사이즈: 270             3
색상: BLACK/BLACK/BLACK / 사이즈: 280             3
색상: BLACK/BLACK/WHITE / 사이즈: 235             3
색상: BLUE / 사이즈: 100(L)                       3
색상: BLUE/LIGHT BLUE / 사이즈: W95(WL)           3
색상: BROWN / 사이즈: 110(2XL)                    3
색상: BROWN / 사이즈: W95(WL)                     3
색상: BROWN/BEIGE/BEIGE / 사이즈: 250             3
색상: BROWN/BROWN/BROWN / 사이즈: 225             3
색상: BROWN/BROWN/BROWN / 사이즈: 230             3
색상: BROWN/BROWN/BROWN / 사이즈: 255             3
색상: BROWN/BROWN/BROWN / 사이즈: 260             3
색상: Beige / Beige / White / 사이즈: 240         3
색상: Beige / 사이즈: 270                         3
색상: Beige / 사이즈: 280                         3
색상: Black / Black / Red / 사이즈: 280           3
색상: Brown/Brown/Brown / 사이즈: 250             3
색상: DARK NAVY / 사이즈: 110                     3
색상: DARK NAVY / 사이즈: W85                     3
색상: GRAY/GRAY/GRAY / 사이즈: 235                3
색상: GREEN / 사이즈: 095                         3
색상: GREEN/GREEN/GREEN / 사이즈: 235             3
색상: GREEN/GREEN/GREEN / 사이즈: 250             3
색상: Grey / Grey / Grey / 사이즈: 235            3
색상: Grey / White / Green / 사이즈: 270          3
색상: PURPLE / 사이즈: 90(S)                      3
색상: White / Blue / Blue / 사이즈: 245           3
색상: White / Blue / Blue / 사이즈: 265           3
색상: White / White / Red / 사이즈: 270           3
색상: 001(블랙) / 사이즈: WS(W85)                   2
색상: 063(실버문) / 사이즈: 240                      2
색상: 217(브라운) / 사이즈: 265                      2
색상: 219(초코) / 사이즈: 245                       2
색상: 234(다크브라운) / 사이즈: WM(W90)                2
색상: 234(다크브라운) / 사이즈: WXS(W80)               2
색상: BEIGE / 사이즈: W90(WM)                     2
색상: BEIGE/BEIGE/BEIGE / 사이즈: 230             2
색상: BEIGE/BEIGE/BEIGE / 사이즈: 260             2
색상: BEIGE/BEIGE/BEIGE / 사이즈: 285             2
색상: BLACK / 사이즈: 090                         2
색상: BLACK / 사이즈: 100(L)                      2
색상: BLACK / 사이즈: M(085)                      2
색상: BLACK / 사이즈: W75                         2
색상: BLACK / 사이즈: W80(WM)                     2
색상: BLACK / 사이즈: W95(WL)                     2
색상: BLACK / 사이즈: WM(W80)                     2
색상: BLACK / 사이즈: WS(W85)                     2
색상: BLACK / 사이즈: XL(105)                     2
색상: BLACK/BLACK/BLACK / 사이즈: 245             2
색상: BLACK/BLACK/BLACK / 사이즈: 250             2
색상: BLACK/BLACK/BLACK / 사이즈: 255             2
색상: BLACK/BLACK/BLACK / 사이즈: 275             2
색상: BLACK/BLACK/GRAY / 사이즈: 245              2
색상: BLACK/WHITE/WHITE / 사이즈: 250             2
색상: BLUE/BLUE/BLUE / 사이즈: 240                2
색상: BLUE/DARK BLUE / 사이즈: WS(W85)            2
색상: BLUE/DARK NAVY / 사이즈: 95(M)              2
색상: BLUE/LIGHT BLUE / 사이즈: W85(WS)           2
색상: BLUE/LIGHT BLUE / 사이즈: WM(W90)           2
색상: BROWN / 사이즈: 100(L)                      2
색상: BROWN / 사이즈: WL(W95)                     2
색상: BROWN/BEIGE/BEIGE / 사이즈: 230             2
색상: BROWN/BROWN/BROWN / 사이즈: 275             2
색상: BROWN/DARK BROWN / 사이즈: 110(2XL)         2
색상: BROWN/DARK BROWN / 사이즈: W90(WM)          2
색상: Beige / Brown / Grey / 사이즈: 250          2
색상: Beige / 사이즈: 225                         2
색상: Black / Black / Red / 사이즈: 275           2
색상: Black / 사이즈: 225                         2
색상: Black / 사이즈: 275                         2
색상: Black / 사이즈: 290                         2
색상: Black(001) / 사이즈: 240                    2
색상: Brown/Brown/Brown / 사이즈: 230             2
색상: Brown/Brown/Brown / 사이즈: 245             2
색상: DARK NAVY / 사이즈: 095                     2
색상: DARK NAVY / 사이즈: 105                     2
색상: DARK NAVY / 사이즈: W80                     2
색상: GRAY / 사이즈: M(095)                       2
색상: GRAY/BROWN/BEIGE / 사이즈: 270              2
색상: GREEN/GREEN/GREEN / 사이즈: 220             2
색상: GREEN/GREEN/GREEN / 사이즈: 225             2
색상: Grey / White / Green / 사이즈: 280          2
색상: Grey / White / Grey / 사이즈: 265           2
색상: Grey / White / Grey / 사이즈: 270           2
색상: OFF WHITE / 사이즈: 085                     2
색상: OFF WHITE / 사이즈: W90                     2
색상: PINK/DARK PINK / 사이즈: W90(WM)            2
색상: PINK/LIGHT PINK / 사이즈: 85(M)             2
색상: PINK/LIGHT PINK / 사이즈: 95(M)             2
색상: PINK/LIGHT PINK / 사이즈: W90(WM)           2
색상: PINK/PINK/BLACK / 사이즈: 230               2
색상: PINK/PINK/PINK / 사이즈: 230                2
색상: PURPLE / 사이즈: 100(L)                     2
색상: RED/RED/GRAY / 사이즈: 240                  2
색상: WHITE/BROWN/WHITE / 사이즈: 230             2
색상: WHITE/BROWN/WHITE / 사이즈: 250             2
색상: WHITE/GRAY/BLUE / 사이즈: 260               2
색상: WHITE/IVORY / 사이즈: 105(XL)               2
색상: WHITE/IVORY / 사이즈: W80(WXS)              2
색상: WHITE/IVORY / 사이즈: WL(W95)               2
색상: WHITE/OFF WHITE / 사이즈: WL(W95)           2
색상: White / Blue / Blue / 사이즈: 235           2
색상: White / Blue / Blue / 사이즈: 270           2
색상: White / White / Red / 사이즈: 240           2
색상: White / White / Red / 사이즈: 265           2
색상: White / 사이즈: 235                         2
색상: YELLOW/YELLOW/YELLOW / 사이즈: 250          2
색상: 001(블랙) / 사이즈: WL(W95)                   1
색상: 001(블랙) / 사이즈: WM(W90)                   1
색상: 032(베이지) / 사이즈: 230                      1
색상: 032(베이지) / 사이즈: 235                      1
색상: 063(실버문) / 사이즈: 235                      1
색상: 063(실버문) / 사이즈: 245                      1
색상: 100(크림) / 사이즈: 230                       1
색상: 100(크림) / 사이즈: 235                       1
색상: 100(크림) / 사이즈: 275                       1
색상: 175(화이트) / 사이즈: WS(W85)                  1
색상: 217(브라운) / 사이즈: 230                      1
색상: 217(브라운) / 사이즈: 245                      1
색상: 217(브라운) / 사이즈: 255                      1
색상: 217(브라운) / 사이즈: 280                      1
색상: 219(초코) / 사이즈: 225                       1
색상: 219(초코) / 사이즈: 235                       1
색상: 219(초코) / 사이즈: 270                       1
색상: 370(말차) / 사이즈: 240                       1
색상: 626(다크레드) / 사이즈: WM(W90)                 1
색상: BEIGE / 사이즈: W85(WS)                     1
색상: BEIGE / 사이즈: WS(W75)                     1
색상: BEIGE / 사이즈: XL(105)                     1
색상: BEIGE/BEIGE/BEIGE / 사이즈: 220             1
색상: BEIGE/BEIGE/BEIGE / 사이즈: 255             1
색상: BEIGE/BEIGE/BEIGE / 사이즈: 265             1
색상: BEIGE/BEIGE/BEIGE / 사이즈: 270             1
색상: BEIGE/BEIGE/BEIGE / 사이즈: 280             1
색상: BEIGE/BEIGE/BEIGE / 사이즈: 290             1
색상: BEIGE/BEIGE/BROWN / 사이즈: 250             1
색상: BEIGE/BLACK/PINK / 사이즈: 270              1
색상: BEIGE/CAMEL / 사이즈: 100(L)                1
색상: BEIGE/OATMEAL MELANGE / 사이즈: W90(WM)     1
색상: BEIGE/WHITE/BEIGE / 사이즈: 240             1
색상: BEIGE/WHITE/BEIGE / 사이즈: 250             1
색상: BEIGE/WHITE/BEIGE / 사이즈: 270             1
색상: BLACK / 사이즈: 085                         1
색상: BLACK / 사이즈: 110(2XL)                    1
색상: BLACK / 사이즈: 2XL(110)                    1
색상: BLACK / 사이즈: 60                          1
색상: BLACK / 사이즈: 85(M)                       1
색상: BLACK / 사이즈: 90(L)                       1
색상: BLACK / 사이즈: 95(XL)                      1
색상: BLACK / 사이즈: L(90)                       1
색상: BLACK / 사이즈: S(090)                      1
색상: BLACK / 사이즈: W80                         1
색상: BLACK / 사이즈: W85                         1
색상: BLACK / 사이즈: W85(WS)                     1
색상: BLACK / 사이즈: WL(W85)                     1
색상: BLACK / 사이즈: WM(W90)                     1
색상: BLACK / 사이즈: WXS(W80)                    1
색상: BLACK / 사이즈: XL(95)                      1
색상: BLACK/BLACK/BLACK / 사이즈: 225             1
색상: BLACK/BLACK/BLACK / 사이즈: 265             1
색상: BLACK/BLACK/GRAY / 사이즈: 235              1
색상: BLACK/BLACK/GRAY / 사이즈: 255              1
색상: BLACK/BLACK/GRAY / 사이즈: 270              1
색상: BLACK/BLACK/GRAY / 사이즈: 275              1
색상: BLACK/BLACK/WHITE / 사이즈: 225             1
색상: BLACK/GRAY/WHITE / 사이즈: 240              1
색상: BLACK/WHITE/WHITE / 사이즈: 220             1
색상: BLACK/WHITE/WHITE / 사이즈: 225             1
색상: BLUE / 사이즈: 000(Free)                    1
색상: BLUE / 사이즈: 105(XL)                      1
색상: BLUE / 사이즈: 110(2XL)                     1
색상: BLUE/BLUE/BLUE / 사이즈: 225                1
색상: BLUE/BLUE/BLUE / 사이즈: 230                1
색상: BLUE/BLUE/BLUE / 사이즈: 235                1
색상: BLUE/BLUE/BLUE / 사이즈: 245                1
색상: BLUE/BLUE/BLUE / 사이즈: 255                1
색상: BLUE/DARK BLUE / 사이즈: L(100)             1
색상: BLUE/DARK BLUE / 사이즈: M(095)             1
색상: BLUE/DARK NAVY / 사이즈: 100(L)             1
색상: BLUE/DARK NAVY / 사이즈: 90(L)              1
색상: BLUE/DARK NAVY / 사이즈: WM(W90)            1
색상: BLUE/RED/BLUE / 사이즈: 250                 1
색상: BLUE/WHITE/BLACK / 사이즈: 240              1
색상: BROWN / 사이즈: 105(XL)                     1
색상: BROWN / 사이즈: L(100)                      1
색상: BROWN / 사이즈: S(090)                      1
색상: BROWN / 사이즈: W85(WL)                     1
색상: BROWN / 사이즈: WL(W85)                     1
색상: BROWN / 사이즈: WS(W75)                     1
색상: BROWN / 사이즈: WXS(W80)                    1
색상: BROWN/BEIGE/BEIGE / 사이즈: 240             1
색상: BROWN/BEIGE/BEIGE / 사이즈: 245             1
색상: BROWN/BEIGE/BEIGE / 사이즈: 265             1
색상: BROWN/BROWN/BROWN / 사이즈: 265             1
색상: BROWN/BROWN/BROWN / 사이즈: 270             1
색상: BROWN/DARK BROWN / 사이즈: 2XL(110)         1
색상: BROWN/DARK BROWN / 사이즈: 90(S)            1
색상: BROWN/DARK BROWN / 사이즈: L(100)           1
색상: BROWN/DARK BROWN / 사이즈: M(095)           1
색상: BROWN/DARK BROWN / 사이즈: W75(WS)          1
색상: BROWN/DARK BROWN / 사이즈: W85(WL)          1
색상: BROWN/DARK BROWN / 사이즈: WM(W90)          1
색상: BROWN/DARK BROWN / 사이즈: WS(W85)          1
색상: BROWN/DARK BROWN / 사이즈: XL(105)          1
색상: BROWN/ORANGE/WHITE / 사이즈: 235            1
색상: BROWN/ORANGE/WHITE / 사이즈: 240            1
색상: BROWN/ORANGE/WHITE / 사이즈: 245            1
색상: BROWN/ORANGE/WHITE / 사이즈: 255            1
색상: BROWN/ORANGE/WHITE / 사이즈: 260            1
색상: Beige / Beige / Beige / 사이즈: 280         1
색상: Beige / Beige / White / 사이즈: 220         1
색상: Beige / Beige / White / 사이즈: 235         1
색상: Beige / Beige / White / 사이즈: 245         1
색상: Beige / Blue / Red / 사이즈: 245            1
색상: Beige / Blue / Red / 사이즈: 250            1
색상: Beige / Brown / Grey / 사이즈: 240          1
색상: Beige / Brown / Grey / 사이즈: 260          1
색상: Beige / Brown / Grey / 사이즈: 280          1
색상: Beige / 사이즈: 255                         1
색상: Black / Black / Silver / 사이즈: 235        1
색상: Black / Black / Silver / 사이즈: 240        1
색상: Black / Black / Silver / 사이즈: 275        1
색상: Black / Black / Silver / 사이즈: 280        1
색상: Black / 사이즈: 220                         1
색상: Black(001) / 사이즈: 270                    1
색상: Blue / Blue / Blue / 사이즈: 280            1
색상: Brown / Brown / Brown / 사이즈: 280         1
색상: Brown / 사이즈: 260                         1
색상: Brown/Brown/Brown / 사이즈: 225             1
색상: Brown/Brown/Brown / 사이즈: 275             1
색상: Brown/Brown/Brown / 사이즈: 285             1
색상: DARK GREY / 사이즈: 085                     1
색상: DARK NAVY / 사이즈: 085                     1
색상: DARK NAVY / 사이즈: 100                     1
색상: DARK NAVY / 사이즈: W75                     1
색상: DARK NAVY / 사이즈: W90                     1
색상: DARK NAVY / 사이즈: W95                     1
색상: GRAY / 사이즈: 75(XS)                       1
색상: GRAY / 사이즈: S(090)                       1
색상: GRAY/BLACK/GRAY / 사이즈: 250               1
색상: GRAY/BLUE/BLACK / 사이즈: 255               1
색상: GRAY/BLUE/WHITE / 사이즈: 245               1
색상: GRAY/BROWN/BEIGE / 사이즈: 245              1
색상: GRAY/BROWN/BEIGE / 사이즈: 260              1
색상: GRAY/BROWN/BEIGE / 사이즈: 275              1
색상: GRAY/GRAY/BLACK / 사이즈: 230               1
색상: GRAY/GRAY/BLACK / 사이즈: 235               1
색상: GRAY/GRAY/BLACK / 사이즈: 240               1
색상: GRAY/GRAY/BLACK / 사이즈: 245               1
색상: GRAY/GRAY/BLACK / 사이즈: 250               1
색상: GRAY/GRAY/BLACK / 사이즈: 260               1
색상: GRAY/GRAY/BLACK / 사이즈: 265               1
색상: GRAY/GRAY/BLACK / 사이즈: 270               1
색상: GRAY/GRAY/GRAY / 사이즈: 240                1
색상: GRAY/GRAY/GRAY / 사이즈: 245                1
색상: GRAY/GRAY/GRAY / 사이즈: 250                1
색상: GRAY/GRAY/GRAY / 사이즈: 260                1
색상: GRAY/MELANGE GRAY / 사이즈: 85(XS)          1
색상: GRAY/WHITE/BLACK / 사이즈: 245              1
색상: GRAY/WHITE/WHITE / 사이즈: 250              1
색상: GREEN / 사이즈: 110                         1
색상: GREEN/GREEN/GREEN / 사이즈: 270             1
색상: GREEN/KHAKI / 사이즈: 000(Free)             1
색상: Grey / Black / White / 사이즈: 265          1
색상: Grey / Grey / Grey / 사이즈: 225            1
색상: Grey / Grey / Grey / 사이즈: 255            1
색상: Grey / Grey / Grey / 사이즈: 260            1
색상: Grey / Grey / Grey / 사이즈: 280            1
색상: Grey / White / Grey / 사이즈: 235           1
색상: Grey / White / Grey / 사이즈: 245           1
색상: Grey / White / Grey / 사이즈: 250           1
색상: Grey / White / Grey / 사이즈: 275           1
색상: Grey / White / Grey / 사이즈: 280           1
색상: Grey(050) / 사이즈: 250                     1
색상: Grey/Black/Black / 사이즈: 230              1
색상: Grey/Grey/Grey / 사이즈: 230                1
색상: LIGHT BEIGE / 사이즈: 105                   1
색상: LIGHT PINK / 사이즈: 000                    1
색상: LIGHT PINK / 사이즈: 095                    1
색상: LIGHT PINK / 사이즈: W95                    1
색상: NAVY / 사이즈: 000                          1
색상: OFF WHITE / 사이즈: W80                     1
색상: PINK/DARK PINK / 사이즈: 000(Free)          1
색상: PINK/DARK PINK / 사이즈: W85(WS)            1
색상: PINK/DARK PINK / 사이즈: W95(WL)            1
색상: PINK/LIGHT PINK / 사이즈: 000(Free)         1
색상: PINK/LIGHT PINK / 사이즈: 90(L)             1
색상: PINK/LIGHT PINK / 사이즈: 90(S)             1
색상: PINK/PINK/BLACK / 사이즈: 235               1
색상: PINK/PINK/PINK / 사이즈: 255                1
색상: PURPLE / 사이즈: 95(M)                      1
색상: PURPLE / 사이즈: W80(WM)                    1
색상: Pink / Pink / Black / 사이즈: 225           1
색상: Pink / Pink / Black / 사이즈: 230           1
색상: Pink / Pink / Black / 사이즈: 235           1
색상: Pink / Pink / Black / 사이즈: 240           1
색상: Pink / Pink / Black / 사이즈: 245           1
색상: RED / 사이즈: W75                           1
색상: RED / 사이즈: W85                           1
색상: RED/DARK RED / 사이즈: WXS(W80)             1
색상: RED/WINE / 사이즈: W90(WM)                  1
색상: SAND WHITE / 사이즈: 000                    1
색상: SKY BLUE / 사이즈: 000                      1
색상: WHITE / 사이즈: 100(L)                      1
색상: WHITE / 사이즈: 110(2XL)                    1
색상: WHITE / 사이즈: 85(M)                       1
색상: WHITE/BLACK/BLACK / 사이즈: 235             1
색상: WHITE/BLACK/BLACK / 사이즈: 260             1
색상: WHITE/BLACK/BLACK / 사이즈: 270             1
색상: WHITE/BROWN/BEIGE / 사이즈: 240             1
색상: WHITE/BROWN/BEIGE / 사이즈: 245             1
색상: WHITE/BROWN/BROWN / 사이즈: 250             1

In [180]:
# ========================================
# purchase_option 텍스트 정제 - 자동화 코드
# ========================================
import re

def normalize_purchase_option(text):
    if pd.isna(text):
        return text
    
    text = str(text)
    
    # 1. 영문 소문자 통일
    text = text.lower()
    
    # 2. 콜론 뒤 띄어쓰기 제거 (색상: black → 색상:black)
    text = re.sub(r':\s+', ':', text)
    
    # 3. 슬래시 앞뒤 공백 통일 ( / )
    text = re.sub(r'\s*/\s*', ' / ', text)
    
    # 4. 앞뒤 공백 제거
    text = text.strip()
    
    return text

df_review_fila_naverstore_copy['purchase_option'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .astype(str)
    .apply(normalize_purchase_option)
)

In [181]:
# ======================================================================
# purchase_option 텍스트 정제 - 컬러 부분 슬래시( / ) → 쉼표(, )로 통일
# ======================================================================

import re

def fix_color_slash(text):
    if pd.isna(text):
        return text
    
    text = str(text)
    
    def replace_with_size(m):
        color_part = re.sub(r'\s*/\s*', ',', m.group(1))
        return f'색상:{color_part} / {m.group(2)}'  # / 앞뒤 공백 유지
    
    def replace_without_size(m):
        color_part = re.sub(r'\s*/\s*', ',', m.group(1))
        return f'색상:{color_part}'
    
    if '사이즈:' in text:
        text = re.sub(r'색상:(.+?)\s*/\s*(사이즈:.+)', replace_with_size, text)
    else:
        text = re.sub(r'색상:(.+)', replace_without_size, text)
    
    return text

df_review_fila_naverstore_copy['purchase_option'] = df_review_fila_naverstore_copy['purchase_option'].apply(fix_color_slash)

In [182]:
# ================================================
# purchase_option 텍스트 정제 - 색상 영문 → 한글 변환
# ================================================
color_map = {
    'dark navy': '다크네이비',
    'dark blue': '다크블루',
    'sky blue': '스카이블루',
    'light blue': '라이트블루',
    'off white': '오프화이트',
    'light pink': '라이트핑크',
    'dark pink': '다크핑크',
    'dark red': '다크레드',
    'dark gray': '다크그레이',
    'dark grey': '다크그레이',
    'melange gray': '멜란지그레이',
    'sand white': '샌드화이트',
    'light beige': '라이트베이지',
    'oatmeal melange': '오트밀멜란지',
    'black': '블랙',
    'brown': '브라운',
    'beige': '베이지',
    'white': '화이트',
    'cream': '크림',
    'blue': '블루',
    'navy': '네이비',
    'pink': '핑크',
    'red': '레드',
    'wine': '와인',
    'green': '그린',
    'khaki': '카키',
    'gray': '그레이',
    'grey': '그레이',
    'ivory': '아이보리',
    'purple': '퍼플',
    'yellow': '옐로우',
    'silver': '실버',
    'camel': '카멜',
    'orange' : '오렌지',
    'dark brown' : '다크브라운',
    '다크레드' : '다크레드'
}

def replace_colors(text):
    if pd.isna(text):
        return text
    
    # 색상: 이후 / 사이즈: 이전 부분만 추출해서 변환
    def convert_color_part(m):
        color_part = m.group(1)
        for eng, kor in color_map.items():
            # 단어 단위로 정확히 매칭 (앞뒤가 단어 경계)
            color_part = re.sub(r'\b' + eng + r'\b', kor, color_part)
        return f'색상:{color_part}'
    
    text = re.sub(r'색상:(.+?)(?= / 사이즈:|$)', convert_color_part, text)
    return text

df_review_fila_naverstore_copy['purchase_option'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .apply(replace_colors)
)

In [183]:
# ========================================
# purchase_option 텍스트 정제 - 수동
# ========================================

df_review_fila_naverstore_copy['purchase_option'] = df_review_fila_naverstore_copy['purchase_option'].replace({
    '색상:234(다크브라운) / 사이즈:85' : '색상:다크브라운 / 사이즈:85'
})

In [184]:
# ========================================
# (free) 또는 (Free) 만 제거
# ========================================
df_review_fila_naverstore_copy['purchase_option'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .str.replace(r'\([Ff]ree\)', '', regex=True)
    .str.strip()
)

In [185]:
# ========================================
# 여성 사이즈 여부 컬럼 생성
# 여자 사이즈는 '사이즈:' 뒤에 w가 있는 경우로 판단
# 1이면 여성 사이즈, 0이면 여성 사이즈 아님
# ========================================
df_review_fila_naverstore_copy['women_size_yn'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .str.contains(r'사이즈:.*w', case=False, na=False)
    .astype(int)
) # 잘 됨 확인.

In [186]:
# ========================================
# purchase_option 텍스트 정제 - 사이즈 텍스트 매핑
# ========================================
size_map = {
    '2xl': '110',
    'xl': '105',   # 필요시 추가
    'l': '100',    # 필요시 추가
    'm': '95',     # 필요시 추가
    's': '90',     # 필요시 추가
}

def normalize_size(text):
    if pd.isna(text):
        return text
    
    text = str(text)
    
    def extract_size(m):
        size_val = m.group(1).lower()
        
        # 1. 사이즈 텍스트 매핑 먼저 처리 (2xl → 110 등)
        for key, val in size_map.items():
            if size_val == key:
                return f'사이즈:{val}'
        
        # 2. 숫자 추출
        numbers = re.findall(r'\d+', size_val)
        if numbers:
            return f'사이즈:{numbers[0]}'
        else:
            return f'사이즈:{m.group(1)}'  # 숫자 없으면 그대로 유지
    
    text = re.sub(r'사이즈:(\S+)', extract_size, text)
    return text

df_review_fila_naverstore_copy['purchase_option'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .apply(normalize_size)
)
# tests = [
#     '색상:다크_네이비 / 사이즈:w70',
#     '색상:화이트,아이보리 / 사이즈:w95(wl)',
#     '색상:234(다크브라운) / 사이즈:ws(w85)',
#     '색상:브라운 / 사이즈:w85(ws)',
#     '색상:블루,라이트_블루 / 사이즈:w90(wm)',
#     '색상:블랙 / 사이즈:000',      # 숫자만 있는 경우 → 그대로
#     '색상:블랙 / 사이즈:free',     # 숫자 없는 경우 → 그대로
# ]
# for t in tests:
#     print(normalize_size(t))

In [187]:
# ====================
# 추가 영어 매핑
# ====================
extra_color_map = {
    'dark 브라운': '다크브라운',
    'orange': '오렌지',
}

def clean_remaining(text):
    if pd.isna(text):
        return text
    
    text = str(text)
    
    # 1. 색상 부분만 추출해서 처리
    def process_color(m):
        color_part = m.group(1)
        
        # 2. '선택XX.코드(한글명)' → 한글명만 추출
        color_part = re.sub(r'선택\d+\.\d+\([^)]+\)', lambda x: re.search(r'\(([^)]+)\)', x.group()).group(1), color_part)
        
        # 3. '숫자(한글명)' → 한글명만 추출
        color_part = re.sub(r'\d+\(([^)]+)\)', r'\1', color_part)
        
        # 4. '한글명(숫자)' → 한글명만 추출
        color_part = re.sub(r'([가-힣]+)\(\d+\)', r'\1', color_part)
        
        # 5. 남은 영어 한글 혼재 처리
        for eng, kor in extra_color_map.items():
            color_part = re.sub(r'\b' + eng + r'\b', kor, color_part, flags=re.IGNORECASE)
        
        return f'색상:{color_part}'
    
    text = re.sub(r'색상:(.+?)(?= / 사이즈:|$)', process_color, text)
    return text

df_review_fila_naverstore_copy['purchase_option'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .apply(clean_remaining)
)

In [188]:
# ========================================
# purchase_option 텍스트 정제 - 사이즈 앞의 0 제거
# ========================================
def remove_leading_zero_size(text):
    if pd.isna(text):
        return text
    
    text = str(text)
    
    # 사이즈: 뒤의 0으로 시작하는 숫자 → 앞의 0 제거 (000은 유지)
    text = re.sub(r'(사이즈:)0+([1-9]\d*)', r'\g<1>\2', text)
    
    return text

df_review_fila_naverstore_copy['purchase_option'] = (
    df_review_fila_naverstore_copy['purchase_option']
    .apply(remove_leading_zero_size)
)

In [189]:
# ====================
# 변환 확인
# ====================

# 영어 포함된 행 확인
mask_eng = df_review_fila_naverstore_copy['purchase_option'].str.contains(r'[a-zA-Z]', na=False)
print(f"영어 포함된 행 수: {mask_eng.sum()}")
display(df_review_fila_naverstore_copy[mask_eng]['purchase_option'].value_counts())

# ' / ' 외의 공백이 있는지 확인
mask_space = df_review_fila_naverstore_copy['purchase_option'].str.replace(' / ', '', regex=False).str.contains(r' ', na=False)
print(f"\n' / ' 외 공백 포함된 행 수: {mask_space.sum()}")
display(df_review_fila_naverstore_copy[mask_space]['purchase_option'].value_counts())

영어 포함된 행 수: 0

Series([], Name: count, dtype: int64)

' / ' 외 공백 포함된 행 수: 0

Series([], Name: count, dtype: int64)

In [190]:
df_review_fila_naverstore_copy['purchase_option'] = df_review_fila_naverstore_copy['purchase_option'].replace({
    '색상:블랙 / 사이즈:2' : '색상:블랙 / 사이즈:110',
    '색상:브라운,다크_브라운 / 사이즈:2' : '색상:브라운,다크브라운 / 사이즈:110',
})

In [191]:
# ====================
# 실시간 확인
# ====================
display(df_review_fila_naverstore_copy['purchase_option'].value_counts(dropna=False))

purchase_option
색상:블랙 / 사이즈:000             89
색상:블랙 / 사이즈:240             29
색상:블랙 / 사이즈:90              22
색상:브라운,브라운,브라운 / 사이즈:240    18
색상:블랙 / 사이즈:270             17
색상:베이지 / 사이즈:235            16
색상:브라운 / 사이즈:85             16
색상:오프화이트 / 사이즈:95           13
색상:브라운 / 사이즈:90             13
색상:블루,라이트블루 / 사이즈:90        13
색상:블랙 / 사이즈:260             12
색상:블랙 / 사이즈:95              12
색상:브라운,브라운,브라운 / 사이즈:245    12
색상:베이지,베이지,베이지 / 사이즈:240    12
색상:블랙 / 사이즈:85              11
색상:브라운,브라운,브라운 / 사이즈:250    11
색상:화이트,크림 / 사이즈:000         11
색상:블랙 / 사이즈:250             10
색상:블랙 / 사이즈:245             10
색상:블랙 / 사이즈:235             10
색상:블랙 / 사이즈:100             10
색상:블랙 / 사이즈:105             10
색상:베이지 / 사이즈:240             9
색상:블랙 / 사이즈:280              9
색상:오프화이트 / 사이즈:85            9
색상:오프화이트 / 사이즈:105           9
색상:오프화이트 / 사이즈:110           9
색상:브라운,브라운,브라운 / 사이즈:235     9
색상:베이지,베이지,베이지 / 사이즈:235     9
색상:화이트,브라운,화이트 / 사이즈:240     8
색상:화이트 / 사이즈:240             8
색상:화이트 / 사이즈:260             8
색상:그레이,화이트,그린 / 사이즈:260      8
색상:화이트,아이보리 / 사이즈:85         8
색상:브라운 / 사이즈:000             8
색상:베이지 / 사이즈:000             8
색상:핑크 / 사이즈:000              8
색상:그레이 / 사이즈:000             8
색상:화이트 / 사이즈:250             7
색상:화이트,블랙,그레이 / 사이즈:250      7
색상:베이지 / 사이즈:245             7
색상:오프화이트 / 사이즈:100           7
색상:화이트,블랙,그레이 / 사이즈:245      7
색상:화이트,아이보리 / 사이즈:95         7
색상:다크브라운 / 사이즈:85            7
색상:블랙,블랙,화이트 / 사이즈:240       7
색상:핑크,핑크,블랙 / 사이즈:240        6
색상:핑크,핑크,블랙 / 사이즈:245        6
색상:화이트 / 사이즈:280             6
색상:화이트,블루,블루 / 사이즈:260       6
색상:블랙 / 사이즈:255              6
색상:화이트,블랙,그레이 / 사이즈:265      6
색상:오프화이트 / 사이즈:90            6
색상:그레이,그레이,그레이 / 사이즈:235     6
색상:그레이,그레이,그레이 / 사이즈:250     6
색상:그레이,그레이,그레이 / 사이즈:245     6
색상:그레이,그레이,그레이 / 사이즈:240     6
색상:블랙 / 사이즈:80               6
색상:그린,그린,그린 / 사이즈:240        6
색상:블랙,블랙,블랙 / 사이즈:240        6
색상:브라운 / 사이즈:240             6
색상:핑크,핑크,핑크 / 사이즈:240        6
색상:베이지 / 사이즈:260             5
색상:베이지 / 사이즈:250             5
색상:베이지 / 사이즈:230             5
색상:블랙 / 사이즈:230              5
색상:블랙 / 사이즈:265              5
색상:그린 / 사이즈:105              5
색상:화이트,블랙,그레이 / 사이즈:270      5
색상:화이트,블랙,그레이 / 사이즈:255      5
색상:블랙 / 사이즈:110              5
색상:그레이,그레이,그레이 / 사이즈:230     5
색상:화이트,아이보리 / 사이즈:90         5
색상:브라운 / 사이즈:95              5
색상:브라운,브라운,브라운 / 사이즈:230     5
색상:블랙,블랙,화이트 / 사이즈:245       5
색상:그레이,다크그레이 / 사이즈:000       5
색상:핑크,핑크,블랙 / 사이즈:250        5
색상:베이지 / 사이즈:220             4
색상:화이트,브라운,화이트 / 사이즈:235     4
색상:다크네이비 / 사이즈:85            4
색상:화이트,화이트,레드 / 사이즈:255      4
색상:다크네이비 / 사이즈:70            4
색상:화이트,블루,블루 / 사이즈:255       4
색상:화이트,블루,블루 / 사이즈:250       4
색상:화이트,블루,블루 / 사이즈:240       4
색상:화이트 / 사이즈:230             4
색상:화이트 / 사이즈:255             4
색상:화이트,블랙,그레이 / 사이즈:240      4
색상:화이트,블랙,그레이 / 사이즈:260      4
색상:화이트,블루,블루 / 사이즈:275       4
색상:브라운 / 사이즈:260             4
색상:크림 / 사이즈:000              4
색상:오프화이트 / 사이즈:000           4
색상:핑크,라이트핑크 / 사이즈:90         4
색상:오프화이트 / 사이즈:75            4
색상:그레이,화이트,그린 / 사이즈:240      4
색상:브라운,다크브라운 / 사이즈:90        4
색상:블루,네이비 / 사이즈:000          4
색상:블랙,블랙,화이트 / 사이즈:250       4
색상:베이지,베이지,베이지 / 사이즈:245     4
색상:그린,그린,그린 / 사이즈:230        4
색상:그린,그린,그린 / 사이즈:245        4
색상:브라운,브라운,브라운 / 사이즈:225     4
색상:브라운,베이지,베이지 / 사이즈:235     4
색상:크림 / 사이즈:240              3
색상:핑크,핑크,블랙 / 사이즈:230        3
색상:그린 / 사이즈:95               3
색상:화이트,화이트,레드 / 사이즈:270      3
색상:블랙,블랙,레드 / 사이즈:280        3
색상:화이트,블루,블루 / 사이즈:265       3
색상:베이지 / 사이즈:270             3
색상:베이지 / 사이즈:280             3
색상:화이트,블루,블루 / 사이즈:245       3
색상:베이지,베이지,화이트 / 사이즈:240     3
색상:브라운 / 사이즈:100             3
색상:브라운 / 사이즈:110             3
색상:블루 / 사이즈:100              3
색상:다크네이비 / 사이즈:110           3
색상:다크네이비 / 사이즈:95            3
색상:그레이,화이트,그린 / 사이즈:270      3
색상:화이트,아이보리 / 사이즈:80         3
색상:브라운,브라운,브라운 / 사이즈:255     3
색상:다크브라운 / 사이즈:95            3
색상:블랙,블랙,화이트 / 사이즈:235       3
색상:베이지,베이지,베이지 / 사이즈:250     3
색상:베이지,베이지,베이지 / 사이즈:225     3
색상:그린,그린,그린 / 사이즈:250        3
색상:그린,그린,그린 / 사이즈:235        3
색상:블랙,블랙,블랙 / 사이즈:260        3
색상:브라운,브라운,브라운 / 사이즈:260     3
색상:퍼플 / 사이즈:90               3
색상:블루,라이트블루 / 사이즈:95         3
색상:블랙,블랙,블랙 / 사이즈:270        3
색상:브라운,브라운,브라운 / 사이즈:275     3
색상:블랙,블랙,블랙 / 사이즈:280        3
색상:브라운 / 사이즈:235             3
색상:브라운,베이지,베이지 / 사이즈:250     3
색상:초코 / 사이즈:245              2
색상:실버문 / 사이즈:245             2
색상:실버문 / 사이즈:240             2
색상:크림 / 사이즈:235              2
색상:화이트,브라운,화이트 / 사이즈:230     2
색상:화이트,브라운,화이트 / 사이즈:250     2
색상:블랙 / 사이즈:275              2
색상:블랙 / 사이즈:290              2
색상:핑크,핑크,블랙 / 사이즈:235        2
색상:화이트,화이트,레드 / 사이즈:240      2
색상:화이트,화이트,레드 / 사이즈:265      2
색상:다크네이비 / 사이즈:80            2
색상:화이트,블루,블루 / 사이즈:235       2
색상:블랙,블랙,레드 / 사이즈:275        2
색상:그레이,화이트,그레이 / 사이즈:265     2
색상:그레이,화이트,그레이 / 사이즈:270     2
색상:화이트 / 사이즈:235             2
색상:화이트,화이트,화이트 / 사이즈:250     2
색상:화이트,화이트,화이트 / 사이즈:270     2
색상:베이지,베이지,베이지 / 사이즈:280     2
색상:베이지 / 사이즈:225             2
색상:라이트핑크 / 사이즈:95            2
색상:화이트,블루,블루 / 사이즈:270       2
색상:블랙 / 사이즈:225              2
색상:화이트 / 사이즈:85              2
색상:블루,다크네이비 / 사이즈:95         2
색상:화이트,아이보리 / 사이즈:105        2
색상:퍼플 / 사이즈:100              2
색상:핑크,라이트핑크 / 사이즈:85         2
색상:블랙 / 사이즈:75               2
색상:다크네이비 / 사이즈:105           2
색상:그레이,화이트,그린 / 사이즈:280      2
색상:베이지,브라운,그레이 / 사이즈:250     2
색상:베이지 / 사이즈:90              2
색상:그레이,그레이,그레이 / 사이즈:260     2
색상:다크브라운 / 사이즈:90            2
색상:다크브라운 / 사이즈:80            2
색상:베이지,베이지,베이지 / 사이즈:230     2
색상:그린,그린,그린 / 사이즈:220        2
색상:그린,그린,그린 / 사이즈:225        2
색상:블랙,블랙,블랙 / 사이즈:275        2
색상:블랙,블랙,블랙 / 사이즈:250        2
색상:블루,다크네이비 / 사이즈:90         2
색상:핑크,라이트핑크 / 사이즈:95         2
색상:브라운,다크브라운 / 사이즈:85        2
색상:브라운,다크브라운 / 사이즈:110       2
색상:블루,라이트블루 / 사이즈:85         2
색상:핑크,다크핑크 / 사이즈:90          2
색상:블랙,블랙,블랙 / 사이즈:245        2
색상:레드,레드,그레이 / 사이즈:240       2
색상:블랙,블랙,그레이 / 사이즈:245       2
색상:화이트,그레이,블루 / 사이즈:260      2
색상:브라운 / 사이즈:265             2
색상:브라운,베이지,베이지 / 사이즈:230     2
색상:블랙,블랙,블랙 / 사이즈:255        2
색상:베이지,베이지,베이지 / 사이즈:260     2
색상:베이지,베이지,베이지 / 사이즈:285     2
색상:옐로우,옐로우,옐로우 / 사이즈:250     2
색상:블루,블루,블루 / 사이즈:240        2
색상:블루,다크블루 / 사이즈:85          2
색상:블랙,화이트,화이트 / 사이즈:250      2
색상:그레이 / 사이즈:95              2
색상:핑크,핑크,핑크 / 사이즈:230        2
색상:그레이,브라운,베이지 / 사이즈:270     2
색상:화이트,오프화이트 / 사이즈:95        2
색상:베이지 / 사이즈:255             1
색상:초코 / 사이즈:225              1
색상:초코 / 사이즈:255              1
색상:크림 / 사이즈:275              1
색상:초코 / 사이즈:235              1
색상:크림 / 사이즈:230              1
색상:실버문 / 사이즈:265             1
색상:말차 / 사이즈:240              1
색상:초코 / 사이즈:270              1
색상:실버문 / 사이즈:235             1
색상:화이트,브라운,화이트 / 사이즈:255     1
색상:화이트,브라운,화이트 / 사이즈:270     1
색상:화이트,브라운,화이트 / 사이즈:245     1
색상:화이트,브라운,화이트 / 사이즈:275     1
색상:네이비 / 사이즈:000             1
색상:블랙,블랙,실버 / 사이즈:240        1
색상:블랙,블랙,실버 / 사이즈:235        1
색상:블랙,블랙,실버 / 사이즈:275        1
색상:블랙,블랙,실버 / 사이즈:280        1
색상:핑크,핑크,블랙 / 사이즈:225        1
색상:다크그레이 / 사이즈:85            1
색상:화이트,블루,레드 / 사이즈:240       1
색상:그린 / 사이즈:110              1
색상:화이트,화이트,레드 / 사이즈:260      1
색상:화이트,화이트,레드 / 사이즈:230      1
색상:화이트,화이트,레드 / 사이즈:275      1
색상:화이트,블루,레드 / 사이즈:275       1
색상:화이트,블루,레드 / 사이즈:235       1
색상:레드 / 사이즈:75               1
색상:레드 / 사이즈:85               1
색상:다크네이비 / 사이즈:90            1
색상:화이트,블루,블루 / 사이즈:280       1
색상:그레이,화이트,그레이 / 사이즈:275     1
색상:화이트 / 사이즈:220             1
색상:화이트,화이트,화이트 / 사이즈:260     1
색상:그레이,블랙,화이트 / 사이즈:265      1
색상:화이트,블랙,그레이 / 사이즈:235      1
색상:화이트 / 사이즈:265             1
색상:화이트 / 사이즈:275             1
색상:그레이,화이트,그레이 / 사이즈:280     1
색상:그레이,화이트,그레이 / 사이즈:245     1
색상:그레이,화이트,그레이 / 사이즈:250     1
색상:그레이,화이트,그레이 / 사이즈:235     1
색상:화이트 / 사이즈:245             1
색상:화이트,블랙,블루 / 사이즈:280       1
색상:브라운,브라운,브라운 / 사이즈:280     1
색상:베이지,블루,레드 / 사이즈:245       1
색상:베이지,블루,레드 / 사이즈:250       1
색상:스카이블루 / 사이즈:000           1
색상:샌드화이트 / 사이즈:000           1
색상:베이지,베이지,화이트 / 사이즈:235     1
색상:베이지,베이지,화이트 / 사이즈:245     1
색상:베이지,베이지,화이트 / 사이즈:220     1
색상:그레이,그레이,그레이 / 사이즈:255     1
색상:그레이,그레이,그레이 / 사이즈:225     1
색상:블루,블루,블루 / 사이즈:280        1
색상:화이트 / 사이즈:100             1
색상:화이트 / 사이즈:110             1
색상:블루,다크네이비 / 사이즈:100        1
색상:다크네이비 / 사이즈:75            1
색상:오프화이트 / 사이즈:80            1
색상:라이트베이지 / 사이즈:105          1
색상:화이트,블랙,그레이 / 사이즈:230      1
색상:라이트핑크 / 사이즈:000           1
색상:다크네이비 / 사이즈:100           1
색상:베이지,브라운,그레이 / 사이즈:240     1
색상:베이지,브라운,그레이 / 사이즈:280     1
색상:베이지,브라운,그레이 / 사이즈:260     1
색상:베이지,오트밀멜란지 / 사이즈:90       1
색상:베이지 / 사이즈:85              1
색상:그레이,그레이,그레이 / 사이즈:280     1
색상:그레이 / 사이즈:250             1
색상:블랙,블랙,블랙 / 사이즈:225        1
색상:그린,카키 / 사이즈:000           1
색상:화이트,크림 / 사이즈:85           1
색상:브라운 / 사이즈:80              1
색상:그레이,블랙,블랙 / 사이즈:230       1
색상:화이트,브라운,블루 / 사이즈:260      1
색상:화이트,브라운,블루 / 사이즈:270      1
색상:블랙 / 사이즈:220              1
색상:다크레드 / 사이즈:90             1
색상:핑크,라이트핑크 / 사이즈:000        1
색상:블랙,블랙,화이트 / 사이즈:225       1
색상:브라운,오렌지,화이트 / 사이즈:240     1
색상:브라운,오렌지,화이트 / 사이즈:255     1
색상:브라운,오렌지,화이트 / 사이즈:235     1
색상:브라운,오렌지,화이트 / 사이즈:260     1
색상:브라운,오렌지,화이트 / 사이즈:245     1
색상:베이지,베이지,베이지 / 사이즈:290     1
색상:그린,그린,그린 / 사이즈:270        1
색상:블랙,블랙,블랙 / 사이즈:265        1
색상:브라운,다크브라운 / 사이즈:95        1
색상:브라운,다크브라운 / 사이즈:100       1
색상:브라운,다크브라운 / 사이즈:105       1
색상:브라운,다크브라운 / 사이즈:2         1
색상:그레이,블루,블랙 / 사이즈:255       1
색상:브라운,다크브라운 / 사이즈:75        1
색상:브라운 / 사이즈:105             1
색상:레드,와인 / 사이즈:90            1
색상:블루 / 사이즈:105              1
색상:퍼플 / 사이즈:95               1
색상:블루 / 사이즈:110              1
색상:핑크,다크핑크 / 사이즈:95          1
색상:핑크,다크핑크 / 사이즈:85          1
색상:화이트,아이보리 / 사이즈:000        1
색상:브라운,브라운,브라운 / 사이즈:265     1
색상:브라운,브라운,브라운 / 사이즈:270     1
색상:베이지,카멜 / 사이즈:100          1
색상:화이트,화이트,화이트 / 사이즈:285     1
색상:블랙,블랙,그레이 / 사이즈:270       1
색상:블랙,블랙,그레이 / 사이즈:235       1
색상:화이트,그레이,블루 / 사이즈:270      1
색상:베이지,블랙,핑크 / 사이즈:270       1
색상:베이지,베이지,베이지 / 사이즈:270     1
색상:그레이,멜란지그레이 / 사이즈:85       1
색상:그레이,블루,화이트 / 사이즈:245      1
색상:브라운 / 사이즈:280             1
색상:브라운 / 사이즈:245             1
색상:브라운 / 사이즈:255             1
색상:브라운 / 사이즈:230             1
색상:브라운,베이지,베이지 / 사이즈:240     1
색상:브라운,베이지,베이지 / 사이즈:265     1
색상:브라운,베이지,베이지 / 사이즈:245     1
색상:브라운,브라운,브라운 / 사이즈:285     1
색상:퍼플 / 사이즈:80               1
색상:그레이,그레이,블랙 / 사이즈:245      1
색상:화이트,그레이,블루 / 사이즈:250      1
색상:그레이 / 사이즈:75              1
색상:블랙,블랙,그레이 / 사이즈:275       1
색상:블랙,블랙,그레이 / 사이즈:255       1
색상:화이트,브라운,브라운 / 사이즈:250     1
색상:베이지,베이지,베이지 / 사이즈:265     1
색상:베이지,베이지,베이지 / 사이즈:255     1
색상:옐로우,옐로우,옐로우 / 사이즈:255     1
색상:블루,블루,블루 / 사이즈:235        1
색상:블루,블루,블루 / 사이즈:245        1
색상:블루,블루,블루 / 사이즈:225        1
색상:블루,블루,블루 / 사이즈:230        1
색상:레드,다크레드 / 사이즈:80          1
색상:블루,다크블루 / 사이즈:100         1
색상:블루,다크블루 / 사이즈:95          1
색상:브라운 / 사이즈:75              1
색상:옐로우 / 사이즈:000             1
색상:블루 / 사이즈:000              1
색상:핑크,다크핑크 / 사이즈:000         1
색상:베이지 / 사이즈:75              1
색상:화이트,화이트,핑크 / 사이즈:230      1
색상:화이트,화이트,블루 / 사이즈:280      1
색상:그레이,화이트,화이트 / 사이즈:250     1
색상:베이지,화이트,베이지 / 사이즈:240     1
색상:베이지,화이트,베이지 / 사이즈:250     1
색상:베이지,화이트,베이지 / 사이즈:270     1
색상:블루,화이트,블랙 / 사이즈:240       1
색상:블랙,그레이,화이트 / 사이즈:240      1
색상:그레이,블랙,그레이 / 사이즈:250      1
색상:화이트,화이트,베이지 / 사이즈:280     1
색상:화이트,화이트,베이지 / 사이즈:255     1
색상:화이트,화이트,베이지 / 사이즈:235     1
색상:화이트,그린,그레이 / 사이즈:290      1
색상:베이지 / 사이즈:105             1
색상:그레이 / 사이즈:90              1
색상:화이트,화이트,화이트 / 사이즈:265     1
색상:화이트,화이트,화이트 / 사이즈:275     1
색상:그레이,화이트,블랙 / 사이즈:245      1
색상:블루,레드,블루 / 사이즈:250        1
색상:블랙,화이트,화이트 / 사이즈:220      1
색상:블랙,화이트,화이트 / 사이즈:225      1
색상:화이트,화이트,화이트 / 사이즈:255     1
색상:화이트,블랙,블랙 / 사이즈:235       1
색상:화이트,블랙,블랙 / 사이즈:260       1
색상:화이트,블랙,블랙 / 사이즈:270       1
색상:화이트,화이트,블랙 / 사이즈:230      1
색상:화이트,그린,그린 / 사이즈:275       1
색상:그레이,그레이,블랙 / 사이즈:235      1
색상:그레이,그레이,블랙 / 사이즈:230      1
색상:그레이,그레이,블랙 / 사이즈:240      1
색상:그레이,그레이,블랙 / 사이즈:265      1
색상:그레이,그레이,블랙 / 사이즈:270      1
색상:그레이,그레이,블랙 / 사이즈:250      1
색상:그레이,그레이,블랙 / 사이즈:260      1
색상:블루,블루,블루 / 사이즈:255        1
색상:핑크,핑크,핑크 / 사이즈:255        1
색상:그레이,브라운,베이지 / 사이즈:275     1
색상:그레이,브라운,베이지 / 사이즈:245     1
색상:그레이,브라운,베이지 / 사이즈:260     1
색상:화이트,브라운,베이지 / 사이즈:240     1
색상:화이트,브라운,베이지 / 사이즈:245     1
색상:베이지,베이지,베이지 / 사이즈:220     1
색상:화이트,화이트,블루 / 사이즈:250      1
색상:화이트,그레이,그레이 / 사이즈:260     1
색상:베이지,베이지,브라운 / 사이즈:250     1
색상:화이트,레드,화이트 / 사이즈:280      1
색상:화이트,아이보리 / 사이즈:100        1
색상:화이트,오프화이트 / 사이즈:100       1
색상:화이트,오프화이트 / 사이즈:90        1
색상:블랙 / 사이즈:60               1
Name: count, dtype: int64

In [192]:
# ========================
# purchase_option 컬럼 분리
# ========================
def split_purchase_option(text):
    color, size = None, None
    
    if pd.isna(text):
        return pd.Series([None, None])
    
    parts = str(text).split(' / ')
    for part in parts:
        if part.startswith('색상:'):
            color = part.replace('색상:', '')
        elif part.startswith('사이즈:'):
            size = part.replace('사이즈:', '')
    
    return pd.Series([color, size])

df_review_fila_naverstore_copy[['purchase_option_color', 'purchase_option_size']] = (
    df_review_fila_naverstore_copy['purchase_option']
    .apply(split_purchase_option)
)

df_review_fila_naverstore_copy.head(10)

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,...,has_image,purchase_option,user_height,user_weight,user_height_group,user_weight_group,product_url,women_size_yn,purchase_option_color,purchase_option_size
0,2026-04-21,네이버스토어,4.669237e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기 매기 딱 좋아요 귀여움은 덤,5,...,1,색상:블랙 / 사이즈:000,None,None,None,None,https://brand.naver.com/fila/products/10769719940,0,블랙,000
1,2026-04-21,네이버스토어,4.652212e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,...,1,색상:블랙 / 사이즈:000,None,None,None,None,https://brand.naver.com/fila/products/10769719940,0,블랙,000
2,2026-04-21,네이버스토어,4.652239e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,...,1,색상:블랙 / 사이즈:000,None,None,None,None,https://brand.naver.com/fila/products/10769719940,0,블랙,000
3,2026-04-21,네이버스토어,4.634973e+09,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다 이뿌구요,5,...,1,색상:블랙 / 사이즈:000,None,None,None,None,https://brand.naver.com/fila/products/10769719940,0,블랙,000
4,2026-04-21,네이버스토어,4.944300e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요 그리고 발은 오래신으면 아플것 같아요 디자인은 꽃처럼 귀여움,4,...,1,색상:베이지 / 사이즈:220,None,None,None,None,https://brand.naver.com/fila/products/11293482675,0,베이지,220
5,2026-04-21,네이버스토어,4.956967e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-18,2026,4,빠른배송 감사합니다,5,...,1,색상:베이지 / 사이즈:260,None,None,None,None,https://brand.naver.com/fila/products/11293482675,0,베이지,260
6,2026-04-21,네이버스토어,4.945147e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-03,2026,4,투박한듯 여성스러운 디테일이 살아있어 다양한 룩에 활용가능해요 아주 마음에 듭니다,5,...,1,색상:베이지 / 사이즈:260,None,None,None,None,https://brand.naver.com/fila/products/11293482675,0,베이지,260
7,2026-04-21,네이버스토어,4.951824e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-11,2026,4,신발 편안하고 이뻐요,5,...,1,색상:베이지 / 사이즈:255,None,None,None,None,https://brand.naver.com/fila/products/11293482675,0,베이지,255
8,2026-04-21,네이버스토어,4.935903e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-03-22,2026,3,굽도 적당하고 봄에 신고 다니기 좋은거 같네요 따로 신발끈 묶을 필요도 없어서 편해요,5,...,1,색상:베이지 / 사이즈:235,None,None,None,None,https://brand.naver.com/fila/products/11293482675,0,베이지,235
9,2026-04-21,네이버스토어,4.935868e+09,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-03-22,2026,3,잘 맞아요 잘 신고 있어요,5,...,1,색상:베이지 / 사이즈:240,None,None,None,None,https://brand.naver.com/fila/products/11293482675,0,베이지,240

In [193]:
# =========================================
# 띄어쓰기 제거 후 5글자 이하인 데이터 확인
# =========================================
short_mask = df_review_fila_naverstore_copy['content'].str.replace(' ', '', regex=False).str.len() <= 5

print(f"5글자 이하 행 수: {short_mask.sum()}")
display(df_review_fila_naverstore_copy[short_mask]['content'].value_counts())

5글자 이하 행 수: 8

content
          3
만족합니다     2
너무 예뻐요    1
좋아요       1
예뻐요       1
Name: count, dtype: int64

In [194]:
# =========================
# 5글자 이하 행 제거
# =========================
before = len(df_review_fila_naverstore_copy)
df_review_fila_naverstore_copy = df_review_fila_naverstore_copy[~short_mask]
after = len(df_review_fila_naverstore_copy)

print(f"제거 전: {before}개")
print(f"제거된 행: {before - after}개")
print(f"제거 후: {after}개")

제거 전: 1277개
제거된 행: 8개
제거 후: 1269개

In [195]:
# ========================
# 최종 컬럼 정리
# ========================

# 1) 데이터 형변환
def convert_dtypes(df):
    
    # 날짜 컬럼
    for col in ["collect_date", "review_date"]:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    # ID 컬럼
    for col in ["review_id", "product_id"]:
        if col in df.columns:
            df[col] = df[col].astype("string")

    # 문자열 컬럼
    for col in ["product_name", "content", "purchase_option", "product_url"]:
        if col in df.columns:
            df[col] = df[col].astype("string")

    # category 컬럼
    for col in ["platform", "purchase_option_color", "purchase_option_size", "user_height_group", "user_weight_group"]:
        if col in df.columns:
            df[col] = df[col].astype("category")

    # 정수형 컬럼
    for col, dtype in [("year", "Int16"), ("month", "Int8"), ("rating", "Int8"), ("helpful_count", "Int32")]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype(dtype)

    # 0/1 플래그 컬럼
    for col in ["has_image", "women_size_yn"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype("int8")

    # 실수형 컬럼
    for col in ["user_height", "user_weight"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("float32")

    return df

# 사용
df_review_fila_naverstore_copy = convert_dtypes(df_review_fila_naverstore_copy)
df_review_fila_naverstore_copy.info(memory_usage="deep")

<class 'pandas.DataFrame'>
Index: 1269 entries, 0 to 1276
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   collect_date           1269 non-null   datetime64[us]
 1   platform               1269 non-null   category
 2   review_id              1269 non-null   string
 3   product_id             1269 non-null   string
 4   product_name           1269 non-null   string
 5   review_date            1269 non-null   datetime64[us]
 6   year                   1269 non-null   Int16
 7   month                  1269 non-null   Int8
 8   content                1269 non-null   string
 9   rating                 1269 non-null   Int8
 10  helpful_count          1269 non-null   Int32
 11  has_image              1269 non-null   int8
 12  purchase_option        1269 non-null   string
 13  user_height            0 non-null      float32
 14  user_weight            0 non-null      float32
 15  user_height_group      0 non-null      category
 16  user_weight_group      0 non-null      category
 17  product_url            1269 non-null   string
 18  women_size_yn          1269 non-null   int8
 19  purchase_option_color  1269 non-null   category
 20  purchase_option_size   1269 non-null   category
dtypes: Int16(1), Int32(1), Int8(2), category(5), datetime64[us](2), float32(2), int8(2), string(6)
memory usage: 451.5 KB

In [196]:
# ======================
# 컬럼 순서 재정렬
# ======================

column_order = [
    'collect_date',
    'platform',
    'review_id',
    'product_id',
    'product_name',
    'review_date',
    'year',
    'month',
    'content',
    'rating',
    'helpful_count',
    'has_image',
    'purchase_option',
    'purchase_option_color',
    'purchase_option_size',
    'women_size_yn',
    'user_height',
    'user_weight',
    'user_height_group',
    'user_weight_group',
    'product_url'
]

# 컬럼 존재하는 것만 선택 (안전하게)
df_review_fila_naverstore_copy = df_review_fila_naverstore_copy[
    [col for col in column_order if col in df_review_fila_naverstore_copy.columns]
]

# 확인
df_review_fila_naverstore_copy.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,...,has_image,purchase_option,purchase_option_color,purchase_option_size,women_size_yn,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,네이버스토어,4669237248.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기 매기 딱 좋아요 귀여움은 덤,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
1,2026-04-21,네이버스토어,4652211610.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
2,2026-04-21,네이버스토어,4652239375.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
3,2026-04-21,네이버스토어,4634973142.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다 이뿌구요,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
4,2026-04-21,네이버스토어,4944299801.0,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요 그리고 발은 오래신으면 아플것 같아요 디자인은 꽃처럼 귀여움,4,...,1,색상:베이지 / 사이즈:220,베이지,220,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/11293482675

In [197]:
# ===============================
# Missing value => None 처리
# ===============================
df_review_fila_naverstore_copy = df_review_fila_naverstore_copy.where(
    df_review_fila_naverstore_copy.notna(), other=None
)

## 저장하기

In [198]:
# ===============================
# 저장하기
# ===============================
df_review_fila_naverstore_2024 = df_review_fila_naverstore_copy[df_review_fila_naverstore_copy['year'] >= 2024]

df_review_fila_naverstore_copy.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_naverstore_review_final.csv", encoding='utf-8-sig', index=False)
df_review_fila_naverstore_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_naverstore_review_final_s2024.csv", encoding='utf-8-sig', index=False)

In [199]:
df_review_fila_naverstore_2024.head()

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,...,has_image,purchase_option,purchase_option_color,purchase_option_size,women_size_yn,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-21,네이버스토어,4669237248.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-02-24,2025,2,크기는 작지만 실용성 잇게 여기저기 매기 딱 좋아요 귀여움은 덤,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
1,2026-04-21,네이버스토어,4652211610.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,생각보다 작은데 가벼운 소지품 가지고 다니긴 딱이예요,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
2,2026-04-21,네이버스토어,4652239375.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-31,2025,1,넘 귀야워요 만족ㅎㅎ,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
3,2026-04-21,네이버스토어,4634973142.0,10718496494,[FILA] 푸퍼 미니 토트백 (FS3BCG4320F_BLK),2025-01-03,2025,1,깜찍합니다 이뿌구요,5,...,1,색상:블랙 / 사이즈:000,블랙,000,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/10769719940
4,2026-04-21,네이버스토어,4944299801.0,11240513968,휠라 에샤페 레이스_1XM02347H920,2026-04-02,2026,4,정사이즈보다 크게 나왔나봐요ㅠㅠ 조금 커요 그리고 발은 오래신으면 아플것 같아요 디자인은 꽃처럼 귀여움,4,...,1,색상:베이지 / 사이즈:220,베이지,220,0,NaN,NaN,NaN,NaN,https://brand.naver.com/fila/products/11293482675