In [328]:
import pandas as pd
import numpy as np

---
# 휠라 자사몰 리뷰 데이터

## 1. 전처리

In [329]:
# ===============================
# 데이터 불러오기
# ===============================
import pandas as pd

df_review_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/reviews/fila_reviews_complete_final.csv", encoding='utf-8')
display(df_review_fila_D2C.head(1))

df_product_fila_D2C = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/products/fila_snapshot_master_260422.csv", encoding='utf-8')
display(df_product_fila_D2C.head(1))

,product_name,search_keyword,review_id,collect_date,post_date,platform,brand,reviewer_id,content,source_url,rating,helpful_count,purchased_option,has_image
0,1911 니트트랙 스커트,1100FS261SK01F002234,138306,2026-04-23,2026-03-03,자사몰리뷰,휠라,das****,믿고 사는 브랜드라 착용감도 좋아요,https://www.fila.co.kr/product/1100fs261sk01f002234,5,0,컬러:001 / 사이즈:WS(W75),0

,category1,category2,category3,collect_date,brand,product_id,product_name,product_type,category,gender,original_price,discount_price,color_count,raw_colors,review_count,launch_year,launch_season
0,상의,긴팔티셔츠,일반,2026-04-20,FILA,1100fs261rl01x001001,베이직 긴팔 티셔츠,의류,긴팔,공용,49900,49900,3,블랙,1,2026,SPRING

In [330]:
print(df_review_fila_D2C.info())
display(df_review_fila_D2C.head())

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_name      10355 non-null  str
 1   search_keyword    10355 non-null  str
 2   review_id         10355 non-null  int64
 3   collect_date      10355 non-null  str
 4   post_date         10355 non-null  str
 5   platform          10355 non-null  str
 6   brand             10355 non-null  str
 7   reviewer_id       10355 non-null  str
 8   content           10355 non-null  str
 9   source_url        10355 non-null  str
 10  rating            10355 non-null  int64
 11  helpful_count     10355 non-null  int64
 12  purchased_option  1655 non-null   str
 13  has_image         10355 non-null  int64
dtypes: int64(4), str(10)
memory usage: 4.6 MB
None

,product_name,search_keyword,review_id,collect_date,post_date,platform,brand,reviewer_id,content,source_url,rating,helpful_count,purchased_option,has_image
0,1911 니트트랙 스커트,1100FS261SK01F002234,138306,2026-04-23,2026-03-03,자사몰리뷰,휠라,das****,믿고 사는 브랜드라 착용감도 좋아요,https://www.fila.co.kr/product/1100fs261sk01f002234,5,0,컬러:001 / 사이즈:WS(W75),0
1,1911 니트트랙 스커트,1100FS261SK01F002234,137413,2026-04-23,2026-02-09,자사몰리뷰,휠라,tjd****,원단도좋고 여섯ㅇ스럽고 이뻐요 다들이뻐다 난리에요...,https://www.fila.co.kr/product/1100fs261sk01f002234,5,0,컬러:234 / 사이즈:WL(W85),1
2,1911 니트트랙 팬츠,1100FS261FP01U001001,139180,2026-04-23,2026-03-18,자사몰리뷰,휠라,gus****,길이도 재질도 너무 좋아서 엄마가 좋아해요,https://www.fila.co.kr/product/1100fs261fp01u001001,5,0,사이즈:M(085),0
3,1911 니트트랙 팬츠,1100FS261FP01U001001,139210,2026-04-23,2026-03-18,자사몰리뷰,휠라,ton****,남편 우즈 만들기!! 우즈가 아니여도 너무너무 예뻐요,https://www.fila.co.kr/product/1100fs261fp01u001001,5,0,사이즈:XL(95),0
4,1911 니트트랙 팬츠,1100FS261FP01U001001,142705,2026-04-23,2026-04-10,자사몰리뷰,휠라,kjs****,니트소재라 보플이 생길것 같으나 부드럽고 지금 입기 딱 좋아보여,https://www.fila.co.kr/product/1100fs261fp01u001001,5,0,사이즈:WM(W80),0

In [331]:
# ===============================
# 필요한 컬럼 선택
# ===============================

df_review_fila_D2C = df_review_fila_D2C[[
    'product_name', 'search_keyword', 'review_id', 'collect_date', 'post_date', 'platform', 'content', 'source_url', 'rating', 'helpful_count', 'purchased_option', 'has_image'
]] # 11개

display(df_review_fila_D2C.head(3))
display(df_review_fila_D2C.info())

,product_name,search_keyword,review_id,collect_date,post_date,platform,content,source_url,rating,helpful_count,purchased_option,has_image
0,1911 니트트랙 스커트,1100FS261SK01F002234,138306,2026-04-23,2026-03-03,자사몰리뷰,믿고 사는 브랜드라 착용감도 좋아요,https://www.fila.co.kr/product/1100fs261sk01f002234,5,0,컬러:001 / 사이즈:WS(W75),0
1,1911 니트트랙 스커트,1100FS261SK01F002234,137413,2026-04-23,2026-02-09,자사몰리뷰,원단도좋고 여섯ㅇ스럽고 이뻐요 다들이뻐다 난리에요...,https://www.fila.co.kr/product/1100fs261sk01f002234,5,0,컬러:234 / 사이즈:WL(W85),1
2,1911 니트트랙 팬츠,1100FS261FP01U001001,139180,2026-04-23,2026-03-18,자사몰리뷰,길이도 재질도 너무 좋아서 엄마가 좋아해요,https://www.fila.co.kr/product/1100fs261fp01u001001,5,0,사이즈:M(085),0

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_name      10355 non-null  str
 1   search_keyword    10355 non-null  str
 2   review_id         10355 non-null  int64
 3   collect_date      10355 non-null  str
 4   post_date         10355 non-null  str
 5   platform          10355 non-null  str
 6   content           10355 non-null  str
 7   source_url        10355 non-null  str
 8   rating            10355 non-null  int64
 9   helpful_count     10355 non-null  int64
 10  purchased_option  1655 non-null   str
 11  has_image         10355 non-null  int64
dtypes: int64(4), str(8)
memory usage: 4.2 MB

None

In [332]:
# ===============================
# 컬럼 이름 정리
# ===============================

df_review_fila_D2C = df_review_fila_D2C.rename(columns={
    'search_keyword' : 'product_id',
    'post_date' : 'review_date',
    'source_url' : 'product_url',
    'purchased_option' : 'purchase_option'
})

df_review_fila_D2C.head(1)

,product_name,product_id,review_id,collect_date,review_date,platform,content,product_url,rating,helpful_count,purchase_option,has_image
0,1911 니트트랙 스커트,1100FS261SK01F002234,138306,2026-04-23,2026-03-03,자사몰리뷰,믿고 사는 브랜드라 착용감도 좋아요,https://www.fila.co.kr/product/1100fs261sk01f002234,5,0,컬러:001 / 사이즈:WS(W75),0

In [333]:
# ===============================
# 없는 컬럼 추가
# ===============================

# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'user_size', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df_review_fila_D2C.columns:
        df_review_fila_D2C[col] = None

# 컬럼 순서 정리
df_review_fila_D2C = df_review_fila_D2C[required_columns]

In [334]:
df_review_fila_D2C.head(1)

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-23,자사몰리뷰,138306,1100FS261SK01F002234,1911 니트트랙 스커트,2026-03-03,None,None,믿고 사는 브랜드라 착용감도 좋아요,5,0,0,컬러:001 / 사이즈:WS(W75),None,None,None,None,None,https://www.fila.co.kr/product/1100fs261sk01f002234

In [335]:
# ===============================
# 데이터 타입 변환
# ===============================
df_review_fila_D2C['collect_date'] = pd.to_datetime(df_review_fila_D2C['collect_date'])
df_review_fila_D2C['review_date'] = pd.to_datetime(df_review_fila_D2C['review_date'])
df_review_fila_D2C['rating'] = df_review_fila_D2C['rating'].astype(int)
df_review_fila_D2C['helpful_count'] = df_review_fila_D2C['helpful_count'].astype(int)

df_review_fila_D2C['platform'] = df_review_fila_D2C['platform'].astype('category')

In [336]:
# ===============================
# year, month 컬럼 만들기
# ===============================
df_review_fila_D2C['year'] = df_review_fila_D2C['review_date'].dt.year
df_review_fila_D2C['month'] = df_review_fila_D2C['review_date'].dt.month

In [337]:
# ===============================
# 데이터 값 확인
# ===============================
df_review_fila_D2C['purchase_option'].value_counts(dropna=False)

purchase_option
NaN                 8700
사이즈:240               69
사이즈:95(M)             50
사이즈:095               48
사이즈:235               41
                    ...
사이즈:270 / 컬러:102       1
사이즈:290 / 컬러:820       1
사이즈:290 / 컬러:002       1
사이즈:255 / 컬러:002       1
사이즈:245 / 컬러:261       1
Name: count, Length: 395, dtype: int64

In [338]:
# ===============================
# platform 데이터 수정하기
# ===============================
# category 타입 해제 후 변경
df_review_fila_D2C['platform'] = df_review_fila_D2C['platform'].astype(str).replace({
    '자사몰리뷰': '자사몰',
    '무신사리뷰': '무신사',
    '네이버리뷰': '네이버스토어'
}).astype('category')

In [339]:
df_review_fila_D2C['purchase_option'].isna().mean()*100

np.float64(84.01738290680831)

In [340]:
# 확인
df_review_fila_D2C.info()
df_review_fila_D2C.head(3)

<class 'pandas.DataFrame'>
RangeIndex: 10355 entries, 0 to 10354
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   collect_date       10355 non-null  datetime64[us]
 1   platform           10355 non-null  category
 2   review_id          10355 non-null  int64
 3   product_id         10355 non-null  str
 4   product_name       10355 non-null  str
 5   review_date        10355 non-null  datetime64[us]
 6   year               10355 non-null  int32
 7   month              10355 non-null  int32
 8   content            10355 non-null  str
 9   rating             10355 non-null  int64
 10  helpful_count      10355 non-null  int64
 11  has_image          10355 non-null  int64
 12  purchase_option    1655 non-null   str
 13  user_size          0 non-null      object
 14  user_height        0 non-null      object
 15  user_weight        0 non-null      object
 16  user_height_group  0 non-null      object
 17  user_weight_group  0 non-null      object
 18  product_url        10355 non-null  str
dtypes: category(1), datetime64[us](2), int32(2), int64(4), object(5), str(5)
memory usage: 4.3+ MB

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,user_size,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-23,자사몰,138306,1100FS261SK01F002234,1911 니트트랙 스커트,2026-03-03,2026,3,믿고 사는 브랜드라 착용감도 좋아요,5,0,0,컬러:001 / 사이즈:WS(W75),None,None,None,None,None,https://www.fila.co.kr/product/1100fs261sk01f002234
1,2026-04-23,자사몰,137413,1100FS261SK01F002234,1911 니트트랙 스커트,2026-02-09,2026,2,원단도좋고 여섯ㅇ스럽고 이뻐요 다들이뻐다 난리에요...,5,0,1,컬러:234 / 사이즈:WL(W85),None,None,None,None,None,https://www.fila.co.kr/product/1100fs261sk01f002234
2,2026-04-23,자사몰,139180,1100FS261FP01U001001,1911 니트트랙 팬츠,2026-03-18,2026,3,길이도 재질도 너무 좋아서 엄마가 좋아해요,5,0,0,사이즈:M(085),None,None,None,None,None,https://www.fila.co.kr/product/1100fs261fp01u001001

## 2. 중복제거

In [341]:
# ===============================
# 제품명 매칭 확인
# ===============================
pd.set_option('display.max_colwidth', None) # 컬럼 안 텍스트 잘림 제거

multi_name = df_review_fila_D2C.groupby('product_id')['product_name'].nunique()
multi_url = df_review_fila_D2C.groupby('product_id')['product_url'].nunique()

# product_name 매핑 확인
print(multi_name.gt(1).sum(), "개의 product_id가 여러 product_name에 매핑됨")
display(
    df_review_fila_D2C[df_review_fila_D2C['product_id'].isin(multi_name[multi_name > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

# product_url 매핑 확인
print(multi_url.gt(1).sum(), "개의 product_id가 여러 product_url에 매핑됨")
display(
    df_review_fila_D2C[df_review_fila_D2C['product_id'].isin(multi_url[multi_url > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

0 개의 product_id가 여러 product_name에 매핑됨

Empty DataFrame
Columns: [product_id, product_name, product_url]
Index: []

194 개의 product_id가 여러 product_url에 매핑됨

,product_id,product_name,product_url
7880,11001JM02570H001,플루이드 v2,https://www.fila.co.kr/product/11001jm02570h001
7883,11001JM02570H001,플루이드 v2,https://www.fila.co.kr/product/1100fs261od03x039021
6742,11001JM02786H067,오크먼트 TR v2,https://www.fila.co.kr/product/11001jm02786h924
6743,11001JM02786H067,오크먼트 TR v2,https://www.fila.co.kr/product/11001jm02786h067
6819,11001JM02787H050,오크먼트 TR 다이얼 v2,https://www.fila.co.kr/product/11001jm02787h001
...,...,...,...
2808,1260FV254BR17F002001,<큰컵추천> 리프팅업 퓨징 브라,https://www.fila.co.kr/product/1260fv254br17f001660
522,1260FV254DR17F001260,<복부보정> 리프팅업 퓨징 팬티,https://www.fila.co.kr/product/1260fv254dr17f001260
523,1260FV254DR17F001260,<복부보정> 리프팅업 퓨징 팬티,https://www.fila.co.kr/product/1260fv254dr17f001660
525,1260FV254DR17F001260,<복부보정> 리프팅업 퓨징 팬티,https://www.fila.co.kr/product/1260fv254dr17f001370
528,1260FV254DR17F001260,<복부보정> 리프팅업 퓨징 팬티,https://www.fila.co.kr/product/1260fv254dr17f001261

In [342]:
# ===============================
# 리뷰 내용 중복 확인
# ===============================
# 2-1. product_id 같고 content 중복인 데이터 확인
dup_mask = df_review_fila_D2C.duplicated(subset=['product_id', 'content'], keep=False)
print("product_id는 같고 content가 중복 개수: ", dup_mask.sum())
display(df_review_fila_D2C[dup_mask][['product_id', 'product_name', 'review_date', 'content']].sort_values(['product_id', 'content']).head(20))

# 2-2. 위 경우 중 review_date까지 완전히 동일한 경우 개수
print(
    "review_date까지 완전히 동일한 경우 개수: "
    , df_review_fila_D2C[dup_mask].duplicated(subset=['product_id', 'content', 'review_date'], keep=False).sum()
)

# 2-3. product_id, content, review_date, purchase_option 까지 모두 중복인 경우
dup_mask_full = df_review_fila_D2C.duplicated(
    subset=['product_id', 'content', 'review_date', 'purchase_option'],
    keep=False
)
print("purchase_option까지 완전히 동일한 경우 개수: ", dup_mask_full.sum())
display(
    df_review_fila_D2C[dup_mask_full][['product_id', 'product_name', 'review_date', 'purchase_option', 'content']]
    .sort_values(['product_id', 'review_date'])
    .head(20)
)

product_id는 같고 content가 중복 개수:  0

Empty DataFrame
Columns: [product_id, product_name, review_date, content]
Index: []

review_date까지 완전히 동일한 경우 개수:  0
purchase_option까지 완전히 동일한 경우 개수:  0

Empty DataFrame
Columns: [product_id, product_name, review_date, purchase_option, content]
Index: []

---
# 주하님 작업 후 정제
- 사용 원본파일: final > fila_homepage_review_final_s2024_jh

In [343]:
# ===============================
# 데이터 로드
# ===============================
import pandas as pd
df = pd.read_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final_s2024_jh.csv", encoding='utf-8')

display(df.info())
display(df.head(40))

<class 'pandas.DataFrame'>
RangeIndex: 10689 entries, 0 to 10688
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   collect_date           10689 non-null  str
 1   brand                  10689 non-null  str
 2   platform               10689 non-null  str
 3   review_id              10689 non-null  int64
 4   product_id             10689 non-null  int64
 5   product_name           10689 non-null  str
 6   post_date              10689 non-null  str
 7   year                   10689 non-null  int64
 8   month                  10689 non-null  int64
 9   content                10689 non-null  str
 10  rating                 10689 non-null  int64
 11  helpful_count          10689 non-null  int64
 12  has_image              10689 non-null  int64
 13  purchased_option       1735 non-null   str
 14  purchase_option_size   1611 non-null   str
 15  purchase_option_color  124 non-null    float64
 16  source_url             10689 non-null  str
 17  ai_positive_tags       9334 non-null   str
 18  ai_negative_tags       1016 non-null   str
 19  product_code           10689 non-null  str
 20  related_product_ids    10689 non-null  str
dtypes: float64(1), int64(7), str(13)
memory usage: 5.7 MB

None

,collect_date,brand,platform,review_id,product_id,product_name,post_date,year,month,content,...,helpful_count,has_image,purchased_option,purchase_option_size,purchase_option_color,source_url,ai_positive_tags,ai_negative_tags,product_code,related_product_ids
0,2026-04-28,FILA,자사몰리뷰,139954,8127678283812,휠라 스피드서브 T9 2.0,2026-03-26,2026,3,"이 신발, 네트 대시가 왜 이렇게 빨라/스피드서브 t9 2.0 실착리뷰! 테니스 구력은 장비빨(?)이라는 말 이번에 휠라 스피드서브 t9 2.0을 하드코트와 인조잔디에서 굴려보며 뼈저리게 느꼈습니다. 결론부터 말씀드리면 발이 편한 건 기본 코트 위에서 날개를 단 기분이었는데요 구체적인 후기 들어갑니다! 1.발볼러들 강추 합니다! 사이즈감과 극강의 편안함 제일 먼저 놀란 건 사이즈감과 핏입니다 2.0 버전은 분리형 텅(tongue) 구조로 바뀌어서 발등 높이에 맞춰 끈 조절이 정말 자유로워요 저는 발이 예민한 편인데도 발이 참 편하다는 생각을 멈출 수가 없었습니다! 발볼도 넉넉하게 나와서 압박감 없이 핏하게 감기는 맛이 일품입니다 2.스플릿 스텝 후 0.1초가 달라진다 접지력과 반응성 이 신발의 진가는 방향 전환에서 나옵니다.하드코트든 인조잔디든 지면을 움켜쥐는 헤링본 패턴의 아웃솔 접지력이 장난 아니에요. 특히 스플릿 스텝 이후 다음 동작으로 넘어갈 때 미끄러짐이 전혀 없어서,에너지가 밖으로 새지 않고 바로 다음 스텝으로 연결되는 느낌이 정말 쾌적했습니다. 3.네트 앞으로 전력 질주 경량성과 네트 플레이 저는 기회만 나면 네트 앞으로 달려가 발리 공격하는 걸 즐기는데 스피드서브 2.0은 확실히 가볍습니다. 신발이 무거우면 첫 발 떼기가 무거운데 이건 발놀림이 경쾌해서 네트 대시 속도가 훨씬 붙더라고요. 좌우로 흔들릴 때도 tpu 생크 기술이 발의 뒤틀림을 딱 잡아주니까 빠른 움직임 속에서도 안정감이 느껴져 발리 찬스를 잡기가 훨씬 수월했습니다. 4.탄탄한 쿠셔닝 무릎 피로도 안녕! 쿠셔닝은 너무 물렁하지도, 너무 딱딱하지도 않은 기분 좋은 탄성을 보여줍니다. 하드코트에서 격하게 뛰어도 충격을 잘 흡수해주어 장시간 게임 후에도 무릎이나 발바닥에 무리가 덜 갔습니다. 5.코트 위 패셔니스타 디자인 한줄평 기능도 기능이지만 디자인이 정말 깔끔하고 예뻐요!측면 로고가 미니멀해져서 그런지 어떤 테니스복에 매치해도 찰떡 입니다. 운동 끝나고 일상복에 그대로 신고 가도 전혀 어색하지 않은 세련된 화이트 톤이라 더 만족스럽네요. 한 줄 요약 스플릿 스텝이 가벼워지고 네트 점령이 쉬워지는 신발 발볼 넓은 공격형 플레이어라면 무조건 이거 가세요!",...,28,1,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 라인(핏), 착용감, 디자인, 사이즈, 기능성",NaN,1100FS261TN02X001106,[8127678283812]
1,2026-04-28,FILA,자사몰리뷰,143752,8100165845028,하레핀 1998,2026-04-21,2026,4,"(후기 사진은 크게 확인 부탁드립니다) 남자친구랑 사귀고 첫 커플 신발인데 뭐를 살까 고민하다가 제가 ""휠라 에샤페 lx 초코""를 신고 있는데 너무 편하게 신고 있던 중 우연히 휠라 하레핀을 보자마자 너무 이뻐서 바로 남자친구한테 보여줬더니 너무 마음에 든다고 주말에 당장 휠라에 가서 신어보고 둘 다 마음에 들어서 바로 남자친구 사줬어요 ! 근데 실물보고 잘 보고 온 게 맞구나 싶었어요 ㅋㅋ디자인, 색감 둘 다 잡았더라구요…? 과한 느낌은 없고 잔잔하게 포인트 줄 수 있는 신발이예요 진짜 만족도 100%입니다. 하레핀 구매하고 계속 이 신발만 신고 다니고 있어요 ㅎㅎ 덕분에 동료들한테도 이쁘다고 칭찬받고 많이 추천도 해줬어요 ㅋㅋ 꼭 구매하라고..! 사이즈도 평소에 신던 사이즈 230mm 그대로 정상 사이즈로 나왔다고 생각했어요 제가 신발 구매할 때마다 발볼이 있다는 이야기를 듣는데 불편함없었습니다 ! 그리고 걷다보면 발가락 아픈 느낌도 없었고 너무 편하게 걸어다녔어요 ! 아 ! 남자친구도 평소에 270mm으로 신는데 휠라도 동일하게 270mm으로 구매해서 착용하고 있는데 편하다고 그러더라구요 ! 평소 사이즈랑 동일하게 구매하시면 될 거 같아요 제가 신발 구매하고 바로 남자친구랑 하레핀 신고 놀러 갔어요! 근데 진짜 사진 찍을 때랑 걸어 다니면서 거울 보일 때 진짜 너무 이뻐요…최고! ! 한강으로 놀러갔는데 오래 걸어도 발이 정말 편했고, 신발이 생각보다 가볍다고 생각도 했습니다 ! 그리고 하레핀 크림색상은 츄리닝에도 잘 어울리고 데일리룩에도 잘 어울리고 소재도 천연 돼지 스웨이드여서 고급감이 더해져 어느 룩에도 잘 매칭이 되는 핫한 아이템이라고 생각해요 ㅎㅎ 또 제가 하레핀 노랑색도 신어봤는데 진짜 30분동안 고민했어요,,색감 진짜 이쁘고 완전 포인트로 신기 좋아보였어요 ! 완전 취향저격… 이번에는 크림색으로 구매했지만 조만간 남자친구랑 포인트 주기 이쁘다고 같이 사러 가자고 꼬섰어요 ㅋㅋ 노랑색도 구매하면 이쁜 사진으로 후기 작성하러 올께요 ㅎㅎ",...,25,1,270,270,NaN,https://www.fila.co.kr/products/1100fs261od03x095217,"만족도, 착용감, 디자인, 색상, 사이즈, 스타일",NaN,1100FS261OD03X095217,"[8100165845028, 8100475764772, 8117765799972]"
2,2026-04-28,FILA,자사몰리뷰,140502,8127678283812,휠라 스피드서브 T9 2.0,2026-03-31,2026,3,"엑실러스3 유저의 스피드서브 2.0 기변 후기 테니스 구력 2년 차, 그동안 저의 베이스라인을 든든하게 지켜주던 '엑실러스 3'에서 드디어 '스피드서브 2.0'으로 기변했습니다! 목빠지게 배송 기다리다 코트에서 직접 뛰어보고 남기는 진또배기 후기 바로 레츠고~ 1. 사이즈 및 핏감 엑실러스 3가 갑옷처럼 발을 보호해 주는 느낌이었다면, 스피드서브 2.0의 유연한 소재와 핏감은 진짜 jmt~ 발볼도 편안하게 잘 나와서 정사이즈로 신으니 완전 맞춤 핏이네요. 특히 끈으로 발등 압박감을 세밀하게 조절할 수 있어서 게임 내내 발이 너무 편안합니다!! 2. 접지력 및 반응성 멈출 때 정확히 멈춰주고, 다음 공을 향해 튀어 나갈 때 바닥을 쫀득하게 밀어주는 폭발력이 진짜 진또배기입니다. 아웃솔이 바닥을 미끄러짐 없이 꽉 잡아주니까 네트 앞으로 대시할 때 반응 속도가 확실히 빨라졌어요. 덕분에 구력 2년 차도 자신감 있게 공격적인 플레이 가능해서 진짜 너무 좋아여!! 3. 쿠셔닝 가벼운 무게에 어떻게 이런 쫀쫀한 쿠션을 넣었는지 휠라 칭찬합니다~~ 하드 코트에서 랠리를 길게 가져가도 발바닥 충격을 잘 분산시켜 주고요. 다음 스텝을 밟을 때 에너지를 리턴해 주는 탄성 덕분에, 3시간 이상 운동해도 하체 피로도가 확실히 적어요^^ 스피드서브 2.0 디자인도 느좋이라 파트너랑 팀 테니스화로 맞춰 신었는데 코트 갈 때마다 주변에서 예쁘다고 난리네요 ㅎㅎ 정말 누구신지 모르겠지만 기획자님 너무 감사합니당 이렇게 이쁜색 테니스화를 만들어주셔서 가볍고 예쁜데 기능까지 완벽한 스피드서브 2.0과 함께 혼복 대회 입상을 넘어 우승까지 렛츠고~~!!",...,22,1,240,240,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 소재, 라인(핏), 착용감, 디자인, 기능성, 사이즈",NaN,1100FS261TN02X001106,[8127678283812]
3,2026-04-28,FILA,자사몰리뷰,143962,8100165845028,하레핀 1998,2026-04-24,2026,4,"첫 커플신발로 휠라 하레핀1998을 선택했어요! 일반적인 스니커즈 디자인이 질려서 고민하고 있을 때, 때마침 딱 캐주얼한 등산화 느낌의 하레핀이 마음에 들어 데꼬 왔어요 저희는 230, 280 크림 색상으로 공식홈페이지에서 구매했어요! (카카오 채널추가 할인쿠폰 굿) 저는 발볼이 좁은 편이고, 남친은 보통인 편인데 둘 다 편하게 잘 맞아요! 정사이즈로 구매하시면 돼요. 처음에 박스 딱 열었을 때 일단 실물이 되게 예뻐서 만족스러웠고, 딱 신었을 때 되게 가볍고 편해서 놀랐어요 그리고 저 평발이라 많이 걸으면 발바닥이 무조건 아픈데, 경주 황리단길을 폭풍워킹해도 정말 발이 안 아팠어요!! 밝은 천 색상에 어두운 밑창과 끈 조합이라, 흰 바지를 입던~ 흑청을 입던~ 중청을 입던~ 정말 캐주얼하게 휘뚤마뚤 잘 신을 수 있어요! 근데 또 아예 안 꾸민 느낌은 아니라 출근룩, 데이트룩 다 가능해서 넘 좋음 여행 앞두고 커플신발을 하레핀으로 장만해서 경주여행을 잘 다녀왔는데, 곧 있을 제주에도 함께 신고 가려고 합니다 커플신발로 휠라 하레핀 추천드려요 ! - 이 리뷰가 도움되셨다면, 도움돼요 눌러주세요 -",...,22,1,280,280,NaN,https://www.fila.co.kr/products/1100fs261od03x095217,"만족도, 착용감, 디자인, 스타일, 사이즈",NaN,1100FS261OD03X095217,"[8100165845028, 8100475764772, 8117765799972]"
4,2026-04-28,FILA,자사몰리뷰,140489,8127678283812,휠라 스피드서브 T9 2.0,2026-03-30,2026,3,"[스피드서브 1 찐유저의 2.0 버전업 후기] 단종의 눈물을 닦아준 완벽한 진화 (feat. 혼복 우승 렛츠고~) 기존에 밑창이 닳도록 신던 인생 테니스화 '스피드서브 1'이 단종되어 더 이상 구매할 수 없어 눈물 흘리던 참에 소울메이트 같은 동생이 스피드서브 2.0이 런칭됐다는 기가 막힌 소식을 알려주더군요. 망설임 없이 바로 기변 렛츠고~ 코트 위에서 직접 굴러보고 쓰는 진또배기 후기 바로 레츠고~ 1. 사이즈 및 핏감 기존 일체형 구조에서 2.0은 분리형 텅으로 변경됐는데, 이게 정말 신의 한 수 같습니다. 그날그날 발 붓기나 양말 두께에 맞춰 끈으로 더 세밀하게 조절할 수 있어 발과의 일체감이 더 좋아졌어요. 발볼이 넉넉하게 나와서 전형적인 한국인 족형에게 강력히 추천드립니다. 2. 쿠셔닝 292.7g이라는 가벼운 무게에 이런 쫀쫀한 쿠션감이라니!무조건 물렁하기만 한 쿠션 보다 오히려 발바닥의 충격을 잘 분산해줍니다. 처음 2.0을 신은 날 4시간을 풀로 뛰었는데도 하체 피로도가 다른 날보다 적어서 감탄했습니다. 3. 접지력 및 움직임 반응 기존 1세대 버전도 접지력은 정말 만족하며 신었는데, 2.0은 바닥 패턴이 바뀌면서 확실히 더 업그레이드됐네요. 스플릿 스텝 후 다음 스텝 치고 나갈 때 바닥을 쫀득하게 밀어주는 지지력이 너무 좋습니다. 미끄러짐이 없으니 덕분에 코트 위에서 더 안정적이고 공격적인 플레이가 가능해졌어요. 4. 착화 시 안정감 테니스는 멈추는 게 더 중요한 운동인거 다들 아시죠? 좌우 사이드 스텝을 밟고 오픈 스탠스로 급브레이크를 걸 때, 신발 뒤틀림 없이 발목을 견고하게 잘 잡아줍니다. 덕분에 발목 불안함 없이 공에만 100% 집중할 수 있습니다. 스피드서브 2.0 런칭을 소개해 준 동생하고 최근 혼복팀을 결성하게 됐는데, 이 참에 팀 테니스화도 2.0으로 같이 맞추게 됐네요. 든든한 스피드서브 2.0과 함께 입상을 넘어 우승까지 렛츠고~~!!",...,20,1,265,265,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 라인(핏), 착용감, 디자인, 사이즈",NaN,1100FS261TN02X001106,[8127678283812]
5,2026-04-28,FILA,자사몰리뷰,143214,8100165845028,하레핀 1998,2026-04-15,2026,4,"일단 색감이 넘 예뻐요. 크림색이라 어떤 색의 옷이든 다 잘어울리는게 큰 장점이에요 ! 앞코가 둥근 타입이라 발도 작아보이고, 귀여워 보여요. 트렌디한 트레킹화 같아요 ㅎㅎ!! 쿠션감이 도톰해서 착화감이 좋아요. 오르막길 많은 공원에서 오래 걸었는데 다른 신발 신었을 때 보다 발바닥 안쪽, 아치가 불편하지 않고, 미끄럽지도 않아요! 남녀공용 디자인이라 똑같이 신기도 좋고 커플로 함께 신으니 더 귀엽고 예쁘더라구요 ! 전 240, 남자친구는 발등이 좀 높고 발볼이 나름 있는 편이라 275~280인데 275 신으니까 정사이즈라 딱 잘맞더라구요! 스웨이드 재질이라 힙하고 고급지게 느껴지고 차려 입거나, 캐쥬얼하게 입었을 때 신어도 넘 잘어울려요! 오늘 신은 착샷 한장 첨부합니다 !! 추가로 다른 색의 신발끈까지 줘서 기분따라 착용하면 될 것 같아요 !! 휠라 많이 버세요 헤헤 도움되셨다면 ""도움돼요"" 버튼 부탁드려요",...,19,1,240,240,NaN,https://www.fila.co.kr/products/1100fs261od03x095217,"만족도, 스타일, 색상, 소재, 착용감, 디자인, 사이즈",NaN,1100FS261OD03X095217,"[8100165845028, 8100475764772, 8117765799972]"
6,2026-04-28,FILA,자사몰리뷰,139580,8127678283812,휠라 스피드서브 T9 2.0,2026-03-22,2026,3,"fila 스피드서브 2.0 실착 후기: ""코트 위의 나의 핫템 승리요정!"" 1. 사이즈감 / 발볼 / 핏 (size&fit) 평소 발볼이 넓은 편이어서 wide한 테니스화를 선호하는데 fila 스피드서브 t9 2.0은 넓은 발볼 공간으로 인해 신는 순간부터 굉장히 편안한 착용감을 느낄 수 있었습니다. 핏감의 경우 놀랐던 부분은 개인별로 차이가 나는 발형태를 고려하여 신발끈으로 손쉽게 개인별 최적화된 핏감을 느낄수 있도록 설계되었습니다. 그리고 fila 스피드서브 t9 2.0의 디테일에서 깜짝 놀란 부분은 신발 뒷부분 고리였습니다. 일반적으로 동호회에서 급하게 테니스 경기에 들어가면서 테니스화가 뒤가 살짝 구겨지는 경우가 종종 있는데 신발뒤 고리가 있으니 구겨짐 없이 빠르고 편하게 테니스화를 신을 수 있습니다. 이게 저에게는 핏감을 올려주는 최적의 옵션이 아니었나 생각합니다. (fila 디테일 칭찬해요 ) 2. 착화 시 안정감 fila 스피드서브 t9 2.0를 착화하고 경기를 하면서 가장 놀랐던 점은 좌우 이동 시의 안정감입니다. 테니스 특성상 급정지와 방향 전환이 많은데, 발목을 꽉 잡아주는 느낌이 발목부상에 대한 불안함 없이 안정감 있는 게임이 가능했습니다. fila 제품소개에 힐과 바닥면에 tpu 생크 기술을 적용했다고 하는데 인터넷을 찾아보니 tpu는 플라스티처럼 단단하면서도 탄성이 있는 소재라고 하더라구요. 아마 tpu 소재가 신발의 뼈대를 이루면서 여기서 나오는 견고함과 부드러움이 안정감을 극대화해준다는 생각이 들었습니다. 3. 접지력과 움직임 반응 우선 접지력의 경우는 너무 뛰어나 보입니다. 사실 과장되게 표현하면 발과 코트가 직접 맞닿은듯 너무 가깝게 느껴져서 오히려 일반 동호인들은 좀 두꺼운 양발을 신고 경기에 임하는 것 강추합니다. ^^ 특히 순간적으로 방향 전환을 할 때 미끄럼 증상이 전혀없어 평소 방향 전환할 때 미끄럼 증상으로 넘어져본 경험이 있는 동호회분들께는 강추할 수 있는 테니스화입니다. (이것도 아마 tpu 소재와 바닥면 설계에서 오는 fila만의 기술력이겠지요 ) fila 스피드서브 t9 2.을 착화하고 움직일 때 눈에 띄게 향상된다고 느껴지 또 다른 한가지는 바로 스플릿 스텝이였습니다. 전체적으로 재질이 견고하면서도 탄성이 있다보니 약간 스피링처럼 스플릿 스텝의 탄성을 만들어 내면서 폭발적인 움직임을 만들어 주는 느낌이 있습니다. fila 스피드서브 t9 2.0 착화 총평 - 넓은 발볼, 효율적인 신발끈 구조, 디테일한 신발 뒤꿈치 고리가 편안한 사이즈감, 완벽한 핏감을 구현 - 단단하면서도 견고한 소재 적용, 훌륭한 바닥면 설계로 빠른 방향 전환시 미끄럼을 방지하여 높은 퍼포먼스 구현 가능 - 신발 전체의 탄성이 스플릿 스텝을 전반적으로 향상시킴 - 인조잔디, 클레이코트에서 착화하고 경기에 착용하여도 놀라운 성능을 그대로 유지하여 올코트용 테니스화로도 적합 추천평 - 평소 넓은 발볼인 동호인, 미끄럼을 느끼던 동호인, 발목부상을 걱정하던 동호인분들은 주저없이 fila 스피드서브 t9 2.0 선택하시는 것을 강추드립니다. - 저는 테니스 단짝과 fila 스피드서브 t9 2.0를 동시 구매하고 테니스 코트에 등장하여 많은 동호회원분들의 부러움을 한몸에 받고 왔습니다. 모두모두 fila 스피드서브 t9 2.0 신고 동호회원분들과 즐테하세요^^ p.s 한가지 빼먹은게 있는데요. 디자인이 너무 좋습니다. ㅎㅎ",...,15,1,275,275,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 라인(핏), 착용감, 디자인, 기능성, 소재, 사이즈",NaN,1100FS261TN02X001106,[8127678283812]
7,2026-04-28,FILA,자사몰리뷰,139595,8127678283812,휠라 스피드서브 T9 2.0,2026-03-22,2026,3,"평소 휠라가 테니스에 쏟는 진심을 좋게 보고 있었습니다. 작년 여름 반포 예빛섬에서 열렸던 '휠라 화이트 오픈'도 직접 관람하며 브랜드 특유의 헤리티지를 체감했었기에, 이번에 여자친구와 커플 테니스화를 맞추면서 고민 없이 스피드서브 2.0을 선택했습니다. -항목별 구체적인 착화 경험 안정감 : 좌우로 급격하게 방향을 전환하는 사이드 스텝을 할때, 발목을 아주 견고하게 잡아줍니다. 특히 베이스라인 깊은 곳에서 스트로크를 뿌리고 다시 코트 중앙으로 복귀할 때 뒤틀림 없이 발을 단단하게 지탱해 주는 느낌이 들고, 발목 불안함 없이 자신 있게 뛸 수 있었습니다. 접지력 및 움직임 반응 : 인조잔디 코트에서 가장 큰 스트레스는 의도치 않은 미끄러짐입니다. 스피드서브 2.0의 아웃솔은 모래 위에서도 지면 접지력이 상당합니다. 서브 후 네트로 대시하거나 짧은 드롭샷을 잡으러 나갈 때, 즉각적으로 지면을 차고 나가는 반발력이 일품입니다. 의도한 타이밍에 정확히 멈추고 다시 튀어 나갈 수 있게 해주는 반응성이 이 신발의 가장 큰 강점이라 생각합니다. 사이즈감 / 발볼 / 핏 : 평소 운동화 정사이즈 그대로 선택했는데, 테니스 양말을 신고도 압박감 없이 딱 좋은 맞춤 핏이 나옵니다. 발볼이 아주 넓게 나온 편은 아니지만, 소재가 유연해서 금방 발 모양에 맞춰 길들여집니다. 특히 디자인이 견고해서 격렬한 움직임 중에도 신발 안으로 모래가 들어오는 것을 잘 막아주어 쾌적함이 유지되는 점이 좋았습니다. 착화 시 쿠셔닝 : 너무 물렁한 쿠션은 오히려 힘 손실이 생기는데, 이 제품은 적당히 탄탄하면서도 충격을 효과적으로 분산해 줍니다. 2시간 가까이 게임을 뛰고 나면 보통 발바닥이 뜨겁거나 무릎이 뻐근한데, 스피드서브 2.0은 탄성 있는 쿠셔닝 덕분에 경기 후반부까지도 발바닥 피로도가 확실히 낮았습니다. 에너지를 리턴해 주는 쫀득한 느낌이 살아있습니다. - 총평 및 추천 인조잔디 코트를 주력으로 운동하시는분께 자신있게 추천드립니다! 국내에 잘 나오지 않는 인조잔디 신발을 직구로 구매하여 신고는 했는데, 타사의 신발과 다르게 인조잔디 코트에서도 미끄러움 없이 땅에 콱 박히는 느낌이 만족스럽습니다. 이 신발 덕분에 더이상 해외직구를 하지 않아도 될듯 합니다! 디자인또한 워낙 깔끔해서 여자친구와 커플로 맞춰 신고 코트에 들어서면 주변에서 예쁘다는 소리를 꼭 한 번씩 듣게 됩니다ㅎㅎ 인조잔디에서의 미끄러움이 고민이거나 스타일과 퍼포먼스를 모두 잡고싶은 동호인분들에게 강추합니다!",...,10,1,275,275,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 기능성, 소재, 라인(핏), 디자인, 착용감, 사이즈",NaN,1100FS261TN02X001106,[8127678283812]
8,2026-04-28,FILA,자사몰리뷰,139596,8127678283812,휠라 스피드서브 T9 2.0,2026-03-22,2026,3,"""디자인에 반하고 기능에 정착한 스피드서브 2.0 실착 리뷰"" 01. 코트 위 존재감, 디자인과 컬러의 조화 처음엔 오로지 디자인만 보고 선택했습니다. 세 가지 컬러 중 고민하다 옆 라인 포인트가 가장 또렷한 그린을 골랐는데 실제 테니스 코트 위에서 움직일 때 라인이 선명하게 살아나서 예뻤어요!! 신고 모임 운동하러 나갔더니 사람들이 다 예쁘다 하더라구요! 02. 테니스를 발로 치는 플레이어들를 위한 신발 저는 공 하나라도 더 살리려고 끝까지 쫓아가는 스타일이라 짧은 대시, 급정지, 방향 전환이 유독 잦습니다. 그동안 신었던 신발들이 반응성이 좋으면 발바닥이 아프고 쿠션이 좋으면 안정감이 없어서 늘 아쉬움이 있었는데 스피드서브 2.0은 이 밸런스를 기가 막히게 잡았습니다. 03. 인조잔디에서도 믿고 신는 쿠셔닝과 안정감 주로 인조잔디에서 플레이하는데, 서브 후 착지할 때 충격이 부드럽게 분산되면서도 발이 너무 꺼지지 않아서 좋았어요. 덕분에 장시간 플레이해도 무릎 부담이 눈에 띄게 줄었습니다. 특히 영상보시면 발목 뒷 부분에 엄청 도톰한 쿠션이 있는데 착지할 때 그게 발목을 잡아주는 역할을 제대로 해줍니다. 사실 올코트 테니스화라고 해서 인조잔디에서 좀 미끄럽지 않을까 은근히 걱정했거든요 근데수비 상황에서 급하게 방향을 꺾을 때도 잘 잡아줘서 헛도는 느낌이 없었어요. 민첩한 전환이 많은 플레이어일수록 이 차이가 더 체감될 것 같습니다. 04. 사이즈 및 핏 가이드 (반 치수 업 추천) 저는 테니스용 두꺼운 양말을 신는 편이라 반 치수 올려서 구매했는데 잘한 선택이었어요. 발볼에 여유가 살짝 생기긴 하는데, 신발끈으로 발등을 조여주면 오히려 안정적으로 고정되는 느낌이라 불편하지 않았습니다. 총평:오래 신어도 안 지치는 올라운드 테니스화 남자친구랑 커플로 맞춰 신고 있는데, 둘 다 느끼는 게 ""격하게 움직여도 발이 불안하지 않고 두 세 시간 뛰고 나서도 피로감이 생각보다 적다""는 거예요. 많이 뛰는 테린이부터 움직임이 거친 상급자까지 두루 맞을 것 같아서 자신 있게 추천합니다!",...,10,1,250,250,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 기능성, 라인(핏), 디자인, 사이즈, 스타일, 색상",NaN,1100FS261TN02X001106,[8127678283812]
9,2026-04-28,FILA,자사몰리뷰,139084,8127678283812,휠라 스피드서브 T9 2.0,2026-03-17,2026,3,"fila 스피드서브 2.0 구매 후기 저는 테니스화를 필라 스피드서브 t9만 세 번째 신을 정도로 애정하는 테니스 동호인입니다 유튜브 머드리tv에서 이형택 감독님, 평소 인스타 팔로우중인 엄선영코치님께서 스피드서브 2.0을 착용하신 모습을 보고 바로 관심이 생겨 필라 공식몰에서 구매하게 되었습니다. ^^ 평소 발목이 좋지 않아 여러브랜드마다 좋다는 테니스화는 하나씩 다 구매해서 신어봤는데 가장 제 발과 발목을 안정적으로 잡아주는 테니스화가 이번 필라 스피드서브 2.0이네요 ! 스피드서브2.0까지 하면 총 네켤레의 필라테니스화~ 착화감 스피드서브 2.0은 텅 구조로 되어 있어 끈이 발등을 직접적으로 누르는 느낌이 적어 발등이 편안했습니다. 발등 높이에 맞게 자연스럽게 잡아줘 장시간 착용해도 발에 무리가 가지 않는 점이 특히 좋았습니다. !! 예전에 다른 브랜드 꽉끼는 테니스화를 신고 발톱이 빠지고, 방향전환때 발목이 꺽이면서 몇달 고생한 경험이 있어 테니스화를 고를 때 가장 중요하게 생각하는 것이 발이 편한 신발입니다. 스피드서브 2.0은 그런 부분에서 정말 만족스러워서 앞으로도 색상별로 소장하고 싶을 정도로 마음에 드는 테니스화입니다 ! 또한 기존 스피드서브 t9보다 쿠셔닝이 더 좋아진 느낌이었습니다. 딱딱한 실내 하드코트에서 레슨을 받는 동안 발목과 무릎에 전달되는 충격을 잘 완화해줘 훨씬 편안하게 레슨을 받을 수 있었습니다. 방향 전환 시에도 밀리는 느낌 없이 안정감 있게 움직일 수 있어 부담이 적었습니다. 덕분에 발에 무리가 덜 가고 플레이 집중도도 높아진 느낌입니다. 사이즈 팁 정사이즈로 출시된 제품이라 발볼이 넓은 분들도 비교적 편하게 신을 수 있을 것 같습니다. 저는 평소 양쪽 발에 발목 보호대를 착용하고 플레이해서 5mm 크게 주문했는데 편하게 잘 맞았습니다. (평소모든운동화는 240mm 신지만 스피드서브2.0은 245mm 신어요) 총평 발 안정감, 쿠셔닝, 착화감까지 모두 만족스러워 테니스 동호인분들께 추천하고 싶은 테니스화입니다. 앞으로도 스피드서브 라인은 계속 찾게 될 것 같아요. 테니스를 처음 시작하시는분, 발볼넓으신분, 발편한 테니스화를 찾고 계시는 동호인이라면 꼭 한번쯤 신어보시면 후회없는 만족감으로 저처럼 필라테니스화로만 재재구매 하실거 같습니다 !",...,8,1,245,245,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 착용감, 사이즈",NaN,1100FS261TN02X001106,[8127678283812]
10,2026-04-28,FILA,자사몰리뷰,140379,8127678283812,휠라 스피드서브 T9 2.0,2026-03-29,2026,3,"<첫 발 반응이 인상적이었던 스피드서브 t9 2.0 실착 리뷰> 나의 플레이 조건 저는 테니스를 정말 좋아하고 계속 실력을 쌓아가고 싶은 고등학교 체육교사입니다. 동호회 활동을 주 3회 정도 꾸준히 하고 있으며 기회가 될 때마다 아마추어 대회에도 참가하고 있습니다. 체격 183cm / 77kg / 왼손잡이 / 원핸드 백핸드 / 구력 4년이며 복식 위주의 경기를 즐깁니다. 베이스라인 근처에서 길게 리턴하는 공격적인 스트로크 플레이를 선호합니다. 현재 라켓은 head speed mp legend 2025 모델을 사용 중이며 빠른 스윙 스피드를 기반으로 한 공격적인 스트로크 플레이에 잘 맞는 라켓입니다. 주로 하드·클레이·인조잔디 코트를 이용하고 있으며 휠라 t9 시리즈 두 모델(270mm)을 번갈아 착용하며 느낀 점을 정리했습니다. 엑실러스 t9은 약 3개월, 스피드서브 t9 2.0은 약 1개월 실제 코트에서 착용했습니다. 한 줄 요약 스피드서브 t9 2.0 가볍고 반응성이 좋은 스피드형 테니스화 한 줄 체감 : 첫 발은 경쾌했고, 장시간 경기에서는 발바닥 피로가 느껴졌습니다. 상황별 느낀 점 복식 공격형 스트로커 기준 비교 복식 게임 비중이 높고 공격적으로 스트로크를 밀어붙이는 스타일이라 테니스화를 볼 때 첫 발 반응, 좌우 전환 안정성, 경기 후반 피로도를 중요하게 생각합니다. 실제 복식경기에서 베이스라인 근처 스트로크 중심 플레이에는 스피드서브 t9 2.0이 더 유리하게 느껴졌고, 비교 기준으로 신어본 엑실러스는 장시간경기에서 편안함과 안정감이 조금 더 강했습니다. 멀티코트 사용자 관점에서 본 스피드서브 t9 2.0 하드코트 - 급정지 후 다시 방향을 틀 때 발이 과하게 비틀리는 느낌이 적어 접지력이 좋다고 느꼈습니다. 경량 퍼포먼스 모델이라 초반 움직임은 매우 경쾌했지만 3시간 이상 플레이에서는 발바닥 피로가 조금 느껴지는 편이었습니다. 클레이코트 - 슬라이드가 자연스럽고 흙 배출도 좋아 관리가 편했습니다. 아웃솔의 3색선 디자인 포인트도 인상적이었습니다. 인조잔디 코트 - 규사 위에서도 미끄러짐 제어가 안정적이고 착지 시 흔들림이 적어 비교적 안정적인 움직임이 가능했습니다. 경기 시간에 따른 착화감 처음 30분 정도는 매우 가볍고 경쾌한 느낌이 강했습니다. 1~2시간 플레이에서는 빠른 스텝 전환이 편안했고 공격적인 움직임에 도움이 되었습니다. 다만 3시간 정도 복식경기를 진행하니 발바닥 피로가 점차 올라왔습니다. 초반 경쾌함은 분명 장점이었지만, 장시간 기준 쿠셔닝 체감에서 아쉬움이 남았습니다. 내 플레이와의 연결 저는 왼손잡이라 몸쪽이나 코너를 겨냥한 슬라이스 서브를 자주 사용합니다. 리턴 후 빠르게 다음 동작을 준비해야 하는 상황이나 포칭을 대응하는 순간에서 스피드서브 t9 2.0은 첫 발 반응이 빠르고 힐 슬립이 없어 경쾌한 움직임이 가능했습니다. 또한 발등 압박이 적고 끈 조절로 핏을 세밀하게 맞출 수 있어 편안한 착용감을 느꼈습니다. 핏(사이즈감&발볼) / 마모 / 관리 힐 슬립 : 없음 앞코 쓸림 : 없음 아웃솔 마모 : 적은 편 사이즈감&발볼 : 발사이즈는 265mm 보통 발볼, 먼저 구입한 액실러스는 반업(270mm), 스피드서브도 같은 사이즈를 구입했지만 엑실러스보다 여유롭게 느껴져 정사이즈도 추천! 결론 스피드서브 t9 2.0은 확실히 가볍고 첫 스텝 반응이 빠른 경량 퍼포먼스 테니스화 높은 접지력으로 빠른 움직임과 공격적인 플레이에 유리 무게는 스피드서브 292.7g, 엑실러스 299.5g으로 6.8g 차이지만 체감상 확실히 가볍게 느껴졌고 빠른 반응에 만족! 쿠셔닝과 편안함을 더 중시한다면 엑실러스 t9도 좋은 선택지가 될 수 있겠다. 이런 플레이어에게 추천 첫 발 반응과 빠른 움직임을 중요하게 생각한다면 스피드서브 t9 2.0 장시간 경기에서도 안정적인 쿠션과 편안함을 원한다면 엑실러스 t9 좋은 테니스화 선택에 도움이 되길 바랍니다.",...,8,1,270,270,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 착용감, 디자인",NaN,1100FS261TN02X001106,[8127678283812]
11,2026-04-28,FILA,자사몰리뷰,143765,8100165845028,하레핀 1998,2026-04-22,2026,4,"하레핀 sns에 뜰 때마다 예쁘고 편해보여서 눈여겨보고있었어요! 궁금해서 그냥 신어보기만 하려고 매장에 갔다가.. 신어보자마자 넘 예쁘고 편해서 바로 첫 커플 신발로 구매결정.. 스포티하기도 하면서 캐주얼하게도 신을 수 있는 귀여운 디자인이에요! 회색 한방울 있는 크림색의 스웨이드라 취향저격이었습니다.. 따로 주시는 스페어 갈색 끈으로 바꿔 신어도 느좋커플 가능. 저는 발볼이 넓고, 남자친구는 발볼이 좁은데 둘다 편안하게 맞았어요! 전 발 길이는 235인데 발볼땜에 보통 240 신는데, 하레핀은 235도 편하게 맞았지만 혹시 몰라 240으로 구매했습니다!ㅎㅎ 남자친구도 평소 신던 운동화 사이즈로 275로 구매했어요. 정사이즈로 구매 추천드립니다ㅎㅎ 낙산공원도 올라가고 거의 2만보 걸었는데도 편안편안 () 넘 가볍고 밑창도 푹신해요 사계절 다 신을듯?? 착화감이랑 디자인 모두 잡은 신발이라 커플 신발로 강추합니다! 오래오래 닳을때까지 신고다닐게용 (커플신발로 고민중이시면 일단 가서 신어보시길.. 바로 구매하게 되실것..) 이 리뷰가 도움되셨다면, 도움돼요 버튼 한번 부탁드립니다",...,7,1,240,240,NaN,https://www.fila.co.kr/products/1100fs261od03x095217,"만족도, 착용감, 디자인, 색상, 사이즈, 품질",NaN,1100FS261OD03X095217,"[8100165845028, 8100475764772, 8117765799972]"
12,2026-04-28,FILA,자사몰리뷰,139594,8127678283812,휠라 스피드서브 T9 2.0,2026-03-22,2026,3,"비가와도 하드에서 미끌림이 없는 테니스에 완벽한 신발 클레이는 사내 테니스 대회에서 실전으로 바로 신고 뛰어봤습니다 실제 경기에서 착용후 리뷰 작성하였습니다 1. 착용 환경/ 사용조건 착용 시점: 사내 테니스 대회실전 경기 척용 시간: 약 3시간 이상 연속 플레이 코트 환경: 클레이+하드코트 모두경험 개인 구력: ntrp 2년 이상 다양한 브랜드 테니스화 착용 경험 있음 2. 착용감&첫 느낌 처음 신었을때부터 발볼.발등이 자연스럽게 감싸지는 느낌이 들었습니다 새 신발 특유의 뻣뻣함이나 눌리는 느낌이 거의 없어서 길들이는 시간없이 바로 실전투입이 가능했습니다 산발끈을 세게 조이지 않아도 발이 고정되는 느낌이 인상적이었습니다 3. 움직임 안정성(급정지&방향전환) 테니스 경기중에는 급정지 사이드 스탭 방향 전환 이 반복되는데 발이 신발안으로 밀리거나 흔들리지 않았습니다 특히, 수비상황에서 급하게 멈출때도 몸이 멈추고 발이 따라오는 안정감이 느껴졌습니다 4. 코트별 체감 추이(클레이/하드) 1) 클레이 코트 과도하게 미끄럽지 않고 스텝을 밟을때 접지력이 일정함 방향전환시 불안감이 적고 스텝이 자연스럽게 이어졌습니다 2) 하드코트 착지시 충격이 발바닥, 허리로 바로 올라오지 않음 쿠셔닝이 충격을 한번 걸러주는 느낌 평소 하드코트에서 몇게임만해도 다음날 허리가 하체에 부담이 있었는데 이신발을 신고 난뒤에는 그 피로감이 확실히 줄었습니다 4. 쿠셔닝&장시간 플레이 피로도 가장 만족한 부분입니다 경기 초반뿐아니라 후반부까지 발바닥이 버티는 느낌이있어서 랠리가 길어질때도 집중력이 잘 유지되었습니다 보통 경기막판에는 발바닥이 먼저 피곤해지고 스텝이 둔해지는데 이 신발은 끝까지 템포를 유지할수 있었던 점이 가장 큰 잔점이었습니다 5. 개인적인 총평&비교 착용즉시 편안함 안정적인 지지력 하드코트에서의 피로감소 이 세가지를 모두 만족시킨 신발입니다 6. 이런분들께 적극 추천합니다 실 착용후 개인적인 생각으로 저처럼 하드코트에서 종아리, 허리통증을 느끼시는분 전위,후위를 자주 뛰어다니신분 실전 테니스화를 찾는분 개인적으로 2년넘는동안 다양한 테니스화를 신어봤지만 이신발은 최고로 만족하며 신고있습니다",...,6,1,270,270,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 착용감",NaN,1100FS261TN02X001106,[8127678283812]
13,2026-04-28,FILA,자사몰리뷰,139025,8127678283812,휠라 스피드서브 T9 2.0,2026-03-13,2026,3,"0. 처음 스피드서브t9을 신게 된 계기 이제 테니스 구력이 4년차에 접어들고 있다. 초반에는 테니스화의 중요성을 무시한 채 여러 브랜드 네임과 디자인만 보고 많은 시행착오를 겪었다. 네 번째 발톱이 빠지기도 하고, 발 뒷꿈치가 까지고 엄지발가락에는 두꺼운 물집이 잡혔다. 발이 좀 편해지는 신발을 찾으면 내구성이 좋지 않았다. 몇 게임만에 바닥이 닳아서 테니스화 구실을 하지 못했다. 그러던 중 '휠라 24년 화이트오픈 서울'에 참여하면서 스피드서브 t9을 알게되었다. 확실히 발등과 발볼이 높은 나에겐 편안한 테니스화였으며, 하드, 클레이 어느 곳에서 신더라도 내구성이 좋아 나에겐 최적화된 테니스화였다. 커스텀 프로그램에 참여하여 나만의 테니스화를 만들기도 하고, 다양한 색상의 스피드서브t9 소장하고 만족하며 신고 있다. 1. 첫인상(디자인) 이번 유튜브 머드리tv에 이형택 감독님이 신으신 신상 스피드서브t9 2.0을 보게되었다. 얼핏 기존 버전과 디자인은 비슷했는데, 신발 사이드에 있는 휠라 박스 로고가 작아졌고, 바닥에 조금 딱딱했던 부분도 푹신한 느낌에 재질이 들어가 있는 듯 했다. 특히 엄선영 코치가 신었던 옅은 핑크색은 남자 사이즈가 있다면 지금 계절과 딱 어울려서 고민할 필요없이 구입해야겠다고 마음을 먹었다. 2. 평가 처음 신었을 때 발볼이 넓은 나에게 볼이 답답하지 않은 편안함을 선사해줬다. 기존에 신던 것과 큰 이질감이 없었기에 얼른 코트에 나가고 싶어졌다. 하드코트 : 실내 하드코드에서 30분 서브앤발리 레슨, 30분 스트로크 랠리 레슨를 연속해서 받았다. 우선 서브 후 서비스라인까지 빠르게 달려와 스플릿 스텝을 할 때의 쿠션 느낌은 기존 스피드서브t9 버전에서 느낄 수 없던 쿠셔닝(충격흡수) 느낌이 들었다. 장시간 플레이를 해도 발에 피로가 심하지 않을 것 같았다. 또한 스토로크 후 리커버리 동작까지 돌아올 때의 방향전환 시 하드코트에서 바닥의 접지력도 좋았다. 기존 스피드서브가 바닥이 단단하고 묵직한 안정감이 있었으나, 이번 버전은 안정감에 발에 피로를 풀어주는 편안함이 추가된 느낌이랄까. 클레이코트 : 실외 클레이코트에서 4경기정도 플레이를 했다. 바닥이 하드코트(올코트용)에 적합하지만 클레이에서의 슬라이딩 시 원하는 만큼 미끄러져나갔고 멈췄을 때의 접지력 또한 부족함이 없다. 3. 이런 분들에게 추천 - 발등이 높고 발볼이 넓어서 기존 테니스화를 구입할 때 사이즈 고민이 되시는 분 - 장시간 플레이에 발에 피로를 느끼시는 분 - 바닥이 튼튼해 쉽게 닳지않는 내구성이 좋은 테니스화를 필요로 하시는 분 - 올코트에 적합한 접지력이 좋은 테니스화를 찾으시는 분 4. 기대 스피드서브t9이 맘에 들어 해외직구 포함해서 색깔별로 구매한 테니스화가 8켤레가 넘어간다. 테니스코트나 그날 입은 운동복에 따라 테니스화의 색상을 맞춰서 신는다면 테니스의 또 다른 재미가 있다. 앞으로 커스텀라인이 나온것과 마찬가지로 인기있는 다양한 색상이 함께 나와준다면 더 좋을 것 같다.",...,5,1,270,270,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,"만족도, 라인(핏), 착용감, 디자인, 품질, 기능성",NaN,1100FS261TN02X001106,[8127678283812]

In [344]:
# ===============================
# 사용 컬럼 선택
# ===============================
# df = df.drop(columns=['brand', 'ai_positive_tags', 'ai_negative_tags', 'product_code'])
df = df.drop(columns=['brand', 'ai_positive_tags', 'ai_negative_tags'])

In [345]:
# ===============================
# women_size_yn 컬럼 만들기
# ===============================
df['women_size_yn'] = 0

In [346]:
# =========================================
# platform 컬럼에서 '자사몰리뷰'는 '자사몰' 변경
# =========================================
df['platform'] = df['platform'].replace({
    '자사몰리뷰': '자사몰'
})

df['platform'].value_counts(dropna=False)

platform
자사몰    10689
Name: count, dtype: int64

In [347]:
# ===============================
# 컬럼명 통일
# ===============================
df = df.rename(columns={
    'post_date' : 'review_date',
    'purchased_option' : 'purchase_option',
    'source_url' : 'product_url'
})

In [348]:
# ===============================
# 데이터값 확인 및 수정
# ===============================
df['product_name'].value_counts(dropna=False, ascending=True)

product_name
여성 초경량 셔링 바람막이        1
FHC 벤티세이 트랙 자켓        1
FHC 벤티세이 트랙 팬츠        1
피셔 로고 나염 트렁크          1
링클 체크 남성 파자마 세트       1
                   ...
페이토 샌들 v2           391
에샤페 벨크로 메리제인        446
휠라 에샤페 LX 브릭        722
휠라 에샤페 LX 블루        963
휠라 에샤페 실버문         1614
Name: count, Length: 323, dtype: int64

## purchase_option 결측치 처리

In [349]:
df['purchase_option_color'] = df['purchase_option_color'].astype(object)
df['purchase_option_size'] = df['purchase_option_size'].astype(object)

In [350]:
# 1)
# df[df['product_name'] == '러버스 트라이앵글 브라']['source_url'].value_counts(dropna=False)
# 동일 제품명에 url 두 가지 -> 제품명 동일하나 url 별로 컬러구성이 다름 & 사이즈 구성은 동일함.
# 085, 090, 095, 100 / 85(XS), 90(S), 95(M), 100(L) ---> 숫자로 통일
import re

def normalize_size_value(text):
    if pd.isna(text):
        return None
    
    text = str(text).strip()
    
    # 괄호 및 괄호 안 내용 제거 (90(S) → 90)
    text = re.sub(r'\(.*?\)', '', text).strip()
    
    # 숫자만 있는 경우
    if re.fullmatch(r'\d+', text):
        num = int(text)
        # 사이즈 범위(60~320)인 경우만 앞의 0 제거
        if 60 <= num <= 320:
            return str(num)
        else:
            return text  # 범위 밖이면 원본 유지
    
    return text

mask = df['product_name'] == '러버스 트라이앵글 브라'

df.loc[mask, 'purchase_option_size'] = (
    df.loc[mask, 'purchase_option']
    .apply(normalize_size_value)
)

df[mask][['purchase_option', 'purchase_option_size']].value_counts()

purchase_option  purchase_option_size
90(S)            90                      5
001              001                     4
95(M)            95                      4
095              95                      2
090              90                      1
100              100                     1
Name: count, dtype: int64

In [351]:
# 2) 푸퍼 미니 토트백
# url은 한 종류로 동일, product_code 등도 한 종류 -> 화이트/블랙 구별 불가 -> purchase_option_color 컬럼 채우기 패스
# purchase_option 종류: 001, 000(free), 150 -> url 확인 시 모드 동일 제품으로 이동함.
#                       -> 옵션에 사이즈 모두 '000(free)'만 있음.
#                       -> 리뷰 직접 확인해보니 '001 = 블랙', '150 = 화이트', '217 = 브라운'
# purchase_option_size 모두 000으로 처리
# purchase_option_color 컬러 1:1 매칭
mask = df['product_name'] == '푸퍼 미니 토트백'

# purchase_option 값이 있는 데이터의 purchase_option_size를 '000'으로
df.loc[mask & df['purchase_option'].notna(), 'purchase_option_size'] = '000'

# purchase_option 값에 따라 purchase_option_color 채우기
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '150'), 'purchase_option_color'] = '화이트'

# 확인
df[mask][['purchase_option', 'purchase_option_color', 'purchase_option_size']].value_counts(dropna=False)

purchase_option  purchase_option_color  purchase_option_size
NaN              NaN                    NaN                     75
001              블랙                     000                     22
000(Free)        NaN                    000                     14
150              화이트                    000                      4
Name: count, dtype: int64

In [352]:
# 3) 버터소프트 스트링 자켓
# url, code 모두 1 종류씩 있음
# purchase_option 종류: 031, 001
# 제품 url에서 컬러옵션을 선택하면 url 뒷부분 숫자가 컬러코드 숫자로 변함.
#   -> 031: 모카
#   -> 001: 블랙
mask = df['product_name'] == '버터소프트 스트링 자켓'

df.loc[mask & (df['purchase_option'] == '031'), 'purchase_option_color'] = '모카'
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# 확인
df[mask][['purchase_option', 'purchase_option_color']].value_counts(dropna=False)

purchase_option  purchase_option_color
NaN              NaN                      2
031              모카                       2
001              블랙                       1
Name: count, dtype: int64

In [353]:
# 4) 버터소프트 스커트
# 032 = 크림
# 031 = 모카
# 001 = 블랙

mask = df['product_name'] == '버터소프트 스커트'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '032'), 'purchase_option_color'] = '크림'
df.loc[mask & (df['purchase_option'] == '031'), 'purchase_option_color'] = '모카'
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# 확인
df[mask][['purchase_option', 'purchase_option_color', 'purchase_option_size']].value_counts(dropna=False)

purchase_option  purchase_option_color  purchase_option_size
NaN              NaN                    NaN                     32
90(S)            NaN                    90                       4
032              크림                     NaN                      3
95(M)            NaN                    95                       3
105(XL)          NaN                    105                      3
001              블랙                     NaN                      2
100(L)           NaN                    100                      2
031              모카                     NaN                      1
Name: count, dtype: int64

In [354]:
# 5) 버터소프트 집업 후드
mask = df['product_name'] == '버터소프트 집업 후드'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '032'), 'purchase_option_color'] = '크림'
df.loc[mask & (df['purchase_option'] == '031'), 'purchase_option_color'] = '모카'
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# 확인
df[mask][['purchase_option', 'purchase_option_color', 'purchase_option_size']].value_counts(dropna=False)

purchase_option  purchase_option_color  purchase_option_size
031              모카                     NaN                     3
105(XL)          NaN                    105                     3
100(L)           NaN                    100                     2
NaN              NaN                    NaN                     2
95(M)            NaN                    95                      2
001              블랙                     NaN                     1
Name: count, dtype: int64

In [355]:
# FHC 벤티세이 트랙 팬츠
mask = df['product_name'] == 'FHC 벤티세이 트랙 팬츠'

df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

In [356]:
# 1911 여성 니트트랙 집업
mask = df['product_name'] == '1911 여성 니트트랙 집업'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WM(W90)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == 'WS(W85)'), 'purchase_option_size'] = '85'
df.loc[mask & (df['purchase_option'] == 'WL(W95)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == 'WXS(W80)'), 'purchase_option_size'] = '80'
df.loc[mask & (df['purchase_option'] == 'W85(WS)'), 'purchase_option_size'] = '85'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '234'), 'purchase_option_color'] = '브라운,다크브라운'
df.loc[mask & (df['purchase_option'] == '175'), 'purchase_option_color'] = '화이트,아이보리'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '234', '175']), 'purchase_option_size'] = None

# 확인
df[mask][['purchase_option', 'purchase_option_color', 'purchase_option_size', 'women_size_yn']].value_counts(dropna=False)

purchase_option  purchase_option_color  purchase_option_size  women_size_yn
NaN              NaN                    NaN                   0                195
WM(W90)          NaN                    90                    1                  7
001              블랙                     NaN                   1                  5
234              브라운,다크브라운              NaN                   1                  4
WS(W85)          NaN                    85                    1                  3
WL(W95)          NaN                    95                    1                  3
WXS(W80)         NaN                    80                    1                  2
175              화이트,아이보리               NaN                   1                  2
W85(WS)          NaN                    85                    1                  1
Name: count, dtype: int64

In [357]:
# ARCHIVE 그래픽 맨투맨

mask = df['product_name'] == 'ARCHIVE 그래픽 맨투맨'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = 100
df.loc[mask & (df['purchase_option'] == 'XL(105)'), 'purchase_option_size'] = 105

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# 확인
df[mask][['purchase_option', 'purchase_option_color', 'purchase_option_size', 'women_size_yn']].value_counts(dropna=False)

purchase_option  purchase_option_color  purchase_option_size  women_size_yn
001              블랙                     NaN                   0                2
L(100)           NaN                    100.0                 0                1
XL(105)          NaN                    105.0                 0                1
Name: count, dtype: int64

In [358]:
# 러버스 베이직 팬티
# url 여러 개: 같은 제품링크인데 색상 별로 나눠지기도 함.
# 색상코드 기준으로 판단.
mask = df['product_name'] == '러버스 베이직 팬티'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = 95
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = 100
df.loc[mask & (df['purchase_option'] == 'XL(105)'), 'purchase_option_size'] = 105

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '650'), 'purchase_option_color'] = '그레이,라이트멜란지'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '650']), 'purchase_option_size'] = None

# 확인
df[mask][['purchase_option', 'purchase_option_color', 'purchase_option_size', 'women_size_yn']].value_counts(dropna=False)

purchase_option  purchase_option_color  purchase_option_size  women_size_yn
NaN              NaN                    NaN                   0                41
001              블랙                     NaN                   0                 7
95(M)            NaN                    95.0                  0                 5
90(S)            NaN                    90.0                  0                 3
100(L)           NaN                    100.0                 0                 3
650              그레이,라이트멜란지             NaN                   0                 1
Name: count, dtype: int64

In [359]:
# 에센셜 세미부츠컷 팬츠

mask = df['product_name'] == '에센셜 세미부츠컷 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WS(W75)'), 'purchase_option_size'] = 74

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '290'), 'purchase_option_color'] = '베이지,오트밀멜란지'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '290']), 'purchase_option_size'] = None

In [360]:
# 버터소프트 스커트
mask = df['product_name'] == '버터소프트 스커트'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = 95
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = 105
df.loc[mask & (df['purchase_option'] == '100(L) '), 'purchase_option_size'] = 100

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '031'), 'purchase_option_color'] = '모카'
df.loc[mask & (df['purchase_option'] == '032'), 'purchase_option_color'] = '크림'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '031', '032']), 'purchase_option_size'] = None

In [361]:
# 러버스 트라이앵글 브라
mask = df['product_name'] == '러버스 트라이앵글 브라'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = 95
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = 105
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = 100
df.loc[mask & (df['purchase_option'] == '090'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == '095'), 'purchase_option_size'] = 95

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '100'), 'purchase_option_color'] = '화이트'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '100']), 'purchase_option_size'] = None

In [362]:
# 러버스 치키 팬티
mask = df['product_name'] == '러버스 치키 팬티'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = 95
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = 100
# df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = 105

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '650'), 'purchase_option_color'] = '핑크,라이트핑크'
df.loc[mask & (df['purchase_option'] == '101'), 'purchase_option_color'] = '레드'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '650', '101']), 'purchase_option_size'] = None

In [363]:
# 1911 니트트랙 팬츠
mask = df['product_name'] == '1911 니트트랙 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'purchase_option_size'] = 80
df.loc[mask & (df['purchase_option'] == 'M(085)'), 'purchase_option_size'] = 85
df.loc[mask & (df['purchase_option'] == 'XL(95)'), 'purchase_option_size'] = 95
df.loc[mask & (df['purchase_option'] == 'L(90)'), 'purchase_option_size'] = 90

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '234'), 'purchase_option_color'] = '브라운,다크브라운'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'women_size_yn'] = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '234']), 'purchase_option_size'] = None

In [364]:
# 에센셜 와이드 팬츠
mask = df['product_name'] == '에센셜 와이드 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(90)'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == 'XL(95)'), 'purchase_option_size'] = 95

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '066'), 'purchase_option_color'] = '그레이,라이트멜란지'

In [365]:
# 벨로 소프트 드로즈

mask = df['product_name'] == '벨로 소프트 드로즈'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '090'), 'purchase_option_size'] = 90
df.loc[mask & (df['purchase_option'] == '095'), 'purchase_option_size'] = 95

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '100'), 'purchase_option_color'] = '화이트'
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '100']), 'purchase_option_size'] = None

In [366]:
# 에센셜 클래식 사각 드로즈
mask = df['product_name'] == '에센셜 클래식 사각 드로즈'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = 100

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

In [367]:
# 레트로백팩 v2
mask = df['product_name'] == '레트로백팩 v2'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '000(Free)'), 'purchase_option_size'] = '000'
df.loc[mask & (df['purchase_option'] == '000'), 'purchase_option_size'] = '000'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '234'), 'purchase_option_color'] = '브라운,다크브라운'
df.loc[mask & (df['purchase_option'] == '150'), 'purchase_option_color'] = '화이트,크림'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '234', '150']), 'purchase_option_size'] = None

# purchase_option 값이 있는 데이터 purchase_option_size = 000
df.loc[mask & df['purchase_option'].notna(), 'purchase_option_size'] = '000'

In [368]:
# 투포켓 백팩
mask = df['product_name'] == '투포켓 백팩'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

# purchase_option 값이 있는 데이터 purchase_option_size = 000
df.loc[mask & df['purchase_option'].notna(), 'purchase_option_size'] = '000'

In [369]:
# 에센셜 골지 부츠컷 팬츠

mask = df['product_name'] == '에센셜 골지 부츠컷 팬츠'
# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WS(W75)'), 'purchase_option_size'] = 75

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

In [370]:
# 에센셜 골지 후드 집업
mask = df['product_name'] == '에센셜 골지 후드 집업'

# purchase_option_size
# df.loc[mask & (df['purchase_option'] == 'WS(W75)'), 'purchase_option_size'] = 75


# purchase_option_color
df.loc[mask & (df['purchase_option'] == '290'), 'purchase_option_color'] = '베이지,오트밀멜란지'
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '290']), 'purchase_option_size'] = None

In [371]:
# 립스탑 포켓 크로스백
mask = df['product_name'] == '립스탑 포켓 크로스백'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '000(Free)'), 'purchase_option_size'] = '000'


# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [372]:
# 에센셜 클래식 남성 드로즈 블랙 5PACK
mask = df['product_name'] == '에센셜 클래식 남성 드로즈 블랙 5PACK'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '110(2XL)'), 'purchase_option_size'] = '110'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [373]:
# 테크 트레이닝 팬츠
mask = df['product_name'] == '테크 트레이닝 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(90)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == 'M(085)'), 'purchase_option_size'] = '85'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [374]:
# 휠라 스포르트 남성 롱드로즈
mask = df['product_name'] == '휠라 스포르트 남성 롱드로즈'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

In [375]:
# Coldwave+ 우븐 긴팔 피스테
mask = df['product_name'] == 'Coldwave+ 우븐 긴팔 피스테'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = '100'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [376]:
# Coldwave 트리코트 후드 트레이닝집업
mask = df['product_name'] == 'Coldwave 트리코트 후드 트레이닝집업'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = '100'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [377]:
# ARCHIVE 그래픽 맨투맨
mask = df['product_name'] == 'ARCHIVE 그래픽 맨투맨'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == 'XL(105)'), 'purchase_option_size'] = '105'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [378]:
# 버터소프트 스트링 자켓
mask = df['product_name'] == '버터소프트 스트링 자켓'

# purchase_option_size
# df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = '100'
# df.loc[mask & (df['purchase_option'] == 'XL(105)'), 'purchase_option_size'] = '105'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '031'), 'purchase_option_color'] = '모카'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '031']), 'purchase_option_size'] = None

In [379]:
# 에센셜 클래식 햄 팬티
mask = df['product_name'] == '에센셜 클래식 햄 팬티'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [380]:
# 1911 유니 니트트랙 집업
mask = df['product_name'] == '1911 유니 니트트랙 집업'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == 'XL(105)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '2XL(110)'), 'purchase_option_size'] = '110'
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == 'S(090)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == 'M(095)'), 'purchase_option_size'] = '95'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '234'), 'purchase_option_color'] = '브라운,다크브라운'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '234']), 'purchase_option_size'] = None

In [381]:
# 버터소프트 와이드 팬츠
mask = df['product_name'] == '버터소프트 와이드 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [382]:
# 벨로 소프트 스트랩 팬티
mask = df['product_name'] == '벨로 소프트 스트랩 팬티'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [383]:
# Drywave 빅리니어 레터링 반팔티
mask = df['product_name'] == 'Drywave 빅리니어 레터링 반팔티'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'XL(105)'), 'purchase_option_size'] = '105'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '191'), 'purchase_option_color'] = '화이트,오프화이트'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '191']), 'purchase_option_size'] = None

In [384]:
# 러버스 보이쇼츠
mask = df['product_name'] == '러버스 보이쇼츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '85(XS)'), 'purchase_option_size'] = '85'
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == '95(M) '), 'purchase_option_size'] = '95'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [385]:
# 버터소프트 부츠컷 팬츠
mask = df['product_name'] == '버터소프트 부츠컷 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '031'), 'purchase_option_color'] = '크림'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '031']), 'purchase_option_size'] = None

In [386]:
# 트레이닝 팬츠
mask = df['product_name'] == '트레이닝 팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'purchase_option_size'] = '80'
df.loc[mask & (df['purchase_option'] == 'L(90)'), 'purchase_option_size'] = '90'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'women_size_yn'] = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [387]:
# 에센셜 스웻 4.5부 쇼츠
mask = df['product_name'] == '에센셜 스웻 4.5부 쇼츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'purchase_option_size'] = '80'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'women_size_yn'] = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [388]:
# Coldwave 트리코트 트레이닝팬츠
mask = df['product_name'] == 'Coldwave 트리코트 트레이닝팬츠'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'XL(95)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'purchase_option_size'] = '80'
df.loc[mask & (df['purchase_option'] == 'WS(W75)'), 'purchase_option_size'] = '75'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & (df['purchase_option'] == 'WM(W80)'), 'women_size_yn'] = 1
df.loc[mask & (df['purchase_option'] == 'WS(W75)'), 'women_size_yn'] = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [389]:
# 투포켓 백팩
mask = df['product_name'] == '투포켓 백팩'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [390]:
# 우븐 트랙 맨투맨
mask = df['product_name'] == '우븐 트랙 맨투맨'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '442'), 'purchase_option_color'] = '블루,라이트블루'

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '442']), 'purchase_option_size'] = None

In [391]:
# 1911 니트트랙 스커트
mask = df['product_name'] == '1911 니트트랙 스커트'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'WXS(W70)'), 'purchase_option_size'] = '70'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '234'), 'purchase_option_color'] = '브라운,다크브라운'

# purchase_option 값이 있는 데이터 women_size_yn = 1
df.loc[mask & (df['purchase_option'] == 'WXS(W70)'), 'women_size_yn'] = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '234']), 'purchase_option_size'] = None

In [392]:
# 스텐넥 트레이닝 집업
mask = df['product_name'] == '스텐넥 트레이닝 집업'
# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '234']), 'purchase_option_size'] = None

In [393]:
# 립스탑 포켓 크로스백
mask = df['product_name'] == '립스탑 포켓 크로스백'
# purchase_option_size
df.loc[mask & (df['purchase_option'] == '000(Free)'), 'purchase_option_size'] = '000'
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_size'] = '000'
# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [394]:
# 에센셜 스몰로고 맨투맨
mask = df['product_name'] == '에센셜 스몰로고 맨투맨'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == 'L(100)'), 'purchase_option_size'] = '100'

# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
df.loc[mask & (df['purchase_option'] == '290'), 'purchase_option_color'] = '베이지,오트밀멜란지'
df.loc[mask & (df['purchase_option'] == '442'), 'purchase_option_color'] = '블루,라이트블루'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '290', '442']), 'purchase_option_size'] = None

In [395]:
# 에센셜 퓨징 모달 남성 드로즈 3PACK
mask = df['product_name'] == '에센셜 퓨징 모달 남성 드로즈 3PACK'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '100'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '095'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '105'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '110(2XL)'), 'purchase_option_size'] = '110'

# purchase_option_color
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '290', '442']), 'purchase_option_size'] = None

In [396]:
# 에센셜 클래식 남성 드로즈 블랙 5PACK
mask = df['product_name'] == '에센셜 클래식 남성 드로즈 블랙 5PACK'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '110(2XL)'), 'purchase_option_size'] = '110'

# purchase_option_color
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '블랙'

# purchase_option 값이 있는 데이터 women_size_yn = 1
# df.loc[mask & df['purchase_option'].notna(), 'women_size_yn'] = 1

# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001', '290', '442']), 'purchase_option_size'] = None

In [397]:
# 에센셜 스트레이트 팬츠
mask = df['product_name'] == '에센셜 스트레이트 팬츠'
# purchase_option_color
df.loc[mask & (df['purchase_option'] == '001'), 'purchase_option_color'] = '블랙'
# purchase_option_size에 색상코드 값 제거
df.loc[mask & df['purchase_option_size'].isin(['001']), 'purchase_option_size'] = None

In [398]:
# 리프팅업 퓨징 브라
mask = df['product_name'] == '리프팅업 퓨징 브라'

# purchase_option_size
df.loc[mask & (df['purchase_option'] == '90(S)'), 'purchase_option_size'] = '90'
df.loc[mask & (df['purchase_option'] == '95(M)'), 'purchase_option_size'] = '95'
df.loc[mask & (df['purchase_option'] == '105(XL)'), 'purchase_option_size'] = '105'
df.loc[mask & (df['purchase_option'] == '100(L)'), 'purchase_option_size'] = '100'

# purchase_option_color
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '블랙'

In [399]:
# 휠라 글리오 핑크
# purchase_option_color
mask = df['product_name'] == '휠라 글리오 핑크'
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '핑크,핑크,핑크'

# 휠라 에샤페 LX 블루
mask = df['product_name'] == '휠라 에샤페 LX 블루'
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '블루'

# 휠라 에샤페 실버문
mask = df['product_name'] == '휠라 에샤페 실버문'
df.loc[mask & (df['purchase_option'].notna()), 'purchase_option_color'] = '그레이,화이트,화이트'

----
확인용 컬럼들

In [400]:
# purchased_option 컬럼에서 파생컬럼 생성
df['purchase_option'].value_counts(dropna=False)

purchase_option
NaN         8954
240          159
001           99
090           93
250           89
            ...
661            1
75B            1
3XL(115)       1
191            1
85(XS)         1
Name: count, Length: 78, dtype: int64

In [401]:
df[df['purchase_option'] == '240']['product_name'].value_counts()

product_name
휠라 에샤페 LX 블루                  30
휠라 글리오 핑크                     21
휠라 에샤페 실버문                    17
휠라 리트모 슬릭 LX                  13
휠라 스피드서브 T9 2.0                9
하레핀 1998                       9
휠라 에샤페 LX 브릭                   5
휠라 웨이비 데이 v2                   5
스트라이프 로고 포인트 중목 양말             5
에샤페 VC v2 x BEAUTY & YOUTH     4
판테라 99/25 LX                   3
레인저 맥스 LT                      3
에샤페 벨크로 메리제인                   2
슬릭 웨이비 샌들 v3                   2
휠라 리트모 슬릭                      2
오크먼트 TR v2                     2
레이 스플라인 MS                     2
인터레이션 v2                       2
엑실러스 3 T9                      2
오크먼트 TR 다이얼 v2                 2
판테라 99/25                      1
휠라 레비오 04/26                   1
휠라 플로트 맥스 쉴드 다이얼               1
메모리 데시무스 v2                    1
펑키 테니스 98/25                   1
휠라 인터런 v2 LITE                 1
페이토 샌들 v2                      1
휠라 RGB 아킴보 3.0                 1
휠라 에샤페 레이스                     1
휠라 플로트 맥스 2.0 LT               1
휠라 인터런 슬릭 실버문                  1
휠라 룰즈 모카신 LX                   1
휠라 플로트 TR9 2.0                 1
레이유나이트 v2                      1
웨이비 맥스 v2                      1
플로트 TR7 2.0 뮬                  1
프론토 v3                         1
테니스 중목 양말                      1
에센셜 장목 3번들                     1
Name: count, dtype: int64

In [402]:
# # url 종류 확인
# display(df[df['product_name'] == '리프팅업 퓨징 브라']['product_id'].value_counts(dropna=False))
display(df[df['product_name'] == '휠라 리트모 슬릭 LX']['product_url'].value_counts(dropna=False))

# # purshase_option 값 종류 확인
display(df[df['product_name'] == '휠라 리트모 슬릭 LX']['purchase_option'].value_counts())

# 실제 데이터 확인
display(df[df['product_name'] == '휠라 리트모 슬릭 LX'][['product_name', 'product_code', 'purchase_option', 'purchase_option_size', 'purchase_option_color', 'women_size_yn', 'product_url']])

product_url
https://www.fila.co.kr/products/1100fs261od03x008370    134
Name: count, dtype: int64

purchase_option
240    13
245    10
235     7
250     4
225     3
230     3
260     2
265     2
255     1
270     1
275     1
280     1
Name: count, dtype: int64

,product_name,product_code,purchase_option,purchase_option_size,purchase_option_color,women_size_yn,product_url
1748,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
1749,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
1750,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
1751,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
1752,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
...,...,...,...,...,...,...,...
6896,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
6897,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
6898,휠라 리트모 슬릭 LX,1100FS261OD03X008370,280,280,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
6899,휠라 리트모 슬릭 LX,1100FS261OD03X008370,230,230,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370
6900,휠라 리트모 슬릭 LX,1100FS261OD03X008370,NaN,NaN,NaN,0,https://www.fila.co.kr/products/1100fs261od03x008370

## 이어서 컬럼 정제

In [403]:
display(df.head())
display(df.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,helpful_count,has_image,purchase_option,purchase_option_size,purchase_option_color,product_url,product_code,related_product_ids,women_size_yn
0,2026-04-28,자사몰,139954,8127678283812,휠라 스피드서브 T9 2.0,2026-03-26,2026,3,"이 신발, 네트 대시가 왜 이렇게 빨라/스피드서브 t9 2.0 실착리뷰! 테니스 구력은 장비빨(?)이라는 말 이번에 휠라 스피드서브 t9 2.0을 하드코트와 인조잔디에서 굴려보며 뼈저리게 느꼈습니다. 결론부터 말씀드리면 발이 편한 건 기본 코트 위에서 날개를 단 기분이었는데요 구체적인 후기 들어갑니다! 1.발볼러들 강추 합니다! 사이즈감과 극강의 편안함 제일 먼저 놀란 건 사이즈감과 핏입니다 2.0 버전은 분리형 텅(tongue) 구조로 바뀌어서 발등 높이에 맞춰 끈 조절이 정말 자유로워요 저는 발이 예민한 편인데도 발이 참 편하다는 생각을 멈출 수가 없었습니다! 발볼도 넉넉하게 나와서 압박감 없이 핏하게 감기는 맛이 일품입니다 2.스플릿 스텝 후 0.1초가 달라진다 접지력과 반응성 이 신발의 진가는 방향 전환에서 나옵니다.하드코트든 인조잔디든 지면을 움켜쥐는 헤링본 패턴의 아웃솔 접지력이 장난 아니에요. 특히 스플릿 스텝 이후 다음 동작으로 넘어갈 때 미끄러짐이 전혀 없어서,에너지가 밖으로 새지 않고 바로 다음 스텝으로 연결되는 느낌이 정말 쾌적했습니다. 3.네트 앞으로 전력 질주 경량성과 네트 플레이 저는 기회만 나면 네트 앞으로 달려가 발리 공격하는 걸 즐기는데 스피드서브 2.0은 확실히 가볍습니다. 신발이 무거우면 첫 발 떼기가 무거운데 이건 발놀림이 경쾌해서 네트 대시 속도가 훨씬 붙더라고요. 좌우로 흔들릴 때도 tpu 생크 기술이 발의 뒤틀림을 딱 잡아주니까 빠른 움직임 속에서도 안정감이 느껴져 발리 찬스를 잡기가 훨씬 수월했습니다. 4.탄탄한 쿠셔닝 무릎 피로도 안녕! 쿠셔닝은 너무 물렁하지도, 너무 딱딱하지도 않은 기분 좋은 탄성을 보여줍니다. 하드코트에서 격하게 뛰어도 충격을 잘 흡수해주어 장시간 게임 후에도 무릎이나 발바닥에 무리가 덜 갔습니다. 5.코트 위 패셔니스타 디자인 한줄평 기능도 기능이지만 디자인이 정말 깔끔하고 예뻐요!측면 로고가 미니멀해져서 그런지 어떤 테니스복에 매치해도 찰떡 입니다. 운동 끝나고 일상복에 그대로 신고 가도 전혀 어색하지 않은 세련된 화이트 톤이라 더 만족스럽네요. 한 줄 요약 스플릿 스텝이 가벼워지고 네트 점령이 쉬워지는 신발 발볼 넓은 공격형 플레이어라면 무조건 이거 가세요!",5,28,1,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,1100FS261TN02X001106,[8127678283812],0
1,2026-04-28,자사몰,143752,8100165845028,하레핀 1998,2026-04-21,2026,4,"(후기 사진은 크게 확인 부탁드립니다) 남자친구랑 사귀고 첫 커플 신발인데 뭐를 살까 고민하다가 제가 ""휠라 에샤페 lx 초코""를 신고 있는데 너무 편하게 신고 있던 중 우연히 휠라 하레핀을 보자마자 너무 이뻐서 바로 남자친구한테 보여줬더니 너무 마음에 든다고 주말에 당장 휠라에 가서 신어보고 둘 다 마음에 들어서 바로 남자친구 사줬어요 ! 근데 실물보고 잘 보고 온 게 맞구나 싶었어요 ㅋㅋ디자인, 색감 둘 다 잡았더라구요…? 과한 느낌은 없고 잔잔하게 포인트 줄 수 있는 신발이예요 진짜 만족도 100%입니다. 하레핀 구매하고 계속 이 신발만 신고 다니고 있어요 ㅎㅎ 덕분에 동료들한테도 이쁘다고 칭찬받고 많이 추천도 해줬어요 ㅋㅋ 꼭 구매하라고..! 사이즈도 평소에 신던 사이즈 230mm 그대로 정상 사이즈로 나왔다고 생각했어요 제가 신발 구매할 때마다 발볼이 있다는 이야기를 듣는데 불편함없었습니다 ! 그리고 걷다보면 발가락 아픈 느낌도 없었고 너무 편하게 걸어다녔어요 ! 아 ! 남자친구도 평소에 270mm으로 신는데 휠라도 동일하게 270mm으로 구매해서 착용하고 있는데 편하다고 그러더라구요 ! 평소 사이즈랑 동일하게 구매하시면 될 거 같아요 제가 신발 구매하고 바로 남자친구랑 하레핀 신고 놀러 갔어요! 근데 진짜 사진 찍을 때랑 걸어 다니면서 거울 보일 때 진짜 너무 이뻐요…최고! ! 한강으로 놀러갔는데 오래 걸어도 발이 정말 편했고, 신발이 생각보다 가볍다고 생각도 했습니다 ! 그리고 하레핀 크림색상은 츄리닝에도 잘 어울리고 데일리룩에도 잘 어울리고 소재도 천연 돼지 스웨이드여서 고급감이 더해져 어느 룩에도 잘 매칭이 되는 핫한 아이템이라고 생각해요 ㅎㅎ 또 제가 하레핀 노랑색도 신어봤는데 진짜 30분동안 고민했어요,,색감 진짜 이쁘고 완전 포인트로 신기 좋아보였어요 ! 완전 취향저격… 이번에는 크림색으로 구매했지만 조만간 남자친구랑 포인트 주기 이쁘다고 같이 사러 가자고 꼬섰어요 ㅋㅋ 노랑색도 구매하면 이쁜 사진으로 후기 작성하러 올께요 ㅎㅎ",5,25,1,270,270,NaN,https://www.fila.co.kr/products/1100fs261od03x095217,1100FS261OD03X095217,"[8100165845028, 8100475764772, 8117765799972]",0
2,2026-04-28,자사몰,140502,8127678283812,휠라 스피드서브 T9 2.0,2026-03-31,2026,3,"엑실러스3 유저의 스피드서브 2.0 기변 후기 테니스 구력 2년 차, 그동안 저의 베이스라인을 든든하게 지켜주던 '엑실러스 3'에서 드디어 '스피드서브 2.0'으로 기변했습니다! 목빠지게 배송 기다리다 코트에서 직접 뛰어보고 남기는 진또배기 후기 바로 레츠고~ 1. 사이즈 및 핏감 엑실러스 3가 갑옷처럼 발을 보호해 주는 느낌이었다면, 스피드서브 2.0의 유연한 소재와 핏감은 진짜 jmt~ 발볼도 편안하게 잘 나와서 정사이즈로 신으니 완전 맞춤 핏이네요. 특히 끈으로 발등 압박감을 세밀하게 조절할 수 있어서 게임 내내 발이 너무 편안합니다!! 2. 접지력 및 반응성 멈출 때 정확히 멈춰주고, 다음 공을 향해 튀어 나갈 때 바닥을 쫀득하게 밀어주는 폭발력이 진짜 진또배기입니다. 아웃솔이 바닥을 미끄러짐 없이 꽉 잡아주니까 네트 앞으로 대시할 때 반응 속도가 확실히 빨라졌어요. 덕분에 구력 2년 차도 자신감 있게 공격적인 플레이 가능해서 진짜 너무 좋아여!! 3. 쿠셔닝 가벼운 무게에 어떻게 이런 쫀쫀한 쿠션을 넣었는지 휠라 칭찬합니다~~ 하드 코트에서 랠리를 길게 가져가도 발바닥 충격을 잘 분산시켜 주고요. 다음 스텝을 밟을 때 에너지를 리턴해 주는 탄성 덕분에, 3시간 이상 운동해도 하체 피로도가 확실히 적어요^^ 스피드서브 2.0 디자인도 느좋이라 파트너랑 팀 테니스화로 맞춰 신었는데 코트 갈 때마다 주변에서 예쁘다고 난리네요 ㅎㅎ 정말 누구신지 모르겠지만 기획자님 너무 감사합니당 이렇게 이쁜색 테니스화를 만들어주셔서 가볍고 예쁜데 기능까지 완벽한 스피드서브 2.0과 함께 혼복 대회 입상을 넘어 우승까지 렛츠고~~!!",5,22,1,240,240,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,1100FS261TN02X001106,[8127678283812],0
3,2026-04-28,자사몰,143962,8100165845028,하레핀 1998,2026-04-24,2026,4,"첫 커플신발로 휠라 하레핀1998을 선택했어요! 일반적인 스니커즈 디자인이 질려서 고민하고 있을 때, 때마침 딱 캐주얼한 등산화 느낌의 하레핀이 마음에 들어 데꼬 왔어요 저희는 230, 280 크림 색상으로 공식홈페이지에서 구매했어요! (카카오 채널추가 할인쿠폰 굿) 저는 발볼이 좁은 편이고, 남친은 보통인 편인데 둘 다 편하게 잘 맞아요! 정사이즈로 구매하시면 돼요. 처음에 박스 딱 열었을 때 일단 실물이 되게 예뻐서 만족스러웠고, 딱 신었을 때 되게 가볍고 편해서 놀랐어요 그리고 저 평발이라 많이 걸으면 발바닥이 무조건 아픈데, 경주 황리단길을 폭풍워킹해도 정말 발이 안 아팠어요!! 밝은 천 색상에 어두운 밑창과 끈 조합이라, 흰 바지를 입던~ 흑청을 입던~ 중청을 입던~ 정말 캐주얼하게 휘뚤마뚤 잘 신을 수 있어요! 근데 또 아예 안 꾸민 느낌은 아니라 출근룩, 데이트룩 다 가능해서 넘 좋음 여행 앞두고 커플신발을 하레핀으로 장만해서 경주여행을 잘 다녀왔는데, 곧 있을 제주에도 함께 신고 가려고 합니다 커플신발로 휠라 하레핀 추천드려요 ! - 이 리뷰가 도움되셨다면, 도움돼요 눌러주세요 -",5,22,1,280,280,NaN,https://www.fila.co.kr/products/1100fs261od03x095217,1100FS261OD03X095217,"[8100165845028, 8100475764772, 8117765799972]",0
4,2026-04-28,자사몰,140489,8127678283812,휠라 스피드서브 T9 2.0,2026-03-30,2026,3,"[스피드서브 1 찐유저의 2.0 버전업 후기] 단종의 눈물을 닦아준 완벽한 진화 (feat. 혼복 우승 렛츠고~) 기존에 밑창이 닳도록 신던 인생 테니스화 '스피드서브 1'이 단종되어 더 이상 구매할 수 없어 눈물 흘리던 참에 소울메이트 같은 동생이 스피드서브 2.0이 런칭됐다는 기가 막힌 소식을 알려주더군요. 망설임 없이 바로 기변 렛츠고~ 코트 위에서 직접 굴러보고 쓰는 진또배기 후기 바로 레츠고~ 1. 사이즈 및 핏감 기존 일체형 구조에서 2.0은 분리형 텅으로 변경됐는데, 이게 정말 신의 한 수 같습니다. 그날그날 발 붓기나 양말 두께에 맞춰 끈으로 더 세밀하게 조절할 수 있어 발과의 일체감이 더 좋아졌어요. 발볼이 넉넉하게 나와서 전형적인 한국인 족형에게 강력히 추천드립니다. 2. 쿠셔닝 292.7g이라는 가벼운 무게에 이런 쫀쫀한 쿠션감이라니!무조건 물렁하기만 한 쿠션 보다 오히려 발바닥의 충격을 잘 분산해줍니다. 처음 2.0을 신은 날 4시간을 풀로 뛰었는데도 하체 피로도가 다른 날보다 적어서 감탄했습니다. 3. 접지력 및 움직임 반응 기존 1세대 버전도 접지력은 정말 만족하며 신었는데, 2.0은 바닥 패턴이 바뀌면서 확실히 더 업그레이드됐네요. 스플릿 스텝 후 다음 스텝 치고 나갈 때 바닥을 쫀득하게 밀어주는 지지력이 너무 좋습니다. 미끄러짐이 없으니 덕분에 코트 위에서 더 안정적이고 공격적인 플레이가 가능해졌어요. 4. 착화 시 안정감 테니스는 멈추는 게 더 중요한 운동인거 다들 아시죠? 좌우 사이드 스텝을 밟고 오픈 스탠스로 급브레이크를 걸 때, 신발 뒤틀림 없이 발목을 견고하게 잘 잡아줍니다. 덕분에 발목 불안함 없이 공에만 100% 집중할 수 있습니다. 스피드서브 2.0 런칭을 소개해 준 동생하고 최근 혼복팀을 결성하게 됐는데, 이 참에 팀 테니스화도 2.0으로 같이 맞추게 됐네요. 든든한 스피드서브 2.0과 함께 입상을 넘어 우승까지 렛츠고~~!!",5,20,1,265,265,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106,1100FS261TN02X001106,[8127678283812],0

<class 'pandas.DataFrame'>
RangeIndex: 10689 entries, 0 to 10688
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   collect_date           10689 non-null  str
 1   platform               10689 non-null  str
 2   review_id              10689 non-null  int64
 3   product_id             10689 non-null  int64
 4   product_name           10689 non-null  str
 5   review_date            10689 non-null  str
 6   year                   10689 non-null  int64
 7   month                  10689 non-null  int64
 8   content                10689 non-null  str
 9   rating                 10689 non-null  int64
 10  helpful_count          10689 non-null  int64
 11  has_image              10689 non-null  int64
 12  purchase_option        1735 non-null   str
 13  purchase_option_size   1613 non-null   object
 14  purchase_option_color  537 non-null    object
 15  product_url            10689 non-null  str
 16  product_code           10689 non-null  str
 17  related_product_ids    10689 non-null  str
 18  women_size_yn          10689 non-null  int64
dtypes: int64(8), object(2), str(9)
memory usage: 5.1+ MB

None

In [404]:
# 없는 컬럼 추가하기
required_columns = [
    'collect_date', 'platform', 'review_id', 'product_id', 'product_name',
    'review_date', 'year', 'month', 'content', 'rating', 'helpful_count',
    'has_image', 'purchase_option', 'purchase_option_color', 'purchase_option_size', 'women_size_yn', 'user_height', 'user_weight',
    'user_height_group', 'user_weight_group', 'product_url'
]

for col in required_columns:
    if col not in df.columns:
        df[col] = None

# 컬럼 순서 정리
df = df[required_columns]

In [405]:
# ========================
# 최종 컬럼 정리
# ========================

# 1) 데이터 형변환
def convert_dtypes(df):
    # 날짜 컬럼
    for col in ["collect_date", "review_date"]:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    # ID 컬럼
    for col in ["review_id", "product_id"]:
        if col in df.columns:
            df[col] = df[col].astype("string")

    # 문자열 컬럼
    for col in ["product_name", "content", "purchase_option", "product_url"]:
        if col in df.columns:
            df[col] = df[col].astype("string")

    # category 컬럼
    for col in ["platform", "purchase_option_color", "purchase_option_size", "user_height_group", "user_weight_group"]:
        if col in df.columns:
            df[col] = df[col].astype("category")

    # 정수형 컬럼
    for col, dtype in [("year", "Int16"), ("month", "Int8"), ("rating", "Int8"), ("helpful_count", "Int32")]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype(dtype)

    # 0/1 플래그 컬럼
    for col in ["has_image", "women_size_yn"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype("int8")

    # 실수형 컬럼
    for col in ["user_height", "user_weight"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("float32")

    return df

# 사용
df = convert_dtypes(df)
df.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 10689 entries, 0 to 10688
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   collect_date           10689 non-null  datetime64[us]
 1   platform               10689 non-null  category
 2   review_id              10689 non-null  string
 3   product_id             10689 non-null  string
 4   product_name           10689 non-null  string
 5   review_date            10689 non-null  datetime64[us]
 6   year                   10689 non-null  Int16
 7   month                  10689 non-null  Int8
 8   content                10689 non-null  string
 9   rating                 10689 non-null  Int8
 10  helpful_count          10689 non-null  Int32
 11  has_image              10689 non-null  int8
 12  purchase_option        1735 non-null   string
 13  purchase_option_color  537 non-null    category
 14  purchase_option_size   1613 non-null   category
 15  women_size_yn          10689 non-null  int8
 16  user_height            0 non-null      float32
 17  user_weight            0 non-null      float32
 18  user_height_group      0 non-null      category
 19  user_weight_group      0 non-null      category
 20  product_url            10689 non-null  string
dtypes: Int16(1), Int32(1), Int8(2), category(5), datetime64[us](2), float32(2), int8(2), string(6)
memory usage: 3.9 MB

In [411]:
# ===============================
# 제품명 매칭 확인
# ===============================
multi_name = df.groupby('product_id')['product_name'].nunique()
multi_url = df.groupby('product_id')['product_url'].nunique()

# product_name 매핑 확인
print(multi_name.gt(1).sum(), "개의 product_id가 여러 product_name에 매핑됨")
display(
    df[df['product_id'].isin(multi_name[multi_name > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

# product_url 매핑 확인
print(multi_url.gt(1).sum(), "개의 product_id가 여러 product_url에 매핑됨")
display(
    df[df['product_id'].isin(multi_url[multi_url > 1].index)]
    [['product_id', 'product_name', 'product_url']]
    .drop_duplicates()
    .sort_values('product_id')
)

0 개의 product_id가 여러 product_name에 매핑됨

Empty DataFrame
Columns: [product_id, product_name, product_url]
Index: []

10 개의 product_id가 여러 product_url에 매핑됨

,product_id,product_name,product_url
3813,8093700849700,오크먼트 TR v2,https://www.fila.co.kr/products/11001jm02786h924
3862,8093700849700,오크먼트 TR v2,https://www.fila.co.kr/products/11001jm02786h067
4536,8093701013540,오크먼트 TR 다이얼 v2,https://www.fila.co.kr/products/11001jm02787h925
4609,8093701013540,오크먼트 TR 다이얼 v2,https://www.fila.co.kr/products/11001jm02787h001
83,8093803249700,엑실러스 3 T9,https://www.fila.co.kr/products/11001tm01987h125
4272,8093803249700,엑실러스 3 T9,https://www.fila.co.kr/products/11001tm01987h822
4515,8093803249700,엑실러스 3 T9,https://www.fila.co.kr/products/11001tm01987g475
3421,8093882843172,벨로 소프트 팬티,https://www.fila.co.kr/products/1170fi4drh1450fdrd
4239,8093882843172,벨로 소프트 팬티,https://www.fila.co.kr/products/1170fi4drh1101fdrd
4628,8096560775204,후드티,https://www.fila.co.kr/products/1170fi4poh1146mdid
9527,8096560775204,후드티,https://www.fila.co.kr/products/1170fi4poh1147mblk
3360,8097057275940,러버스 베이직 팬티,https://www.fila.co.kr/products/1170fi261bf01f006100
3391,8097057275940,러버스 베이직 팬티,https://www.fila.co.kr/products/1170fi261bf01f006066
3451,8097057275940,러버스 베이직 팬티,https://www.fila.co.kr/products/1170fi261bf01f006650
3532,8097057275940,러버스 베이직 팬티,https://www.fila.co.kr/products/1170fi261bf01f006412
1,8100165845028,하레핀 1998,https://www.fila.co.kr/products/1100fs261od03x095217
18,8100165845028,하레핀 1998,https://www.fila.co.kr/products/1100fs261od03x095734
3740,8100404723748,러버스 치키 팬티,https://www.fila.co.kr/products/1170fi261bf01f007001
8713,8100404723748,러버스 치키 팬티,https://www.fila.co.kr/products/1170fi261bf01f007452
3767,8127630082084,벨로 소프트 팬티,https://www.fila.co.kr/products/1170fi261dr01f025001
4371,8127630082084,벨로 소프트 팬티,https://www.fila.co.kr/products/1170fi261dr01f025661
8862,8127630082084,벨로 소프트 팬티,https://www.fila.co.kr/products/1170fi261dr01f025250
4024,8139111989284,벨로 소프트 T팬티,https://www.fila.co.kr/products/1170fi261bf01f016001
8858,8139111989284,벨로 소프트 T팬티,https://www.fila.co.kr/products/1170fi261bf01f016071

In [408]:
# ===============================
# 리뷰 내용 중복 확인
# ===============================
# 2-1. product_id 같고 content 중복인 데이터 확인
dup_mask = df.duplicated(subset=['product_id', 'content'], keep=False)
print("product_id는 같고 content가 중복 개수: ", dup_mask.sum())
display(df[dup_mask][['product_id', 'product_name', 'review_date', 'content']].sort_values(['product_id', 'content']).head(20))

# 2-2. 위 경우 중 review_date까지 완전히 동일한 경우 개수
print(
    "review_date까지 완전히 동일한 경우 개수: "
    , df[dup_mask].duplicated(subset=['product_id', 'content', 'review_date'], keep=False).sum()
)

# 2-3. product_id, content, review_date, purchase_option 까지 모두 중복인 경우
dup_mask_full = df.duplicated(
    subset=['product_id', 'content', 'review_date', 'purchase_option'],
    keep=False
)
print("purchase_option까지 완전히 동일한 경우 개수: ", dup_mask_full.sum())
display(
    df[dup_mask_full][['product_id', 'product_name', 'review_date', 'purchase_option', 'content']]
    .sort_values(['product_id', 'review_date'])
    .head(20)
)

product_id는 같고 content가 중복 개수:  285

,product_id,product_name,review_date,content
6141,8093792796708,에샤페 벨크로 메리제인,2025-08-23,귀여운 디자인이 마음에 쏙 들어요 생각보다 발등은 불편하지 않고 정사이즈입니다
6142,8093792796708,에샤페 벨크로 메리제인,2025-08-22,귀여운 디자인이 마음에 쏙 들어요 생각보다 발등은 불편하지 않고 정사이즈입니다
6569,8093792796708,에샤페 벨크로 메리제인,2025-08-24,기존 220-225 신고 발등 낮은 편이고 칼발인데 그래도 반업하라는 후기둘이 많아서 230주문했어요 225했어도 충분했을듯 합니다 신벌은 넘 예뻐오
6570,8093792796708,에샤페 벨크로 메리제인,2025-08-23,기존 220-225 신고 발등 낮은 편이고 칼발인데 그래도 반업하라는 후기둘이 많아서 230주문했어요 225했어도 충분했을듯 합니다 신벌은 넘 예뻐오
6685,8093792796708,에샤페 벨크로 메리제인,2025-07-24,메리제인 운동화 여름에 신기 좋네요 사이즈 잘맞아요
6686,8093792796708,에샤페 벨크로 메리제인,2025-07-23,메리제인 운동화 여름에 신기 좋네요 사이즈 잘맞아요
1351,8093792796708,에샤페 벨크로 메리제인,2025-08-05,배송이 생각보다 하루이틀 늦은게 조금 아쉬웠지만 신발은 너무 맘에 듭니다!! 올 여름 자주 신고 다닐수 있을꺼 같아요!!
1352,8093792796708,에샤페 벨크로 메리제인,2025-08-04,배송이 생각보다 하루이틀 늦은게 조금 아쉬웠지만 신발은 너무 맘에 듭니다!! 올 여름 자주 신고 다닐수 있을꺼 같아요!!
1224,8093792796708,에샤페 벨크로 메리제인,2025-07-24,사이즈도 딱 맞고 일단 발이 아프지 않아서 편하게 신규 다니고 있어요
1225,8093792796708,에샤페 벨크로 메리제인,2025-07-23,사이즈도 딱 맞고 일단 발이 아프지 않아서 편하게 신규 다니고 있어요
1416,8093792796708,에샤페 벨크로 메리제인,2025-07-24,샌동화 고민하다가 구매했어용 너무 발레슈즈같은건 안어울릭거 같아서 운동화 디자인으로 구매했는데 푹신하고 조아용
1417,8093792796708,에샤페 벨크로 메리제인,2025-07-23,샌동화 고민하다가 구매했어용 너무 발레슈즈같은건 안어울릭거 같아서 운동화 디자인으로 구매했는데 푹신하고 조아용
6171,8093792796708,에샤페 벨크로 메리제인,2025-08-24,선물햤는데 신발은 말할것없이 이쁘고 편하다고 하네요 양말신고 신으면 더운감은 좀있다고합니다 사이즈는 평소240이며 245하니깐 딱맞드라구요 참고가 됬음 하네여 즐 쇼!!
6172,8093792796708,에샤페 벨크로 메리제인,2025-08-23,선물햤는데 신발은 말할것없이 이쁘고 편하다고 하네요 양말신고 신으면 더운감은 좀있다고합니다 사이즈는 평소240이며 245하니깐 딱맞드라구요 참고가 됬음 하네여 즐 쇼!!
933,8093792796708,에샤페 벨크로 메리제인,2025-08-19,신발 자체는 너무 귀엽고 바닥도 폭신폭신해서 좋아요! 근데 반업을 해서 그런지 약간 커보이는 느낌..? 치마에도 바지에더 다 잘 어울려서 코디하기 좋아요!
934,8093792796708,에샤페 벨크로 메리제인,2025-08-18,신발 자체는 너무 귀엽고 바닥도 폭신폭신해서 좋아요! 근데 반업을 해서 그런지 약간 커보이는 느낌..? 치마에도 바지에더 다 잘 어울려서 코디하기 좋아요!
6269,8093792796708,에샤페 벨크로 메리제인,2025-08-21,신발이 편하고 귀여워요 색감도 맘에들고 디자인도 굿
6270,8093792796708,에샤페 벨크로 메리제인,2025-08-20,신발이 편하고 귀여워요 색감도 맘에들고 디자인도 굿
775,8093792796708,에샤페 벨크로 메리제인,2025-08-27,"에샤페 벨크로 v2는 진짜 ""귀여움"" 그 자체예요! 처음 봤을 때부터 메리제인 무드 나는 디자인이 너무 귀여워서 눈여겨보고 있었는데요, 흰색이랑 은빛 톤의 조합이 깔끔하면서도 포인트가 돼서 신자마자 만족했어요. 사실 ""내가 잘 소화할 수 있을까?"" 걱정도 됐는데 막상 받아보니 생각보다 코디도 쉽고 편해서 자주 손이 가네요. 동생이랑 커플로 신으려고 샀는데, 같이 신으니 더 기분 좋아요ㅎㅎ"
776,8093792796708,에샤페 벨크로 메리제인,2025-08-26,"에샤페 벨크로 v2는 진짜 ""귀여움"" 그 자체예요! 처음 봤을 때부터 메리제인 무드 나는 디자인이 너무 귀여워서 눈여겨보고 있었는데요, 흰색이랑 은빛 톤의 조합이 깔끔하면서도 포인트가 돼서 신자마자 만족했어요. 사실 ""내가 잘 소화할 수 있을까?"" 걱정도 됐는데 막상 받아보니 생각보다 코디도 쉽고 편해서 자주 손이 가네요. 동생이랑 커플로 신으려고 샀는데, 같이 신으니 더 기분 좋아요ㅎㅎ"

review_date까지 완전히 동일한 경우 개수:  16
purchase_option까지 완전히 동일한 경우 개수:  8

,product_id,product_name,review_date,purchase_option,content
1284,8093881991204,휠라 에샤페 v2 실버,2025-06-26,<NA>,"이쁩니다, 맘에 들어요, 배송도 빠르구요 very good"
1287,8093881991204,휠라 에샤페 v2 실버,2025-06-26,<NA>,"이쁩니다, 맘에 들어요, 배송도 빠르구요 very good"
3917,8093882548260,벨로 소프트 브라,2024-03-13,<NA>,착용 정보: 90 / blk
3918,8093882548260,벨로 소프트 브라,2024-03-13,<NA>,착용 정보: 90 / blk
8919,8093885333540,멜로우 팬티,2025-08-21,<NA>,배송빠르고좋아요 감사합니다
8920,8093885333540,멜로우 팬티,2025-08-21,<NA>,배송빠르고좋아요 감사합니다
3642,8100258349092,멜로우 트렁크,2024-09-20,<NA>,착용 정보: 95 / pbe 가볍고 통풍이 잘 되는데도 가슴을 잘 모아줘서 좋아용 :) !! 트렁크는 너무 편안하구요 !!
3643,8100258349092,멜로우 트렁크,2024-09-20,<NA>,착용 정보: 95 / pbe 가볍고 통풍이 잘 되는데도 가슴을 잘 모아줘서 좋아용 :) !! 트렁크는 너무 편안하구요 !!

In [409]:
# ===============================
# 중복리뷰 제거
# ===============================
before = len(df)

df = (
    df
    .sort_values(
        by=['helpful_count', 'has_image', 'user_height', 'user_weight', 'user_height_group', 'user_weight_group'],
        ascending=[False, False, False, False, False, False],
        na_position='last'
    )
    .drop_duplicates(
        subset=['product_id', 'content', 'review_date', 'purchase_option'],
        keep='first'
    )
    .sort_index()
)

after = len(df)

print(f"제거 전: {before}개")
print(f"제거된 데이터: {before - after}개")
print(f"남은 데이터: {after}개")

제거 전: 10689개
제거된 데이터: 4개
남은 데이터: 10685개

In [412]:
import re

def clean_text(text):
    # 1. 결측치 처리
    if pd.isna(text):
        return ' '
    text = str(text)
    
    # 2. HTML 태그 제거
    text = re.sub(r'<[^>]+>', ' ', text)
    
    # 3. URL 제거
    text = re.sub(r'http\S+|www\.\S+', ' ', text)
    
    # 4. 이메일 제거
    text = re.sub(r'\S+@\S+', ' ', text)
    
    # 5. 이모지 & 이모티콘 제거
    text = re.sub(r'[^\w\s\uAC00-\uD7A3\u3130-\u318F]', ' ', text)
    
    # \uAC00-\uD7A3 : 한글 완성형
    # \u3130-\u318F : ㅎ, ㅋ 같은 한글 자모음 (반복 제거 대상이라 유지)
    
    # 6. 줄바꿈, 탭 → 공백으로 변환
    text = re.sub(r'[\n\r\t]', ' ', text)
    
    # 7. 반복 문자 1개로 통일 (ㅎㅎㅎ→ㅎ, ㅋㅋㅋ→ㅋ, ~~~→~)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    
    # 8. 연속 공백 → 공백 1개로 통일
    text = re.sub(r'\s+', ' ', text)
    
    # 9. 대소문자 통합 (영문 소문자)
    text = text.lower()
    
    # 10. 앞뒤 공백 제거
    text = text.strip()
    
    return text

df['content'] = df['content'].apply(clean_text)

In [413]:
# =========================================
# 띄어쓰기 제거 후 5글자 이하인 데이터 확인
# =========================================
short_mask = df['content'].str.replace(' ', '', regex=False).str.len() <= 5

print(f"5글자 이하 행 수: {short_mask.sum()}")
display(df[short_mask]['content'].value_counts())

5글자 이하 행 수: 12

content
너무 편해요    2
이뻐요 너무    1
아주좋아요     1
핏 죽입니다    1
아주조아요     1
아주 좋아요    1
착용감 굿     1
넘 편합니다    1
좋습니다      1
아주편해요     1
너무 이뻐요    1
Name: count, dtype: int64

In [414]:
# =========================
# 5글자 이하 행 제거
# =========================
before = len(df)
df = df[~short_mask]
after = len(df)

print(f"제거 전: {before}개")
print(f"제거된 행: {before - after}개")
print(f"제거 후: {after}개")

제거 전: 10685개
제거된 행: 12개
제거 후: 10673개

## 저장

In [ ]:
# ============================
# 저장하기
# ============================

df_2024 = df[df['year'] >= 2024]

df.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final.csv", encoding='utf-8-sig', index=False)
df_2024.to_csv("/Users/kimsunyeong/Desktop/SPARTA_PROJECT_4TH_E_COMMERCE/김선영/data/final/fila_homepage_review_final_s2024.csv", encoding='utf-8-sig', index=False)

In [416]:
display(df_2024.head())
display(df_2024.info())

,collect_date,platform,review_id,product_id,product_name,review_date,year,month,content,rating,...,has_image,purchase_option,purchase_option_color,purchase_option_size,women_size_yn,user_height,user_weight,user_height_group,user_weight_group,product_url
0,2026-04-28,자사몰,139954,8127678283812,휠라 스피드서브 T9 2.0,2026-03-26,2026,3,이 신발 네트 대시가 왜 이렇게 빨라 스피드서브 t9 2 0 실착리뷰 테니스 구력은 장비빨 이라는 말 이번에 휠라 스피드서브 t9 2 0을 하드코트와 인조잔디에서 굴려보며 뼈저리게 느꼈습니다 결론부터 말씀드리면 발이 편한 건 기본 코트 위에서 날개를 단 기분이었는데요 구체적인 후기 들어갑니다 1 발볼러들 강추 합니다 사이즈감과 극강의 편안함 제일 먼저 놀란 건 사이즈감과 핏입니다 2 0 버전은 분리형 텅 tongue 구조로 바뀌어서 발등 높이에 맞춰 끈 조절이 정말 자유로워요 저는 발이 예민한 편인데도 발이 참 편하다는 생각을 멈출 수가 없었습니다 발볼도 넉넉하게 나와서 압박감 없이 핏하게 감기는 맛이 일품입니다 2 스플릿 스텝 후 0 1초가 달라진다 접지력과 반응성 이 신발의 진가는 방향 전환에서 나옵니다 하드코트든 인조잔디든 지면을 움켜쥐는 헤링본 패턴의 아웃솔 접지력이 장난 아니에요 특히 스플릿 스텝 이후 다음 동작으로 넘어갈 때 미끄러짐이 전혀 없어서 에너지가 밖으로 새지 않고 바로 다음 스텝으로 연결되는 느낌이 정말 쾌적했습니다 3 네트 앞으로 전력 질주 경량성과 네트 플레이 저는 기회만 나면 네트 앞으로 달려가 발리 공격하는 걸 즐기는데 스피드서브 2 0은 확실히 가볍습니다 신발이 무거우면 첫 발 떼기가 무거운데 이건 발놀림이 경쾌해서 네트 대시 속도가 훨씬 붙더라고요 좌우로 흔들릴 때도 tpu 생크 기술이 발의 뒤틀림을 딱 잡아주니까 빠른 움직임 속에서도 안정감이 느껴져 발리 찬스를 잡기가 훨씬 수월했습니다 4 탄탄한 쿠셔닝 무릎 피로도 안녕 쿠셔닝은 너무 물렁하지도 너무 딱딱하지도 않은 기분 좋은 탄성을 보여줍니다 하드코트에서 격하게 뛰어도 충격을 잘 흡수해주어 장시간 게임 후에도 무릎이나 발바닥에 무리가 덜 갔습니다 5 코트 위 패셔니스타 디자인 한줄평 기능도 기능이지만 디자인이 정말 깔끔하고 예뻐요 측면 로고가 미니멀해져서 그런지 어떤 테니스복에 매치해도 찰떡 입니다 운동 끝나고 일상복에 그대로 신고 가도 전혀 어색하지 않은 세련된 화이트 톤이라 더 만족스럽네요 한 줄 요약 스플릿 스텝이 가벼워지고 네트 점령이 쉬워지는 신발 발볼 넓은 공격형 플레이어라면 무조건 이거 가세요,5,...,1,<NA>,NaN,NaN,0,NaN,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106
1,2026-04-28,자사몰,143752,8100165845028,하레핀 1998,2026-04-21,2026,4,후기 사진은 크게 확인 부탁드립니다 남자친구랑 사귀고 첫 커플 신발인데 뭐를 살까 고민하다가 제가 휠라 에샤페 lx 초코 를 신고 있는데 너무 편하게 신고 있던 중 우연히 휠라 하레핀을 보자마자 너무 이뻐서 바로 남자친구한테 보여줬더니 너무 마음에 든다고 주말에 당장 휠라에 가서 신어보고 둘 다 마음에 들어서 바로 남자친구 사줬어요 근데 실물보고 잘 보고 온 게 맞구나 싶었어요 ㅋㅋ디자인 색감 둘 다 잡았더라구요 과한 느낌은 없고 잔잔하게 포인트 줄 수 있는 신발이예요 진짜 만족도 100 입니다 하레핀 구매하고 계속 이 신발만 신고 다니고 있어요 ㅎㅎ 덕분에 동료들한테도 이쁘다고 칭찬받고 많이 추천도 해줬어요 ㅋㅋ 꼭 구매하라고 사이즈도 평소에 신던 사이즈 230mm 그대로 정상 사이즈로 나왔다고 생각했어요 제가 신발 구매할 때마다 발볼이 있다는 이야기를 듣는데 불편함없었습니다 그리고 걷다보면 발가락 아픈 느낌도 없었고 너무 편하게 걸어다녔어요 아 남자친구도 평소에 270mm으로 신는데 휠라도 동일하게 270mm으로 구매해서 착용하고 있는데 편하다고 그러더라구요 평소 사이즈랑 동일하게 구매하시면 될 거 같아요 제가 신발 구매하고 바로 남자친구랑 하레핀 신고 놀러 갔어요 근데 진짜 사진 찍을 때랑 걸어 다니면서 거울 보일 때 진짜 너무 이뻐요 최고 한강으로 놀러갔는데 오래 걸어도 발이 정말 편했고 신발이 생각보다 가볍다고 생각도 했습니다 그리고 하레핀 크림색상은 츄리닝에도 잘 어울리고 데일리룩에도 잘 어울리고 소재도 천연 돼지 스웨이드여서 고급감이 더해져 어느 룩에도 잘 매칭이 되는 핫한 아이템이라고 생각해요 ㅎㅎ 또 제가 하레핀 노랑색도 신어봤는데 진짜 30분동안 고민했어요 색감 진짜 이쁘고 완전 포인트로 신기 좋아보였어요 완전 취향저격 이번에는 크림색으로 구매했지만 조만간 남자친구랑 포인트 주기 이쁘다고 같이 사러 가자고 꼬섰어요 ㅋㅋ 노랑색도 구매하면 이쁜 사진으로 후기 작성하러 올께요 ㅎㅎ,5,...,1,270,NaN,270,0,NaN,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261od03x095217
2,2026-04-28,자사몰,140502,8127678283812,휠라 스피드서브 T9 2.0,2026-03-31,2026,3,엑실러스3 유저의 스피드서브 2 0 기변 후기 테니스 구력 2년 차 그동안 저의 베이스라인을 든든하게 지켜주던 엑실러스 3 에서 드디어 스피드서브 2 0 으로 기변했습니다 목빠지게 배송 기다리다 코트에서 직접 뛰어보고 남기는 진또배기 후기 바로 레츠고 1 사이즈 및 핏감 엑실러스 3가 갑옷처럼 발을 보호해 주는 느낌이었다면 스피드서브 2 0의 유연한 소재와 핏감은 진짜 jmt 발볼도 편안하게 잘 나와서 정사이즈로 신으니 완전 맞춤 핏이네요 특히 끈으로 발등 압박감을 세밀하게 조절할 수 있어서 게임 내내 발이 너무 편안합니다 2 접지력 및 반응성 멈출 때 정확히 멈춰주고 다음 공을 향해 튀어 나갈 때 바닥을 쫀득하게 밀어주는 폭발력이 진짜 진또배기입니다 아웃솔이 바닥을 미끄러짐 없이 꽉 잡아주니까 네트 앞으로 대시할 때 반응 속도가 확실히 빨라졌어요 덕분에 구력 2년 차도 자신감 있게 공격적인 플레이 가능해서 진짜 너무 좋아여 3 쿠셔닝 가벼운 무게에 어떻게 이런 쫀쫀한 쿠션을 넣었는지 휠라 칭찬합니다 하드 코트에서 랠리를 길게 가져가도 발바닥 충격을 잘 분산시켜 주고요 다음 스텝을 밟을 때 에너지를 리턴해 주는 탄성 덕분에 3시간 이상 운동해도 하체 피로도가 확실히 적어요 스피드서브 2 0 디자인도 느좋이라 파트너랑 팀 테니스화로 맞춰 신었는데 코트 갈 때마다 주변에서 예쁘다고 난리네요 ㅎㅎ 정말 누구신지 모르겠지만 기획자님 너무 감사합니당 이렇게 이쁜색 테니스화를 만들어주셔서 가볍고 예쁜데 기능까지 완벽한 스피드서브 2 0과 함께 혼복 대회 입상을 넘어 우승까지 렛츠고,5,...,1,240,NaN,240,0,NaN,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106
3,2026-04-28,자사몰,143962,8100165845028,하레핀 1998,2026-04-24,2026,4,첫 커플신발로 휠라 하레핀1998을 선택했어요 일반적인 스니커즈 디자인이 질려서 고민하고 있을 때 때마침 딱 캐주얼한 등산화 느낌의 하레핀이 마음에 들어 데꼬 왔어요 저희는 230 280 크림 색상으로 공식홈페이지에서 구매했어요 카카오 채널추가 할인쿠폰 굿 저는 발볼이 좁은 편이고 남친은 보통인 편인데 둘 다 편하게 잘 맞아요 정사이즈로 구매하시면 돼요 처음에 박스 딱 열었을 때 일단 실물이 되게 예뻐서 만족스러웠고 딱 신었을 때 되게 가볍고 편해서 놀랐어요 그리고 저 평발이라 많이 걸으면 발바닥이 무조건 아픈데 경주 황리단길을 폭풍워킹해도 정말 발이 안 아팠어요 밝은 천 색상에 어두운 밑창과 끈 조합이라 흰 바지를 입던 흑청을 입던 중청을 입던 정말 캐주얼하게 휘뚤마뚤 잘 신을 수 있어요 근데 또 아예 안 꾸민 느낌은 아니라 출근룩 데이트룩 다 가능해서 넘 좋음 여행 앞두고 커플신발을 하레핀으로 장만해서 경주여행을 잘 다녀왔는데 곧 있을 제주에도 함께 신고 가려고 합니다 커플신발로 휠라 하레핀 추천드려요 이 리뷰가 도움되셨다면 도움돼요 눌러주세요,5,...,1,280,NaN,280,0,NaN,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261od03x095217
4,2026-04-28,자사몰,140489,8127678283812,휠라 스피드서브 T9 2.0,2026-03-30,2026,3,스피드서브 1 찐유저의 2 0 버전업 후기 단종의 눈물을 닦아준 완벽한 진화 feat 혼복 우승 렛츠고 기존에 밑창이 닳도록 신던 인생 테니스화 스피드서브 1 이 단종되어 더 이상 구매할 수 없어 눈물 흘리던 참에 소울메이트 같은 동생이 스피드서브 2 0이 런칭됐다는 기가 막힌 소식을 알려주더군요 망설임 없이 바로 기변 렛츠고 코트 위에서 직접 굴러보고 쓰는 진또배기 후기 바로 레츠고 1 사이즈 및 핏감 기존 일체형 구조에서 2 0은 분리형 텅으로 변경됐는데 이게 정말 신의 한 수 같습니다 그날그날 발 붓기나 양말 두께에 맞춰 끈으로 더 세밀하게 조절할 수 있어 발과의 일체감이 더 좋아졌어요 발볼이 넉넉하게 나와서 전형적인 한국인 족형에게 강력히 추천드립니다 2 쿠셔닝 292 7g이라는 가벼운 무게에 이런 쫀쫀한 쿠션감이라니 무조건 물렁하기만 한 쿠션 보다 오히려 발바닥의 충격을 잘 분산해줍니다 처음 2 0을 신은 날 4시간을 풀로 뛰었는데도 하체 피로도가 다른 날보다 적어서 감탄했습니다 3 접지력 및 움직임 반응 기존 1세대 버전도 접지력은 정말 만족하며 신었는데 2 0은 바닥 패턴이 바뀌면서 확실히 더 업그레이드됐네요 스플릿 스텝 후 다음 스텝 치고 나갈 때 바닥을 쫀득하게 밀어주는 지지력이 너무 좋습니다 미끄러짐이 없으니 덕분에 코트 위에서 더 안정적이고 공격적인 플레이가 가능해졌어요 4 착화 시 안정감 테니스는 멈추는 게 더 중요한 운동인거 다들 아시죠 좌우 사이드 스텝을 밟고 오픈 스탠스로 급브레이크를 걸 때 신발 뒤틀림 없이 발목을 견고하게 잘 잡아줍니다 덕분에 발목 불안함 없이 공에만 100 집중할 수 있습니다 스피드서브 2 0 런칭을 소개해 준 동생하고 최근 혼복팀을 결성하게 됐는데 이 참에 팀 테니스화도 2 0으로 같이 맞추게 됐네요 든든한 스피드서브 2 0과 함께 입상을 넘어 우승까지 렛츠고,5,...,1,265,NaN,265,0,NaN,NaN,NaN,NaN,https://www.fila.co.kr/products/1100fs261tn02x001106

<class 'pandas.DataFrame'>
Index: 10673 entries, 0 to 10688
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   collect_date           10673 non-null  datetime64[us]
 1   platform               10673 non-null  category
 2   review_id              10673 non-null  string
 3   product_id             10673 non-null  string
 4   product_name           10673 non-null  string
 5   review_date            10673 non-null  datetime64[us]
 6   year                   10673 non-null  Int16
 7   month                  10673 non-null  Int8
 8   content                10673 non-null  str
 9   rating                 10673 non-null  Int8
 10  helpful_count          10673 non-null  Int32
 11  has_image              10673 non-null  int8
 12  purchase_option        1733 non-null   string
 13  purchase_option_color  536 non-null    category
 14  purchase_option_size   1611 non-null   category
 15  women_size_yn          10673 non-null  int8
 16  user_height            0 non-null      float32
 17  user_weight            0 non-null      float32
 18  user_height_group      0 non-null      category
 19  user_weight_group      0 non-null      category
 20  product_url            10673 non-null  string
dtypes: Int16(1), Int32(1), Int8(2), category(5), datetime64[us](2), float32(2), int8(2), str(1), string(5)
memory usage: 3.9 MB

None